## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [5]:
df1 = pl.read_csv("data/test_noLabel.csv", encoding="utf8-lossy")
df2 = pl.read_csv("data/submit_example.csv", encoding="utf8-lossy")
df3 = pl.read_csv("data/train.csv", encoding="utf8-lossy")

# Join df1 and df2 on the "ID" column (you can adjust join type if needed)
joined_df = df1.join(df2, on="ID", how="inner")

# Concatenate the joined result with df3 (assumes matching schema)
df = pl.concat([joined_df, df3], how="vertical", rechunk=True)

df

shape: (1_450, 32)
┌──────┬─────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬─────────────┬───────┐
│ ID   ┆ Age ┆ BusinessTrav ┆ Department   ┆ … ┆ YearsInCurre ┆ YearsSinceLa ┆ YearsWithCu ┆ Label │
│ ---  ┆ --- ┆ el           ┆ ---          ┆   ┆ ntRole       ┆ stPromotion  ┆ rrManager   ┆ ---   │
│ i64  ┆ i64 ┆ ---          ┆ str          ┆   ┆ ---          ┆ ---          ┆ ---         ┆ i64   │
│      ┆     ┆ str          ┆              ┆   ┆ i64          ┆ i64          ┆ i64         ┆       │
╞══════╪═════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪═════════════╪═══════╡
│ 1100 ┆ 40  ┆ Non-Travel   ┆ Research &   ┆ … ┆ 7            ┆ 0            ┆ 7           ┆ 0     │
│      ┆     ┆              ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ 1101 ┆ 53  ┆ Travel_Rarel ┆ Research &   ┆ … ┆ 7            ┆ 4            ┆ 7           ┆ 0     │
│      ┆     ┆ y            ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ 1102 ┆ 42  ┆ Travel_Rarel ┆ Research &   ┆ … ┆ 0            ┆ 0            ┆ 0           ┆ 0     │
│      ┆     ┆ y            ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ 1103 ┆ 34  ┆ Travel_Frequ ┆ Human        ┆ … ┆ 9            ┆ 1            ┆ 8           ┆ 0     │
│      ┆     ┆ ently        ┆ Resources    ┆   ┆              ┆              ┆             ┆       │
│ 1104 ┆ 32  ┆ Travel_Rarel ┆ Research &   ┆ … ┆ 0            ┆ 0            ┆ 0           ┆ 0     │
│      ┆     ┆ y            ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ …    ┆ …   ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …           ┆ …     │
│ 1095 ┆ 35  ┆ Travel_Rarel ┆ Research &   ┆ … ┆ 2            ┆ 2            ┆ 2           ┆ 0     │
│      ┆     ┆ y            ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ 1096 ┆ 38  ┆ Travel_Rarel ┆ Sales        ┆ … ┆ 2            ┆ 0            ┆ 3           ┆ 0     │
│      ┆     ┆ y            ┆              ┆   ┆              ┆              ┆             ┆       │
│ 1097 ┆ 37  ┆ Travel_Rarel ┆ Sales        ┆ … ┆ 0            ┆ 0            ┆ 0           ┆ 0     │
│      ┆     ┆ y            ┆              ┆   ┆              ┆              ┆             ┆       │
│ 1098 ┆ 22  ┆ Travel_Rarel ┆ Research &   ┆ … ┆ 0            ┆ 0            ┆ 0           ┆ 1     │
│      ┆     ┆ y            ┆ Development  ┆   ┆              ┆              ┆             ┆       │
│ 1099 ┆ 26  ┆ Travel_Frequ ┆ Research &   ┆ … ┆ 2            ┆ 1            ┆ 2           ┆ 1     │
│      ┆     ┆ ently        ┆ Development  ┆   ┆              ┆              ┆             ┆       │
└──────┴─────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴─────────────┴───────┘

### Retrieve Number of Nulls in Each Feature

In [6]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (32, 2)
┌──────────────────────────┬────────────┐
│ feature                  ┆ null_count │
│ ---                      ┆ ---        │
│ str                      ┆ i64        │
╞══════════════════════════╪════════════╡
│ ID                       ┆ 0          │
│ Age                      ┆ 0          │
│ BusinessTravel           ┆ 0          │
│ Department               ┆ 0          │
│ DistanceFromHome         ┆ 0          │
│ Education                ┆ 0          │
│ EducationField           ┆ 0          │
│ EmployeeNumber           ┆ 0          │
│ EnvironmentSatisfaction  ┆ 0          │
│ Gender                   ┆ 0          │
│ JobInvolvement           ┆ 0          │
│ JobLevel                 ┆ 0          │
│ JobRole                  ┆ 0          │
│ JobSatisfaction          ┆ 0          │
│ MaritalStatus            ┆ 0          │
│ MonthlyIncome            ┆ 0          │
│ NumCompaniesWorked       ┆ 0          │
│ Over18                   ┆ 0          │
│ OverTime                 ┆ 0          │
│ PercentSalaryHike        ┆ 0          │
│ PerformanceRating        ┆ 0          │
│ RelationshipSatisfaction ┆ 0          │
│ StandardHours            ┆ 0          │
│ StockOptionLevel         ┆ 0          │
│ TotalWorkingYears        ┆ 0          │
│ TrainingTimesLastYear    ┆ 0          │
│ WorkLifeBalance          ┆ 0          │
│ YearsAtCompany           ┆ 0          │
│ YearsInCurrentRole       ┆ 0          │
│ YearsSinceLastPromotion  ┆ 0          │
│ YearsWithCurrManager     ┆ 0          │
│ Label                    ┆ 0          │
└──────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [7]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
ID                             | Int64
Age                            | Int64
BusinessTravel                 | String
Department                     | String
DistanceFromHome               | Int64
Education                      | Int64
EducationField                 | String
EmployeeNumber                 | Int64
EnvironmentSatisfaction        | Int64
Gender                         | String
JobInvolvement                 | Int64
JobLevel                       | Int64
JobRole                        | String
JobSatisfaction                | Int64
MaritalStatus                  | String
MonthlyIncome                  | Int64
NumCompaniesWorked             | Int64
Over18                         | String
OverTime                       | String
PercentSalaryHike              | Int64
PerformanceRating              | Int64
RelationshipSatisfaction       | Int64
StandardHours                  | Int64
StockOptionLevel               | Int64
TotalWorkingYears              | Int64
TrainingTimesLastYear          | Int64
WorkLifeBalance                | Int64
YearsAtCompany                 | Int64
YearsInCurrentRole             | Int64
YearsSinceLastPromotion        | Int64
YearsWithCurrManager           | Int64
Label                          | Int64

### Display Summary Statistics for All Columns

In [8]:
summary = df.describe()
print(summary)

shape: (9, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ ID        ┆ Age       ┆ BusinessT ┆ … ┆ YearsInCu ┆ YearsSinc ┆ YearsWith ┆ Label    │
│ ---       ┆ ---       ┆ ---       ┆ ravel     ┆   ┆ rrentRole ┆ eLastProm ┆ CurrManag ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ otion     ┆ er        ┆ f64      │
│           ┆           ┆           ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1450.0    ┆ 1450.0    ┆ 1450      ┆ … ┆ 1450.0    ┆ 1450.0    ┆ 1450.0    ┆ 1450.0   │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 724.5     ┆ 36.871724 ┆ null      ┆ … ┆ 4.22      ┆ 2.16      ┆ 4.097931  ┆ 0.357241 │
│ std       ┆ 418.72325 ┆ 9.119033  ┆ null      ┆ … ┆ 3.617954  ┆ 3.18867   ┆ 3.546603  ┆ 0.479352 │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 18.0      ┆ Non-Trave ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆ l         ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 362.0     ┆ 30.0      ┆ null      ┆ … ┆ 2.0       ┆ 0.0       ┆ 2.0       ┆ 0.0      │
│ 50%       ┆ 725.0     ┆ 36.0      ┆ null      ┆ … ┆ 3.0       ┆ 1.0       ┆ 3.0       ┆ 0.0      │
│ 75%       ┆ 1087.0    ┆ 43.0      ┆ null      ┆ … ┆ 7.0       ┆ 3.0       ┆ 7.0       ┆ 1.0      │
│ max       ┆ 1449.0    ┆ 60.0      ┆ Travel_Ra ┆ … ┆ 18.0      ┆ 15.0      ┆ 17.0      ┆ 1.0      │
│           ┆           ┆           ┆ rely      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [9]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 8)
┌───────────────┬────────────┬───────────────┬────────┬─────────┬──────────────┬────────┬──────────┐
│ BusinessTrave ┆ Department ┆ EducationFiel ┆ Gender ┆ JobRole ┆ MaritalStatu ┆ Over18 ┆ OverTime │
│ l             ┆ ---        ┆ d             ┆ ---    ┆ ---     ┆ s            ┆ ---    ┆ ---      │
│ ---           ┆ u32        ┆ ---           ┆ u32    ┆ u32     ┆ ---          ┆ u32    ┆ u32      │
│ u32           ┆            ┆ u32           ┆        ┆         ┆ u32          ┆        ┆          │
╞═══════════════╪════════════╪═══════════════╪════════╪═════════╪══════════════╪════════╪══════════╡
│ 17            ┆ 22         ┆ 16            ┆ 6      ┆ 25      ┆ 8            ┆ 1      ┆ 3        │
└───────────────┴────────────┴───────────────┴────────┴─────────┴──────────────┴────────┴──────────┘

### Retrieve Data Types of All Columns

In [10]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Int64, Int64, String, String, Int64, Int64, String, Int64, Int64, String, Int64, Int64, String, Int64, String, Int64, Int64, String, String, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64]

### Count Unique Values in Each Column

In [11]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                           Unique values in ID : 1450
                          Unique values in Age : 43
               Unique values in BusinessTravel : 3
                   Unique values in Department : 3
             Unique values in DistanceFromHome : 29
                    Unique values in Education : 5
               Unique values in EducationField : 6
               Unique values in EmployeeNumber : 1450
      Unique values in EnvironmentSatisfaction : 4
                       Unique values in Gender : 2
               Unique values in JobInvolvement : 4
                     Unique values in JobLevel : 5
                      Unique values in JobRole : 9
              Unique values in JobSatisfaction : 4
                Unique values in MaritalStatus : 3
                Unique values in MonthlyIncome : 1329
           Unique values in NumCompaniesWorked : 10
                       Unique values in Over18 : 1
                     Unique values in OverTime : 2
            Unique values in PercentSalaryHike : 15
            Unique values in PerformanceRating : 2
     Unique values in RelationshipSatisfaction : 4
                Unique values in StandardHours : 1
             Unique values in StockOptionLevel : 4
            Unique values in TotalWorkingYears : 40
        Unique values in TrainingTimesLastYear : 7
              Unique values in WorkLifeBalance : 4
               Unique values in YearsAtCompany : 36
           Unique values in YearsInCurrentRole : 19
      Unique values in YearsSinceLastPromotion : 16
         Unique values in YearsWithCurrManager : 18
                        Unique values in Label : 2

### Check Distribution of Numerical Columns

In [12]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

Age
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ Age       │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 1450.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 36.871724 │
│ std        ┆ 9.119033  │
│ min        ┆ 18.0      │
│ 25%        ┆ 30.0      │
│ 50%        ┆ 36.0      │
│ 75%        ┆ 43.0      │
│ max        ┆ 60.0      │
└────────────┴───────────┘


DistanceFromHome
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ DistanceFromHome │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 1450.0           │
│ null_count ┆ 0.0              │
│ mean       ┆ 9.177241         │
│ std        ┆ 8.085783         │
│ min        ┆ 1.0              │
│ 25%        ┆ 2.0              │
│ 50%        ┆ 7.0              │
│ 75%        ┆ 14.0             │
│ max        ┆ 29.0             │
└────────────┴──────────────────┘


Education
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ Education │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 1450.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 2.909655  │
│ std        ┆ 1.023925  │
│ min        ┆ 1.0       │
│ 25%        ┆ 2.0       │
│ 50%        ┆ 3.0       │
│ 75%        ┆ 4.0       │
│ max        ┆ 5.0       │
└────────────┴───────────┘


EmployeeNumber
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ EmployeeNumber │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 1450.0         │
│ null_count ┆ 0.0            │
│ mean       ┆ 1026.981379    │
│ std        ┆ 602.029616     │
│ min        ┆ 1.0            │
│ 25%        ┆ 494.0          │
│ 50%        ┆ 1024.0         │
│ 75%        ┆ 1560.0         │
│ max        ┆ 2068.0         │
└────────────┴────────────────┘


EnvironmentSatisfaction
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ EnvironmentSatisfaction │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 1450.0                  │
│ null_count ┆ 0.0                     │
│ mean       ┆ 2.722759                │
│ std        ┆ 1.090314                │
│ min        ┆ 1.0                     │
│ 25%        ┆ 2.0                     │
│ 50%        ┆ 3.0                     │
│ 75%        ┆ 4.0                     │
│ max        ┆ 4.0                     │
└────────────┴─────────────────────────┘


JobInvolvement
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ JobInvolvement │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 1450.0         │
│ null_count ┆ 0.0            │
│ mean       ┆ 2.731724       │
│ std        ┆ 0.711068       │
│ min        ┆ 1.0            │
│ 25%        ┆ 2.0            │
│ 50%        ┆ 3.0            │
│ 75%        ┆ 3.0            │
│ max        ┆ 4.0            │
└────────────┴────────────────┘


JobLevel
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ JobLevel │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 1450.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 2.057931 │
│ std        ┆ 1.103084 │
│ min        ┆ 1.0      │
│ 25%        ┆ 1.0      │
│ 50%        ┆ 2.0      │
│ 75%        ┆ 3.0      │
│ max        ┆ 5.0      │
└────────────┴──────────┘


JobSatisfaction
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ JobSatisfaction │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 1450.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 2.731034        │
│ std        ┆ 1.103074        │
│ min        ┆ 1.0             │
│ 25%        ┆ 2.0             │
│ 50%        ┆ 3.0             │
│ 75%        ┆ 4.0             │
│ max        ┆ 4.0             │
└────────────┴─────────────────┘


MonthlyIncome
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ MonthlyIncome │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1450.0        │
│ null_count ┆ 0.0           │
│ mean       ┆ 6482.624138   │
│ std        ┆ 4694.115546   │
│ min        ┆ 1009.0        │
│ 25%        ┆ 2909.0        │
│ 50%        ┆ 4907.0        │
│ 75%        ┆ 8346.0        │
│ max        ┆ 19999.0       │
└────────────┴───────────────┘


NumCompaniesWorked
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ NumCompaniesWorked │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 1450.0             │
│ null_count ┆ 0.0                │
│ mean       ┆ 2.685517           │
│ std        ┆ 2.496457           │
│ min        ┆ 0.0                │
│ 25%        ┆ 1.0                │
│ 50%        ┆ 2.0                │
│ 75%        ┆ 4.0                │
│ max        ┆ 9.0                │
└────────────┴────────────────────┘


PercentSalaryHike
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ PercentSalaryHike │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 1450.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 15.226897         │
│ std        ┆ 3.668111          │
│ min        ┆ 11.0              │
│ 25%        ┆ 12.0              │
│ 50%        ┆ 14.0              │
│ 75%        ┆ 18.0              │
│ max        ┆ 25.0              │
└────────────┴───────────────────┘


PerformanceRating
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ PerformanceRating │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 1450.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 3.154483          │
│ std        ┆ 0.361536          │
│ min        ┆ 3.0               │
│ 25%        ┆ 3.0               │
│ 50%        ┆ 3.0               │
│ 75%        ┆ 3.0               │
│ max        ┆ 4.0               │
└────────────┴───────────────────┘


RelationshipSatisfaction
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ RelationshipSatisfaction │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 1450.0                   │
│ null_count ┆ 0.0                      │
│ mean       ┆ 2.708276                 │
│ std        ┆ 1.08239                  │
│ min        ┆ 1.0                      │
│ 25%        ┆ 2.0                      │
│ 50%        ┆ 3.0                      │
│ 75%        ┆ 4.0                      │
│ max        ┆ 4.0                      │
└────────────┴──────────────────────────┘


StandardHours
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ StandardHours │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1450.0        │
│ null_count ┆ 0.0           │
│ mean       ┆ 80.0          │
│ std        ┆ 0.0           │
│ min        ┆ 80.0          │
│ 25%        ┆ 80.0          │
│ 50%        ┆ 80.0          │
│ 75%        ┆ 80.0          │
│ max        ┆ 80.0          │
└────────────┴───────────────┘


StockOptionLevel
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ StockOptionLevel │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 1450.0           │
│ null_count ┆ 0.0              │
│ mean       ┆ 0.795172         │
│ std        ┆ 0.853752         │
│ min        ┆ 0.0              │
│ 25%        ┆ 0.0              │
│ 50%        ┆ 1.0              │
│ 75%        ┆ 1.0              │
│ max        ┆ 3.0              │
└────────────┴──────────────────┘


TotalWorkingYears
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ TotalWorkingYears │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 1450.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 11.217241         │
│ std        ┆ 7.738772          │
│ min        ┆ 0.0               │
│ 25%        ┆ 6.0               │
│ 50%        ┆ 10.0              │
│ 75%        ┆ 15.0              │
│ max        ┆ 40.0              │
└────────────┴───────────────────┘


TrainingTimesLastYear
shape: (9, 2)
┌────────────┬───────────────────────┐
│ statistic  ┆ TrainingTimesLastYear │
│ ---        ┆ ---                   │
│ str        ┆ f64                   │
╞════════════╪═══════════════════════╡
│ count      ┆ 1450.0                │
│ null_count ┆ 0.0                   │
│ mean       ┆ 2.801379              │
│ std        ┆ 1.292009              │
│ min        ┆ 0.0                   │
│ 25%        ┆ 2.0                   │
│ 50%        ┆ 3.0                   │
│ 75%        ┆ 3.0                   │
│ max        ┆ 6.0                   │
└────────────┴───────────────────────┘


WorkLifeBalance
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ WorkLifeBalance │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 1450.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 2.761379        │
│ std        ┆ 0.706588        │
│ min        ┆ 1.0             │
│ 25%        ┆ 2.0             │
│ 50%        ┆ 3.0             │
│ 75%        ┆ 3.0             │
│ max        ┆ 4.0             │
└────────────┴─────────────────┘


YearsAtCompany
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ YearsAtCompany │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 1450.0         │
│ null_count ┆ 0.0            │
│ mean       ┆ 6.956552       │
│ std        ┆ 6.053036       │
│ min        ┆ 0.0            │
│ 25%        ┆ 3.0            │
│ 50%        ┆ 5.0            │
│ 75%        ┆ 9.0            │
│ max        ┆ 37.0           │
└────────────┴────────────────┘


YearsInCurrentRole
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ YearsInCurrentRole │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 1450.0             │
│ null_count ┆ 0.0                │
│ mean       ┆ 4.22               │
│ std        ┆ 3.617954           │
│ min        ┆ 0.0                │
│ 25%        ┆ 2.0                │
│ 50%        ┆ 3.0                │
│ 75%        ┆ 7.0                │
│ max        ┆ 18.0               │
└────────────┴────────────────────┘


YearsSinceLastPromotion
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ YearsSinceLastPromotion │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 1450.0                  │
│ null_count ┆ 0.0                     │
│ mean       ┆ 2.16                    │
│ std        ┆ 3.18867                 │
│ min        ┆ 0.0                     │
│ 25%        ┆ 0.0                     │
│ 50%        ┆ 1.0                     │
│ 75%        ┆ 3.0                     │
│ max        ┆ 15.0                    │
└────────────┴─────────────────────────┘


YearsWithCurrManager
shape: (9, 2)
┌────────────┬──────────────────────┐
│ statistic  ┆ YearsWithCurrManager │
│ ---        ┆ ---                  │
│ str        ┆ f64                  │
╞════════════╪══════════════════════╡
│ count      ┆ 1450.0               │
│ null_count ┆ 0.0                  │
│ mean       ┆ 4.097931             │
│ std        ┆ 3.546603             │
│ min        ┆ 0.0                  │
│ 25%        ┆ 2.0                  │
│ 50%        ┆ 3.0                  │
│ 75%        ┆ 7.0                  │
│ max        ┆ 17.0                 │
└────────────┴──────────────────────┘


Label
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Label    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 1450.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.357241 │
│ std        ┆ 0.479352 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 1.0      │
│ max        ┆ 1.0      │
└────────────┴──────────┘

### List Unique Values For Certain Features

In [13]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: ID (1450 unique values)
shape: (1_450,)
Series: 'ID' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	…
	1433
	1434
	1435
	1436
	1437
	1438
	1439
	1440
	1441
	1442
	1443
	1444
	1445
	1446
	1447
	1448
	1449
]
--------------------------------------------------
Column: Age (43 unique values)
shape: (43,)
Series: 'Age' [i64]
[
	18
	19
	20
	21
	22
	23
	24
	25
	26
	27
	28
	29
	30
	31
	32
	33
	34
	35
	…
	44
	45
	46
	47
	48
	49
	50
	51
	52
	53
	54
	55
	56
	57
	58
	59
	60
]
--------------------------------------------------
Column: BusinessTravel (3 unique values)
shape: (3,)
Series: 'BusinessTravel' [str]
[
	"Non-Travel"
	"Travel_Frequently"
	"Travel_Rarely"
]
--------------------------------------------------
Column: Department (3 unique values)
shape: (3,)
Series: 'Department' [str]
[
	"Human Resources"
	"Research & Development"
	"Sales"
]
--------------------------------------------------
Column: DistanceFromHome (29 unique values)
shape: (29,)
Series: 'DistanceFromHome' [i64]
[
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
	22
	23
	24
	25
	26
	27
	28
	29
]
--------------------------------------------------
Column: Education (5 unique values)
shape: (5,)
Series: 'Education' [i64]
[
	1
	2
	3
	4
	5
]
--------------------------------------------------
Column: EducationField (6 unique values)
shape: (6,)
Series: 'EducationField' [str]
[
	"Human Resources"
	"Life Sciences"
	"Marketing"
	"Medical"
	"Other"
	"Technical Degree"
]
--------------------------------------------------
Column: EmployeeNumber (1450 unique values)
shape: (1_450,)
Series: 'EmployeeNumber' [i64]
[
	1
	2
	4
	5
	7
	8
	10
	11
	12
	13
	14
	15
	16
	18
	19
	20
	21
	22
	…
	2045
	2046
	2048
	2049
	2051
	2052
	2053
	2054
	2055
	2056
	2057
	2060
	2061
	2062
	2064
	2065
	2068
]
--------------------------------------------------
Column: EnvironmentSatisfaction (4 unique values)
shape: (4,)
Series: 'EnvironmentSatisfaction' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: Gender (2 unique values)
shape: (2,)
Series: 'Gender' [str]
[
	"Female"
	"Male"
]
--------------------------------------------------
Column: JobInvolvement (4 unique values)
shape: (4,)
Series: 'JobInvolvement' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: JobLevel (5 unique values)
shape: (5,)
Series: 'JobLevel' [i64]
[
	1
	2
	3
	4
	5
]
--------------------------------------------------
Column: JobRole (9 unique values)
shape: (9,)
Series: 'JobRole' [str]
[
	"Healthcare Representative"
	"Human Resources"
	"Laboratory Technician"
	"Manager"
	"Manufacturing Director"
	"Research Director"
	"Research Scientist"
	"Sales Executive"
	"Sales Representative"
]
--------------------------------------------------
Column: JobSatisfaction (4 unique values)
shape: (4,)
Series: 'JobSatisfaction' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: MaritalStatus (3 unique values)
shape: (3,)
Series: 'MaritalStatus' [str]
[
	"Divorced"
	"Married"
	"Single"
]
--------------------------------------------------
Column: MonthlyIncome (1329 unique values)
shape: (1_329,)
Series: 'MonthlyIncome' [i64]
[
	1009
	1051
	1052
	1081
	1091
	1102
	1118
	1129
	1200
	1223
	1232
	1261
	1274
	1281
	1359
	1393
	1416
	1483
	…
	19613
	19626
	19627
	19636
	19658
	19665
	19701
	19717
	19740
	19833
	19845
	19847
	19859
	19926
	19943
	19973
	19999
]
--------------------------------------------------
Column: NumCompaniesWorked (10 unique values)
shape: (10,)
Series: 'NumCompaniesWorked' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
]
--------------------------------------------------
Column: Over18 (1 unique values)
shape: (1,)
Series: 'Over18' [str]
[
	"Y"
]
--------------------------------------------------
Column: OverTime (2 unique values)
shape: (2,)
Series: 'OverTime' [str]
[
	"No"
	"Yes"
]
--------------------------------------------------
Column: PercentSalaryHike (15 unique values)
shape: (15,)
Series: 'PercentSalaryHike' [i64]
[
	11
	12
	13
	14
	15
	16
	17
	18
	19
	20
	21
	22
	23
	24
	25
]
--------------------------------------------------
Column: PerformanceRating (2 unique values)
shape: (2,)
Series: 'PerformanceRating' [i64]
[
	3
	4
]
--------------------------------------------------
Column: RelationshipSatisfaction (4 unique values)
shape: (4,)
Series: 'RelationshipSatisfaction' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: StandardHours (1 unique values)
shape: (1,)
Series: 'StandardHours' [i64]
[
	80
]
--------------------------------------------------
Column: StockOptionLevel (4 unique values)
shape: (4,)
Series: 'StockOptionLevel' [i64]
[
	0
	1
	2
	3
]
--------------------------------------------------
Column: TotalWorkingYears (40 unique values)
shape: (40,)
Series: 'TotalWorkingYears' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	…
	23
	24
	25
	26
	27
	28
	29
	30
	31
	32
	33
	34
	35
	36
	37
	38
	40
]
--------------------------------------------------
Column: TrainingTimesLastYear (7 unique values)
shape: (7,)
Series: 'TrainingTimesLastYear' [i64]
[
	0
	1
	2
	3
	4
	5
	6
]
--------------------------------------------------
Column: WorkLifeBalance (4 unique values)
shape: (4,)
Series: 'WorkLifeBalance' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: YearsAtCompany (36 unique values)
shape: (36,)
Series: 'YearsAtCompany' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	…
	19
	20
	21
	22
	23
	24
	25
	26
	27
	29
	30
	31
	32
	33
	34
	36
	37
]
--------------------------------------------------
Column: YearsInCurrentRole (19 unique values)
shape: (19,)
Series: 'YearsInCurrentRole' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	18
]
--------------------------------------------------
Column: YearsSinceLastPromotion (16 unique values)
shape: (16,)
Series: 'YearsSinceLastPromotion' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
]
--------------------------------------------------
Column: YearsWithCurrManager (18 unique values)
shape: (18,)
Series: 'YearsWithCurrManager' [i64]
[
	0
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
]
--------------------------------------------------
Column: Label (2 unique values)
shape: (2,)
Series: 'Label' [i64]
[
	0
	1
]
--------------------------------------------------