## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("mysql_scripts/data.csv")

df

shape: (799, 13)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ age      ┆ sex    ┆ occupation ┆ days_indoo ┆ … ┆ mood_swing ┆ coping_st ┆ work_inte ┆ social_we │
│ ---      ┆ ---    ┆ ---        ┆ rs         ┆   ┆ s          ┆ ruggles   ┆ rest      ┆ akness    │
│ str      ┆ str    ┆ str        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 20-25    ┆ Female ┆ Corporate  ┆ 1-14 days  ┆ … ┆ Medium     ┆ No        ┆ No        ┆ Yes       │
│ 30-Above ┆ Male   ┆ Others     ┆ 31-60 days ┆ … ┆ High       ┆ No        ┆ No        ┆ Yes       │
│ 30-Above ┆ Female ┆ Student    ┆ Go out     ┆ … ┆ Medium     ┆ Yes       ┆ Maybe     ┆ No        │
│          ┆        ┆            ┆ Every day  ┆   ┆            ┆           ┆           ┆           │
│ 25-30    ┆ Male   ┆ Others     ┆ 1-14 days  ┆ … ┆ Medium     ┆ No        ┆ Maybe     ┆ Yes       │
│ 16-20    ┆ Female ┆ Student    ┆ More than  ┆ … ┆ Medium     ┆ Yes       ┆ Maybe     ┆ No        │
│          ┆        ┆            ┆ 2 months   ┆   ┆            ┆           ┆           ┆           │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 30-Above ┆ Female ┆ Housewife  ┆ Go out     ┆ … ┆ Low        ┆ No        ┆ No        ┆ Yes       │
│          ┆        ┆            ┆ Every day  ┆   ┆            ┆           ┆           ┆           │
│ 25-30    ┆ Male   ┆ Student    ┆ Go out     ┆ … ┆ High       ┆ Yes       ┆ Maybe     ┆ No        │
│          ┆        ┆            ┆ Every day  ┆   ┆            ┆           ┆           ┆           │
│ 20-25    ┆ Male   ┆ Others     ┆ Go out     ┆ … ┆ Medium     ┆ Yes       ┆ No        ┆ Maybe     │
│          ┆        ┆            ┆ Every day  ┆   ┆            ┆           ┆           ┆           │
│ 30-Above ┆ Female ┆ Housewife  ┆ 1-14 days  ┆ … ┆ High       ┆ No        ┆ Yes       ┆ Yes       │
│ 30-Above ┆ Male   ┆ Corporate  ┆ 15-30 days ┆ … ┆ Medium     ┆ No        ┆ Maybe     ┆ No        │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Retrieve Basic Information About DataFrame

In [4]:
print(df.shape)
print(df.dtypes)

(799, 13)
[String, String, String, String, String, String, String, String, String, String, String, String, String]

### Display Summary Statistics for All Columns

In [5]:
summary = df.describe()
print(summary)

shape: (9, 14)
┌────────────┬──────────┬────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ age      ┆ sex    ┆ occupation ┆ … ┆ mood_swing ┆ coping_st ┆ work_inte ┆ social_we │
│ ---        ┆ ---      ┆ ---    ┆ ---        ┆   ┆ s          ┆ ruggles   ┆ rest      ┆ akness    │
│ str        ┆ str      ┆ str    ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆          ┆        ┆            ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞════════════╪══════════╪════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 799      ┆ 799    ┆ 799        ┆ … ┆ 799        ┆ 799       ┆ 799       ┆ 799       │
│ null_count ┆ 0        ┆ 0      ┆ 0          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ mean       ┆ null     ┆ null   ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ std        ┆ null     ┆ null   ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ min        ┆ 16-20    ┆ Female ┆ Business   ┆ … ┆ High       ┆ No        ┆ Maybe     ┆ Maybe     │
│ 25%        ┆ null     ┆ null   ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null     ┆ null   ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null     ┆ null   ┆ null       ┆ … ┆ null       ┆ null      ┆ null      ┆ null      │
│ max        ┆ 30-Above ┆ Male   ┆ Student    ┆ … ┆ Medium     ┆ Yes       ┆ Yes       ┆ Yes       │
└────────────┴──────────┴────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

### Find Longest Text Length in Each Column

In [6]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 13)
┌─────┬─────┬────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ age ┆ sex ┆ occupation ┆ days_indoor ┆ … ┆ mood_swings ┆ coping_stru ┆ work_intere ┆ social_weak │
│ --- ┆ --- ┆ ---        ┆ s           ┆   ┆ ---         ┆ ggles       ┆ st          ┆ ness        │
│ u32 ┆ u32 ┆ u32        ┆ ---         ┆   ┆ u32         ┆ ---         ┆ ---         ┆ ---         │
│     ┆     ┆            ┆ u32         ┆   ┆             ┆ u32         ┆ u32         ┆ u32         │
╞═════╪═════╪════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 8   ┆ 6   ┆ 9          ┆ 18          ┆ … ┆ 6           ┆ 3           ┆ 5           ┆ 5           │
└─────┴─────┴────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### Retrieve Data Types of All Columns

In [7]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, String, String, String, String, String, String, String, String, String]

### Count Unique Values in Each Column

In [8]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                          Unique values in age : 4
                          Unique values in sex : 2
                   Unique values in occupation : 5
                 Unique values in days_indoors : 5
               Unique values in growing_stress : 3
      Unique values in quarantine_frustrations : 3
               Unique values in changes_habits : 3
        Unique values in mental_health_history : 3
                Unique values in weight_change : 3
                  Unique values in mood_swings : 3
             Unique values in coping_struggles : 2
                Unique values in work_interest : 3
              Unique values in social_weakness : 3

### Show Unique Values in Each Column

In [9]:
for col in df.columns:
    unique_values = df[col].unique()
    print(f"Column: {col}")
    print(f"Number of unique values ({unique_values.shape[0]}): {unique_values.to_list()}")

Column: age
Number of unique values (4): ['16-20', '20-25', '25-30', '30-Above']
Column: sex
Number of unique values (2): ['Male', 'Female']
Column: occupation
Number of unique values (5): ['Business', 'Corporate', 'Housewife', 'Others', 'Student']
Column: days_indoors
Number of unique values (5): ['More than 2 months', '31-60 days', 'Go out Every day', '1-14 days', '15-30 days']
Column: growing_stress
Number of unique values (3): ['Maybe', 'Yes', 'No']
Column: quarantine_frustrations
Number of unique values (3): ['Maybe', 'Yes', 'No']
Column: changes_habits
Number of unique values (3): ['Maybe', 'No', 'Yes']
Column: mental_health_history
Number of unique values (3): ['No', 'Yes', 'Maybe']
Column: weight_change
Number of unique values (3): ['Maybe', 'No', 'Yes']
Column: mood_swings
Number of unique values (3): ['Low', 'High', 'Medium']
Column: coping_struggles
Number of unique values (2): ['No', 'Yes']
Column: work_interest
Number of unique values (3): ['Maybe', 'No', 'Yes']
Column: social_weakness
Number of unique values (3): ['Maybe', 'Yes', 'No']

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

### List Unique Values for Select Columns/Features

In [11]:
cols_2_check = [

]

for col in cols_2_check:
    unique_values = df[col].unique().sort().to_list()
    print(f"Column: {col} [{len(unique_values)}]")
    print(f"Unique values: {unique_values}\n")

### Show Number of Missing Values in Each Column

In [12]:
print("Missing values in each column")

for col in df.columns:
    missing_count = df[col].is_null().sum()
    print(f"{col}: {missing_count}")

Missing values in each column
age: 0
sex: 0
occupation: 0
days_indoors: 0
growing_stress: 0
quarantine_frustrations: 0
changes_habits: 0
mental_health_history: 0
weight_change: 0
mood_swings: 0
coping_struggles: 0
work_interest: 0
social_weakness: 0