## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("pg_scripts/data.csv",
                 ignore_errors=True)

df

shape: (172_838, 15)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ accessed_d ┆ duration_ ┆ network_p ┆ ip        ┆ … ┆ sales    ┆ returned ┆ returned_ ┆ pay_metho │
│ ate        ┆ secs      ┆ rotocol   ┆ ---       ┆   ┆ ---      ┆ ---      ┆ amount    ┆ d         │
│ ---        ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64      ┆ str      ┆ ---       ┆ ---       │
│ str        ┆ i64       ┆ str       ┆           ┆   ┆          ┆          ┆ f64       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 2017-03-14 ┆ 2533      ┆ TCP       ┆ 1.10.195. ┆ … ┆ 261.96   ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:57.1 ┆           ┆           ┆ 126       ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4034      ┆ TCP       ┆ 1.1.217.2 ┆ … ┆ 731.94   ┆ No       ┆ 0.0       ┆ Debit     │
│ 17:43:57.1 ┆           ┆           ┆ 11        ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 1525      ┆ TCP       ┆ 1.115.198 ┆ … ┆ 14.62    ┆ No       ┆ 0.0       ┆ Cash      │
│ 17:43:26.1 ┆           ┆           ┆ .107      ┆   ┆          ┆          ┆           ┆           │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4572      ┆ TCP       ┆ 1.121.152 ┆ … ┆ 957.5775 ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:26.1 ┆           ┆           ┆ .143      ┆   ┆          ┆          ┆           ┆ Card      │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 3652      ┆ TCP       ┆ 1.123.135 ┆ … ┆ 22.368   ┆ No       ┆ 0.0       ┆ Cash      │
│ 18:17:09.0 ┆           ┆           ┆ .213      ┆   ┆          ┆          ┆           ┆           │
│ 05         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 2017-03-16 ┆ 4372      ┆ TCP       ┆ 94.197.12 ┆ … ┆ 0.0      ┆ Yes      ┆ 143.36    ┆ Debit     │
│ 11:42:01.2 ┆           ┆           ┆ 1.229     ┆   ┆          ┆          ┆           ┆ Card      │
│ 98         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 2167      ┆ TCP       ┆ 129.110.2 ┆ … ┆ 15.15    ┆ No       ┆ 0.0       ┆ Cash      │
│ 12:10:17.3 ┆           ┆           ┆ 41.72     ┆   ┆          ┆          ┆           ┆           │
│ 40         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 2725      ┆ TCP       ┆ 185.119.2 ┆ … ┆ 600.16   ┆ No       ┆ 0.0       ┆ Credit    │
│ 12:10:17.3 ┆           ┆           ┆ 52.121    ┆   ┆          ┆          ┆           ┆ Card      │
│ 40         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 3728      ┆ TCP       ┆ 185.145.1 ┆ … ┆ 75.75    ┆ No       ┆ 0.0       ┆ Cash      │
│ 15:52:58.3 ┆           ┆           ┆ 07.23     ┆   ┆          ┆          ┆           ┆           │
│ 42         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 3420      ┆ TCP       ┆ 202.69.12 ┆ … ┆ 23.46    ┆ No       ┆ 0.0       ┆ Credit    │
│ 15:52:58.3 ┆           ┆           ┆ .251      ┆   ┆          ┆          ┆           ┆ Card      │
│ 42         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 15)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ accessed_d ┆ duration_ ┆ network_p ┆ ip        ┆ … ┆ sales    ┆ returned ┆ returned_ ┆ pay_metho │
│ ate        ┆ secs      ┆ rotocol   ┆ ---       ┆   ┆ ---      ┆ ---      ┆ amount    ┆ d         │
│ ---        ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64      ┆ str      ┆ ---       ┆ ---       │
│ str        ┆ i64       ┆ str       ┆           ┆   ┆          ┆          ┆ f64       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 2017-03-14 ┆ 2533      ┆ TCP       ┆ 1.10.195. ┆ … ┆ 261.96   ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:57.1 ┆           ┆           ┆ 126       ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4034      ┆ TCP       ┆ 1.1.217.2 ┆ … ┆ 731.94   ┆ No       ┆ 0.0       ┆ Debit     │
│ 17:43:57.1 ┆           ┆           ┆ 11        ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 1525      ┆ TCP       ┆ 1.115.198 ┆ … ┆ 14.62    ┆ No       ┆ 0.0       ┆ Cash      │
│ 17:43:26.1 ┆           ┆           ┆ .107      ┆   ┆          ┆          ┆           ┆           │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4572      ┆ TCP       ┆ 1.121.152 ┆ … ┆ 957.5775 ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:26.1 ┆           ┆           ┆ .143      ┆   ┆          ┆          ┆           ┆ Card      │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 3652      ┆ TCP       ┆ 1.123.135 ┆ … ┆ 22.368   ┆ No       ┆ 0.0       ┆ Cash      │
│ 18:17:09.0 ┆           ┆           ┆ .213      ┆   ┆          ┆          ┆           ┆           │
│ 05         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

### Retrieve Basic Information About DataFrame

In [5]:
print(df.shape)
print(df.dtypes)

(172838, 15)
[String, Int64, String, String, Int64, String, Int64, String, String, String, String, Float64, String, Float64, String]

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ accessed_ ┆ duration_ ┆ network_p ┆ … ┆ sales     ┆ returned ┆ returned_ ┆ pay_metho │
│ ---       ┆ date      ┆ secs      ┆ rotocol   ┆   ┆ ---       ┆ ---      ┆ amount    ┆ d         │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ str      ┆ ---       ┆ ---       │
│           ┆ str       ┆ f64       ┆ str       ┆   ┆           ┆          ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 172838    ┆ 172838.0  ┆ 172838    ┆ … ┆ 172838.0  ┆ 172838   ┆ 172838.0  ┆ 172838    │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0        ┆ 0.0       ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ null      ┆ 3248.0318 ┆ null      ┆ … ┆ 411.34644 ┆ null     ┆ 74.012092 ┆ null      │
│           ┆           ┆ 27        ┆           ┆   ┆ 9         ┆          ┆           ┆           │
│ std       ┆ null      ┆ 1010.8722 ┆ null      ┆ … ┆ 785.53786 ┆ null     ┆ 364.44643 ┆ null      │
│           ┆           ┆ 7         ┆           ┆   ┆ 8         ┆          ┆ 5         ┆           │
│ min       ┆ 2017-03-1 ┆ 1500.0    ┆ HTTP      ┆ … ┆ 0.0       ┆ No       ┆ 0.0       ┆ Cash      │
│           ┆ 4 17:43:2 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 6.135     ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 25%       ┆ null      ┆ 2371.0    ┆ null      ┆ … ┆ 5.23      ┆ null     ┆ 0.0       ┆ null      │
│ 50%       ┆ null      ┆ 3246.0    ┆ null      ┆ … ┆ 46.92     ┆ null     ┆ 0.0       ┆ null      │
│ 75%       ┆ null      ┆ 4124.0    ┆ null      ┆ … ┆ 600.16    ┆ null     ┆ 0.0       ┆ null      │
│ max       ┆ 2017-03-2 ┆ 5000.0    ┆ UDP       ┆ … ┆ 11199.968 ┆ Yes      ┆ 22638.48  ┆ Others    │
│           ┆ 1 23:59:3 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0.671     ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 10)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬──────────┬────────────┐
│ accessed_d ┆ network_pr ┆ ip  ┆ accessed_f ┆ … ┆ membership ┆ language_i ┆ returned ┆ pay_method │
│ ate        ┆ otocol     ┆ --- ┆ rom        ┆   ┆ ---        ┆ n_log      ┆ ---      ┆ ---        │
│ ---        ┆ ---        ┆ u32 ┆ ---        ┆   ┆ u32        ┆ ---        ┆ u32      ┆ u32        │
│ u32        ┆ u32        ┆     ┆ u32        ┆   ┆            ┆ u32        ┆          ┆            │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪══════════╪════════════╡
│ 23         ┆ 6          ┆ 16  ┆ 15         ┆ … ┆ 13         ┆ 10         ┆ 3        ┆ 11         │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴──────────┴────────────┘

### Null Counts

In [18]:
for col in df.columns:
    print(f"{col}: {df[col].is_null().sum()}")

accessed_date: 0
duration_secs: 0
network_protocol: 0
ip: 0
bytes: 0
accessed_from: 0
age: 88124
gender: 0
country: 0
membership: 0
language_in_log: 0
sales: 0
returned: 0
returned_amount: 0
pay_method: 0

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, Int64, String, String, Int64, String, Int64, String, String, String, String, Float64, String, Float64, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                Unique values in accessed_date : 81747
                Unique values in duration_secs : 3501
             Unique values in network_protocol : 5
                           Unique values in ip : 137199
                        Unique values in bytes : 4695
                Unique values in accessed_from : 8
                          Unique values in age : 53
                       Unique values in gender : 3
                      Unique values in country : 27
                   Unique values in membership : 3
              Unique values in language_in_log : 30
                        Unique values in sales : 5600
                     Unique values in returned : 2
              Unique values in returned_amount : 2135
                   Unique values in pay_method : 4

### List Unique Values in Columns With Fewer Than 35 Unique Values

In [10]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 35:
        print(f"{col}: {unique_values}")

network_protocol: shape: (5,)
Series: 'network_protocol' [str]
[
	"UDP  "
	"HTTP"
	"HTTP  "
	"ICMP "
	"TCP  "
]
accessed_from: shape: (8,)
Series: 'accessed_from' [str]
[
	"Chrome"
	"Safari"
	"Others"
	"Microsoft Edge"
	"IOS App"
	"SafFRi"
	"Android App"
	"Mozilla Firefox"
]
gender: shape: (3,)
Series: 'gender' [str]
[
	"Female"
	"Unknown"
	"Male"
]
country: shape: (27,)
Series: 'country' [str]
[
	"PL"
	"IE"
	"GB"
	"JP"
	"CO"
	…
	"PE"
	"CN"
	"NO"
	"IN"
	"DK"
]
membership: shape: (3,)
Series: 'membership' [str]
[
	"Not Logged In"
	"Normal"
	"Premium"
]
language_in_log: shape: (30,)
Series: 'language_in_log' [str]
[
	"Russian"
	"Slovak"
	"Dutch"
	"tegulu"
	"malay"
	…
	"slovene"
	"malayalam"
	"italian"
	"urdu"
	"macedonian"
]
returned: shape: (2,)
Series: 'returned' [str]
[
	"No"
	"Yes"
]
pay_method: shape: (4,)
Series: 'pay_method' [str]
[
	"Others"
	"Debit Card"
	"Credit Card"
	"Cash"
]

In [11]:
pl.Config.set_tbl_rows(100)

df['country'].unique()

shape: (27,)
Series: 'country' [str]
[
	"NO"
	"ZA"
	"FI"
	"KR"
	"IE"
	"AU"
	"PL"
	"FR"
	"PE"
	"MX"
	"IN"
	"CO"
	"AE"
	"AT"
	"IT"
	"PR"
	"SE"
	"DK"
	"JP"
	"CN"
	"DE"
	"US"
	"AR"
	"RU"
	"CH"
	"GB"
	"CA"
]

In [12]:
pl.Config.set_tbl_rows(100)

df['language_in_log'].unique()

shape: (30,)
Series: 'language_in_log' [str]
[
	"Slovak"
	"Russian"
	"swahili"
	"Spanish"
	"polish"
	"serbian"
	"Italian"
	"marathi"
	"slovene"
	"romanian"
	"urdu"
	"Portuguese"
	"italian"
	"Thai"
	"mongolian"
	"English"
	"persian"
	"macedonian"
	"tegulu"
	"swedish"
	"norwegian"
	"Japanese"
	"German"
	"Chinese"
	"Dutch"
	"French"
	"Arabic"
	"nepali"
	"malay"
	"malayalam"
]

### Check Distribution of Numerical Columns

In [13]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

duration_secs
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ duration_secs │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 172838.0      │
│ null_count ┆ 0.0           │
│ mean       ┆ 3248.031827   │
│ std        ┆ 1010.87227    │
│ min        ┆ 1500.0        │
│ 25%        ┆ 2371.0        │
│ 50%        ┆ 3246.0        │
│ 75%        ┆ 4124.0        │
│ max        ┆ 5000.0        │
└────────────┴───────────────┘


bytes
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ bytes       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 172838.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ 1535.206858 │
│ std        ┆ 6349.555845 │
│ min        ┆ 28.0        │
│ 25%        ┆ 264.0       │
│ 50%        ┆ 589.0       │
│ 75%        ┆ 2430.0      │
│ max        ┆ 932858.0    │
└────────────┴─────────────┘


age
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ age       │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 84714.0   │
│ null_count ┆ 88124.0   │
│ mean       ┆ 43.438263 │
│ std        ┆ 14.980135 │
│ min        ┆ 18.0      │
│ 25%        ┆ 30.0      │
│ 50%        ┆ 43.0      │
│ 75%        ┆ 56.0      │
│ max        ┆ 69.0      │
└────────────┴───────────┘


sales
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ sales      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 172838.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 411.346449 │
│ std        ┆ 785.537868 │
│ min        ┆ 0.0        │
│ 25%        ┆ 5.23       │
│ 50%        ┆ 46.92      │
│ 75%        ┆ 600.16     │
│ max        ┆ 11199.968  │
└────────────┴────────────┘


returned_amount
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ returned_amount │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 172838.0        │
│ null_count ┆ 0.0             │
│ mean       ┆ 74.012092       │
│ std        ┆ 364.446435      │
│ min        ┆ 0.0             │
│ 25%        ┆ 0.0             │
│ 50%        ┆ 0.0             │
│ 75%        ┆ 0.0             │
│ max        ┆ 22638.48        │
└────────────┴─────────────────┘

In [14]:
numerical_cols

['duration_secs', 'bytes', 'age', 'sales', 'returned_amount']

In [15]:
string_columns

['accessed_date',
 'network_protocol',
 'ip',
 'accessed_from',
 'gender',
 'country',
 'membership',
 'language_in_log',
 'returned',
 'pay_method']

In [16]:
columns_to_check = [
    "network_protocol",
    "accessed_from",
    "age",
    "gender",
    "country",
    "membership",
    "language_in_log",
    "returned",
    "pay_method"
]

for col in columns_to_check:
    unique_values = df[col].unique().to_list()
    print(f"Unique values in {col}: {unique_values}")

Unique values in network_protocol: ['HTTP', 'HTTP  ', 'TCP  ', 'UDP  ', 'ICMP ']
Unique values in accessed_from: ['Android App', 'SafFRi', 'IOS App', 'Mozilla Firefox', 'Chrome', 'Others', 'Microsoft Edge', 'Safari']
Unique values in age: [None, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
Unique values in gender: ['Female', 'Male', 'Unknown']
Unique values in country: ['CN', 'IE', 'PE', 'SE', 'ZA', 'FI', 'CH', 'FR', 'AU', 'PL', 'AR', 'PR', 'AT', 'IN', 'AE', 'NO', 'GB', 'KR', 'MX', 'DK', 'RU', 'IT', 'CA', 'DE', 'US', 'CO', 'JP']
Unique values in membership: ['Premium', 'Not Logged In', 'Normal']
Unique values in language_in_log: ['Japanese', 'Dutch', 'Spanish', 'polish', 'Russian', 'romanian', 'norwegian', 'italian', 'marathi', 'slovene', 'Italian', 'swahili', 'swedish', 'Thai', 'English', 'urdu', 'persian', 'Portuguese', 'tegulu', 'French', 'malayalam', 'Chinese', 'Arabic', 'German', 'nepali', 'mongolian', 'malay', 'serbian', 'Slovak', 'macedonian']
Unique values in returned: ['No', 'Yes']
Unique values in pay_method: ['Cash', 'Debit Card', 'Others', 'Credit Card']