In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("pg_scripts/Orders.csv")

df

    order_id  order_date customer_name        state_name city_name
0    B-26055  10-03-2018     Harivansh     Uttar Pradesh   Mathura
1    B-25993  03-02-2018        Madhav             Delhi     Delhi
2    B-25973  24-01-2018   Madan Mohan     Uttar Pradesh   Mathura
3    B-25923  27-12-2018         Gopal       Maharashtra    Mumbai
4    B-25757  21-08-2018      Vishakha    Madhya Pradesh    Indore
..       ...         ...           ...               ...       ...
495  B-25742  03-08-2018        Ashwin               Goa       Goa
496  B-26088  26-03-2018        Bhavna            Sikkim   Gangtok
497  B-25707  01-07-2018       Shivani       Maharashtra    Mumbai
498  B-25758  22-08-2018       Shubham  Himachal Pradesh     Simla
499  B-26095  28-03-2018       Monisha         Rajasthan    Jaipur

[500 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    object
 1   order_date     500 non-null    object
 2   customer_name  500 non-null    object
 3   state_name     500 non-null    object
 4   city_name      500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

In [4]:
df.describe()

       order_id  order_date customer_name   state_name city_name
count       500         500           500          500       500
unique      500         307           336           19        25
top     B-26055  24-11-2018        Shreya  Maharashtra    Indore
freq          1           7             6           94        71

In [5]:
df.nunique()

order_id         500
order_date       307
customer_name    336
state_name        19
city_name         25
dtype: int64

In [6]:
# Count null values per column
null_counts = df.isnull().sum()
null_counts

order_id         0
order_date       0
customer_name    0
state_name       0
city_name        0
dtype: int64

In [7]:
cutoff = 100

for col in df.columns:
    unique_vals = df[col].unique()
    if len(unique_vals) < cutoff:
        print(f"{col} ({len(unique_vals)}): {unique_vals}")
    else:
        print(f"{col} ({len(unique_vals)})")

order_id (500)
order_date (307)
customer_name (336)
state_name (19): ['Uttar Pradesh' 'Delhi' 'Maharashtra' 'Madhya Pradesh' 'Andhra Pradesh'
 'Gujarat' 'Bihar' 'Himachal Pradesh' 'Punjab' 'Kerala ' 'Nagaland'
 'Haryana' 'Rajasthan' 'Karnataka' 'Tamil Nadu' 'West Bengal'
 'Jammu and Kashmir' 'Goa' 'Sikkim']
city_name (25): ['Mathura' 'Delhi' 'Mumbai' 'Indore' 'Prayagraj' 'Pune' 'Hyderabad'
 'Surat' 'Ahmedabad' 'Patna' 'Simla' 'Chandigarh' 'Bhopal'
 'Thiruvananthapuram' 'Kohima' 'Udaipur' 'Bangalore' 'Lucknow' 'Chennai'
 'Kolkata' 'Kashmir' 'Jaipur' 'Amritsar' 'Goa' 'Gangtok']

In [8]:
import pandas as pd
from tabulate import tabulate

def find_and_display_longest_strings(df):
    # Initialize a list to store results
    results = []
    
    # Iterate through columns
    for column in df.columns:
        # Check if the column has string (object) data type
        if df[column].dtype == 'object':
            # Find the longest string in the column
            longest_string_index = df[column].astype(str).str.len().idxmax()
            longest_string = df.loc[longest_string_index, column]
            # Store the result
            results.append([column, longest_string, len(longest_string)])
    
    # Create a DataFrame from the results
    result_df = pd.DataFrame(results, columns=['Column', 'Longest String', 'Length'])
    
    # Sort the results by length in descending order
    result_df = result_df.sort_values('Length', ascending=False).reset_index(drop=True)
    
    # Display the results in a pretty table
    print("\nLongest Strings in Each Column:")
    print(tabulate(result_df, headers='keys', tablefmt='pretty', showindex=False))
    
    return result_df


result = find_and_display_longest_strings(df)

Longest Strings in Each Column:
+---------------+--------------------+--------+
|    Column     |   Longest String   | Length |
+---------------+--------------------+--------+
|   city_name   | Thiruvananthapuram |   18   |
|  state_name   | Jammu and Kashmir  |   17   |
| customer_name |    Divyeshkumar    |   12   |
|  order_date   |     10-03-2018     |   10   |
|   order_id    |      B-26055       |   7    |
+---------------+--------------------+--------+