## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys, os
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

## Exploratory Data Analysis with Polars

### Load CSV File into Polars DataFrame

In [3]:
import polars as pl
import os

def read_and_concatenate_parquet(folder_path):
    # List all Parquet files in the folder
    files = [f for f in os.listdir(folder_path) if f.endswith('.parquet')]

    df_list = []
    for file in files:
        file_path = os.path.join(folder_path, file)
        df_interim = pl.read_parquet(file_path)

        # Only cast columns that are numeric (Int64 or Float64) to Float64,
        # leaving others (e.g., strings, dates) unchanged.
        df_interim = df_interim.with_columns([
            pl.col(col).cast(pl.Float64) if df_interim.schema[col] in (pl.Int64, pl.Float64) else pl.col(col)
            for col in df_interim.columns
        ])

        df_list.append(df_interim)

    # Concatenate all DataFrames into one
    concatenated_df = pl.concat(df_list)

    return concatenated_df

In [4]:
folder_path = 'data'
df = read_and_concatenate_parquet(folder_path)
df

shape: (29_193_782, 62)
┌─────────────┬────────────┬────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ FlightDate  ┆ Airline    ┆ Origin ┆ Dest ┆ … ┆ ArrTimeBlk ┆ DistanceGr ┆ DivAirport ┆ __index_le │
│ ---         ┆ ---        ┆ ---    ┆ ---  ┆   ┆ ---        ┆ oup        ┆ Landings   ┆ vel_0__    │
│ datetime[ns ┆ str        ┆ str    ┆ str  ┆   ┆ str        ┆ ---        ┆ ---        ┆ ---        │
│ ]           ┆            ┆        ┆      ┆   ┆            ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════════╪════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2018-01-23  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 0.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-24  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 1.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-25  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 2.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-26  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 3.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-27  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1500-1559  ┆ 1.0        ┆ 0.0        ┆ 4.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ …           ┆ …          ┆ …      ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2021-06-01  ┆ Southwest  ┆ BNA    ┆ MDW  ┆ … ┆ 1400-1459  ┆ 2.0        ┆ 0.0        ┆ 573774.0   │
│ 00:00:00    ┆ Airlines   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│             ┆ Co.        ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2021-06-01  ┆ Southwest  ┆ BNA    ┆ MDW  ┆ … ┆ 0900-0959  ┆ 2.0        ┆ 0.0        ┆ 573775.0   │
│ 00:00:00    ┆ Airlines   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│             ┆ Co.        ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2021-06-01  ┆ Southwest  ┆ BNA    ┆ MIA  ┆ … ┆ 1100-1159  ┆ 4.0        ┆ 0.0        ┆ 573776.0   │
│ 00:00:00    ┆ Airlines   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│             ┆ Co.        ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2021-06-01  ┆ Southwest  ┆ BNA    ┆ MIA  ┆ … ┆ 1600-1659  ┆ 4.0        ┆ 0.0        ┆ 573777.0   │
│ 00:00:00    ┆ Airlines   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│             ┆ Co.        ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2021-06-01  ┆ Southwest  ┆ BNA    ┆ MKE  ┆ … ┆ 2000-2059  ┆ 2.0        ┆ 0.0        ┆ 573778.0   │
│ 00:00:00    ┆ Airlines   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│             ┆ Co.        ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
└─────────────┴────────────┴────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
column_data_types = zip(df.columns, df.dtypes)

for column, dtype in column_data_types:
    print(f"{column}:\t\t{dtype}")

FlightDate:		Datetime(time_unit='ns', time_zone=None)
Airline:		String
Origin:		String
Dest:		String
Cancelled:		Boolean
Diverted:		Boolean
CRSDepTime:		Float64
DepTime:		Float64
DepDelayMinutes:		Float64
DepDelay:		Float64
ArrTime:		Float64
ArrDelayMinutes:		Float64
AirTime:		Float64
CRSElapsedTime:		Float64
ActualElapsedTime:		Float64
Distance:		Float64
Year:		Float64
Quarter:		Float64
Month:		Float64
DayofMonth:		Float64
DayOfWeek:		Float64
Marketing_Airline_Network:		String
Operated_or_Branded_Code_Share_Partners:		String
DOT_ID_Marketing_Airline:		Float64
IATA_Code_Marketing_Airline:		String
Flight_Number_Marketing_Airline:		Float64
Operating_Airline:		String
DOT_ID_Operating_Airline:		Float64
IATA_Code_Operating_Airline:		String
Tail_Number:		String
Flight_Number_Operating_Airline:		Float64
OriginAirportID:		Float64
OriginAirportSeqID:		Float64
OriginCityMarketID:		Float64
OriginCityName:		String
OriginState:		String
OriginStateFips:		Float64
OriginStateName:		String
OriginWac:		Float64
DestAirportID:		Float64
DestAirportSeqID:		Float64
DestCityMarketID:		Float64
DestCityName:		String
DestState:		String
DestStateFips:		Float64
DestStateName:		String
DestWac:		Float64
DepDel15:		Float64
DepartureDelayGroups:		Float64
DepTimeBlk:		String
TaxiOut:		Float64
WheelsOff:		Float64
WheelsOn:		Float64
TaxiIn:		Float64
CRSArrTime:		Float64
ArrDelay:		Float64
ArrDel15:		Float64
ArrivalDelayGroups:		Float64
ArrTimeBlk:		String
DistanceGroup:		Float64
DivAirportLandings:		Float64
__index_level_0__:		Float64

### Display First Few Rows to Understand Structure of Data

In [6]:
print(df.head())

shape: (5, 62)
┌─────────────┬────────────┬────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ FlightDate  ┆ Airline    ┆ Origin ┆ Dest ┆ … ┆ ArrTimeBlk ┆ DistanceGr ┆ DivAirport ┆ __index_le │
│ ---         ┆ ---        ┆ ---    ┆ ---  ┆   ┆ ---        ┆ oup        ┆ Landings   ┆ vel_0__    │
│ datetime[ns ┆ str        ┆ str    ┆ str  ┆   ┆ str        ┆ ---        ┆ ---        ┆ ---        │
│ ]           ┆            ┆        ┆      ┆   ┆            ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪════════════╪════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2018-01-23  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 0.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-24  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 1.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-25  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 2.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-26  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1300-1359  ┆ 1.0        ┆ 0.0        ┆ 3.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
│ 2018-01-27  ┆ Endeavor   ┆ ABY    ┆ ATL  ┆ … ┆ 1500-1559  ┆ 1.0        ┆ 0.0        ┆ 4.0        │
│ 00:00:00    ┆ Air Inc.   ┆        ┆      ┆   ┆            ┆            ┆            ┆            │
└─────────────┴────────────┴────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [7]:
print(df.shape)
print(df.dtypes)

(29193782, 62)
[Datetime(time_unit='ns', time_zone=None), String, String, String, Boolean, Boolean, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, String, Float64, String, String, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Float64, Float64]

### Display Summary Statistics for All Columns

In [8]:
summary = df.describe()
print(summary)

shape: (9, 63)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ FlightDat ┆ Airline   ┆ Origin   ┆ … ┆ ArrTimeBl ┆ DistanceG ┆ DivAirpor ┆ __index_l │
│ ---       ┆ e         ┆ ---       ┆ ---      ┆   ┆ k         ┆ roup      ┆ tLandings ┆ evel_0__  │
│ str       ┆ ---       ┆ str       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆           ┆          ┆   ┆ str       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 29193782  ┆ 29193782  ┆ 29193782 ┆ … ┆ 29193782  ┆ 2.9193782 ┆ 2.9193692 ┆ 2.9193782 │
│           ┆           ┆           ┆          ┆   ┆           ┆ e7        ┆ e7        ┆ e7        │
│ null_coun ┆ 0         ┆ 0         ┆ 0        ┆ … ┆ 0         ┆ 0.0       ┆ 90.0      ┆ 0.0       │
│ t         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ 2020-04-2 ┆ null      ┆ null     ┆ … ┆ null      ┆ 3.593297  ┆ 0.003506  ┆ 283958.04 │
│           ┆ 3 22:27:0 ┆           ┆          ┆   ┆           ┆           ┆           ┆ 478       │
│           ┆ 3.485603  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ std       ┆ null      ┆ null      ┆ null     ┆ … ┆ null      ┆ 2.287532  ┆ 0.112753  ┆ 178810.90 │
│           ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆ 5112      │
│ min       ┆ 2018-01-0 ┆ Air       ┆ ABE      ┆ … ┆ 0001-0559 ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│           ┆ 1         ┆ Wisconsin ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 00:00:00  ┆ Airlines  ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ Corp      ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%       ┆ 2019-03-1 ┆ null      ┆ null     ┆ … ┆ null      ┆ 2.0       ┆ 0.0       ┆ 132699.0  │
│           ┆ 8         ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 00:00:00  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 50%       ┆ 2020-02-0 ┆ null      ┆ null     ┆ … ┆ null      ┆ 3.0       ┆ 0.0       ┆ 267305.0  │
│           ┆ 8         ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 00:00:00  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 75%       ┆ 2021-07-1 ┆ null      ┆ null     ┆ … ┆ null      ┆ 5.0       ┆ 0.0       ┆ 422541.0  │
│           ┆ 7         ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 00:00:00  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ max       ┆ 2022-07-3 ┆ Virgin    ┆ YUM      ┆ … ┆ 2300-2359 ┆ 11.0      ┆ 9.0       ┆ 717683.0  │
│           ┆ 1         ┆ America   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ 00:00:00  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Counting Null Values in Each Column

In [9]:
for col in df.columns:
    print(f"{col} : {df[col].is_null().sum()}")

FlightDate : 0
Airline : 0
Origin : 0
Dest : 0
Cancelled : 0
Diverted : 0
CRSDepTime : 0
DepTime : 761652
DepDelayMinutes : 763084
DepDelay : 763084
ArrTime : 786177
ArrDelayMinutes : 846183
AirTime : 852561
CRSElapsedTime : 22
ActualElapsedTime : 845637
Distance : 0
Year : 0
Quarter : 0
Month : 0
DayofMonth : 0
DayOfWeek : 0
Marketing_Airline_Network : 0
Operated_or_Branded_Code_Share_Partners : 0
DOT_ID_Marketing_Airline : 0
IATA_Code_Marketing_Airline : 0
Flight_Number_Marketing_Airline : 0
Operating_Airline : 0
DOT_ID_Operating_Airline : 0
IATA_Code_Operating_Airline : 0
Tail_Number : 267613
Flight_Number_Operating_Airline : 0
OriginAirportID : 0
OriginAirportSeqID : 0
OriginCityMarketID : 0
OriginCityName : 0
OriginState : 0
OriginStateFips : 0
OriginStateName : 0
OriginWac : 0
DestAirportID : 0
DestAirportSeqID : 0
DestCityMarketID : 0
DestCityName : 0
DestState : 0
DestStateFips : 0
DestStateName : 0
DestWac : 0
DepDel15 : 763084
DepartureDelayGroups : 763084
DepTimeBlk : 0
TaxiOut : 780561
WheelsOff : 780551
WheelsOn : 793133
TaxiIn : 793143
CRSArrTime : 0
ArrDelay : 846183
ArrDel15 : 846183
ArrivalDelayGroups : 846183
ArrTimeBlk : 0
DistanceGroup : 0
DivAirportLandings : 90
__index_level_0__ : 0

### Find Longest Text Length in Each Column

In [10]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 17)
┌─────────┬────────┬──────┬───────────────┬───┬───────────┬──────────────┬────────────┬────────────┐
│ Airline ┆ Origin ┆ Dest ┆ Marketing_Air ┆ … ┆ DestState ┆ DestStateNam ┆ DepTimeBlk ┆ ArrTimeBlk │
│ ---     ┆ ---    ┆ ---  ┆ line_Network  ┆   ┆ ---       ┆ e            ┆ ---        ┆ ---        │
│ u32     ┆ u32    ┆ u32  ┆ ---           ┆   ┆ u32       ┆ ---          ┆ u32        ┆ u32        │
│         ┆        ┆      ┆ u32           ┆   ┆           ┆ u32          ┆            ┆            │
╞═════════╪════════╪══════╪═══════════════╪═══╪═══════════╪══════════════╪════════════╪════════════╡
│ 41      ┆ 3      ┆ 3    ┆ 2             ┆ … ┆ 2         ┆ 46           ┆ 9          ┆ 9          │
└─────────┴────────┴──────┴───────────────┴───┴───────────┴──────────────┴────────────┴────────────┘

### Retrieve Data Types of All Columns

In [11]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Datetime(time_unit='ns', time_zone=None), String, String, String, Boolean, Boolean, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, String, Float64, String, String, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, Float64, Float64, Float64, String, String, Float64, String, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Float64, Float64]

### Count Unique Values in Each Column

In [12]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                   Unique values in FlightDate : 1673
                      Unique values in Airline : 28
                       Unique values in Origin : 388
                         Unique values in Dest : 388
                    Unique values in Cancelled : 2
                     Unique values in Diverted : 2
                   Unique values in CRSDepTime : 1425
                      Unique values in DepTime : 1441
              Unique values in DepDelayMinutes : 1863
                     Unique values in DepDelay : 2013
                      Unique values in ArrTime : 1441
              Unique values in ArrDelayMinutes : 1878
                      Unique values in AirTime : 700
               Unique values in CRSElapsedTime : 734
            Unique values in ActualElapsedTime : 734
                     Unique values in Distance : 1741
                         Unique values in Year : 5
                      Unique values in Quarter : 4
                        Unique values in Month : 12
                   Unique values in DayofMonth : 31
                    Unique values in DayOfWeek : 7
    Unique values in Marketing_Airline_Network : 11
Unique values in Operated_or_Branded_Code_Share_Partners : 16
     Unique values in DOT_ID_Marketing_Airline : 11
  Unique values in IATA_Code_Marketing_Airline : 11
Unique values in Flight_Number_Marketing_Airline : 7387
            Unique values in Operating_Airline : 28
     Unique values in DOT_ID_Operating_Airline : 28
  Unique values in IATA_Code_Operating_Airline : 28
                  Unique values in Tail_Number : 7090
Unique values in Flight_Number_Operating_Airline : 7411
              Unique values in OriginAirportID : 388
           Unique values in OriginAirportSeqID : 429
           Unique values in OriginCityMarketID : 362
               Unique values in OriginCityName : 381
                  Unique values in OriginState : 53
              Unique values in OriginStateFips : 53
              Unique values in OriginStateName : 53
                    Unique values in OriginWac : 53
                Unique values in DestAirportID : 388
             Unique values in DestAirportSeqID : 429
             Unique values in DestCityMarketID : 362
                 Unique values in DestCityName : 381
                    Unique values in DestState : 53
                Unique values in DestStateFips : 53
                Unique values in DestStateName : 53
                      Unique values in DestWac : 53
                     Unique values in DepDel15 : 3
         Unique values in DepartureDelayGroups : 16
                   Unique values in DepTimeBlk : 19
                      Unique values in TaxiOut : 203
                    Unique values in WheelsOff : 1441
                     Unique values in WheelsOn : 1441
                       Unique values in TaxiIn : 261
                   Unique values in CRSArrTime : 1440
                     Unique values in ArrDelay : 2053
                     Unique values in ArrDel15 : 3
           Unique values in ArrivalDelayGroups : 16
                   Unique values in ArrTimeBlk : 19
                Unique values in DistanceGroup : 11
           Unique values in DivAirportLandings : 6
            Unique values in __index_level_0__ : 717684

### Retrieve Unique Values in Column If There Are Fewer Than 100

In [13]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 20:
        print(f"'{col}' {len(unique_values)}: {unique_values}")

'Cancelled' 2: shape: (2,)
Series: 'Cancelled' [bool]
[
	false
	true
]
'Diverted' 2: shape: (2,)
Series: 'Diverted' [bool]
[
	false
	true
]
'Year' 5: shape: (5,)
Series: 'Year' [f64]
[
	2018.0
	2019.0
	2020.0
	2021.0
	2022.0
]
'Quarter' 4: shape: (4,)
Series: 'Quarter' [f64]
[
	1.0
	2.0
	3.0
	4.0
]
'Month' 12: shape: (12,)
Series: 'Month' [f64]
[
	1.0
	2.0
	3.0
	4.0
	5.0
	…
	8.0
	9.0
	10.0
	11.0
	12.0
]
'DayOfWeek' 7: shape: (7,)
Series: 'DayOfWeek' [f64]
[
	1.0
	2.0
	3.0
	4.0
	5.0
	6.0
	7.0
]
'Marketing_Airline_Network' 11: shape: (11,)
Series: 'Marketing_Airline_Network' [str]
[
	"F9"
	"UA"
	"HA"
	"AS"
	"AA"
	…
	"VX"
	"DL"
	"B6"
	"NK"
	"WN"
]
'Operated_or_Branded_Code_Share_Partners' 16: shape: (16,)
Series: 'Operated_or_Branded_Code_Share_Partners' [str]
[
	"B6"
	"AA"
	"DL"
	"AS"
	"AA_CODESHARE"
	…
	"F9"
	"WN"
	"AS_CODESHARE"
	"G4"
	"UA"
]
'DOT_ID_Marketing_Airline' 11: shape: (11,)
Series: 'DOT_ID_Marketing_Airline' [f64]
[
	19393.0
	19690.0
	19790.0
	19805.0
	19930.0
	…
	20368.0
	20409.0
	20416.0
	20436.0
	21171.0
]
'IATA_Code_Marketing_Airline' 11: shape: (11,)
Series: 'IATA_Code_Marketing_Airline' [str]
[
	"NK"
	"DL"
	"B6"
	"AA"
	"HA"
	…
	"AS"
	"VX"
	"WN"
	"F9"
	"G4"
]
'DepDel15' 3: shape: (3,)
Series: 'DepDel15' [f64]
[
	null
	0.0
	1.0
]
'DepartureDelayGroups' 16: shape: (16,)
Series: 'DepartureDelayGroups' [f64]
[
	null
	-2.0
	-1.0
	0.0
	1.0
	…
	8.0
	9.0
	10.0
	11.0
	12.0
]
'DepTimeBlk' 19: shape: (19,)
Series: 'DepTimeBlk' [str]
[
	"2100-2159"
	"2000-2059"
	"1700-1759"
	"0001-0559"
	"0900-0959"
	…
	"1400-1459"
	"1900-1959"
	"1100-1159"
	"0700-0759"
	"0600-0659"
]
'ArrDel15' 3: shape: (3,)
Series: 'ArrDel15' [f64]
[
	null
	0.0
	1.0
]
'ArrivalDelayGroups' 16: shape: (16,)
Series: 'ArrivalDelayGroups' [f64]
[
	null
	-2.0
	-1.0
	0.0
	1.0
	…
	8.0
	9.0
	10.0
	11.0
	12.0
]
'ArrTimeBlk' 19: shape: (19,)
Series: 'ArrTimeBlk' [str]
[
	"1600-1659"
	"1100-1159"
	"0900-0959"
	"2000-2059"
	"0600-0659"
	…
	"1900-1959"
	"0001-0559"
	"2100-2159"
	"1400-1459"
	"1500-1559"
]
'DistanceGroup' 11: shape: (11,)
Series: 'DistanceGroup' [f64]
[
	1.0
	2.0
	3.0
	4.0
	5.0
	…
	7.0
	8.0
	9.0
	10.0
	11.0
]
'DivAirportLandings' 6: shape: (6,)
Series: 'DivAirportLandings' [f64]
[
	null
	0.0
	1.0
	2.0
	3.0
	9.0
]

### Check Distribution of Numerical Columns

In [14]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

FlightDate
shape: (9, 2)
┌────────────┬────────────────────────────┐
│ statistic  ┆ FlightDate                 │
│ ---        ┆ ---                        │
│ str        ┆ str                        │
╞════════════╪════════════════════════════╡
│ count      ┆ 29193782                   │
│ null_count ┆ 0                          │
│ mean       ┆ 2020-04-23 22:27:03.485603 │
│ std        ┆ null                       │
│ min        ┆ 2018-01-01 00:00:00        │
│ 25%        ┆ 2019-03-18 00:00:00        │
│ 50%        ┆ 2020-02-08 00:00:00        │
│ 75%        ┆ 2021-07-17 00:00:00        │
│ max        ┆ 2022-07-31 00:00:00        │
└────────────┴────────────────────────────┘


Cancelled
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Cancelled   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 0.026624    │
│ std        ┆ null        │
│ min        ┆ 0.0         │
│ 25%        ┆ null        │
│ 50%        ┆ null        │
│ 75%        ┆ null        │
│ max        ┆ 1.0         │
└────────────┴─────────────┘


Diverted
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Diverted    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 0.002341    │
│ std        ┆ null        │
│ min        ┆ 0.0         │
│ 25%        ┆ null        │
│ 50%        ┆ null        │
│ 75%        ┆ null        │
│ max        ┆ 1.0         │
└────────────┴─────────────┘


CRSDepTime
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ CRSDepTime  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 1326.261738 │
│ std        ┆ 482.3463    │
│ min        ┆ 1.0         │
│ 25%        ┆ 918.0       │
│ 50%        ┆ 1320.0      │
│ 75%        ┆ 1730.0      │
│ max        ┆ 2359.0      │
└────────────┴─────────────┘


DepTime
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DepTime     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.843213e7  │
│ null_count ┆ 761652.0    │
│ mean       ┆ 1329.295567 │
│ std        ┆ 494.97504   │
│ min        ┆ 1.0         │
│ 25%        ┆ 920.0       │
│ 50%        ┆ 1323.0      │
│ 75%        ┆ 1736.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


DepDelayMinutes
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ DepDelayMinutes │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2.8430698e7     │
│ null_count ┆ 763084.0        │
│ mean       ┆ 12.783107       │
│ std        ┆ 46.173367       │
│ min        ┆ 0.0             │
│ 25%        ┆ 0.0             │
│ 50%        ┆ 0.0             │
│ 75%        ┆ 5.0             │
│ max        ┆ 7223.0          │
└────────────┴─────────────────┘


DepDelay
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DepDelay    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8430698e7 │
│ null_count ┆ 763084.0    │
│ mean       ┆ 9.306866    │
│ std        ┆ 47.280106   │
│ min        ┆ -1280.0     │
│ 25%        ┆ -6.0        │
│ 50%        ┆ -3.0        │
│ 75%        ┆ 5.0         │
│ max        ┆ 7223.0      │
└────────────┴─────────────┘


ArrTime
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ ArrTime     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8407605e7 │
│ null_count ┆ 786177.0    │
│ mean       ┆ 1468.046257 │
│ std        ┆ 525.617712  │
│ min        ┆ 1.0         │
│ 25%        ┆ 1055.0      │
│ 50%        ┆ 1505.0      │
│ 75%        ┆ 1910.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


ArrDelayMinutes
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ ArrDelayMinutes │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2.8347599e7     │
│ null_count ┆ 846183.0        │
│ mean       ┆ 12.809917       │
│ std        ┆ 45.799592       │
│ min        ┆ 0.0             │
│ 25%        ┆ 0.0             │
│ 50%        ┆ 0.0             │
│ 75%        ┆ 6.0             │
│ max        ┆ 7232.0          │
└────────────┴─────────────────┘


AirTime
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ AirTime     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8341221e7 │
│ null_count ┆ 852561.0    │
│ mean       ┆ 109.087503  │
│ std        ┆ 69.066686   │
│ min        ┆ -1244.0     │
│ 25%        ┆ 59.0        │
│ 50%        ┆ 91.0        │
│ 75%        ┆ 138.0       │
│ max        ┆ 1557.0      │
└────────────┴─────────────┘


CRSElapsedTime
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ CRSElapsedTime │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 2.919376e7     │
│ null_count ┆ 22.0           │
│ mean       ┆ 138.760512     │
│ std        ┆ 70.773163      │
│ min        ┆ -292.0         │
│ 25%        ┆ 88.0           │
│ 50%        ┆ 121.0          │
│ 75%        ┆ 169.0          │
│ max        ┆ 1645.0         │
└────────────┴────────────────┘


ActualElapsedTime
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ ActualElapsedTime │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 2.8348145e7       │
│ null_count ┆ 845637.0          │
│ mean       ┆ 133.29412         │
│ std        ┆ 70.778028         │
│ min        ┆ -1228.0           │
│ 25%        ┆ 82.0              │
│ 50%        ┆ 116.0             │
│ 75%        ┆ 164.0             │
│ max        ┆ 1604.0            │
└────────────┴───────────────────┘


Distance
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Distance    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 779.734565  │
│ std        ┆ 581.273883  │
│ min        ┆ 16.0        │
│ 25%        ┆ 354.0       │
│ 50%        ┆ 626.0       │
│ 75%        ┆ 1014.0      │
│ max        ┆ 5812.0      │
└────────────┴─────────────┘


Year
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Year        │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 2019.828655 │
│ std        ┆ 1.342521    │
│ min        ┆ 2018.0      │
│ 25%        ┆ 2019.0      │
│ 50%        ┆ 2020.0      │
│ 75%        ┆ 2021.0      │
│ max        ┆ 2022.0      │
└────────────┴─────────────┘


Quarter
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Quarter     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 2.448568    │
│ std        ┆ 1.121206    │
│ min        ┆ 1.0         │
│ 25%        ┆ 1.0         │
│ 50%        ┆ 2.0         │
│ 75%        ┆ 3.0         │
│ max        ┆ 4.0         │
└────────────┴─────────────┘


Month
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Month       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 6.32784     │
│ std        ┆ 3.452305    │
│ min        ┆ 1.0         │
│ 25%        ┆ 3.0         │
│ 50%        ┆ 6.0         │
│ 75%        ┆ 9.0         │
│ max        ┆ 12.0        │
└────────────┴─────────────┘


DayofMonth
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DayofMonth  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 15.751611   │
│ std        ┆ 8.778879    │
│ min        ┆ 1.0         │
│ 25%        ┆ 8.0         │
│ 50%        ┆ 16.0        │
│ 75%        ┆ 23.0        │
│ max        ┆ 31.0        │
└────────────┴─────────────┘


DayOfWeek
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DayOfWeek   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 3.974879    │
│ std        ┆ 2.002314    │
│ min        ┆ 1.0         │
│ 25%        ┆ 2.0         │
│ 50%        ┆ 4.0         │
│ 75%        ┆ 6.0         │
│ max        ┆ 7.0         │
└────────────┴─────────────┘


DOT_ID_Marketing_Airline
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ DOT_ID_Marketing_Airline │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 2.9193782e7              │
│ null_count ┆ 0.0                      │
│ mean       ┆ 19827.925582             │
│ std        ┆ 277.601479               │
│ min        ┆ 19393.0                  │
│ 25%        ┆ 19790.0                  │
│ 50%        ┆ 19805.0                  │
│ 75%        ┆ 19977.0                  │
│ max        ┆ 21171.0                  │
└────────────┴──────────────────────────┘


Flight_Number_Marketing_Airline
shape: (9, 2)
┌────────────┬─────────────────────────────────┐
│ statistic  ┆ Flight_Number_Marketing_Airlin… │
│ ---        ┆ ---                             │
│ str        ┆ f64                             │
╞════════════╪═════════════════════════════════╡
│ count      ┆ 2.9193782e7                     │
│ null_count ┆ 0.0                             │
│ mean       ┆ 2691.382805                     │
│ std        ┆ 1838.752974                     │
│ min        ┆ 1.0                             │
│ 25%        ┆ 1100.0                          │
│ 50%        ┆ 2294.0                          │
│ 75%        ┆ 4256.0                          │
│ max        ┆ 9888.0                          │
└────────────┴─────────────────────────────────┘


DOT_ID_Operating_Airline
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ DOT_ID_Operating_Airline │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 2.9193782e7              │
│ null_count ┆ 0.0                      │
│ mean       ┆ 20001.727755             │
│ std        ┆ 391.203046               │
│ min        ┆ 19393.0                  │
│ 25%        ┆ 19790.0                  │
│ 50%        ┆ 19977.0                  │
│ 75%        ┆ 20378.0                  │
│ max        ┆ 21171.0                  │
└────────────┴──────────────────────────┘


Flight_Number_Operating_Airline
shape: (9, 2)
┌────────────┬─────────────────────────────────┐
│ statistic  ┆ Flight_Number_Operating_Airlin… │
│ ---        ┆ ---                             │
│ str        ┆ f64                             │
╞════════════╪═════════════════════════════════╡
│ count      ┆ 2.9193782e7                     │
│ null_count ┆ 0.0                             │
│ mean       ┆ 2691.342808                     │
│ std        ┆ 1838.766373                     │
│ min        ┆ 1.0                             │
│ 25%        ┆ 1100.0                          │
│ 50%        ┆ 2294.0                          │
│ 75%        ┆ 4255.0                          │
│ max        ┆ 9888.0                          │
└────────────┴─────────────────────────────────┘


OriginAirportID
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ OriginAirportID │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2.9193782e7     │
│ null_count ┆ 0.0             │
│ mean       ┆ 12676.298242    │
│ std        ┆ 1525.445487     │
│ min        ┆ 10135.0         │
│ 25%        ┆ 11292.0         │
│ 50%        ┆ 12889.0         │
│ 75%        ┆ 14057.0         │
│ max        ┆ 16869.0         │
└────────────┴─────────────────┘


OriginAirportSeqID
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ OriginAirportSeqID │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 2.9193782e7        │
│ null_count ┆ 0.0                │
│ mean       ┆ 1.2676e6           │
│ std        ┆ 152544.355524      │
│ min        ┆ 1.013505e6         │
│ 25%        ┆ 1.129202e6         │
│ 50%        ┆ 1.288903e6         │
│ 75%        ┆ 1.405702e6         │
│ max        ┆ 1.686901e6         │
└────────────┴────────────────────┘


OriginCityMarketID
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ OriginCityMarketID │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 2.9193782e7        │
│ null_count ┆ 0.0                │
│ mean       ┆ 31761.089423       │
│ std        ┆ 1325.100667        │
│ min        ┆ 30070.0            │
│ 25%        ┆ 30693.0            │
│ 50%        ┆ 31453.0            │
│ 75%        ┆ 32575.0            │
│ max        ┆ 36133.0            │
└────────────┴────────────────────┘


OriginStateFips
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ OriginStateFips │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2.9193782e7     │
│ null_count ┆ 0.0             │
│ mean       ┆ 27.29479        │
│ std        ┆ 16.655891       │
│ min        ┆ 1.0             │
│ 25%        ┆ 12.0            │
│ 50%        ┆ 26.0            │
│ 75%        ┆ 42.0            │
│ max        ┆ 78.0            │
└────────────┴─────────────────┘


OriginWac
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ OriginWac   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 54.787438   │
│ std        ┆ 26.412264   │
│ min        ┆ 1.0         │
│ 25%        ┆ 34.0        │
│ 50%        ┆ 45.0        │
│ 75%        ┆ 82.0        │
│ max        ┆ 93.0        │
└────────────┴─────────────┘


DestAirportID
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ DestAirportID │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 2.9193782e7   │
│ null_count ┆ 0.0           │
│ mean       ┆ 12676.279583  │
│ std        ┆ 1525.449169   │
│ min        ┆ 10135.0       │
│ 25%        ┆ 11292.0       │
│ 50%        ┆ 12889.0       │
│ 75%        ┆ 14057.0       │
│ max        ┆ 16869.0       │
└────────────┴───────────────┘


DestAirportSeqID
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ DestAirportSeqID │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 2.9193782e7      │
│ null_count ┆ 0.0              │
│ mean       ┆ 1.2676e6         │
│ std        ┆ 152544.723779    │
│ min        ┆ 1.013505e6       │
│ 25%        ┆ 1.129202e6       │
│ 50%        ┆ 1.288903e6       │
│ 75%        ┆ 1.405702e6       │
│ max        ┆ 1.686901e6       │
└────────────┴──────────────────┘


DestCityMarketID
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ DestCityMarketID │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 2.9193782e7      │
│ null_count ┆ 0.0              │
│ mean       ┆ 31761.108257     │
│ std        ┆ 1325.095953      │
│ min        ┆ 30070.0          │
│ 25%        ┆ 30693.0          │
│ 50%        ┆ 31453.0          │
│ 75%        ┆ 32575.0          │
│ max        ┆ 36133.0          │
└────────────┴──────────────────┘


DestStateFips
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ DestStateFips │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 2.9193782e7   │
│ null_count ┆ 0.0           │
│ mean       ┆ 27.295023     │
│ std        ┆ 16.655989     │
│ min        ┆ 1.0           │
│ 25%        ┆ 12.0          │
│ 50%        ┆ 26.0          │
│ 75%        ┆ 42.0          │
│ max        ┆ 78.0          │
└────────────┴───────────────┘


DestWac
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DestWac     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 54.787596   │
│ std        ┆ 26.412327   │
│ min        ┆ 1.0         │
│ 25%        ┆ 34.0        │
│ 50%        ┆ 45.0        │
│ 75%        ┆ 82.0        │
│ max        ┆ 93.0        │
└────────────┴─────────────┘


DepDel15
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DepDel15    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8430698e7 │
│ null_count ┆ 763084.0    │
│ mean       ┆ 0.172767    │
│ std        ┆ 0.378046    │
│ min        ┆ 0.0         │
│ 25%        ┆ 0.0         │
│ 50%        ┆ 0.0         │
│ 75%        ┆ 0.0         │
│ max        ┆ 1.0         │
└────────────┴─────────────┘


DepartureDelayGroups
shape: (9, 2)
┌────────────┬──────────────────────┐
│ statistic  ┆ DepartureDelayGroups │
│ ---        ┆ ---                  │
│ str        ┆ f64                  │
╞════════════╪══════════════════════╡
│ count      ┆ 2.8430698e7          │
│ null_count ┆ 763084.0             │
│ mean       ┆ -0.016095            │
│ std        ┆ 2.164261             │
│ min        ┆ -2.0                 │
│ 25%        ┆ -1.0                 │
│ 50%        ┆ -1.0                 │
│ 75%        ┆ 0.0                  │
│ max        ┆ 12.0                 │
└────────────┴──────────────────────┘


TaxiOut
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ TaxiOut     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8413221e7 │
│ null_count ┆ 780561.0    │
│ mean       ┆ 16.710938   │
│ std        ┆ 9.391262    │
│ min        ┆ 0.0         │
│ 25%        ┆ 11.0        │
│ 50%        ┆ 14.0        │
│ 75%        ┆ 19.0        │
│ max        ┆ 1394.0      │
└────────────┴─────────────┘


WheelsOff
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WheelsOff   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8413231e7 │
│ null_count ┆ 780551.0    │
│ mean       ┆ 1352.844916 │
│ std        ┆ 496.18268   │
│ min        ┆ 1.0         │
│ 25%        ┆ 935.0       │
│ 50%        ┆ 1336.0      │
│ 75%        ┆ 1750.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


WheelsOn
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WheelsOn    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8400649e7 │
│ null_count ┆ 793133.0    │
│ mean       ┆ 1463.261979 │
│ std        ┆ 521.556842  │
│ min        ┆ 1.0         │
│ 25%        ┆ 1051.0      │
│ 50%        ┆ 1501.0      │
│ 75%        ┆ 1905.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


TaxiIn
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ TaxiIn      │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.8400639e7 │
│ null_count ┆ 793143.0    │
│ mean       ┆ 7.532169    │
│ std        ┆ 6.092501    │
│ min        ┆ 0.0         │
│ 25%        ┆ 4.0         │
│ 50%        ┆ 6.0         │
│ 75%        ┆ 9.0         │
│ max        ┆ 316.0       │
└────────────┴─────────────┘


CRSArrTime
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ CRSArrTime  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.9193782e7 │

In [15]:
def remove_nulls_and_count(df):
    # Drop rows with any null values
    cleaned_df = df.drop_nulls()
    # Return the number of remaining records
    return cleaned_df.height

In [16]:
num_orig_records = df.height
remaining_count = remove_nulls_and_count(df)
print(f"Number of Records in the original dataframe: {num_orig_records}")
print(f"Number of remaining records: {remaining_count}")

print(f"Percent still remaining: {round(remaining_count/num_orig_records * 100, 4)}")

Number of Records in the original dataframe: 29193782
Number of remaining records: 28339510
Percent still remaining: 97.0738