# US Schools Dataset

## Installations

In [1]:
# !pip3 install --upgrade pip

In [2]:
# %pip install geopandas
# %pip install tabulate

## Imports

In [3]:
import sys

from tabulate import tabulate
import numpy as np
import pandas as pd

import geopandas

## Display Imports & Their Versions

In [4]:
headers = ["Software/Library", "Version"]

table_data = [
    ['Python', sys.version[0:6]],
    ['NumPy', np.__version__],
    ['Pandas', pd.__version__],
    ['geopandas', geopandas.__version__]
    ]

print(tabulate(table_data, headers=headers, tablefmt="grid"))

+--------------------+-----------+
| Software/Library   | Version   |
+====================+===========+
| Python             | 3.11.4    |
+--------------------+-----------+
| NumPy              | 1.26.4    |
+--------------------+-----------+
| Pandas             | 2.2.3     |
+--------------------+-----------+
| geopandas          | 1.0.1     |
+--------------------+-----------+

## Import First Dataset

In [5]:
df_public = geopandas.read_file("data/Public_Schools.csv")

df_public

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
0,-9844095.0453,5230976.1334,1,170330000017,ALDEN-HEBRON HIGH SCHOOL,9604 ILLINOIS ST,HEBRON,IL,60034,9618,...,IMAGERY/OTHER,2010/08/27 00:00:00,NOT AVAILABLE,HIGH,112,09,12,1703300,11,NOT AVAILABLE
1,-9007027.1226,4195441.5319,2,370297001287,WESTERLY HILLS ACADEMY,4420 DENVER AVE,CHARLOTTE,NC,28208,3699,...,IMAGERY/OTHER,2016/08/22 00:00:00,http://schools.cms.k12.nc.us/westerlyhillsES,ELEMENTARY,495,KG,08,3702970,45,NOT AVAILABLE
2,-9580425.8697,4792069.2056,3,180369000584,NORTHWOOD ELEMENTARY SCHOOL,965 GRIZZLY CUB DR,FRANKLIN,IN,46131,1364,...,IMAGERY/OTHER,2010/08/02 00:00:00,NOT AVAILABLE,ELEMENTARY,478,PK,04,1803690,25,NOT AVAILABLE
3,-12432974.0329,3927587.8699,4,040187003479,DR. GARY AND ANNETTE AUXIER ELEMENTARY SCHOOL,22700 S. POWER RD.,QUEEN CREEK,AZ,85298,NOT AVAILABLE,...,IMAGERY/OTHER,2018/10/24 00:00:00,NOT AVAILABLE,ELEMENTARY,958,PK,06,401870,51,NOT AVAILABLE
4,-12432580.2285,3924830.5989,5,040187003483,DR. CAMILLE CASTEEL HIGH SCHOOL,24901 S. POWER RD.,QUEEN CREEK,AZ,85142,NOT AVAILABLE,...,IMAGERY/OTHER,2018/10/24 00:00:00,NOT AVAILABLE,HIGH,2294,07,12,401870,115,NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102329,-10751515.8386,5688107.5703,102330,270015003019,LISMORE COLONY SCHOOL,80391 COUNTY RD 60,CLINTON,MN,56225,361,...,IMAGERY/OTHER,2019/10/01 00:00:00,http://clintongraceville.mn.schoolwebpages.com,OTHER,36,KG,12,2700150,2,NOT AVAILABLE
102330,-10317192.2934,4598065.5046,102331,290699000174,OSAGE BEACH ELEM.,1241 NICHOLS ROAD,OSAGE BEACH,MO,65065,2172,...,IMAGERY/OTHER,2019/12/31 00:00:00,http://www.camdentonschools.org,ELEMENTARY,307,PK,04,2906990,22,NOT AVAILABLE
102331,-8512030.4158,4450964.2506,102332,510264001238,POINT OPTION ALTERNATIVE SCHOOL,813 DILIGENCE DR.,NEWPORT NEWS,VA,23606,NOT AVAILABLE,...,IMAGERY/OTHER,2020/01/23 00:00:00,http://sbo.nn.k12.va.us/schools/pointoption.shtml,NOT APPLICABLE,-999,N,N,5102640,-999,NOT AVAILABLE
102332,-9024168.757,4580375.7488,102333,540030000182,GATEWOOD ELEMENTARY,5094 GATEWOOD ROAD,FAYETTEVILLE,WV,25840,NOT AVAILABLE,...,IMAGERY/OTHER,2020/03/23 00:00:00,NOT AVAILABLE,ELEMENTARY,85,PK,04,5400300,7,NOT AVAILABLE
102333,-13459806.1399,4856353.5479,102334,069110211706,PLUMAS COUNTY OPPORTUNITY,1446 E. MAIN ST.,QUINCY,CA,95971,9402,...,IMAGERY/OTHER,2020/04/08 00:00:00,http://www.pcoe.k12.ca.us,MIDDLE,8,07,09,691102,3,NOT AVAILABLE

In [6]:
df_public.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102334 entries, 0 to 102333
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   X           102334 non-null  object
 1   Y           102334 non-null  object
 2   OBJECTID    102334 non-null  object
 3   NCESID      102334 non-null  object
 4   NAME        102334 non-null  object
 5   ADDRESS     102334 non-null  object
 6   CITY        102334 non-null  object
 7   STATE       102334 non-null  object
 8   ZIP         102334 non-null  object
 9   ZIP4        102334 non-null  object
 10  TELEPHONE   102334 non-null  object
 11  TYPE        102334 non-null  object
 12  STATUS      102334 non-null  object
 13  POPULATION  102334 non-null  object
 14  COUNTY      102334 non-null  object
 15  COUNTYFIPS  102334 non-null  object
 16  COUNTRY     102334 non-null  object
 17  LATITUDE    102334 non-null  object
 18  LONGITUDE   102334 non-null  object
 19  NAICS_CODE  102334 non-null  object
 20  NAICS_DESC  102334 non-null  object
 21  SOURCE      102334 non-null  object
 22  SOURCEDATE  102334 non-null  object
 23  VAL_METHOD  102334 non-null  object
 24  VAL_DATE    102334 non-null  object
 25  WEBSITE     102334 non-null  object
 26  LEVEL_      102334 non-null  object
 27  ENROLLMENT  102334 non-null  object
 28  ST_GRADE    102334 non-null  object
 29  END_GRADE   102334 non-null  object
 30  DISTRICTID  102334 non-null  object
 31  FT_TEACHER  102334 non-null  object
 32  SHELTER_ID  102334 non-null  object
dtypes: object(33)
memory usage: 25.8+ MB

In [7]:
df_public.describe(include='all')

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
count,102334,102334,102334,102334,102334,102334,102334,102334,102334,102334,...,102334,102334,102334,102334,102334,102334,102334,102334,102334,102334
unique,102334,102334,102334,102334,87088,93139,12695,55,22621,8640,...,4,662,33439,10,2946,18,19,17626,266,22508
top,-9844095.0453,5230976.1334,1,170330000017,LINCOLN ELEMENTARY SCHOOL,6420 E. BROADWAY BLVD. SUITE A,HOUSTON,CA,85710,NOT AVAILABLE,...,IMAGERY/OTHER,2017/10/31 00:00:00,NOT AVAILABLE,ELEMENTARY,-999,PK,05,7200030,-999,NOT AVAILABLE
freq,1,1,1,1,88,33,808,10442,53,42414,...,63001,1995,45310,53401,3826,31251,28094,1282,6831,78109

## Import Second Dataset

In [8]:
df_private = geopandas.read_file("data/Private_Schools.csv")

df_private

,X,Y,FID,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,...,SOURCEDATE,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,START_GRAD,END_GRADE,FT_TEACHER,SHELTER_ID
0,-8136078.0189,5055505.9896,1,1201,A0507274,A CHILD'S GARDEN,20 IVY BROOK RD,SHELTON,CT,06484,...,2010/01/29 00:00:00,IMAGERY,2010/02/25 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,6,2,3,2,NOT AVAILABLE
1,-8147299.6039,5037066.9873,2,1202,A0500844,BRIDGEPORT INTERNATIONAL ACADEMY,285 LAFAYETTE ST STE 200,BRIDGEPORT,CT,06604,...,2010/01/29 00:00:00,IMAGERY/OTHER,2010/02/23 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,60,14,17,8,NOT AVAILABLE
2,-8197042.168,5018050.0417,3,1203,A0108054,CARMEL ACADMEY,270 LAKE AVE,GREENWICH,CT,06830,...,2010/01/29 00:00:00,IMAGERY,2010/03/05 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,225,3,13,53,NOT AVAILABLE
3,-8171503.8456,5077290.6691,4,1204,A0507283,COUNTRY KIDS CLUB,94 OLD STATE RD,BROOKFIELD,CT,06804,...,2010/01/29 00:00:00,GEOCODE,2010/02/25 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,10,2,3,1,NOT AVAILABLE
4,-8197595.5419,5017131.4369,5,1205,01612613,EAGLE HILL SCHOOL,45 GLENVILLE RD,GREENWICH,CT,06831,...,2010/01/29 00:00:00,IMAGERY/OTHER,2010/02/26 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,3,253,4,15,65,NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31059,-10284448.5021,5757426.9516,31060,31060,A0790194,NORTHWEST PASSAGE,7818 MOLINE RD,WEBSTER,WI,54893,...,2014/10/23 00:00:00,GEOCODE,2014/12/15 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,23,12,16,2,NOT AVAILABLE
31060,-9952178.326,5724702.2296,31061,31061,A0903868,RHINELANDER CHRISTIAN SCHOOL,123 E MONICO,RHINELANDER,WI,54501,...,2014/10/23 00:00:00,IMAGERY,2014/12/15 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,1,12,3,17,1,NOT AVAILABLE
31061,-11882254.7265,5518318.1733,31062,31062,A1102409,BIG HORN CHRISTIAN ELEMENTARY SCHOOL,201 ASPEN DR,BUFFALO,WY,82834,...,2014/10/23 00:00:00,IMAGERY/OTHER,2014/12/15 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,2,12,17,1,NOT AVAILABLE
31062,-12023545.7801,5460993.7172,31063,31063,A1102411,COLTER HIGH SCHOOL,1550 US HIGHWAY 20 S,WORLAND,WY,82401,...,2014/10/23 00:00:00,GEOCODE,2014/12/15 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,59,14,17,8,NOT AVAILABLE
31063,-11649818.2851,5036039.1546,31064,31064,A1102419,SOUTHEASTERN WYOMING JUVENILE CENTER,3304 I80 SERVICE RD,CHEYENNE,WY,82009,...,2014/10/23 00:00:00,IMAGERY/OTHER,2014/12/15 00:00:00,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2,16,12,17,5,NOT AVAILABLE

In [9]:
df_private.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31064 entries, 0 to 31063
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           31064 non-null  object
 1   Y           31064 non-null  object
 2   FID         31064 non-null  object
 3   OBJECTID    31064 non-null  object
 4   NCESID      31064 non-null  object
 5   NAME        31064 non-null  object
 6   ADDRESS     31064 non-null  object
 7   CITY        31064 non-null  object
 8   STATE       31064 non-null  object
 9   ZIP         31064 non-null  object
 10  ZIP4        31064 non-null  object
 11  TELEPHONE   31064 non-null  object
 12  TYPE        31064 non-null  object
 13  STATUS      31064 non-null  object
 14  POPULATION  31064 non-null  object
 15  COUNTY      31064 non-null  object
 16  COUNTYFIPS  31064 non-null  object
 17  COUNTRY     31064 non-null  object
 18  LATITUDE    31064 non-null  object
 19  LONGITUDE   31064 non-null  object
 20  NAICS_CODE  31064 non-null  object
 21  NAICS_DESC  31064 non-null  object
 22  SOURCE      31064 non-null  object
 23  SOURCEDATE  31064 non-null  object
 24  VAL_METHOD  31064 non-null  object
 25  VAL_DATE    31064 non-null  object
 26  WEBSITE     31064 non-null  object
 27  LEVEL_      31064 non-null  object
 28  ENROLLMENT  31064 non-null  object
 29  START_GRAD  31064 non-null  object
 30  END_GRADE   31064 non-null  object
 31  FT_TEACHER  31064 non-null  object
 32  SHELTER_ID  31064 non-null  object
dtypes: object(33)
memory usage: 7.8+ MB

In [10]:
df_public.describe(include='all')

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID
count,102334,102334,102334,102334,102334,102334,102334,102334,102334,102334,...,102334,102334,102334,102334,102334,102334,102334,102334,102334,102334
unique,102334,102334,102334,102334,87088,93139,12695,55,22621,8640,...,4,662,33439,10,2946,18,19,17626,266,22508
top,-9844095.0453,5230976.1334,1,170330000017,LINCOLN ELEMENTARY SCHOOL,6420 E. BROADWAY BLVD. SUITE A,HOUSTON,CA,85710,NOT AVAILABLE,...,IMAGERY/OTHER,2017/10/31 00:00:00,NOT AVAILABLE,ELEMENTARY,-999,PK,05,7200030,-999,NOT AVAILABLE
freq,1,1,1,1,88,33,808,10442,53,42414,...,63001,1995,45310,53401,3826,31251,28094,1282,6831,78109

### Concatenate DataFrames into One

In [11]:
df = pd.concat([df_public, df_private])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133398 entries, 0 to 31063
Data columns (total 35 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   X           133398 non-null  object
 1   Y           133398 non-null  object
 2   OBJECTID    133398 non-null  object
 3   NCESID      133398 non-null  object
 4   NAME        133398 non-null  object
 5   ADDRESS     133398 non-null  object
 6   CITY        133398 non-null  object
 7   STATE       133398 non-null  object
 8   ZIP         133398 non-null  object
 9   ZIP4        133398 non-null  object
 10  TELEPHONE   133398 non-null  object
 11  TYPE        133398 non-null  object
 12  STATUS      133398 non-null  object
 13  POPULATION  133398 non-null  object
 14  COUNTY      133398 non-null  object
 15  COUNTYFIPS  133398 non-null  object
 16  COUNTRY     133398 non-null  object
 17  LATITUDE    133398 non-null  object
 18  LONGITUDE   133398 non-null  object
 19  NAICS_CODE  133398 non-null  object
 20  NAICS_DESC  133398 non-null  object
 21  SOURCE      133398 non-null  object
 22  SOURCEDATE  133398 non-null  object
 23  VAL_METHOD  133398 non-null  object
 24  VAL_DATE    133398 non-null  object
 25  WEBSITE     133398 non-null  object
 26  LEVEL_      133398 non-null  object
 27  ENROLLMENT  133398 non-null  object
 28  ST_GRADE    102334 non-null  object
 29  END_GRADE   133398 non-null  object
 30  DISTRICTID  102334 non-null  object
 31  FT_TEACHER  133398 non-null  object
 32  SHELTER_ID  133398 non-null  object
 33  FID         31064 non-null   object
 34  START_GRAD  31064 non-null   object
dtypes: object(35)
memory usage: 36.6+ MB

In [12]:
pd.set_option('display.max_columns', None)

df.head()

,X,Y,OBJECTID,NCESID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,TELEPHONE,TYPE,STATUS,POPULATION,COUNTY,COUNTYFIPS,COUNTRY,LATITUDE,LONGITUDE,NAICS_CODE,NAICS_DESC,SOURCE,SOURCEDATE,VAL_METHOD,VAL_DATE,WEBSITE,LEVEL_,ENROLLMENT,ST_GRADE,END_GRADE,DISTRICTID,FT_TEACHER,SHELTER_ID,FID,START_GRAD
0,-9844095.0453,5230976.1334,1,170330000017,ALDEN-HEBRON HIGH SCHOOL,9604 ILLINOIS ST,HEBRON,IL,60034,9618,(815) 648-2442,1,1,123,MCHENRY,17111,USA,42.465566095,-88.431010375,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2009/10/13 00:00:00,IMAGERY/OTHER,2010/08/27 00:00:00,NOT AVAILABLE,HIGH,112,09,12,1703300,11,NOT AVAILABLE,NaN,NaN
1,-9007027.1226,4195441.5319,2,370297001287,WESTERLY HILLS ACADEMY,4420 DENVER AVE,CHARLOTTE,NC,28208,3699,(980) 343-6021,1,1,540,MECKLENBURG,37119,USA,35.23190937,-80.911501287,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2009/12/10 00:00:00,IMAGERY/OTHER,2016/08/22 00:00:00,http://schools.cms.k12.nc.us/westerlyhillsES,ELEMENTARY,495,KG,08,3702970,45,NOT AVAILABLE,NaN,NaN
2,-9580425.8697,4792069.2056,3,180369000584,NORTHWOOD ELEMENTARY SCHOOL,965 GRIZZLY CUB DR,FRANKLIN,IN,46131,1364,(317) 346-8900,1,1,503,JOHNSON,18081,USA,39.489752551,-86.0624298709999,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2009/10/13 00:00:00,IMAGERY/OTHER,2010/08/02 00:00:00,NOT AVAILABLE,ELEMENTARY,478,PK,04,1803690,25,NOT AVAILABLE,NaN,NaN
3,-12432974.0329,3927587.8699,4,040187003479,DR. GARY AND ANNETTE AUXIER ELEMENTARY SCHOOL,22700 S. POWER RD.,QUEEN CREEK,AZ,85298,NOT AVAILABLE,(480) 812-7000,1,1,1009,MARICOPA,04013,USA,33.242888237,-111.687306008,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2018/10/23 00:00:00,IMAGERY/OTHER,2018/10/24 00:00:00,NOT AVAILABLE,ELEMENTARY,958,PK,06,401870,51,NOT AVAILABLE,NaN,NaN
4,-12432580.2285,3924830.5989,5,040187003483,DR. CAMILLE CASTEEL HIGH SCHOOL,24901 S. POWER RD.,QUEEN CREEK,AZ,85142,NOT AVAILABLE,(480) 424-8100,1,1,2409,MARICOPA,04013,USA,33.222170136,-111.683768403,611110,ELEMENTARY AND SECONDARY SCHOOLS,http://nces.ed.gov/GLOBALLOCATOR/sch_info_popu...,2018/10/23 00:00:00,IMAGERY/OTHER,2018/10/24 00:00:00,NOT AVAILABLE,HIGH,2294,07,12,401870,115,NOT AVAILABLE,NaN,NaN

In [13]:
pd.reset_option('display.max_columns')

In [14]:
for col in df.select_dtypes(include=['object', 'string']).columns.tolist():
    u_vals = df[col].unique()
    print(f"{col} ({len(u_vals)})\n{u_vals}\n")

X (133368)
['-9844095.0453' '-9007027.1226' '-9580425.8697' ... '-11882254.7265'
 '-12023545.7801' '-11649818.2851']

Y (133366)
['5230976.1334' '4195441.5319' '4792069.2056' ... '5518318.1733'
 '5460993.7172' '5036039.1546']

OBJECTID (102334)
['1' '2' '3' ... '102332' '102333' '102334']

NCESID (133398)
['170330000017' '370297001287' '180369000584' ... 'A1102409' 'A1102411'
 'A1102419']

NAME (109891)
['ALDEN-HEBRON HIGH SCHOOL' 'WESTERLY HILLS ACADEMY'
 'NORTHWOOD ELEMENTARY SCHOOL' ... 'BIG HORN CHRISTIAN ELEMENTARY SCHOOL'
 'COLTER HIGH SCHOOL' 'SOUTHEASTERN WYOMING JUVENILE CENTER']

ADDRESS (123266)
['9604 ILLINOIS ST' '4420 DENVER AVE' '965 GRIZZLY CUB DR' ...
 '201 ASPEN DR' '1550 US HIGHWAY 20 S' '3304 I80 SERVICE RD']

CITY (13496)
['HEBRON' 'CHARLOTTE' 'FRANKLIN' ... 'RADIANT' 'GREENBANK' 'HIGHBRIDGE']

STATE (55)
['IL' 'NC' 'IN' 'AZ' 'CA' 'DC' 'FL' 'ID' 'KY' 'KS' 'LA' 'MD' 'MI' 'MN'
 'NH' 'NJ' 'OK' 'TX' 'UT' 'IA' 'OH' 'MS' 'MO' 'SD' 'NM' 'WA' 'AL' 'PR'
 'GU' 'AK' 'AR' 'TN' 'OR' 'MT' 'ND' 'MA' 'NE' 'WY' 'NV' 'NY' 'PA' 'SC'
 'WV' 'WI' 'VT' 'VA' 'CO' 'DE' 'RI' 'GA' 'CT' 'ME' 'HI' 'VI' 'AS']

ZIP (23597)
['60034' '28208' '46131' ... '25287' '26504' '54846']

ZIP4 (9468)
['9618' '3699' '1364' ... '6789' '5765' '0379']

TELEPHONE (92879)
['(815) 648-2442' '(980) 343-6021' '(317) 346-8900' ... '(757) 591-7408'
 '(304) 574-2025' 'NOT AVAILABLE']

TYPE (7)
['1' '4' '2' '3' '7' '6' '5']

STATUS (8)
['1' '2' '6' '7' '3' '8' '4' '5']

POPULATION (3087)
['123' '540' '503' ... '3948' '3571' '6446']

COUNTY (1917)
['MCHENRY' 'MECKLENBURG' 'JOHNSON' ... 'DONA ANA' 'OGALA LAKOTA'
 'HEMPSTEAD\xa0\xa0']

COUNTYFIPS (3228)
['17111' '37119' '18081' ... '42183' '46113' '51515']

COUNTRY (5)
['USA' 'PRI' 'GUM' 'VIR' 'ASM']

LATITUDE (133366)
['42.465566095' '35.23190937' '39.489752551' ... '44.34069747'
 '43.971247318' '41.160465343']

LONGITUDE (133368)
['-88.431010375' '-80.911501287' '-86.0624298709999' ... '-106.740110306'
 '-108.009349436' '-104.652098227']

NAICS_CODE (1)
['611110']

NAICS_DESC (1)
['ELEMENTARY AND SECONDARY SCHOOLS']

SOURCE (133398)
['http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Public&ID=170330000017'
 'http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Public&ID=370297001287'
 'http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Public&ID=180369000584'
 ...
 'http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Private&ID=A1102409'
 'http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Private&ID=A1102411'
 'http://nces.ed.gov/GLOBALLOCATOR/sch_info_popup.asp?Type=Private&ID=A1102419']

SOURCEDATE (53)
['2009/10/13 00:00:00' '2009/12/10 00:00:00' '2018/10/23 00:00:00'
 '2010/01/29 00:00:00' '2011/09/30 00:00:00' '2014/02/04 00:00:00'
 '2015/05/08 00:00:00' '2012/11/02 00:00:00' '2017/10/25 00:00:00'
 '2016/01/05 00:00:00' '2010/09/24 00:00:00' '2018/10/29 00:00:00'
 '2011/08/04 00:00:00' '2018/10/30 00:00:00' '2010/03/11 00:00:00'
 '2019/08/07 00:00:00' '2009/12/07 00:00:00' '2009/11/02 00:00:00'
 '2009/11/03 00:00:00' '2010/03/30 00:00:00' '2010/03/19 00:00:00'
 '2020/02/06 00:00:00' '2010/03/10 00:00:00' '2010/03/31 00:00:00'
 '2009/12/08 00:00:00' '2009/12/01 00:00:00' '2009/11/10 00:00:00'
 '2009/11/23 00:00:00' '2010/04/19 00:00:00' '2009/12/09 00:00:00'
 '2009/11/09 00:00:00' '2010/02/12 00:00:00' '2009/11/05 00:00:00'
 '2010/02/11 00:00:00' '2010/02/22 00:00:00' '2010/02/25 00:00:00'
 '2009/10/29 00:00:00' '2010/03/26 00:00:00' '2010/04/01 00:00:00'
 '2009/12/03 00:00:00' '2009/11/18 00:00:00' '2009/11/13 00:00:00'
 '2012/03/07 00:00:00' '2010/04/15 00:00:00' '2010/03/24 00:00:00'
 '2010/02/17 00:00:00' '2010/03/18 00:00:00' '2009/11/12 00:00:00'
 '2009/11/30 00:00:00' '2014/10/23 00:00:00' '2017/10/27 00:00:00'
 '2009/10/19 00:00:00' '2009/10/28 00:00:00']

VAL_METHOD (4)
['IMAGERY/OTHER' 'IMAGERY' 'UNVERIFIED' 'GEOCODE']

VAL_DATE (800)
['2010/08/27 00:00:00' '2016/08/22 00:00:00' '2010/08/02 00:00:00'
 '2018/10/24 00:00:00' '2018/10/25 00:00:00' '2020/03/20 00:00:00'
 '2020/03/31 00:00:00' '2019/02/14 00:00:00' '2019/09/30 00:00:00'
 '2020/04/06 00:00:00' '2018/10/26 00:00:00' '2020/02/04 00:00:00'
 '2020/04/07 00:00:00' '2018/10/29 00:00:00' '2018/10/30 00:00:00'
 '2018/12/28 00:00:00' '2019/01/07 00:00:00' '2019/12/31 00:00:00'
 '2010/05/18 00:00:00' '2017/10/31 00:00:00' '2013/05/28 00:00:00'
 '2020/02/27 00:00:00' '2015/05/21 00:00:00' '2020/02/28 00:00:00'
 '2010/08/31 00:00:00' '2018/10/23 00:00:00' '2018/02/14 00:00:00'
 '2019/12/11 00:00:00' '2010/07/26 00:00:00' '2019/01/25 00:00:00'
 '2020/02/26 00:00:00' '2019/09/18 00:00:00' '2020/01/28 00:00:00'
 '2019/12/20 00:00:00' '2019/01/28 00:00:00' '2020/03/02 00:00:00'
 '2020/03/04 00:00:00' '2020/02/05 00:00:00' '2019/05/31 00:00:00'
 '2010/03/29 00:00:00' '2010/09/14 00:00:00' '2016/02/08 00:00:00'
 '2010/06/03 00:00:00' '2011/09/30 00:00:00' '2016/02/03 00:00:00'
 '2010/05/24 00:00:00' '2019/09/23 00:00:00' '2019/05/14 00:00:00'
 '2019/12/12 00:00:00' '2019/01/15 00:00:00' '2020/03/03 00:00:00'
 '2020/01/09 00:00:00' '2019/09/19 00:00:00' '2010/08/23 00:00:00'
 '2019/09/16 00:00:00' '2010/06/04 00:00:00' '2016/02/12 00:00:00'
 '2016/01/19 00:00:00' '2016/02/23 00:00:00' '2016/01/21 00:00:00'
 '2019/09/24 00:00:00' '2019/02/22 00:00:00' '2010/05/28 00:00:00'
 '2019/09/27 00:00:00' '2015/06/09 00:00:00' '2010/07/16 00:00:00'
 '2010/08/26 00:00:00' '2020/01/03 00:00:00' '2016/02/15 00:00:00'
 '2016/02/16 00:00:00' '2016/02/18 00:00:00' '2020/03/10 00:00:00'
 '2019/12/19 00:00:00' '2020/01/06 00:00:00' '2020/01/08 00:00:00'
 '2019/09/25 00:00:00' '2010/06/01 00:00:00' '2019/01/14 00:00:00'
 '2016/04/21 00:00:00' '2010/06/21 00:00:00' '2016/08/18 00:00:00'
 '2016/08/29 00:00:00' '2019/05/08 00:00:00' '2010/08/24 00:00:00'
 '2014/05/16 00:00:00' '2016/03/03 00:00:00' '2014/05/14 00:00:00'
 '2016/09/08 00:00:00' '2016/02/10 00:00:00' '2020/04/14 00:00:00'
 '2019/01/10 00:00:00' '2019/02/15 00:00:00' '2020/03/05 00:00:00'
 '2019/05/09 00:00:00' '2010/03/10 00:00:00' '2020/01/17 00:00:00'
 '2020/04/02 00:00:00' '2010/09/01 00:00:00' '2020/04/15 00:00:00'
 '2016/09/12 00:00:00' '2016/03/07 00:00:00' '2016/03/09 00:00:00'
 '2016/10/27 00:00:00' '2010/06/23 00:00:00' '2010/06/24 00:00:00'
 '2014/05/15 00:00:00' '2010/02/25 00:00:00' '2016/03/30 00:00:00'
 '2010/09/02 00:00:00' '2010/07/15 00:00:00' '2016/10/03 00:00:00'
 '2014/05/12 00:00:00' '2020/01/14 00:00:00' '2010/09/17 00:00:00'
 '2019/01/09 00:00:00' '2018/12/19 00:00:00' '2019/02/26 00:00:00'
 '2010/06/15 00:00:00' '2016/04/04 00:00:00' '2018/12/20 00:00:00'
 '2010/03/26 00:00:00' '2016/04/11 00:00:00' '2010/02/11 00:00:00'
 '2010/03/18 00:00:00' '2020/04/17 00:00:00' '2016/08/01 00:00:00'
 '2018/12/26 00:00:00' '2018/12/27 00:00:00' '2016/08/05 00:00:00'
 '2018/12/31 00:00:00' '2010/03/24 00:00:00' '2019/01/08 00:00:00'
 '2019/01/02 00:00:00' '2010/05/27 00:00:00' '2019/01/03 00:00:00'
 '2019/10/09 00:00:00' '2016/04/25 00:00:00' '2010/07/02 00:00:00'
 '2020/03/24 00:00:00' '2010/07/20 00:00:00' '2010/08/18 00:00:00'
 '2019/01/04 00:00:00' '2015/05/19 00:00:00' '2010/06/02 00:00:00'
 '2015/06/16 00:00:00' '2020/04/03 00:00:00' '2016/08/04 00:00:00'
 '2016/08/16 00:00:00' '2013/01/31 00:00:00' '2018/10/31 00:00:00'
 '2019/01/11 00:00:00' '2010/07/14 00:00:00' '2019/06/04 00:00:00'
 '2011/10/31 00:00:00' '2010/08/30 00:00:00' '2010/06/10 00:00:00'
 '2010/05/13 00:00:00' '2019/01/16 00:00:00' '2010/03/30 00:00:00'
 '2019/01/17 00:00:00' '2019/01/18 00:00:00' '2019/01/22 00:00:00'
 '2019/01/23 00:00:00' '2016/03/21 00:00:00' '2019/01/24 00:00:00'
 '2016/07/25 00:00:00' '2020/03/26 00:00:00' '2016/08/24 00:00:00'
 '2020/03/30 00:00:00' '2016/09/06 00:00:00' '2016/09/14 00:00:00'
 '2019/01/30 00:00:00' '2010/08/19 00:00:00' '2019/01/31 00:00:00'
 '2020/03/27 00:00:00' '2019/02/01 00:00:00' '2010/09/07 00:00:00'
 '2019/02/04 00:00:00' '2016/03/14 00:00:00' '2016/04/13 00:00:00'
 '2016/04/14 00:00:00' '2019/02/05 00:00:00' '2019/02/06 00:00:00'
 '2019/09/20 00:00:00' '2010/06/11 00:00:00' '2018/11/01 00:00:00'
 '2019/02/07 00:00:00' '2016/09/15 00:00:00' '2010/03/25 00:00:00'
 '2019/09/17 00:00:00' '2010/04/06 00:00:00' '2019/02/18 00:00:00'
 '2020/01/24 00:00:00' '2010/08/13 00:00:00' '2019/02/19 00:00:00'
 '2019/02/20 00:00:00' '2019/02/21 00:00:00' '2016/10/20 00:00:00'
 '2010/09/13 00:00:00' '2019/02/25 00:00:00' '2019/05/06 00:00:00'
 '2019/05/13 00:00:00' '2019/05/07 00:00:00' '2019/08/09 00:00:00'
 '2010/06/09 00:00:00' '2019/06/06 00:00:00' '2010/05/21 00:00:00'
 '2019/08/12 00:00:00' '2019/06/10 00:00:00' '2016/07/15 00:00:00'
 '2016/08/19 00:00:00' '2019/08/13 00:00:00' '2019/08/14 00:00:00'
 '2016/09/30 00:00:00' '2010/08/09 00:00:00' '2020/01/29 00:00:00'
 '2019/08/15 00:00:00' '2018/11/19 00:00:00' '2020/01/27 00:00:00'
 '2018/11/26 00:00:00' '2018/11/27 00:00:00' '2019/08/16 00:00:00'
 '2020/04/16 00:00:00' '2018/11/28 00:00:00' '2020/03/11 00:00:00'
 '2018/11/29 00:00:00' '2020/03/23 00:00:00' '2020/02/03 00:00:00'
 '2010/02/18 00:00:00' '2016/04/29 00:00:00' '2014/05/20 00:00:00'
 '2012/11/29 00:00:00' '2010/03/02 00:00:00' '2010/05/05 00:00:00'
 '2010/05/25 00:00:00' '2010/08/25 00:00:00' '2012/12/21 00:00:00'
 '2014/05/21 00:00:00' '2010/03/31 00:00:00' '2010/09/20 00:00:00'
 '2016/10/19 00:00:00' '2010/03/19 00:00:00' '2010/07/27 00:00:00'
 '2010/05/20 00:00:00' '2010/08/16 00:00:00' '2010/09/09 00:00:00'
 '2010/07/07 00:00:00' '2010/05/12 00:00:00' '2010/06/29 00:00:00'
 '2015/06/08 00:00:00' '2010/06/17 00:00:00' '2010/05/06 00:00:00'
 '2016/02/02 00:00:00' '2016/03/24 00:00:00' '2016/08/15 00:00:00'
 '2016/02/22 00:00:00' '2010/08/04 00:00:00' '2010/08/20 00:00:00'
 '2010/02/26 00:00:00' '2010/08/03 00:00:00' '2010/03/01 00:00:00'
 '2010/05/14 00:00:00' '2011/11/04 00:00:00' '2011/10/26 00:00:00'
 '2010/06/28 00:00:00' '2020/04/13 00:00:00' '2020/03/18 00:00:00'
 '2010/05/17 00:00:00' '2010/05/26 00:00:00' '2012/12/04 00:00:00'
 '2010/03/22 00:00:00' '2014/05/06 00:00:00' '2013/02/20 00:00:00'
 '2015/06/03 00:00:00' '2010/09/16 00:00:00' '2016/04/26 00:00:00'
 '2010/09/28 00:00:00' '2015/06/30 00:00:00' '2010/08/11 00:00:00'
 '2016/01/05 00:00:00' '2016/01/06 00:00:00' '2016/01/07 00:00:00'
 '2010/05/19 00:00:00' '2016/01/13 00:00:00' '2016/01/14 00:00:00'
 '2016/03/18 00:00:00' '2010/03/11 00:00:00' '2011/10/24 00:00:00'
 '2016/02/09 00:00:00' '2016/07/13 00:00:00' '2016/02/11 00:00:00'
 '2016/01/29 00:00:00' '2010/06/22 00:00:00' '2010/09/08 00:00:00'
 '2010/06/25 00:00:00' '2010/02/24 00:00:00' '2011/11/02 00:00:00'
 '2016/10/26 00:00:00' '2016/08/31 00:00:00' '2016/04/05 00:00:00'
 '2016/02/24 00:00:00' '2010/06/18 00:00:00' '2011/10/21 00:00:00'
 '2016/01/12 00:00:00' '2020/04/08 00:00:00' '2011/01/13 00:00:00'
 '2010/07/29 00:00:00' '2010/04/07 00:00:00' '2010/06/08 00:00:00'
 '2010/09/24 00:00:00' '2016/02/04 00:00:00' '2016/02/17 00:00:00'
 '2010/02/16 00:00:00' '2010/05/07 00:00:00' '2010/02/22 00:00:00'
 '2011/01/07 00:00:00' '2016/02/25 00:00:00' '2016/02/26 00:00:00'
 '2016/03/01 00:00:00' '2016/03/04 00:00:00' '2016/03/08 00:00:00'
 '2016/03/10 00:00:00' '2016/03/11 00:00:00' '2016/03/23 00:00:00'
 '2016/04/22 00:00:00' '2016/08/23 00:00:00' '2010/07/08 00:00:00'
 '2016/04/20 00:00:00' '2010/06/16 00:00:00' '2010/04/13 00:00:00'
 '2010/03/17 00:00:00' '2010/08/10 00:00:00' '2010/09/15 00:00:00'
 '2010/02/12 00:00:00' '2010/03/04 00:00:00' '2010/07/28 00:00:00'
 '2010/04/16 00:00:00' '2016/04/01 00:00:00' '2010/09/03 00:00:00'
 '2020/04/09 00:00:00' '2010/05/10 00:00:00' '2016/03/15 00:00:00'
 '2016/03/16 00:00:00' '2016/03/17 00:00:00' '2016/03/28 00:00:00'
 '2016/03/31 00:00:00' '2016/04/06 00:00:00' '2016/04/07 00:00:00'
 '2016/04/15 00:00:00' '2016/04/19 00:00:00' '2011/11/08 00:00:00'
 '2012/11/16 00:00:00' '2016/09/20 00:00:00' '2017/12/14 00:00:00'
 '2010/12/21 00:00:00' '2010/08/12 00:00:00' '2016/01/15 00:00:00'
 '2016/08/26 00:00:00' '2015/06/22 00:00:00' '2014/05/07 00:00:00'
 '2018/01/10 00:00:00' '2018/02/06 00:00:00' '2018/02/08 00:00:00'
 '2010/08/17 00:00:00' '2010/07/19 00:00:00' '2010/07/22 00:00:00'
 '2016/08/08 00:00:00' '2010/03/03 00:00:00' '2010/08/05 00:00:00'
 '2016/04/27 00:00:00' '2016/04/28 00:00:00' '2018/01/16 00:00:00'
 '2010/07/12 00:00:00' '2016/09/07 00:00:00' '2010/07/30 00:00:00'
 '2010/02/10 00:00:00' '2010/06/07 00:00:00' '2016/08/02 00:00:00'
 '2010/03/16 00:00:00' '2016/09/26 00:00:00' '2016/01/27 00:00:00'
 '2010/06/14 00:00:00' '2010/04/01 00:00:00' '2016/07/29 00:00:00'
 '2016/02/29 00:00:00' '2012/11/30 00:00:00' '2016/08/30 00:00:00'
 '2011/11/01 00:00:00' '2012/11/13 00:00:00' '2015/05/28 00:00:00'
 '2020/04/01 00:00:00' '2015/05/26 00:00:00' '2016/09/02 00:00:00'
 '2020/03/13 00:00:00' '2020/03/19 00:00:00' '2016/03/22 00:00:00'
 '2018/02/12 00:00:00' '2011/01/31 00:00:00' '2018/01/11 00:00:00'
 '2018/02/05 00:00:00' '2018/01/18 00:00:00' '2018/01/08 00:00:00'
 '2016/09/13 00:00:00' '2010/09/10 00:00:00' '2016/04/08 00:00:00'
 '2010/07/01 00:00:00' '2016/04/18 00:00:00' '2010/12/30 00:00:00'
 '2020/04/20 00:00:00' '2013/02/22 00:00:00' '2016/07/14 00:00:00'
 '2013/02/26 00:00:00' '2016/10/21 00:00:00' '2018/02/13 00:00:00'
 '2016/11/01 00:00:00' '2018/02/09 00:00:00' '2018/01/12 00:00:00'
 '2018/01/26 00:00:00' '2018/02/01 00:00:00' '2018/02/02 00:00:00'
 '2010/04/12 00:00:00' '2015/05/20 00:00:00' '2016/08/25 00:00:00'
 '2012/12/17 00:00:00' '2013/01/23 00:00:00' '2011/10/25 00:00:00'
 '2011/11/07 00:00:00' '2016/01/08 00:00:00' '2010/07/21 00:00:00'
 '2010/07/23 00:00:00' '2016/10/04 00:00:00' '2016/07/18 00:00:00'
 '2012/12/06 00:00:00' '2016/10/28 00:00:00' '2019/12/10 00:00:00'
 '2020/01/13 00:00:00' '2015/06/12 00:00:00' '2016/08/17 00:00:00'
 '2011/10/27 00:00:00' '2011/11/03 00:00:00' '2011/01/18 00:00:00'
 '2010/07/09 00:00:00' '2015/06/23 00:00:00' '2016/09/19 00:00:00'
 '2010/12/20 00:00:00' '2012/12/03 00:00:00' '2012/11/20 00:00:00'
 '2013/02/27 00:00:00' '2011/01/03 00:00:00' '2016/08/03 00:00:00'
 '2016/09/16 00:00:00' '2016/09/21 00:00:00' '2016/10/25 00:00:00'
 '2010/03/09 00:00:00' '2013/01/02 00:00:00' '2014/05/19 00:00:00'
 '2010/07/06 00:00:00' '2016/08/09 00:00:00' '2012/12/07 00:00:00'
 '2010/12/28 00:00:00' '2012/12/05 00:00:00' '2013/02/21 00:00:00'
 '2011/01/20 00:00:00' '2012/12/13 00:00:00' '2014/05/13 00:00:00'
 '2010/07/13 00:00:00' '2011/01/27 00:00:00' '2019/08/20 00:00:00'
 '2019/09/11 00:00:00' '2010/06/30 00:00:00' '2010/03/05 00:00:00'
 '2012/11/15 00:00:00' '2010/05/11 00:00:00' '2016/09/01 00:00:00'
 '2015/05/27 00:00:00' '2011/10/20 00:00:00' '2014/05/05 00:00:00'
 '2013/02/25 00:00:00' '2010/03/15 00:00:00' '2011/10/18 00:00:00'
 '2010/03/08 00:00:00' '2016/02/05 00:00:00' '2010/02/15 00:00:00'
 '2015/06/04 00:00:00' '2010/12/17 00:00:00' '2016/04/12 00:00:00'
 '2011/01/05 00:00:00' '2011/01/24 00:00:00' '2016/07/26 00:00:00'
 '2016/07/28 00:00:00' '2015/06/05 00:00:00' '2015/06/25 00:00:00'
 '2015/06/19 00:00:00' '2015/05/29 00:00:00' '2015/05/22 00:00:00'
 '2015/06/10 00:00:00' '2010/12/22 00:00:00' '2016/01/11 00:00:00'
 '2010/02/17 00:00:00' '2016/07/27 00:00:00' '2011/10/17 00:00:00'
 '2010/03/23 00:00:00' '2010/02/23 00:00:00' '2020/02/06 00:00:00'
 '2010/02/19 00:00:00' '2016/02/19 00:00:00' '2016/01/28 00:00:00'
 '2011/01/21 00:00:00' '2011/12/21 00:00:00' '2010/05/04 00:00:00'
 '2013/01/07 00:00:00' '2016/03/29 00:00:00' '2012/12/20 00:00:00'
 '2016/03/02 00:00:00' '2011/10/14 00:00:00' '2011/01/12 00:00:00'
 '2010/04/14 00:00:00' '2012/11/27 00:00:00' '2014/05/08 00:00:00'
 '2019/08/21 00:00:00' '2016/10/31 00:00:00' '2016/10/24 00:00:00'
 '2010/12/15 00:00:00' '2020/03/17 00:00:00' '2010/04/23 00:00:00'
 '2010/08/06 00:00:00' '2016/01/26 00:00:00' '2010/04/05 00:00:00'
 '2016/02/01 00:00:00' '2019/08/22 00:00:00' '2019/08/23 00:00:00'
 '2019/08/26 00:00:00' '2019/08/27 00:00:00' '2019/08/28 00:00:00'
 '2019/08/29 00:00:00' '2020/01/02 00:00:00' '2019/09/03 00:00:00'
 '2019/09/04 00:00:00' '2019/09/06 00:00:00' '2019/09/09 00:00:00'
 '2020/04/21 00:00:00' '2019/08/19 00:00:00' '2019/06/03 00:00:00'
 '2019/09/05 00:00:00' '2019/09/26 00:00:00' '2019/09/12 00:00:00'
 '2019/10/08 00:00:00' '2019/10/01 00:00:00' '2019/10/02 00:00:00'
 '2019/10/03 00:00:00' '2019/10/04 00:00:00' '2019/10/07 00:00:00'
 '2011/01/28 00:00:00' '2019/10/10 00:00:00' '2019/10/11 00:00:00'
 '2019/12/30 00:00:00' '2020/01/07 00:00:00' '2020/01/10 00:00:00'
 '2020/01/15 00:00:00' '2020/01/16 00:00:00' '2020/01/22 00:00:00'
 '2020/01/23 00:00:00' '2012/12/14 00:00:00' '2012/01/09 00:00:00'
 '2020/02/13 00:00:00' '2020/02/18 00:00:00' '2020/02/17 00:00:00'
 '2020/02/19 00:00:00' '2020/02/24 00:00:00' '2020/02/25 00:00:00'
 '2020/02/12 00:00:00' '2020/02/21 00:00:00' '2020/02/20 00:00:00'
 '2020/02/11 00:00:00' '2020/02/07 00:00:00' '2020/02/14 00:00:00'
 '2020/02/10 00:00:00' '2020/03/12 00:00:00' '2020/03/16 00:00:00'
 '2010/05/03 00:00:00' '2020/03/06 00:00:00' '2015/06/02 00:00:00'
 '2020/03/25 00:00:00' '2013/01/03 00:00:00' '2012/11/12 00:00:00'
 '2011/10/28 00:00:00' '2013/01/04 00:00:00' '2011/12/22 00:00:00'
 '2015/06/26 00:00:00' '2010/04/15 00:00:00' '2012/11/28 00:00:00'
 '2016/09/23 00:00:00' '2015/06/29 00:00:00' '2015/06/01 00:00:00'
 '2018/01/24 00:00:00' '2015/05/18 00:00:00' '2011/02/01 00:00:00'
 '2011/11/09 00:00:00' '2011/10/19 00:00:00' '2013/05/24 00:00:00'
 '2019/04/12 00:00:00' '2014/05/09 00:00:00' '2018/02/07 00:00:00'
 '2016/10/18 00:00:00' '2010/12/29 00:00:00' '2011/01/26 00:00:00'
 '2016/11/10 00:00:00' '2010/03/12 00:00:00' '2012/01/06 00:00:00'
 '2015/06/15 00:00:00' '2019/06/05 00:00:00' '2011/01/19 00:00:00'
 '2019/06/07 00:00:00' '2010/12/14 00:00:00' '2011/11/16 00:00:00'
 '2011/12/29 00:00:00' '2012/11/26 00:00:00' '2010/04/08 00:00:00'
 '2015/06/17 00:00:00' '2011/01/06 00:00:00' '2018/01/09 00:00:00'
 '2010/04/19 00:00:00' '2010/12/27 00:00:00' '2010/09/27 00:00:00'
 '2012/12/28 00:00:00' '2011/01/04 00:00:00' '2019/05/30 00:00:00'
 '2018/01/03 00:00:00' '2011/12/27 00:00:00' '2019/05/10 00:00:00'
 '2016/11/07 00:00:00' '2011/11/17 00:00:00' '2010/09/21 00:00:00'
 '2015/06/11 00:00:00' '2015/06/18 00:00:00' '2011/01/25 00:00:00'
 '2011/12/06 00:00:00' '2018/01/04 00:00:00' '2011/01/11 00:00:00'
 '2018/01/29 00:00:00' '2010/09/30 00:00:00' '2010/12/02 00:00:00'
 '2015/06/24 00:00:00' '2016/11/04 00:00:00' '2010/12/06 00:00:00'
 '2010/04/09 00:00:00' '2016/11/09 00:00:00' '2011/12/01 00:00:00'
 '2011/05/26 00:00:00' '2012/12/31 00:00:00' '2011/12/07 00:00:00'
 '2018/01/23 00:00:00' '2018/01/05 00:00:00' '2012/05/04 00:00:00'
 '2012/11/02 00:00:00' '2012/03/15 00:00:00' '2013/04/01 00:00:00'
 '2016/07/12 00:00:00' '2018/01/31 00:00:00' '2018/12/21 00:00:00'
 '2012/04/20 00:00:00' '2011/01/14 00:00:00' '2014/12/10 00:00:00'
 '2018/04/25 00:00:00' '2018/05/02 00:00:00' '2017/10/27 00:00:00'
 '2018/04/17 00:00:00' '2018/04/18 00:00:00' '2018/04/24 00:00:00'
 '2018/04/19 00:00:00' '2018/04/27 00:00:00' '2014/12/16 00:00:00'
 '2014/12/11 00:00:00' '2014/12/12 00:00:00' '2014/12/15 00:00:00'
 '2014/12/01 00:00:00' '2009/12/31 00:00:00' '2014/12/03 00:00:00'
 '2014/12/09 00:00:00' '2018/04/20 00:00:00' '2018/04/23 00:00:00'
 '2018/04/30 00:00:00' '2018/05/01 00:00:00' '2018/05/07 00:00:00'
 '2018/05/03 00:00:00' '2018/04/26 00:00:00' '2018/05/08 00:00:00'
 '2018/05/04 00:00:00' '2010/12/16 00:00:00' '2011/12/08 00:00:00'
 '2014/11/25 00:00:00' '2010/12/10 00:00:00' '2010/12/09 00:00:00'
 '2018/06/07 00:00:00' '2009/11/17 00:00:00' '2009/11/30 00:00:00'
 '2009/11/20 00:00:00' '2009/11/18 00:00:00' '2009/11/19 00:00:00'
 '2009/11/16 00:00:00' '2018/06/05 00:00:00' '2009/11/24 00:00:00'
 '2009/12/03 00:00:00' '2009/12/01 00:00:00' '2010/09/23 00:00:00'
 '2010/10/05 00:00:00' '2014/12/08 00:00:00' '2009/10/29 00:00:00'
 '2009/12/07 00:00:00' '2009/12/08 00:00:00' '2009/10/19 00:00:00'
 '2009/10/28 00:00:00' '2009/11/02 00:00:00' '2009/11/04 00:00:00'
 '2009/11/09 00:00:00' '2009/11/03 00:00:00' '2011/12/09 00:00:00'
 '2009/10/20 00:00:00' '2009/11/12 00:00:00' '2009/11/10 00:00:00'

### Return Information About Unqiue Values in Select Features

In [15]:
for col in df.select_dtypes(include=['object', 'string']).columns.tolist():
    u_vals = df[col].unique()
    if len(u_vals) < 8000:
        print(f"{col} ({len(u_vals)})\n{u_vals}\n")
    else:
        print(f"{col} ({len(u_vals)})\n")

X (133368)

Y (133366)

OBJECTID (102334)

NCESID (133398)

NAME (109891)

ADDRESS (123266)

CITY (13496)

STATE (55)
['IL' 'NC' 'IN' 'AZ' 'CA' 'DC' 'FL' 'ID' 'KY' 'KS' 'LA' 'MD' 'MI' 'MN'
 'NH' 'NJ' 'OK' 'TX' 'UT' 'IA' 'OH' 'MS' 'MO' 'SD' 'NM' 'WA' 'AL' 'PR'
 'GU' 'AK' 'AR' 'TN' 'OR' 'MT' 'ND' 'MA' 'NE' 'WY' 'NV' 'NY' 'PA' 'SC'
 'WV' 'WI' 'VT' 'VA' 'CO' 'DE' 'RI' 'GA' 'CT' 'ME' 'HI' 'VI' 'AS']

ZIP (23597)

ZIP4 (9468)

TELEPHONE (92879)

TYPE (7)
['1' '4' '2' '3' '7' '6' '5']

STATUS (8)
['1' '2' '6' '7' '3' '8' '4' '5']

POPULATION (3087)
['123' '540' '503' ... '3948' '3571' '6446']

COUNTY (1917)
['MCHENRY' 'MECKLENBURG' 'JOHNSON' ... 'DONA ANA' 'OGALA LAKOTA'
 'HEMPSTEAD\xa0\xa0']

COUNTYFIPS (3228)
['17111' '37119' '18081' ... '42183' '46113' '51515']

COUNTRY (5)
['USA' 'PRI' 'GUM' 'VIR' 'ASM']

LATITUDE (133366)

LONGITUDE (133368)

NAICS_CODE (1)
['611110']

NAICS_DESC (1)
['ELEMENTARY AND SECONDARY SCHOOLS']

SOURCE (133398)

SOURCEDATE (53)
['2009/10/13 00:00:00' '2009/12/10 00:00:00' '2018/10/23 00:00:00'
 '2010/01/29 00:00:00' '2011/09/30 00:00:00' '2014/02/04 00:00:00'
 '2015/05/08 00:00:00' '2012/11/02 00:00:00' '2017/10/25 00:00:00'
 '2016/01/05 00:00:00' '2010/09/24 00:00:00' '2018/10/29 00:00:00'
 '2011/08/04 00:00:00' '2018/10/30 00:00:00' '2010/03/11 00:00:00'
 '2019/08/07 00:00:00' '2009/12/07 00:00:00' '2009/11/02 00:00:00'
 '2009/11/03 00:00:00' '2010/03/30 00:00:00' '2010/03/19 00:00:00'
 '2020/02/06 00:00:00' '2010/03/10 00:00:00' '2010/03/31 00:00:00'
 '2009/12/08 00:00:00' '2009/12/01 00:00:00' '2009/11/10 00:00:00'
 '2009/11/23 00:00:00' '2010/04/19 00:00:00' '2009/12/09 00:00:00'
 '2009/11/09 00:00:00' '2010/02/12 00:00:00' '2009/11/05 00:00:00'
 '2010/02/11 00:00:00' '2010/02/22 00:00:00' '2010/02/25 00:00:00'
 '2009/10/29 00:00:00' '2010/03/26 00:00:00' '2010/04/01 00:00:00'
 '2009/12/03 00:00:00' '2009/11/18 00:00:00' '2009/11/13 00:00:00'
 '2012/03/07 00:00:00' '2010/04/15 00:00:00' '2010/03/24 00:00:00'
 '2010/02/17 00:00:00' '2010/03/18 00:00:00' '2009/11/12 00:00:00'
 '2009/11/30 00:00:00' '2014/10/23 00:00:00' '2017/10/27 00:00:00'
 '2009/10/19 00:00:00' '2009/10/28 00:00:00']

VAL_METHOD (4)
['IMAGERY/OTHER' 'IMAGERY' 'UNVERIFIED' 'GEOCODE']

VAL_DATE (800)
['2010/08/27 00:00:00' '2016/08/22 00:00:00' '2010/08/02 00:00:00'
 '2018/10/24 00:00:00' '2018/10/25 00:00:00' '2020/03/20 00:00:00'
 '2020/03/31 00:00:00' '2019/02/14 00:00:00' '2019/09/30 00:00:00'
 '2020/04/06 00:00:00' '2018/10/26 00:00:00' '2020/02/04 00:00:00'
 '2020/04/07 00:00:00' '2018/10/29 00:00:00' '2018/10/30 00:00:00'
 '2018/12/28 00:00:00' '2019/01/07 00:00:00' '2019/12/31 00:00:00'
 '2010/05/18 00:00:00' '2017/10/31 00:00:00' '2013/05/28 00:00:00'
 '2020/02/27 00:00:00' '2015/05/21 00:00:00' '2020/02/28 00:00:00'
 '2010/08/31 00:00:00' '2018/10/23 00:00:00' '2018/02/14 00:00:00'
 '2019/12/11 00:00:00' '2010/07/26 00:00:00' '2019/01/25 00:00:00'
 '2020/02/26 00:00:00' '2019/09/18 00:00:00' '2020/01/28 00:00:00'
 '2019/12/20 00:00:00' '2019/01/28 00:00:00' '2020/03/02 00:00:00'
 '2020/03/04 00:00:00' '2020/02/05 00:00:00' '2019/05/31 00:00:00'
 '2010/03/29 00:00:00' '2010/09/14 00:00:00' '2016/02/08 00:00:00'
 '2010/06/03 00:00:00' '2011/09/30 00:00:00' '2016/02/03 00:00:00'
 '2010/05/24 00:00:00' '2019/09/23 00:00:00' '2019/05/14 00:00:00'
 '2019/12/12 00:00:00' '2019/01/15 00:00:00' '2020/03/03 00:00:00'
 '2020/01/09 00:00:00' '2019/09/19 00:00:00' '2010/08/23 00:00:00'
 '2019/09/16 00:00:00' '2010/06/04 00:00:00' '2016/02/12 00:00:00'
 '2016/01/19 00:00:00' '2016/02/23 00:00:00' '2016/01/21 00:00:00'
 '2019/09/24 00:00:00' '2019/02/22 00:00:00' '2010/05/28 00:00:00'
 '2019/09/27 00:00:00' '2015/06/09 00:00:00' '2010/07/16 00:00:00'
 '2010/08/26 00:00:00' '2020/01/03 00:00:00' '2016/02/15 00:00:00'
 '2016/02/16 00:00:00' '2016/02/18 00:00:00' '2020/03/10 00:00:00'
 '2019/12/19 00:00:00' '2020/01/06 00:00:00' '2020/01/08 00:00:00'
 '2019/09/25 00:00:00' '2010/06/01 00:00:00' '2019/01/14 00:00:00'
 '2016/04/21 00:00:00' '2010/06/21 00:00:00' '2016/08/18 00:00:00'
 '2016/08/29 00:00:00' '2019/05/08 00:00:00' '2010/08/24 00:00:00'
 '2014/05/16 00:00:00' '2016/03/03 00:00:00' '2014/05/14 00:00:00'
 '2016/09/08 00:00:00' '2016/02/10 00:00:00' '2020/04/14 00:00:00'
 '2019/01/10 00:00:00' '2019/02/15 00:00:00' '2020/03/05 00:00:00'
 '2019/05/09 00:00:00' '2010/03/10 00:00:00' '2020/01/17 00:00:00'
 '2020/04/02 00:00:00' '2010/09/01 00:00:00' '2020/04/15 00:00:00'
 '2016/09/12 00:00:00' '2016/03/07 00:00:00' '2016/03/09 00:00:00'
 '2016/10/27 00:00:00' '2010/06/23 00:00:00' '2010/06/24 00:00:00'
 '2014/05/15 00:00:00' '2010/02/25 00:00:00' '2016/03/30 00:00:00'
 '2010/09/02 00:00:00' '2010/07/15 00:00:00' '2016/10/03 00:00:00'
 '2014/05/12 00:00:00' '2020/01/14 00:00:00' '2010/09/17 00:00:00'
 '2019/01/09 00:00:00' '2018/12/19 00:00:00' '2019/02/26 00:00:00'
 '2010/06/15 00:00:00' '2016/04/04 00:00:00' '2018/12/20 00:00:00'
 '2010/03/26 00:00:00' '2016/04/11 00:00:00' '2010/02/11 00:00:00'
 '2010/03/18 00:00:00' '2020/04/17 00:00:00' '2016/08/01 00:00:00'
 '2018/12/26 00:00:00' '2018/12/27 00:00:00' '2016/08/05 00:00:00'
 '2018/12/31 00:00:00' '2010/03/24 00:00:00' '2019/01/08 00:00:00'
 '2019/01/02 00:00:00' '2010/05/27 00:00:00' '2019/01/03 00:00:00'
 '2019/10/09 00:00:00' '2016/04/25 00:00:00' '2010/07/02 00:00:00'
 '2020/03/24 00:00:00' '2010/07/20 00:00:00' '2010/08/18 00:00:00'
 '2019/01/04 00:00:00' '2015/05/19 00:00:00' '2010/06/02 00:00:00'
 '2015/06/16 00:00:00' '2020/04/03 00:00:00' '2016/08/04 00:00:00'
 '2016/08/16 00:00:00' '2013/01/31 00:00:00' '2018/10/31 00:00:00'
 '2019/01/11 00:00:00' '2010/07/14 00:00:00' '2019/06/04 00:00:00'
 '2011/10/31 00:00:00' '2010/08/30 00:00:00' '2010/06/10 00:00:00'
 '2010/05/13 00:00:00' '2019/01/16 00:00:00' '2010/03/30 00:00:00'
 '2019/01/17 00:00:00' '2019/01/18 00:00:00' '2019/01/22 00:00:00'
 '2019/01/23 00:00:00' '2016/03/21 00:00:00' '2019/01/24 00:00:00'
 '2016/07/25 00:00:00' '2020/03/26 00:00:00' '2016/08/24 00:00:00'
 '2020/03/30 00:00:00' '2016/09/06 00:00:00' '2016/09/14 00:00:00'
 '2019/01/30 00:00:00' '2010/08/19 00:00:00' '2019/01/31 00:00:00'
 '2020/03/27 00:00:00' '2019/02/01 00:00:00' '2010/09/07 00:00:00'
 '2019/02/04 00:00:00' '2016/03/14 00:00:00' '2016/04/13 00:00:00'
 '2016/04/14 00:00:00' '2019/02/05 00:00:00' '2019/02/06 00:00:00'
 '2019/09/20 00:00:00' '2010/06/11 00:00:00' '2018/11/01 00:00:00'
 '2019/02/07 00:00:00' '2016/09/15 00:00:00' '2010/03/25 00:00:00'
 '2019/09/17 00:00:00' '2010/04/06 00:00:00' '2019/02/18 00:00:00'
 '2020/01/24 00:00:00' '2010/08/13 00:00:00' '2019/02/19 00:00:00'
 '2019/02/20 00:00:00' '2019/02/21 00:00:00' '2016/10/20 00:00:00'
 '2010/09/13 00:00:00' '2019/02/25 00:00:00' '2019/05/06 00:00:00'
 '2019/05/13 00:00:00' '2019/05/07 00:00:00' '2019/08/09 00:00:00'
 '2010/06/09 00:00:00' '2019/06/06 00:00:00' '2010/05/21 00:00:00'
 '2019/08/12 00:00:00' '2019/06/10 00:00:00' '2016/07/15 00:00:00'
 '2016/08/19 00:00:00' '2019/08/13 00:00:00' '2019/08/14 00:00:00'
 '2016/09/30 00:00:00' '2010/08/09 00:00:00' '2020/01/29 00:00:00'
 '2019/08/15 00:00:00' '2018/11/19 00:00:00' '2020/01/27 00:00:00'
 '2018/11/26 00:00:00' '2018/11/27 00:00:00' '2019/08/16 00:00:00'
 '2020/04/16 00:00:00' '2018/11/28 00:00:00' '2020/03/11 00:00:00'
 '2018/11/29 00:00:00' '2020/03/23 00:00:00' '2020/02/03 00:00:00'
 '2010/02/18 00:00:00' '2016/04/29 00:00:00' '2014/05/20 00:00:00'
 '2012/11/29 00:00:00' '2010/03/02 00:00:00' '2010/05/05 00:00:00'
 '2010/05/25 00:00:00' '2010/08/25 00:00:00' '2012/12/21 00:00:00'
 '2014/05/21 00:00:00' '2010/03/31 00:00:00' '2010/09/20 00:00:00'
 '2016/10/19 00:00:00' '2010/03/19 00:00:00' '2010/07/27 00:00:00'
 '2010/05/20 00:00:00' '2010/08/16 00:00:00' '2010/09/09 00:00:00'
 '2010/07/07 00:00:00' '2010/05/12 00:00:00' '2010/06/29 00:00:00'
 '2015/06/08 00:00:00' '2010/06/17 00:00:00' '2010/05/06 00:00:00'
 '2016/02/02 00:00:00' '2016/03/24 00:00:00' '2016/08/15 00:00:00'
 '2016/02/22 00:00:00' '2010/08/04 00:00:00' '2010/08/20 00:00:00'
 '2010/02/26 00:00:00' '2010/08/03 00:00:00' '2010/03/01 00:00:00'
 '2010/05/14 00:00:00' '2011/11/04 00:00:00' '2011/10/26 00:00:00'
 '2010/06/28 00:00:00' '2020/04/13 00:00:00' '2020/03/18 00:00:00'
 '2010/05/17 00:00:00' '2010/05/26 00:00:00' '2012/12/04 00:00:00'
 '2010/03/22 00:00:00' '2014/05/06 00:00:00' '2013/02/20 00:00:00'
 '2015/06/03 00:00:00' '2010/09/16 00:00:00' '2016/04/26 00:00:00'
 '2010/09/28 00:00:00' '2015/06/30 00:00:00' '2010/08/11 00:00:00'
 '2016/01/05 00:00:00' '2016/01/06 00:00:00' '2016/01/07 00:00:00'
 '2010/05/19 00:00:00' '2016/01/13 00:00:00' '2016/01/14 00:00:00'
 '2016/03/18 00:00:00' '2010/03/11 00:00:00' '2011/10/24 00:00:00'
 '2016/02/09 00:00:00' '2016/07/13 00:00:00' '2016/02/11 00:00:00'
 '2016/01/29 00:00:00' '2010/06/22 00:00:00' '2010/09/08 00:00:00'
 '2010/06/25 00:00:00' '2010/02/24 00:00:00' '2011/11/02 00:00:00'
 '2016/10/26 00:00:00' '2016/08/31 00:00:00' '2016/04/05 00:00:00'
 '2016/02/24 00:00:00' '2010/06/18 00:00:00' '2011/10/21 00:00:00'
 '2016/01/12 00:00:00' '2020/04/08 00:00:00' '2011/01/13 00:00:00'
 '2010/07/29 00:00:00' '2010/04/07 00:00:00' '2010/06/08 00:00:00'
 '2010/09/24 00:00:00' '2016/02/04 00:00:00' '2016/02/17 00:00:00'
 '2010/02/16 00:00:00' '2010/05/07 00:00:00' '2010/02/22 00:00:00'
 '2011/01/07 00:00:00' '2016/02/25 00:00:00' '2016/02/26 00:00:00'
 '2016/03/01 00:00:00' '2016/03/04 00:00:00' '2016/03/08 00:00:00'
 '2016/03/10 00:00:00' '2016/03/11 00:00:00' '2016/03/23 00:00:00'
 '2016/04/22 00:00:00' '2016/08/23 00:00:00' '2010/07/08 00:00:00'
 '2016/04/20 00:00:00' '2010/06/16 00:00:00' '2010/04/13 00:00:00'
 '2010/03/17 00:00:00' '2010/08/10 00:00:00' '2010/09/15 00:00:00'
 '2010/02/12 00:00:00' '2010/03/04 00:00:00' '2010/07/28 00:00:00'
 '2010/04/16 00:00:00' '2016/04/01 00:00:00' '2010/09/03 00:00:00'
 '2020/04/09 00:00:00' '2010/05/10 00:00:00' '2016/03/15 00:00:00'
 '2016/03/16 00:00:00' '2016/03/17 00:00:00' '2016/03/28 00:00:00'
 '2016/03/31 00:00:00' '2016/04/06 00:00:00' '2016/04/07 00:00:00'
 '2016/04/15 00:00:00' '2016/04/19 00:00:00' '2011/11/08 00:00:00'
 '2012/11/16 00:00:00' '2016/09/20 00:00:00' '2017/12/14 00:00:00'
 '2010/12/21 00:00:00' '2010/08/12 00:00:00' '2016/01/15 00:00:00'
 '2016/08/26 00:00:00' '2015/06/22 00:00:00' '2014/05/07 00:00:00'
 '2018/01/10 00:00:00' '2018/02/06 00:00:00' '2018/02/08 00:00:00'
 '2010/08/17 00:00:00' '2010/07/19 00:00:00' '2010/07/22 00:00:00'
 '2016/08/08 00:00:00' '2010/03/03 00:00:00' '2010/08/05 00:00:00'
 '2016/04/27 00:00:00' '2016/04/28 00:00:00' '2018/01/16 00:00:00'
 '2010/07/12 00:00:00' '2016/09/07 00:00:00' '2010/07/30 00:00:00'
 '2010/02/10 00:00:00' '2010/06/07 00:00:00' '2016/08/02 00:00:00'
 '2010/03/16 00:00:00' '2016/09/26 00:00:00' '2016/01/27 00:00:00'
 '2010/06/14 00:00:00' '2010/04/01 00:00:00' '2016/07/29 00:00:00'
 '2016/02/29 00:00:00' '2012/11/30 00:00:00' '2016/08/30 00:00:00'
 '2011/11/01 00:00:00' '2012/11/13 00:00:00' '2015/05/28 00:00:00'
 '2020/04/01 00:00:00' '2015/05/26 00:00:00' '2016/09/02 00:00:00'
 '2020/03/13 00:00:00' '2020/03/19 00:00:00' '2016/03/22 00:00:00'
 '2018/02/12 00:00:00' '2011/01/31 00:00:00' '2018/01/11 00:00:00'
 '2018/02/05 00:00:00' '2018/01/18 00:00:00' '2018/01/08 00:00:00'
 '2016/09/13 00:00:00' '2010/09/10 00:00:00' '2016/04/08 00:00:00'
 '2010/07/01 00:00:00' '2016/04/18 00:00:00' '2010/12/30 00:00:00'
 '2020/04/20 00:00:00' '2013/02/22 00:00:00' '2016/07/14 00:00:00'
 '2013/02/26 00:00:00' '2016/10/21 00:00:00' '2018/02/13 00:00:00'
 '2016/11/01 00:00:00' '2018/02/09 00:00:00' '2018/01/12 00:00:00'
 '2018/01/26 00:00:00' '2018/02/01 00:00:00' '2018/02/02 00:00:00'
 '2010/04/12 00:00:00' '2015/05/20 00:00:00' '2016/08/25 00:00:00'
 '2012/12/17 00:00:00' '2013/01/23 00:00:00' '2011/10/25 00:00:00'
 '2011/11/07 00:00:00' '2016/01/08 00:00:00' '2010/07/21 00:00:00'
 '2010/07/23 00:00:00' '2016/10/04 00:00:00' '2016/07/18 00:00:00'
 '2012/12/06 00:00:00' '2016/10/28 00:00:00' '2019/12/10 00:00:00'
 '2020/01/13 00:00:00' '2015/06/12 00:00:00' '2016/08/17 00:00:00'
 '2011/10/27 00:00:00' '2011/11/03 00:00:00' '2011/01/18 00:00:00'
 '2010/07/09 00:00:00' '2015/06/23 00:00:00' '2016/09/19 00:00:00'
 '2010/12/20 00:00:00' '2012/12/03 00:00:00' '2012/11/20 00:00:00'
 '2013/02/27 00:00:00' '2011/01/03 00:00:00' '2016/08/03 00:00:00'
 '2016/09/16 00:00:00' '2016/09/21 00:00:00' '2016/10/25 00:00:00'
 '2010/03/09 00:00:00' '2013/01/02 00:00:00' '2014/05/19 00:00:00'
 '2010/07/06 00:00:00' '2016/08/09 00:00:00' '2012/12/07 00:00:00'
 '2010/12/28 00:00:00' '2012/12/05 00:00:00' '2013/02/21 00:00:00'
 '2011/01/20 00:00:00' '2012/12/13 00:00:00' '2014/05/13 00:00:00'
 '2010/07/13 00:00:00' '2011/01/27 00:00:00' '2019/08/20 00:00:00'
 '2019/09/11 00:00:00' '2010/06/30 00:00:00' '2010/03/05 00:00:00'
 '2012/11/15 00:00:00' '2010/05/11 00:00:00' '2016/09/01 00:00:00'
 '2015/05/27 00:00:00' '2011/10/20 00:00:00' '2014/05/05 00:00:00'
 '2013/02/25 00:00:00' '2010/03/15 00:00:00' '2011/10/18 00:00:00'
 '2010/03/08 00:00:00' '2016/02/05 00:00:00' '2010/02/15 00:00:00'
 '2015/06/04 00:00:00' '2010/12/17 00:00:00' '2016/04/12 00:00:00'
 '2011/01/05 00:00:00' '2011/01/24 00:00:00' '2016/07/26 00:00:00'
 '2016/07/28 00:00:00' '2015/06/05 00:00:00' '2015/06/25 00:00:00'
 '2015/06/19 00:00:00' '2015/05/29 00:00:00' '2015/05/22 00:00:00'
 '2015/06/10 00:00:00' '2010/12/22 00:00:00' '2016/01/11 00:00:00'
 '2010/02/17 00:00:00' '2016/07/27 00:00:00' '2011/10/17 00:00:00'
 '2010/03/23 00:00:00' '2010/02/23 00:00:00' '2020/02/06 00:00:00'
 '2010/02/19 00:00:00' '2016/02/19 00:00:00' '2016/01/28 00:00:00'
 '2011/01/21 00:00:00' '2011/12/21 00:00:00' '2010/05/04 00:00:00'
 '2013/01/07 00:00:00' '2016/03/29 00:00:00' '2012/12/20 00:00:00'
 '2016/03/02 00:00:00' '2011/10/14 00:00:00' '2011/01/12 00:00:00'
 '2010/04/14 00:00:00' '2012/11/27 00:00:00' '2014/05/08 00:00:00'
 '2019/08/21 00:00:00' '2016/10/31 00:00:00' '2016/10/24 00:00:00'
 '2010/12/15 00:00:00' '2020/03/17 00:00:00' '2010/04/23 00:00:00'
 '2010/08/06 00:00:00' '2016/01/26 00:00:00' '2010/04/05 00:00:00'
 '2016/02/01 00:00:00' '2019/08/22 00:00:00' '2019/08/23 00:00:00'
 '2019/08/26 00:00:00' '2019/08/27 00:00:00' '2019/08/28 00:00:00'
 '2019/08/29 00:00:00' '2020/01/02 00:00:00' '2019/09/03 00:00:00'
 '2019/09/04 00:00:00' '2019/09/06 00:00:00' '2019/09/09 00:00:00'
 '2020/04/21 00:00:00' '2019/08/19 00:00:00' '2019/06/03 00:00:00'
 '2019/09/05 00:00:00' '2019/09/26 00:00:00' '2019/09/12 00:00:00'
 '2019/10/08 00:00:00' '2019/10/01 00:00:00' '2019/10/02 00:00:00'
 '2019/10/03 00:00:00' '2019/10/04 00:00:00' '2019/10/07 00:00:00'
 '2011/01/28 00:00:00' '2019/10/10 00:00:00' '2019/10/11 00:00:00'
 '2019/12/30 00:00:00' '2020/01/07 00:00:00' '2020/01/10 00:00:00'
 '2020/01/15 00:00:00' '2020/01/16 00:00:00' '2020/01/22 00:00:00'
 '2020/01/23 00:00:00' '2012/12/14 00:00:00' '2012/01/09 00:00:00'
 '2020/02/13 00:00:00' '2020/02/18 00:00:00' '2020/02/17 00:00:00'
 '2020/02/19 00:00:00' '2020/02/24 00:00:00' '2020/02/25 00:00:00'
 '2020/02/12 00:00:00' '2020/02/21 00:00:00' '2020/02/20 00:00:00'
 '2020/02/11 00:00:00' '2020/02/07 00:00:00' '2020/02/14 00:00:00'
 '2020/02/10 00:00:00' '2020/03/12 00:00:00' '2020/03/16 00:00:00'
 '2010/05/03 00:00:00' '2020/03/06 00:00:00' '2015/06/02 00:00:00'
 '2020/03/25 00:00:00' '2013/01/03 00:00:00' '2012/11/12 00:00:00'
 '2011/10/28 00:00:00' '2013/01/04 00:00:00' '2011/12/22 00:00:00'
 '2015/06/26 00:00:00' '2010/04/15 00:00:00' '2012/11/28 00:00:00'
 '2016/09/23 00:00:00' '2015/06/29 00:00:00' '2015/06/01 00:00:00'
 '2018/01/24 00:00:00' '2015/05/18 00:00:00' '2011/02/01 00:00:00'
 '2011/11/09 00:00:00' '2011/10/19 00:00:00' '2013/05/24 00:00:00'
 '2019/04/12 00:00:00' '2014/05/09 00:00:00' '2018/02/07 00:00:00'
 '2016/10/18 00:00:00' '2010/12/29 00:00:00' '2011/01/26 00:00:00'
 '2016/11/10 00:00:00' '2010/03/12 00:00:00' '2012/01/06 00:00:00'
 '2015/06/15 00:00:00' '2019/06/05 00:00:00' '2011/01/19 00:00:00'
 '2019/06/07 00:00:00' '2010/12/14 00:00:00' '2011/11/16 00:00:00'
 '2011/12/29 00:00:00' '2012/11/26 00:00:00' '2010/04/08 00:00:00'
 '2015/06/17 00:00:00' '2011/01/06 00:00:00' '2018/01/09 00:00:00'
 '2010/04/19 00:00:00' '2010/12/27 00:00:00' '2010/09/27 00:00:00'
 '2012/12/28 00:00:00' '2011/01/04 00:00:00' '2019/05/30 00:00:00'
 '2018/01/03 00:00:00' '2011/12/27 00:00:00' '2019/05/10 00:00:00'
 '2016/11/07 00:00:00' '2011/11/17 00:00:00' '2010/09/21 00:00:00'
 '2015/06/11 00:00:00' '2015/06/18 00:00:00' '2011/01/25 00:00:00'
 '2011/12/06 00:00:00' '2018/01/04 00:00:00' '2011/01/11 00:00:00'
 '2018/01/29 00:00:00' '2010/09/30 00:00:00' '2010/12/02 00:00:00'
 '2015/06/24 00:00:00' '2016/11/04 00:00:00' '2010/12/06 00:00:00'
 '2010/04/09 00:00:00' '2016/11/09 00:00:00' '2011/12/01 00:00:00'
 '2011/05/26 00:00:00' '2012/12/31 00:00:00' '2011/12/07 00:00:00'
 '2018/01/23 00:00:00' '2018/01/05 00:00:00' '2012/05/04 00:00:00'
 '2012/11/02 00:00:00' '2012/03/15 00:00:00' '2013/04/01 00:00:00'
 '2016/07/12 00:00:00' '2018/01/31 00:00:00' '2018/12/21 00:00:00'
 '2012/04/20 00:00:00' '2011/01/14 00:00:00' '2014/12/10 00:00:00'
 '2018/04/25 00:00:00' '2018/05/02 00:00:00' '2017/10/27 00:00:00'
 '2018/04/17 00:00:00' '2018/04/18 00:00:00' '2018/04/24 00:00:00'
 '2018/04/19 00:00:00' '2018/04/27 00:00:00' '2014/12/16 00:00:00'
 '2014/12/11 00:00:00' '2014/12/12 00:00:00' '2014/12/15 00:00:00'
 '2014/12/01 00:00:00' '2009/12/31 00:00:00' '2014/12/03 00:00:00'
 '2014/12/09 00:00:00' '2018/04/20 00:00:00' '2018/04/23 00:00:00'
 '2018/04/30 00:00:00' '2018/05/01 00:00:00' '2018/05/07 00:00:00'
 '2018/05/03 00:00:00' '2018/04/26 00:00:00' '2018/05/08 00:00:00'
 '2018/05/04 00:00:00' '2010/12/16 00:00:00' '2011/12/08 00:00:00'
 '2014/11/25 00:00:00' '2010/12/10 00:00:00' '2010/12/09 00:00:00'
 '2018/06/07 00:00:00' '2009/11/17 00:00:00' '2009/11/30 00:00:00'
 '2009/11/20 00:00:00' '2009/11/18 00:00:00' '2009/11/19 00:00:00'
 '2009/11/16 00:00:00' '2018/06/05 00:00:00' '2009/11/24 00:00:00'
 '2009/12/03 00:00:00' '2009/12/01 00:00:00' '2010/09/23 00:00:00'
 '2010/10/05 00:00:00' '2014/12/08 00:00:00' '2009/10/29 00:00:00'
 '2009/12/07 00:00:00' '2009/12/08 00:00:00' '2009/10/19 00:00:00'
 '2009/10/28 00:00:00' '2009/11/02 00:00:00' '2009/11/04 00:00:00'
 '2009/11/09 00:00:00' '2009/11/03 00:00:00' '2011/12/09 00:00:00'
 '2009/10/20 00:00:00' '2009/11/12 00:00:00' '2009/11/10 00:00:00'
 '2012/03/23 00:00:00' '2012/03/27 00:00:00' '2012/04/24 00:00:00'
 '2012/05/01 00:00:00' '2012/05/07 00:00:00' '2012/03/21 00:00:00'
 '2012/03/26 00:00:00' '2012/04/18 00:00:00' '2012/03/13 00:00:00'
 '2012/07/09 00:00:00' '2012/05/08 00:00:00' '2012/05/09 00:00:00'
 '2012/05/10 00:00:00' '2012/05/21 00:00:00' '2012/05/22 00:00:00'
 '2012/05/30 00:00:00' '2012/05/31 00:00:00' '2012/06/05 00:00:00'
 '2012/05/24 00:00:00' '2012/06/18 00:00:00' '2012/06/21 00:00:00'
 '2012/07/02 00:00:00' '2012/05/23 00:00:00' '2012/06/28 00:00:00'
 '2012/06/25 00:00:00' '2012/06/26 00:00:00' '2012/06/15 00:00:00'
 '2012/06/11 00:00:00' '2012/06/12 00:00:00' '2012/06/06 00:00:00'
 '2012/06/08 00:00:00' '2012/06/01 00:00:00' '2012/06/07 00:00:00'
 '2012/06/27 00:00:00' '2012/06/29 00:00:00' '2012/03/19 00:00:00'
 '2012/03/29 00:00:00' '2012/06/04 00:00:00' '2012/07/03 00:00:00'
 '2012/04/02 00:00:00' '2012/07/06 00:00:00' '2012/03/22 00:00:00'
 '2012/04/03 00:00:00' '2014/11/13 00:00:00' '2014/11/14 00:00:00'
 '2014/11/17 00:00:00' '2014/11/21 00:00:00' '2014/11/18 00:00:00'
 '2014/11/19 00:00:00' '2014/11/20 00:00:00' '2012/04/25 00:00:00'
 '2012/04/26 00:00:00' '2012/05/02 00:00:00' '2012/05/03 00:00:00'
 '2012/03/08 00:00:00' '2012/06/20 00:00:00' '2012/07/05 00:00:00'
 '2012/04/27 00:00:00' '2012/06/13 00:00:00' '2012/04/13 00:00:00'
 '2012/04/16 00:00:00' '2012/04/19 00:00:00' '2012/04/17 00:00:00'
 '2014/11/11 00:00:00' '2014/11/12 00:00:00' '2012/04/09 00:00:00'
 '2012/04/10 00:00:00' '2012/05/25 00:00:00' '2012/06/14 00:00:00'
 '2012/04/11 00:00:00' '2012/03/20 00:00:00' '2012/04/12 00:00:00'
 '2014/11/24 00:00:00' '2014/11/26 00:00:00' '2014/12/02 00:00:00'

In [25]:
print(df["ZIP"].unique().tolist())

['60034', '28208', '46131', '85298', '85142', '85338', '86040', '85212', '95821', '93254', '94501', '93458', '91505', '94605', '93550', '95363', '95023', '96093', '20019', '20002', '20001', '20003', '32257', '32043', '33142', '32216', '33896', '32340', '34203', '83301', '62650', '62075', '62846', '46227', '46628', '42431', '67037', '41017', '42240', '41076', '40218', '70119', '70607', '70122', '70117', '71334', '70053', '70501', '70131', '70128', '70663', '70058', '70056', '70462', '21401', '49423', '48207', '55345', '55423', '48152', '48043', '48174', '48075', '55419', '55027', '55404', '55070', '55106', '56001', '03235', '08530', '07083', '28590', '27704', '27701', '27713', '27596', '74129', '74105', '75235', '76554', '77091', '78839', '76031', '84065', '84326', '84043', '55075', '60139', '70544', '55720', '52339', '56626', '74465', '85364', '78741', '44114', '84738', '32256', '91361', '39462', '65582', '57772', '43207', '45415', '87013', '65401', '87313', '87401', '75057', '98802', '35543', '00735', '00783', '00766', '57775', '00729', '96929', '96912', '96924', '76119', '85710', '35474', '36867', '99577', '95461', '99501', '99801', '99623', '72117', '36116', '72206', '72764', '72730', '72173', '85266', '86514', '85356', '38127', '38118', '38106', '33321', '85349', '63764', '85705', '85014', '85354', '85215', '85008', '85040', '85033', '86044', '37404', '37040', '37013', '37206', '98513', '97305', '37204', '37764', '37075', '37148', '38019', '33771', '32825', '60543', '75204', '59522', '37015', '59713', '59032', '65560', '65761', '63942', '63851', '85743', '85085', '91006', '85641', '94568', '92019', '95316', '85043', '90222', '58638', '59345', '78572', '41171', '01581', '59270', '59338', '59501', '66607', '59351', '27278', '59525', '59332', '59526', '59457', '59714', '68822', '00970', '85937', '47591', '51342', '48910', '59427', '35210', '99921', '69201', '77571', '75237', '77327', '75147', '83001', '86314', '85344', '85138', '55441', '56098', '56384', '85546', '85250', '55420', '85122', '95901', '33170', '61354', '89830', '89834', '92114', '95959', '76011', '07305', '75212', '76105', '08758', '75220', '75703', '87109', '87532', '78745', '77081', '76853', '78629', '77083', '77017', '75165', '77080', '78626', '77030', '75224', '75028', '76210', '77568', '78660', '79907', '78753', '78220', '78203', '78752', '75216', '78574', '77084', '75007', '75104', '77530', '75052', '75038', '95501', '76180', '76014', '03103', '03102', '77707', '08505', '76028', '76233', '76705', '75069', '78413', '77583', '92027', '96022', '92028', '92020', '92544', '90623', '95762', '91502', '95422', '95207', '93060', '92007', '95942', '90808', '90063', '90062', '90011', '90002', '90031', '91352', '87571', '90008', '91340', '95955', '95348', '91331', '75232', '75203', '75068', '27215', '27516', '75228', '77573', '78537', '79029', '76179', '79762', '28806', '76102', '75034', '27921', '92882', '28734', '77407', '43615', '45723', '75040', '78114', '75051', '77004', '77023', '58335', '44612', '77338', '78636', '91406', '90023', '90245', '93927', '90650', '77494', '76544', '75010', '28422', '10454', '28037', '76549', '76137', '78616', '78653', '76661', '75754', '78650', '75070', '76859', '76861', '75455', '77316', '77868', '78217', '77504', '75252', '78579', '79778', '75075', '97738', '97842', '78235', '77434', '17740', '75032', '78842', '20735', '17047', '78154', '79928', '79936', '18210', '78069', '02739', '77055', '77014', '75160', '29102', '17901', '76084', '78596', '18826', '11791', '76302', '75098', '79925', '82721', '82523', '10989', '97060', '94040', '92363', '95953', '95957', '95304', '37210', '44907', '57322', '57735', '57356', '57744', '57201', '37874', '26351', '95405', '25550', '26520', '92107', '54539', '92110', '95005', '93003', '79512', '53186', '54822', '18603', '54136', '53948', '93627', '53215', '54157', '98632', '98661', '98104', '98168', '99217', '99202', '98604', '98826', '98499', '98312', '99004', '98201', '98930', '99021', '98564', '99026', '99301', '99357', '98118', '90221', '98108', '19087', '98942', '98388', '98321', '98674', '78245', '05477', '60135', '05465', '05490', '76207', '75236', '94952', '94063', '29607', '62221', '37066', '93907', '92106', '56150', '95662', '92701', '93065', '94080', '92782', '78239', '37064', '77099', '95112', '18360', '23061', '20148', '20176', '20136', '23225', '23223', '80904', '80033', '22572', '84094', '19971', '84104', '33030', '84009', '84058', '32110', '84096', '36726', '90280', '80010', '80031', '75904', '80401', '80011', '80112', '81428', '84404', '84405', '94533', '32776', '57319', '32626', '57783', '29902', '29483', '77503', '29615', '02865', '02909', '02895', '02842', '02891', '78249', '15132', '80207', '80249', '80236', '18101', '19131', '15137', '15042', '79556', '80864', '80634', '80905', '30315', '83328', '80487', '80550', '06232', '06401', '06410', '30016', '60618', '62920', '18232', '15239', '18354', '17408', '97007', '97701', '97702', '97754', '97338', '84119', '97360', '97862', '84325', '06082', '78119', '06615', '20011', '20024', '33063', '84728', '33311', '84050', '84074', '33332', '06479', '97801', '73109', '00949', '73555', '74873', '74931', '73601', '74023', '73012', '73034', '83716', '73160', '73170', '45506', '44128', '44108', '43215', '43204', '45680', '75081', '78541', '44111', '44086', '45431', '44656', '78336', '77054', '46409', '43054', '45241', '43050', '45840', '10470', '10462', '11370', '11432', '47802', '62025', '60181', '60411', '10962', '10469', '14901', '14222', '10455', '11201', '77625', '11434', '78503', '10453', '12211', '12534', '06062', '14454', '10954', '14609', '89110', '89106', '89820', '89509', '88001', '78006', '87507', '79353', '87328', '87417', '42635', '41040', '60487', '67062', '71060', '67877', '41143', '40504', '87144', '33935', '32465', '32446', '71111', '32536', '34786', '34787', '33405', '77995', '33407', '34610', '76958', '55445', '84041', '07062', '08232', '07304', '08805', '55920', '08103', '08102', '07060', '68803', '68949', '68506', '68046', '58201', '58701', '27909', '28027', '27522', '60555', '28205', '27610', '28269', '27523', '04926', '02332', '32725', '30311', '30633', '31602', '01340', '03861', '49221', '04344', '31211', '31206', '31324', '87506', '31404', '30032', '30344', '86505', '30046', '54235', '30093', '19438', '00792', '00692', '30253', '30904', '31709', '96913', '96919', '35057', '96926', '96928', '55976', '96911', '96916', '85207', '85120', '72601', '38868', '39532', '93513', '27617', '27604', '28607', '27893', '46407', '59645', '59106', '39204', '39769', '39759', '93311', '92583', '67039', '39773', '49036', '39741', '39083', '38930', '39701', '39753', '39110', '39666', '39648', '92131', '95116', '95110', '50428', '45631', '50482', '52240', '51035', '50263', '83642', '35148', '38860', '35188', '38619', '38863', '63118', '64802', '63104', '64111', '65323', '80122', '37873', '59057', '68039', '83687', '83402', '74344', '61520', '62864', '62960', '60506', '05403', '63366', '63755', '63126', '32905', '32940', '63390', '56308', '55013', '55343', '55428', '06333', '75140', '61270', '62613', '62010', '62814', '61876', '61817', '62220', '60458', '60644', '62223', '60033', '28311', '62351', '62447', '60451', '97303', '61368', '46218', '46060', '47848', '46222', '46155', '46204', '47904', '47040', '42420', '47838', '41721', '70811', '70115', '70778', '70113', '32073', '42101', '34142', '56649', '55430', '33166', '10460', '55362', '55104', '34117', '32209', '34202', '34972', '32663', '70126', '70764', '70807', '55042', '56011', '56537', '55355', '56156', '70507', '70592', '70114', '70127', '00610', '00605', '21710', '83252', '21043', '48831', '55403', '55412', '55109', '53095', '56560', '55372', '55422', '46517', '28304', '53088', '55912', '06796', '43616', '39183', '73055', '03051', '06106', '06120', '06112', '06051', '27804', '28697', '29036', '13037', '06357', '06360', '06877', '53910', '74960', '25177', '26416', '98801', '98936', '06790', '06484', '06704', '06708', '06705', '99115', '98146', '98607', '28217', '28079', '43793', '29461', '93272', '44012', '63334', '00601', '27344', '29710', '29406', '23114', '23325', '84015', '98021', '98248', '84332', '44241', '73932', '99338', '98501', '78727', '90723', '12545', '58413', '37355', '26444', '54935', '53406', '53154', '54612', '78207', '75189', '78681', '78582', '83644', '78023', '79241', '77351', '77656', '71006', '70129', '29334', '78645', '70805', '70714', '83350', '01034', '01105', '02601', '01915', '02131', '76454', '02720', '77070', '01843', '02644', '76401', '01109', '01104', '79035', '01570', '55386', '21212', '87125', '76120', '01880', '48310', '75119', '07032', '20874', '20878', '11234', '47725', '37034', '37080', '38501', '78330', '48219', '75217', '75218', '49454', '49012', '06042', '13901', '29407', '97230', '31513', '36451', '35014', '92231', '67216', '41501', '71038', '70586', '06238', '24055', '03857', '72722', '85259', '60659', '99835', '31779', '64423', '48237', '60804', '38112', '38115', '75009', '03086', '01301', '73840', '98465', '85003', '94010', '77063', '48813', '48001', '48706', '04351', '48809', '48880', '49107', '48035', '48450', '48128', '04086', '04259', '04330', '92630', '94806', '91423', '93535', '95492', '90019', '93274', '85232', '85303', '32809', '39740', '90201', '48341', '31792', '49203', '48897', '18505', '48601', '63650', '49202', '86001', '85543', '85607', '93551', '85297', '85323', '85201', '85540', '85037', '91325', '85302', '85009', '78602', '17025', '64477', '25601', '29650', '94070', '44126', '46072', '89018', '72517', '71832', '19382', '92618', '15333', '90660', '50156', '93291', '87016', '90057', '87002', '98338', '92275', '15044', '75002', '53205', '98087', '98682', '04578', '04860', '04915', '04952', '04973', '04216', '98685', '85745', '98405', '71929', '58801', '61866', '95212', '22603', '75556', '92571', '06053', '06256', '06052', '61277', '61561', '36266', '93618', '78580', '98273', '81632', '73038', '34758', '56529', '33947', '24073', '63010', '75901', '43046', '61548', '43229', '24277', '99159', '94589', '74726', '90004', '46809', '33406', '00646', '45889', '53821', '12838', '40505', '77506', '28024', '10035', '23847', '06451', '41144', '40014', '77520', '76303', '45503', '97405', '17516', '35967', '10306', '63845', '54650', '45122', '06614', '49509', '53086', '65802', '84604', '87047', '71801', '94566', '95503', '55927', '65656', '97068', '29405', '29571', '20147', '98328', '55443', '77510', '08865', '24702', '93923', '78254', '96029', '07302', '11208', '53204', '92407', '50220', '60540', '60516', '60521', '46835', '83204', '29654', '78644', '70630', '70582', '02120', '28732', '04359', '49265', '49437', '48195', '28083', '68763', '13204', '75116', '10607', '43130', '44483', '75567', '78852', '79106', '26301', '28166', '27405', '79905', '27573', '27107', '33023', '32765', '55082', '32114', '50590', '55409', '54868', '16673', '13856', '91911', '33823', '68818', '84624', '19147', '67410', '67880', '78389', '94117', '48301', '26554', '37207', '96101', '48884', '64740', '01027', '96734', '53703', '90803', '01085', '70570', '92057', '18370', '94560', '91342', '91741', '91766', '93905', '95982', '80526', '30297', '30518', '30092', '31601', '96706', '96732', '60504', '46360', '84501', '71291', '29485', '70071', '49677', '36265', '42301', '77385', '29316', '29492', '99556', '35160', '78253', '77705', '40390', '06039', '06255', '95553', '36751', '06450', '60162', '03275', '78732', '62294', '77904', '40391', '04062', '04350', '61322', '57350', '93222', '95202', '86504', '57108', '57401', '30631', '33174', '35501', '57382', '36360', '21228', '75103', '84037', '32207', '00685', '84341', '84081', '64083', '85044', '85015', '85193', '85306', '85006', '84025', '84401', '56187', '72076', '72209', '16666', '27302', '93244', '95687', '95356', '98937', '98284', '98065', '80235', '80907', '80631', '81501', '99173', '98444', '80538', '77096', '98331', '26426', '26104', '33194', '33033', '32526', '36081', '35080', '99578', '99630', '99666', '99552', '99608', '99688', '99631', '99721', '99591', '99918', '99686', '85296', '33626', '32344', '33334', '66083', '42164', '40310', '40486', '40962', '42303', '41649', '41035', '30354', '30606', '41537', '41240', '41222', '33172', '42038', '42647', '40353', '41472', '40741', '41723', '40977', '40031', '40769', '70301', '04572', '30071', '30901', '20634', '20660', '48506', '30411', '48185', '37865', '84720', '98663', '55429', '48710', '92154', '33467', '33563', '48126', '81504', '39576', '78201', '34771', '03264', '78538', '07860', '32128', '54664', '19124', '32810', '74464', '71302', '02832', '78244', '00782', '99580', '85225', '83422', '76016', '93926', '82324', '19025', '80233', '06119', '59353', '76633', '76008', '00678', '32766', '59937', '59727', '75205', '57481', '85234', '33411', '37379', '10037', '11507', '11211', '39206', '72031', '52556', '65668', '88310', '76114', '98642', '71202', '59748', '91730', '75501', '92543', '80643', '87327', '30115', '63136', '78202', '04473', '27295', '24874', '79932', '07522', '91301', '30809', '47424', '06830', '52356', '75041', '59036', '42167', '01830', '01253', '57216', '03909', '22835', '89084', '95948', '34470', '40456', '44004', '07926', '63131', '33966', '32084', '33437', '11433', '90747', '91709', '74820', '41048', '78132', '66538', '66048', '74884', '99508', '48881', '00731', '79331', '02140', '74127', '97209', '40004', '44134', '72633', '39564', '07067', '85632', '65685', '00638', '35007', '61320', '75078', '38114', '97080', '48214', '52202', '22310', '31522', '28052', '72210', '77511', '85029', '19348', '06001', '85746', '01545', '80239', '94556', '93725', '93309', '93230', '90504', '32541', '77406', '99637', '72616', '35973', '61401', '36303', '21113', '36610', '65270', '76367', '20743', '21286', '79065', '11235', '05651', '84740', '74331', '62052', '20171', '44130', '55416', '95206', '61032', '15139', '65556', '14468', '14225', '99625', '95372', '14220', '01850', '92129', '55102', '80517', '32803', '34994', '80230', '91506', '17257', '15022', '29127', '37367', '30134', '96781', '19134', '78623', '72315', '79521', '78577', '92801', '76134', '40026', '96766', '93436', '10956', '00624', '63122', '25701', '03561', '91381', '93619', '45003', '59063', '31321', '94607', '04920', '32347', '85017', '67737', '75067', '85335', '78255', '75211', '92867', '49618', '93710', '91405', '91722', '90732', '90045', '94561', '81323', '93601', '95490', '95415', '70806', '92649', '02053', '63130', '59729', '92308', '92392', '28753', '92117', '92083', '92054', '92124', '78251', '94110', '95237', '30110', '94044', '95118', '93955', '95991', '92869', '80102', '81211', '80910', '80547', '80723', '32641', '33313', '34102', '19934', '32967', '33180', '96819', '02021', '01519', '49079', '33625', '95127', '60964', '63933', '28379', '54603', '11221', '77623', '27349', '62226', '60073', '34266', '60548', '01731', '17065', '11205', '76578', '20111', '41606', '64114', '55124', '60544', '08260', '32205', '39443', '10473', '46214', '11223', '24572', '35203', '28273', '44047', '94536', '28654', '04103', '01701', '95632', '55418', '20902', '55060', '00754', '15767', '07751', '37027', '92093', '78237', '79761', '60074', '76092', '76384', '05077', '27217', '02476', '29669', '77378', '01057', '79701', '33013', '33176', '32703', '34677', '30236', '31768', '30022', '30228', '30824', '96821', '50588', '50619', '52060', '52761', '50312', '50313', '83202', '60619', '46324', '46229', '66062', '67522', '66442', '40744', '40033', '70605', '70560', '70065', '70458', '01879', '02169', '96008', '80004', '48892', '45342', '98516', '32211', '36587', '97124', '54817', '07090', '37659', '77521', '61064', '70538', '32601', '43452', '83401', '95051', '62540', '21207', '86004', '60435', '44827', '98360', '98237', '28043', '98225', '88047', '61088', '58104', '99507', '46504', '98374', '33472', '43532', '54814', '93451', '08402', '08012', '60643', '06492', '11215', '79104', '01475', '19140', '75071', '23606', '20860', '62246', '24127', '98122', '54901', '60084', '58561', '03060', '67864', '48209', '07009', '08009', '78586', '93950', '64113', '20784', '73008', '75025', '75077', '27589', '07076', '21078', '48307', '69301', '11779', '50129', '54902', '95926', '95822', '92377', '32327', '04210', '04042', '49616', '48612', '48823', '48843', '48044', '49442', '48621', '48429', '55304', '78375', '47342', '48375', '02766', '35619', '85048', '61554', '47403', '97039', '98335', '72662', '95694', '83101', '87301', '83631', '82604', '83629', '16503', '36460', '71647', '74734', '83539', '08631', '12590', '71105', '47371', '12524', '39440', '43044', '54481', '73129', '19148', '98902', '00969', '99223', '46382', '41018', '80108', '11548', '21230', '03867', '40380', '73062', '98188', '68005', '70767', '34285', '76561', '35126', '63732', '87020', '18103', '68127', '60510', '55376', '73717', '60431', '51054', '14845', '87106', '21042', '90805', '84003', '62451', '54302', '41031', '11710', '27106', '94608', '98042', '85086', '56097', '72211', '85257', '76205', '65717', '95401', '36456', '11784', '81082', '78643', '47302', '29910', '44653', '66901', '72015', '11735', '54201', '76571', '47404', '02769', '21229', '59068', '44035', '23347', '22201', '33613', '85202', '56284', '27858', '32424', '52640', '42413', '08055', '11771', '53813', '54950', '03873', '54871', '22473', '46526', '69336', '99518', '11001', '97448', '53913', '83651', '71242', '80654', '60542', '60503', '52336', '98390', '32312', '66226', '27890', '91901', '67525', '99669', '59826', '31055', '49654', '47959', '28612', '27320', '29550', '76065', '27205', '56058', '95965', '91737', '80831', '44677', '76557', '60018', '67124', '10583', '28301', '01867', '43081', '22030', '79935', '10451', '81226', '68510', '17028', '98597', '72310', '47433', '60015', '74047', '00977', '14517', '98903', '62675', '30815', '06489', '97443', '00960', '33185', '61443', '46814', '46783', '12861', '44125', '98584', '54487', '48906', '47274', '46064', '11720', '65325', '47355', '38128', '10305', '61738', '77584', '16417', '59828', '22407', '19145', '11214', '62341', '02125', '12022', '15650', '54956', '76542', '96792', '96130', '92121', '12561', '58721', '35674', '88267', '44509', '11023', '19146', '57737', '12068', '48160', '95831', '51103', '54930', '66424', '93552', '21090', '92130', '98221', '52323', '46385', '35759', '75042', '59221', '94538', '17090', '27576', '22701', '35044', '40324', '91335', '36048', '61063', '00703', '27235', '39211', '76648', '65340', '10472', '53511', '62691', '06043', '14904', '73026', '63139', '55040', '69101', '75125', '87801', '02333', '08021', '12309', '70583', '76123', '71071', '07446', '28570', '77003', '94530', '55946', '55736', '69361', '97267', '55426', '11566', '85255', '39120', '53222', '21903', '76018', '75035', '75050', '38761', '36426', '68901', '49505', '97106', '06226', '06033', '60030', '60953', '55411', '55414', '56326', '63050', '89130', '10468', '85194', '91950', '45845', '32771', '01520', '80104', '05055', '85050', '08109', '38016', '94402', '34221', '30058', '60453', '62024', '62431', '17603', '61956', '90703', '21921', '12209', '11953', '43105', '33510', '61802', '98550', '11978', '70808', '48872', '11596', '18322', '06457', '56048', '60440', '27540', '98532', '83805', '06516', '58601', '45864', '91910', '97523', '54124', '94925', '77032', '99705', '14559', '45359', '18704', '11694', '47201', '64080', '97457', '60061', '61742', '44074', '54880', '32164', '97062', '15074', '32303', '97466', '03221', '15234', '98531', '27806', '11901', '49525', '21157', '73560', '76487', '07093', '78578', '75126', '06264', '30224', '60010', '99148', '75961', '49316', '33324', '77547', '64671', '35475', '76010', '01062', '48048', '93305', '93610', '92683', '46368', '70070', '01760', '62265', '94022', '61360', '78717', '22039', '47240', '79415', '21224', '55904', '24401', '00718', '19056', '69350', '90255', '75241', '26059', '99703', '85021', '12550', '98005', '

### Return Null Count For Each Feature

In [ ]:
print("Number of nulls in each feature")
for col in df.columns:
    print(f"{col} : {df[col].isnull().sum()}")

### Retrieve Longest String in Each Feature

In [ ]:
# Compute max string length per column
longest_lengths = df.astype(str).applymap(len).max()

# Format result
result = longest_lengths.reset_index()
result.columns = ["Feature", "Max String Length"]

result