## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

## Exploratory Data Analysis with Polars

### Load CSV File into Polars DataFrame

In [5]:
df = pl.read_csv("../data/Insurance_Result_data.csv",
                 ignore_errors=True)

df

shape: (34_110, 4)
┌──────────────┬──────────────┬──────────────┬─────────────────┐
│ Claim Number ┆ Claim Amount ┆ Close Amount ┆ Disposition     │
│ ---          ┆ ---          ┆ ---          ┆ ---             │
│ str          ┆ f64          ┆ f64          ┆ str             │
╞══════════════╪══════════════╪══════════════╪═════════════════╡
│ Y5VA9KOE89   ┆ 100.0        ┆ 0.0          ┆ Deny            │
│ P51DOJLR8W   ┆ 199.99       ┆ 0.0          ┆ Deny            │
│ OUUZFP7EFL   ┆ 410.0        ┆ 59.85        ┆ Settle          │
│ CGP3L1CCP2   ┆ 240.0        ┆ 0.0          ┆ Deny            │
│ JDFLPD7J9Z   ┆ 11.36        ┆ 11.36        ┆ Approve in Full │
│ …            ┆ …            ┆ …            ┆ …               │
│ OYT2XKKCG7   ┆ 400.0        ┆ 0.0          ┆ Deny            │
│ 0WTU4L3YXH   ┆ 380.8        ┆ 142.0        ┆ Settle          │
│ X9MZQW0X3Q   ┆ 28.95        ┆ 28.95        ┆ Approve in Full │
│ ITF3RPFW6L   ┆ 75.15        ┆ 75.15        ┆ Approve in Full │
│ A9G61X0801   ┆ 299.0        ┆ 149.5        ┆ Settle          │
└──────────────┴──────────────┴──────────────┴─────────────────┘

In [6]:
column_data_types = zip(df.columns, df.dtypes)

for column, dtype in column_data_types:
    print(f"{column}:\t\t{dtype}")

Claim Number:		String
Claim Amount:		Float64
Close Amount:		Float64
Disposition:		String

### Display Summary Statistics for All Columns

In [7]:
summary = df.describe()
print(summary)

shape: (9, 5)
┌────────────┬──────────────┬──────────────┬──────────────┬─────────────────┐
│ statistic  ┆ Claim Number ┆ Claim Amount ┆ Close Amount ┆ Disposition     │
│ ---        ┆ ---          ┆ ---          ┆ ---          ┆ ---             │
│ str        ┆ str          ┆ f64          ┆ f64          ┆ str             │
╞════════════╪══════════════╪══════════════╪══════════════╪═════════════════╡
│ count      ┆ 34110        ┆ 34110.0      ┆ 34110.0      ┆ 34110           │
│ null_count ┆ 0            ┆ 0.0          ┆ 0.0          ┆ 0               │
│ mean       ┆ null         ┆ 717.844178   ┆ 104.883016   ┆ null            │
│ std        ┆ null         ┆ 8290.881802  ┆ 1393.564677  ┆ null            │
│ min        ┆ 000TQE7Z0O   ┆ 0.0          ┆ 0.0          ┆ Approve in Full │
│ 25%        ┆ null         ┆ 60.0         ┆ 0.0          ┆ null            │
│ 50%        ┆ null         ┆ 175.0        ┆ 0.0          ┆ null            │
│ 75%        ┆ null         ┆ 460.0        ┆ 75.0         ┆ null            │
│ max        ┆ ZZW9JKTJMJ   ┆ 900000.0     ┆ 250000.0     ┆ Settle          │
└────────────┴──────────────┴──────────────┴──────────────┴─────────────────┘

### Count of Nulls In Each Feature

In [8]:
for col in df.columns:
    print(f"{col} : {df[col].is_null().sum()}")

Claim Number : 0
Claim Amount : 0
Close Amount : 0
Disposition : 0

### Find Longest Text Length in Each Column

In [9]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 2)
┌──────────────┬─────────────┐
│ Claim Number ┆ Disposition │
│ ---          ┆ ---         │
│ u32          ┆ u32         │
╞══════════════╪═════════════╡
│ 10           ┆ 15          │
└──────────────┴─────────────┘

### Count Unique Values in Each Column

In [10]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                 Unique values in Claim Number : 34110
                 Unique values in Claim Amount : 11944
                 Unique values in Close Amount : 6509
                  Unique values in Disposition : 3

### Retrieve Unique Values in Each Feature

In [11]:
for col in df.columns:
    unique_values = df[col].unique()
    print(f"'{col}' {len(unique_values)}: {unique_values.to_list()}")

'Claim Number' 34110: ['QBRY5IML51', '10XRRCHSOM', 'J7AVDISITE', 'JNE80XCTV4', 'V4P7VYA55G', 'XUB3FNO4IR', 'KWTGT2F3C0', 'SA46S3DKNA', 'B64ZE7FM64', 'W3SQVLMY7X', 'VI7B3BE0U2', 'CTDUGQUDUA', 'K9D3XZYA5J', 'GKCY0XIJFQ', 'KWDUJRVFQD', 'OLTVTH3Y1K', 'BWR6HK4DJ8', '0T6A0KQBMQ', 'W85C5NMNH2', 'NHFALTI4I8', '84NBSA7S7V', '9701RA265U', 'SF1636GVUW', 'VMUP7CFZZB', '987SNPCODV', 'AXV59TV5LZ', 'D3MWOC0NGN', 'OTJKZHPGQ5', 'UOS3W10PTF', '67ICXZDSQS', '6YV9T28FAE', 'V3SNDRYOZ0', 'N36GBSFBCK', 'L8DR2AIGDT', 'HU91S88VPE', 'XJDRA7RKYK', 'P7HQEDD4PV', 'BCDELXLCJR', 'J8ODWOIRZ5', 'UM8PQR1OSO', 'OW9PNT3CD7', 'ZW7U60DPAD', 'D2D06OORCT', 'CURV5E6ZL4', 'DM7FNX36SR', 'EI5IDMAMKQ', 'CK8VD8NTGL', 'K6IC1GNGD7', 'HPF87HJPUW', 'VDETGY6SFW', 'S1GIC18VI2', 'Y4DN6OYV9D', 'YA3KZ1D708', 'OPK0F5M32Y', '2HNF4CIC80', 'OSUK6NVT39', 'GYWIOAQRJK', 'O1BSKY6C7L', 'TEVKR6FC24', 'ZRW8L70OF9', 'AK8OKRJ8S1', 'OUYSONQS9P', 'FT9Q8S6N25', 'SUAGGCTL68', 'WPWPWPJIFC', 'TF65YZHLLX', 'Y2TXDWX6C9', '9ZYMR8DNE1', 'URNO7JL2A1', 'D50AWFLOVQ', '33GRG423FO', 'OHJIUBRXPU', 'U7K57EFXKN', 'LOQA67FIAD', 'BO303RXT4H', 'OC2G94MFMP', 'AAVFFCVX8X', 'O9UVBRT8PW', 'LHACYLEH3D', 'AJAU2UKB30', 'NLP0AR8WPZ', 'CKWFNRACVO', '2G01CQK558', 'Q136SX053I', 'MA005V3TX3', 'F713O8MLR1', 'FS1USH0TR9', 'WOR94EVENC', 'XAQNUU8WXV', 'T1PLXFBWZW', '06C6HXB40J', 'LQOYGAZ73Q', 'QIE8QLIY0D', 'E7PT7CHJFJ', '49K3SSRACT', 'LUJTIZI6JE', 'X8046O6NOB', 'O9NXH9CBPT', 'Y78SRE8XMS', 'Q56UP620F5', '6P0WU8ALI1', 'V2EQGYHDMQ', 'T5TI2SJQA6', 'NWB3UMO2K6', 'KS4XFXP09M', 'ZZB4ELZNEP', 'H2T5K3FQCZ', '3938LJFVK7', 'Z1TFCQIGCM', '0B520CL5BV', '2T4F6HXREC', 'ZQUEJI9AC7', 'PCUV9MSD0M', 'YDLN8OLS3U', 'HVX199IT66', 'HB184FO18L', '5NOIZJEGCA', 'QAVOP6XTZC', 'BN4YJ4U4X6', '61DIPAKGSZ', 'ODQEN4CMWX', 'ZAGTCWO2BO', 'I4Q2QMIOIN', 'ERLZFXOJEZ', 'ZWMP3PPWIO', 'NCKTJVYC76', 'P5942W6435', '1FXJN8C4CN', 'EFUBEZAP1B', '2NHR3605OT', 'MRLA4S6DK7', 'XDAF8K59LF', 'GYD8JPO3XF', 'PCJD1X3HU4', '2DP8KC3Y3B', '7OVQLOP9BA', 'ENDUO5IKVI', 'CLAEMH2KL9', 'VBAA66F9PJ', 'E6NR8Y5YBQ', 'SLS1WPQT8R', 'CBKXVRI0WI', 'SF6HBHCVPR', '6VKPX65GG3', '919TL42KPC', 'STXJMD6DN6', 'HB0ITPUTBQ', 'VEWCP2Q57K', 'JLZ20Y0LOF', 'GXK766VEG5', 'CR0N3XGAQH', '70WSTE4QGM', '76ZBK1LKO3', 'Y6R91F7RK0', '6RVUFWAKEX', 'ZCNWZ4Z9UP', 'MAH77EV5AA', 'LVVJ4BJP13', '96EDOBWBE0', 'IDA0DEIS1Y', 'PNZPCWIJI0', 'GF68FFZ3KL', '0XQEIGJTIZ', 'HI3JA8FSST', 'SW1XNZPN7N', 'VO5EWXLLP4', 'TYSZ9U1HBA', '4D5E2KZSI9', 'CY8D1RPWYC', 'GOLDWKNIGF', 'PSR79SG5YP', 'BP41KYUB0I', '09DXE4TWMS', 'VBEKPBCKJL', 'EU11UR7V1J', 'GZNUKWTM0Z', '1IIO96XILX', 'I0ER5EG4E7', 'IKXVKHG5C9', 'HWG8WQQSF8', 'NIY25IAIIN', 'Y1KS92SH9A', 'QZJPE6FGT9', 'Z1CL1LKVL0', 'M4FYNV8Y79', 'J762MJFLOT', '0J1PW6ZURW', 'E7OCLPX6D5', 'K8HDKZT3A6', 'ZR5WVHANLR', 'RNPVWJIW8C', '72O68CII94', 'Q6X94594NY', 'OE6L76NSDN', '8A5CR3BG5P', 'ZVSPUI9WYO', 'URO5JUHGH5', 'NWR641GMHL', 'HP1BCT5XYB', '42AUY0JSVO', 'AOEOD8NKEJ', 'FTJILCH7V7', '0FTKHKG4GO', '07OYIZT67W', '8XZBHYIYY6', 'E2R306ZJ08', '4CYIEIDKF1', 'QATP0MB3SK', 'UAATYD92RW', 'TEJLUV4GT7', 'HU7TEIM8EA', '2R7MQ0DZ8K', 'EWH39I4YF7', 'VPTF7HNYB8', '6GGDJ09OJD', 'AOTOO1M2XP', 'EMQE3TWRVP', 'NO7OOFNUH5', 'GLJTGTLQNE', 'SWGIY2ZLUS', 'N94KNLXYI4', 'NELGT8JKUG', 'MGP29N4ENL', 'FXEAJPNL04', 'NTE5J52JCD', 'V1IW21RR7G', '0Y8A1VTPBI', 'U1R1SGHUHG', 'PAZ3N13DC5', 'GU7WVBBI16', 'RXSP3192V5', 'E3E5N6V060', '4IJZAQ38RJ', 'UERGBL30LF', '5GLOEHASXF', 'G0UJWWZYRE', 'INUC9DE0FI', 'APWYVKAWLD', 'B6WWOJ9WJX', '1XQAG40ONR', 'WPXFMSXWT4', 'EYHQA93KGW', 'IUMPMIP4WX', 'B953JE2578', 'VIO8W5B4LQ', '2F76Y78QFS', '3YVW6DZ3ZP', '9NEU9ZYF6J', '2PDKJGRGN5', '9VVX74WSZL', 'DX6VRJ0TN5', '4A12AICITL', 'JYWQ16HP04', '3UW34V1Y15', '96G2UA6I3E', '2C7WJSWX8Y', 'CGTY5MOA7A', '09IGIZP1NZ', 'BMUC5Q6I6R', 'KOWORM0OQP', 'MY6SFR7YCW', 'XBFJH19866', '4W23V1VLBA', 'PPDJD7NOHQ', 'DGPXAFY0QZ', '7NT5L80D2I', '1ETEKX0K2B', '9PKQGFEXQX', 'Q31KXAKJQV', 'F4GKUQWK9Y', 'MO842HUEQ0', '9SVS1LXH23', 'OUL4UV1NY9', 'YTI4W99FIC', '1TUYTRABEM', '16Y2QNRS52', 'X1PPKBGC3I', 'RZHP6Y212J', 'EI0BOH1PLS', '6HOXM9X6LJ', 'MX0IYW0A8P', 'DB0FJLKWPU', '1FGWESMIDD', 'BLS4ARSQG5', 'B96L7OM81I', '9EN3KJR9RQ', '0P3FEZM0TX', 'QT7X2BPYQ8', 'DOE6KRTMKC', '6B6JNJ4WZW', '0DIPKVJNF2', 'BBSJ70R88N', 'FX1BVV7BTY', '8QC82T6YVW', 'A59Y2RLPR3', '46BD7CCBZ7', 'FQ71RKJ1BH', 'UN4RPTGSDY', '5KH7JO79ZB', 'QNW4PGWZO5', 'N2ZBZKIY2N', 'UQ9KQF86I0', '2ABAKAACA8', 'CBHHHNDU7J', 'FHWE2KMQK3', 'FGA0QM6LRJ', 'NO52Y3PCX2', '5C73C6G220', 'TVTCHJ9UE9', 'LR1WRF7J7H', 'OTSX1TRBQ0', 'SJVXXU0PSC', 'WY420HF8QB', 'LSZEFE4BEX', 'IAJ2XBIZ4B', 'DS0CSPFUM1', '9BOCYAK8XD', '4379BYWDA4', 'VLB2GI9LLL', '9AH6BVYMHI', 'RG8EZF0W4T', '9NOYYRABP6', '9WEM2TR5WR', 'XGH79QZRI4', 'C6GGKIBKOJ', 'D464EIRIQ6', '0N68TVA4IZ', 'IMAZO42Z23', 'Z31UU3BBUY', 'UCLU501MQO', 'CDBXU39F57', 'NJVZ2FYPI7', '9BEIRXZAFF', 'KOPB56W79Q', '446D2FPJLO', 'V5NYALLJHE', '5F4J8Q7ZUL', 'XS4RGOQQZ6', 'XGB02V5549', 'H5C8RM4PF0', 'HIWG9CXRY5', 'QUOV8KCU3J', 'SLC7S6IS0L', '3XL22Q98YM', '7MZ1QQCODJ', 'MI1OTXP4KU', 'OGVXQ0GNVS', 'YCZN08QYCY', 'BKO0ETYUAG', 'W7NSPPV35N', 'QM7RXUF3MJ', 'HEP7DBTZ7K', '409NGEM8LV', 'I001GOIHE5', 'WGJF2RFGKM', 'KZ6TV8W090', '2DVYL0POLX', '7TSXKAF052', 'RVW2Y3IFX5', 'DGYZ4BMN86', 'C8C735US1H', 'W874QYTAL9', 'SGBI9ZFRWA', 'VF88YBDRMI', 'NSB1JZLXPO', '1U5MLCT5Q3', 'P3U508AH9F', 'NJ4YIQOLL7', 'XCVXLJDI52', 'OV1IIVB9SY', 'OESXHKEZRW', 'A70CHQ4LBW', '7Z1REK5RQK', '6DXCWLURKT', '33K8PR9MT5', 'OQY4GOBYAS', 'GPRYGUA6W7', '9N3DYANGIK', 'FQQZ6EBHPZ', '2X8K4TTJED', '5CWGAPUVDX', '0T4DOSR2FX', 'Q9XBP6XI84', 'XKKOPQP3EL', 'K1U2A8QCE7', 'TL43HKEKNP', 'EEW3KIT768', '7AD6Q4SL5O', 'HD41D6NEGW', 'ELJYE4E9PU', 'B0W204ZRYU', 'RSB6LNY5PC', '6ZKNFVIPBI', 'JBUFLQ5Q3X', 'E1WR2MBZYZ', '3Z9QJPU8Z0', 'CYJEVE3CI2', '0WTU4L3YXH', 'MQFR2Y4LKT', 'S332DOR3J6', 'P0GRPIQIU8', '4KDHT1H4EL', 'QDB5ZH27AS', 'Y6ZKE8T0GP', 'WRO9Y9ADNB', 'DHL620CCTQ', 'PFPPE92IGM', 'G1R0D3J4MN', 'RTFKYB3DKJ', 'GE1DZYG5KJ', 'GBCB8WAMIX', 'B0JJ3HQJXS', 'T6QD3WDJRY', '3TNIVDEJKC', '96N0L379N0', 'V48P7J4I2T', 'RZOZFRXKEN', '3SXMZPY0PJ', 'J5UC892BHN', 'ILTAKEVP33', '5PGWHKZCB4', 'YL8HIYX32F', '45MS9E2HAP', 'AKICI7SPVS', 'JMGX0LYKLA', 'MP2WQ8C72X', 'VTYLL7I0C1', '4F1LDOM6ZD', 'B5DHCVYNU3', 'V6QL7TC1OB', 'FFK18DMN2Z', 'UVDBC86I59', '8GFVCGYQ8A', 'UWPOPF8C92', 'ATN1A63B8U', '1HDTRYJVGU', 'PT5ZBZNWI2', '752034XUC5', '8RX7YOB554', 'SOJD85GKIB', 'DFFPWQ8IXE', '6MUTBP3E38', 'CJD6K0SI6T', '8CVQUINBYL', 'HBNO3ZILOV', 'GV310PKDHF', 'ADQQ1D6G31', 'JLDHG6Q76V', 'V3H3KUY5KN', '13ZNUKXL79', 'AN0HMLH4ST', 'AKYEYSCTPR', 'V2IAAIVSAM', 'B0OMKUIIE4', 'VASKSQ81SM', 'E8L47CGWSX', 'Z3UXO9QVIZ', 'EZ5UQV2SPL', 'EABQDMOCA5', 'MRS5TBK47E', 'PUE0CSIE92', 'DNO9UXE2NB', 'XVA69PEW6W', 'ZEKKKKGL31', '191QRZXQ3T', 'EYYD8XV7BL', 'O0YHTM0HQS', '678B2OK2TG', '6GO1XFMWZD', '5ANVI0KG05', 'XU9SDVYY1O', 'H7IESPVNN9', 'DHKT1YZUZH', 'Z607E9UWPS', 'POPZF0S4U2', 'YPZCYNC1ZC', 'DJ0CZOV010', '5OTXC71RBO', 'MFS08P8QYQ', 'LW51DI6Q6I', 'FWXOEAHIHH', 'F1LXBE88N1', '8GN7VVIROB', '7SIJ88DQYU', 'YJMEBDABW0', '6YHIM72ZZ7', '9V99H1CQE0', 'TFPUO9GOEO', 'W1L8E5W56F', '6YRFN5RAE5', '7OKDI1D443', '096UKF5IIV', 'NGXQJV4LTQ', '08KGT992AP', 'MFCV026C8C', '0JLPCU3ADR', 'R0SEOJOZKG', '32O239XJUW', 'FHF3V8MZMX', 'XJ43UYRU9D', 'ZRYOIOQLVM', 'ZIIRICIRUC', '25JOFTXGJQ', 'RM1KS56QQP', 'F30YGVSDYH', 'UBX26IV2A3', '0QMJZ87PE2', 'U8444AU288', 'CCIZPY76T6', '5JXZAHO6CT', '7UVAOUX1W1', 'C31KN414O5', 'IJO7DG4V12', '83I6YGQ93F', '8BUD9DR66T', 'Z3QG8X53LT', 'G2ESNAD52C', '7WV8UX1QGV', '8VA3SQGBFA', 'XOMRDMRDIM', 'J68VHUJPCH', 'B13O2Y5SAF', 'GI6Z8FYEKP', 'Q9UTSJUAW1', 'KVTB3RSAQO', 'I8MSEJMJWT', 'SQOGNKXYNT', 'BOE1MV96VP', 'VJ3CSBE8QC', '1NNVVFHV4H', 'THI0ERWX3H', '67D2PTHXSS', 'HKCKNYRX0E', '4GCIK2JS7U', 'FI92RBGW6P', '35QLUI7T3N', 'RYLI2BEOPY', '21AW2MUQMA', 'KADJFWSL22', 'O60RA1NFUQ', 'FKBIBMIRW8', 'XZYUQA2YHI', 'OTJWEY106H', 'XF4GP4C6R9', 'B3IVYE6ULS', 'AMDQ05K085', 'O9T7MG4H7P', 'FPB7Q70YYL', 'ZIU229FJGW', 'OQP9EHS62T', 'M2R3GTLTZN', 'RJGMOS6C4T', '132RL6DHM4', 'L2OBZT18C4', 'FT1ER5V6S7', 'C3O84YD1XA', '5D0WKE89X4', 'MFF2ZMXFDY', '34XHXS2IT0', 'NKEKONLB7Q', 'XBBTXWMD55', '1LFXHA4RX7', 'D78DN2YFTR', 'MLATAPCSHO', '6MEHP6EZTE', 'RKKKWMIWG8', 'XIKU5VMP1Z', 'V2EZ37W0AZ', 'I68R49P596', 'GNYI5GJRHJ', 'OXBIS3GVQU', 'HCBLSOFBTA', 'YTTKD4VA7A', '2GFVXKHWDR', '31M5KLXWWO', '8PC0YLD7UZ', 'VW5NXS0LXP', 'JUQM4O8LLZ', 'S5BW8GAXV3', 'V7VL78WZ4C', 'X5LMWFFTRN', 'ZAQ6E6D2NP', 'W1T0785GEW', 'NG4LZFPO4K', 'X9O5OCOGM2', 'JJ642H1V5M', '5YWENTYCPZ', '0QBLEMZ3U2', 'PB03DGXZCR', '68XXCI2KY8', 'CR5KFBL20M', '03LO16AVY6', '2RC9FHDCKY', '0QIF67R0FC', '29YX9BLQ6C', 'BTVNMTCZTP', 'HRVUV34PG7', 'OUEBTLQ24X', '8ANJ2B0G9X', 'VMIY2WU528', 'HEHDYMU460', 'N2EI1MRUUI', 'EGBKT54VR7', '5JTXXP1ZFS', '2ENXLK3TNP', '1QMAFRKP8Z', 'AUH905PK58', '3CDB33GEA2', 'CKCNI006LU', '0P5ZSQN2OM', 'NX6VVAPWGG', 'IH2OUHVTEN', 'MA15SCMS74', 'UVLLPIG4K0', 'LZJ63KX9GD', 'QI2RRP21N5', 'AXE0LZ9D0U', 'WBZAOCPISH', 'DRR3W7MHZQ', 'QZKCAV5L2K', 'YLTXK8J7ME', 'XD07GACDY1', 'KN3W0SAC5C', 'TJL2TKJ0JY', '4P0XAXKS4V', 'IFFLSVLLNB', 'R8HOT3HYC2', '23SOETPVIB', 'DVPTQOYQ9V', 'K0F90XJZT1', '94IJ5KVQ8N', 'U9TIRVYDCD', '1MEH0MSB9C', '7JCB1Z5X2V', 'IQRIK00FTK', 'O00U7TEUPD', '3VA9HPQXZN', 'LA74BRO46P', '1DLAC2X62P', 'GMP1990RD8', 'RH62PGPGLT', 'AZ9IMOSYT3', 'BAHXBEPQGA', 'O9XZRU6R1N', 'PWMC2ANQ9E', 'MJG0JQF4O1', '3E02QBOR3D', '81SEL226O1', 'OP63YN3I33', '1O8EPMBI2S', 'CNOIS7ZILQ', 'UBV585VY6Q', 'Q8HU7TA8NE', 'IIM9HWKTG3', 'VPESZ1OZX8', '7RZ0HIDR4N', 'NGMMIZNXWQ', 'QXSFI3QKA1', 'LGPQV5I8HL', 'RFRGQWJE7K', 'DPHKOVS873', 'V1I7V003NA', 'H9WVYC4VSN', 'X8TGUOF8XS', 'XRSK3E61O4', 'FP0BQ3R521', '9BEFM7EHKD', 'Z8EZ0GL8DB', 'QYQ8L46JM2', 'WA3UYZV8ZV', 'NGC73EFGGY', 'ZKVWYSRV2T', 'M2TKQ0OR7I', 'J202KSYXAZ', 'NQ1Y3Z38AZ', '652RTKO29V', 'TU94CJYIPT', '2A47NXSOBM', '1EY6P3LNJA', 'ZK53X24XLK', 'Q6MLWOAZ65', 'AZTL3J5W4E', '5PB24SH8Z9', 'J5POKR4OE2', '571KEUIKQX', '9SGIIUIY4V', 'KL1S0QUNE4', 'BIDTHX9Q3P', 'JWAHN81QX1', '313R8VCAEB', 'BSSRSL34NT', '4PFJSM0C4A', '8QVPLMKXH0', '7XO8SR7LBT', 'C1D4M3LQZK', 'EZI8GT3QH7', '0AE6GRFGBW', 'QE6KVQNM2E', 'AF6CQ33RWV', 'XVB7Z6U986', '87SARB4BQR', 'Z2JZPPODQX', 'PMKHG3CBD4', 'M4QF71RWG8', 'ZVTR4RI326', 'NFTOIWF6DH', 'R4GYZUA8L3', 'AR1WOKN3LT', '4CR8S9E6UW', 'LI2IG1LYCN', 'MA59988DTU', '1TSWEU1CEQ', 'IHCF6YXOM8', 'GMMWT4EZ55', '8N9XRMS9CE', '2XUBBKMJA5', '1S3T16RRWG', '0Y9XW15Q2B', '2P842GK16F', '5MT3Z2JI3K', 'WYZDB0P5X2', '334SAP7L7W', 'K1JB868T6J', 'DI33G6S35Q', 'TU46K8BFKM', 'CEWN2OJC8W', 'Y5NUG8AS4R', '0G7GZC2HC0', 'S5PKDGDRNW', 'HASG8XO03Y', 'BHU040JWZF', '10OW66QI2P', 'KFZ0YZU3GO', 'UWSGIYLS9S', '5FLGEJRM5U', 'D42GFKD0KP', 'AAX1YSYQ5E', 'DDR7QILVJZ', 'KJA9YYFZ85', 'Y7SKPCVQMP', '7FWK65UAVU', 'ST11BGU76B', 'WN8C9N3O4S', '9HOT9GAXNB', 'D4UK2EM69Q', 'H3XQC0UX5G', '4IB1L1BVJY', 'GR1KM7RZ3K', '7OIEGE9CCP', 'QIPN32PF6J', 'ZYC7AK9FA9', 'A3ZW0P6RBK', 'Z5JRNAX1LW', 'ZLZYT5PU6I', '8NDBYLUIF3', 'HAAB605E8M', '6RZU0PC411', 'FAN66E41YT', 'ZOAYP0R911', '3ZQVN1K12T', '927WBL7ZO6', '83MM4AQ76I', 'OX6CDV5P8C', 'KHXXD7RY1F', 'B43LJVP1HT', '1AQ7FM92FY', 'M4XQTVMD1K', 'VFGETR5JYY', 'BYZMH01FKQ', '5TG2BBP66I', '4IN4M734PL', '9WTT2X746O', 'X4FCI8K2AD', 'VMCUEYVQU8', 'OROVTZ8SVD', 'CMKXONZPMW', '3NLWIPG6EG', 'J72F4D9VIA', 'NJJUKDZO2K', 'SU6BJK4D51', 'OAT3OJT4QG', 'F49Z93IVHZ', '1OBIY16TWA', 'CIJXB9B9ST', 'S10CRDLJNI', 'ZG1CR8G08G', '560K1MI98L', '0GZ9FH4CQU', 'JOJYT30F6P', 'UTFROR8Z56', 'VWBQJDEMCI', '2O8RR9LRD4', 'Y7UH4ZEE9G', 'UA807Q43XA', '6M8MAHS1XP', 'LDA4DT3219', 'KG9UJRSOPJ', 'SR764JIDK1', 'PURO7K7O67', 'MGQ8MDT6US', 'LOCGP0WMSZ', 'P1ECTE4U02', '4WJE44J44M', 'QQZRWZQSBZ', 'TNUDP3ITUE', '2Z9P0SNLIT', 'IDT89O88X6', 'IZMOREALUL', 'RCJDEBQO9J', '3LTBVNLVFT', 'TGAMWHYK9R', 'BR6PPF9S3V', 'NUX6KOB1JC', '01CFQ052RN', '4W0S9TLCRX', 'K8RM5FDLM7', 'YQ6I0MGZGN', 'BVW29MPPOA', '2C9LAHKKYR', '7N516TXER1', 'SZ8PEPQN8O', 'W459IPZBBA', 'CXSN9KP55Z', '14TGDV515P', 'XTCRCJLEJW', 'HEV4M7RNTF', 'JSI223VT47', '6AT0JCOAKQ', 'A6X09CH9KH', '72KBJZGF64', '73C9CDWH5N', 'KJRUF9VQIB', 'BZZIS76JA4', '63HA253L9R', 'A0PPINVK64', 'KTV3540NIE', '4EPMINCAA0', 'JNSZ8LQU97', 'QE3IJ2UWKN', 'H57HZHSRS5', '8YA6GD883Y', 'ORBTINQL1B', 'QDKRCMHX5Q', 'IFJUIEAGTV', 'LC58PKLUS5', 'D5UGN1XBAY', 'C37HOE9MQS', 'CXSS37XIRE', 'CMCFDKCYUT', 'Y9N630PO7M', 'KKZ1HOHL7K', 'PY7VWS0IYE', '5Z3538R8J4', 'Y8S8AA1PPX', 'A3CQMG3M7P', 'RWJ7WQP3HY', '5VYYJ4A3NY', '13JR8XN1BE', 'XHXF1LB635', 'KCG4LH2LCP', 'YU80I52QG4', 'XCKY4388XA', 'EV9I6H8L6O', 'HQDOCQIUYK', '2K19KA6UUO', 'IZG614WYLM', 'T74CZU0FN1', 'MD4EM4CCZL', 'OTJUZPNN9N', 'R9MOBVKFT3', 'UX7NVAXSOU', 'RRU0EAZNHK', 'UNQO7A5XBS', '68TLWKGMNH', '7KJ97S8O95', 'D4ADDZMGOS', 'NEJOX69AY3', 'C9EKNZC9PP', 'ZKJKFG5A18', '2S52OIDWGK', 'RJHOSMVRXI', 'KJEYN0M908', 'L4581VKXYR', '5XH5SRVNVG', 'K4373STQ3Y', 'ROT4OG7KG7', '5JDZNZIH47', 'B3GPD5IZQW', 'LA6BN7ZPF5', 'XZA3T5Y4L8', 'PY9MTZKVB4', 'JS99IRXFXB', 'I639852B5S', 'V956P4AQW5', 'KL4J9VY18H', 'E4A7WGJED8', 'O4M4B8D56K', '9FZYZYMA1H', '9GDD0H6FI2', 'WQ4MQ16PQV', 'HQ4Y8XKRWH', 'IQEV5CWW8V', 'V76X7M0531', 'C6L69TXQSY', '4NEB1IABVN', '0P2GSX3GHO', 'BFTOFHVRB2', 'JC52LXK4G7', 'P21PAC3CTC', 'TD6KT1IAFI', '6P1K4JT3RL', 'H1S6KOOD1C', 'DWUYK1NPAY', 'ZV9H7MY9II', 'AB5TC60CGU', '64AIEQQYS8', '1NZFO7HAFZ', '1USQYKMIBR', 'HEIINYR4FB', 'JSPHGY3BOP', 'TF95TJU4T2', '1LXYJXK6DM', 'S9XRJ3VTXU', 'ERLBX3P4HR', 'ZPGBVNCI1C', '2C1CKWG0UO', 'WGPKNVV43S', '4ZUJDO8VBP', 'CXU21XK0K0', '2B6OZP41IZ', 'HV62QBTQT5', 'FRAW4ZBFR3', 'EQTF6SDQE5', '541V8II00I', 'UKZIHQ1S6A', 'AIL80QU472', '9MB3RRU6SI', '6XFJQQ3NA5', 'MELXJAOZ27', 'LE72UW8CFS', 'BPAB05NL3Z', 'PS2E8Z4EPV', 'QETOFYIBMW', 'H56RG0T7HK', 'QITAESISD0', 'LIXUQW6VOR', 'K6TMJFA91U', 'LOND5ZQH69', 'Y1V4DSBDXP', 'GGY30HZG59', 'AHMNEM1CBH', 'QHQX38TUE4', '344L7PE687', '22DLH0KH3R', '5W87T1GUQ6', '4LI4OUNRVI', 'Q1LZA3K7GQ', 'BJ80ICOKFY', 'RCM83UUGMB', 'AL1E029NO3', 'B1CBPN7O9Z', 'Z37JOBVNM7', 'JHDRM4YVO7', 'S47C82MEJL', 'EPQ3B2FQW6', 'RC30J1QFSX', '4S7EH7I93Y', 'W5KVBO0M4R', 'MRW9NAAFOE', 'P4KMYK9AWV', 'KRAAUNCOCW', 'WZCZ1VEAY0', 'HN0SSNL3P8', 'IZ200FBCFV', 'YBI6YBLO4G', 'A2JAOAGIHB', 'DKW8PF5QMS', 'NWF7RO2FQG', '4K4FO51LHU', 'M6DGOQLGGB', 'JCPHKUJNG5', 'YMLXBM5DW3', 'MNGYUD3PM4', '1NNOTTX9O1', 'O72TEYPOTE', 'V8078F0GZP', 'P50MY2IWLL', '7FUJ7XWROD', 'P41A89B2XA', '4418GE188G', 'LI1QLP64OH', 'X112YIDXRV', 'E742RYWBFD', 'JG5WRKV14J', '5OR5UIB439', 'AVF8L8ZDYL', 'XPMZSPZCJ4', 'AQ5E6R0QVV', 'KY42K1TQVI', 'TDO4W50Y7R', '3ZE39LFEU1', 'EWJ7OUAFKO', '92KHTLKTPT', 'DIDBLB28EQ', 'JQYFAHX1Q4', 'Z9TICIOQAJ', 'UQM6G05HWD', '0P366EK1KA', 'N2IGMHK16E', 'GKUVOAKLKB', '8SE7X445L1', 'H2VO1E0G1P', '7H2J5380SU', 'HI7CB68P8D', '85SKFAZI9X', 'I6EDHNTA45', 'AH3QV25MLV', 'HG81SOIWPD', 'MTDIX4RDMB', '103OI023KT', '185TJJMDWY', 'YDPLUX6JOW', 'C4LCO56WGD', 'SMCHSVTHSS', '03R67G779M', 'B5N6K1RLPL', 'JVE5QMP685', 'FVMHT2KSVX', 'ETXHT56G2U', '5WMCD9N98E', 'GMOJ67184L', 'TKOT4CQ1I7', 'DMIG9NTSC0', '003BPVIC9T', '83DZNEQ9OB', 'JFETNV24Q2', '4GQU3XQ6AR', 'KGA045TDX0', '3HIWPG519K', 'D4Y89FBSF3', 'KV1LM3KPYF', 'VJ48COF4H6', 'HP6G1DGAWT', '83MRJCY5DK', '79LT6R7WI8', 'J2TB8PS8VK', 'SYVBNV9UJ7', 'GQBX6E2CAF', '32QNML4XUI', '7TPRQQECNC', 'JLC71E2HAA', '9FD1ZTMQYI', 'JFYB2OO2QL', 'XQKBR2VIV8', 'IW4KZOF1BW', '2D960UQF2N', 'IFXQ2T9TOG', '5IRBVP08XX', '153L094IWY', 'IJ2J6PMMJR', 'AQ8VY4C2YQ', 'MBFLK82BWQ', 'NHFLU9MVK3', 'KASI55LGHT', 'PVSTLFSAGI', 'WBNC4L497N', '1TJPBB1EBH', 'K7VOPEQX2M', 'RMCGPMLZ6R', 'XYAGX0H269', 'YYJO6TKRGF', 'B41EJ56NFN', 'FP0KVNJMC5', '0WG741BMHC', 'E114ZHL95Q', '3GKX8UAXOA', 'M9CHBDWHFF', 'WGMBERVHO2', 'WMNFFAA2YA', 'QAHX008QR7', 'F93XAHXIGT', '705LJ9M78Z', '68OUVZHTS1', 'J530QHV98E', 'MB7XFZ5MVA', '2CZ4VYLW88', 'KG4L4X0JNB', 'Z7PAHMODVT', 'TZ1B1XHH6T', 'PUUBZB4GW4', '3JUD24B0HP', 'KQASW3NYJG', '79UWN4KKDR', 'J5YOVHONL5', 'AF5HAM0D6A', 'Q0FFWQB86L', 'FSALGE4GG8', '40SQ5Y6JV1', 'F4N3LG4BKL', 'E59LIHW1PU', 'WE7B392LMQ', 'VTJDLWWRFH', 'OW1J26XNEZ', 'IKJZOD8485', 'EGSDSMZQ9J', 'QR1Q3JOFY3', 'ON10SJH3RD', 'J6VXBC8W7H', 'TRM3257BL2', 'YBNCH05ZXY', 'J9OCK6YJHG', '30L1OQOGDK', 'YB4GSL2YMQ', 'CUVGAB3YC3', 'V2J8PBWXTV', 'WU7H4QHO3Z', 'VIPLBOK9GF', 'TRWMP1FA53', 'Q57WOGJAI3', 'GN8ILD905Y', 'MD08XVX32J', 'TVJNDA4810', '0ZOE8LX4E6', '5343OVNQZN', '56V8CW1WZS', 'ZF01X8UBT6', 'ZV3OYRBN4W', 'INVMAYS1N3', 'W8OPYZDO77', 'J36FVMQ54Z', 'YRA38VC2LX', 'BKF2NOJMHR', '9N9DFZA3UN', 'T2JU3ATCW9', '1CUHHTM29Z', '4SC8NE8GLH', 'T4EFLHRXQS', '6H0JMIXTPE', '4VN2DMO3G6', 'FNKQA0QO4O', '5B0SPGPP6S', 'VI2NWAH4TS', 'MOV6X5HUG9', 'LBKVRHBL98', 'T5O3XPG415', 'MCFYHR1TXH', 'YQVJRB2M7A', 'ZW2OA90961', 'LGYPVR6GSK', 'K57F4YT7MF', 'WRHVZLRSJK', 'A2K5OIU3YN', 'FXF9ZNI66H', '5QZCRC2QU6', '6QGIHBO91N', 'D5OL464BNB', '6UH4EK7AW5', 'DPQ7N5WUFK', '96343FXOQ3', '2AP2O5B3ZC', 'Y7BBIL632B', 'OCILHGMHZ1', '8CRV73VI28', '6XGZYWL4DJ', '6OU6I9JTR3', 'F83N5IA8WE', '6A2SQ9UCCA', 'HY3V9WW7E9', 'HK21U2O6VV', '0BZC7LHDVK', '538EQ9H2SF', '35OQY6YLYL', 'GIVY0WD7Z0', 'E6MBK0EYKL', '041WNWHAY9', 'YCEHKYK7Q2', 'V518MRJ2O2', 'RS6NSHWGYU', '5JXEW279VZ', '4I8V4D3WWP', 'Z6RMJQ41DC', '6T4GU0PLE4', 'KT60B1GHJQ', 'JJ62G5ZH9S', 'F6QM9VUT88', 'UB3Q23MULX', 'ZKG9UIJ26X', 'X9KTQYQJD9', '49EAR8LTV7', 'BMY60Y6PAI', 'F9LZWVLRLD', 'Q4IXAIFYWD', '6HRCA01J0Q', 'ZXSP4N8SZA', 'M6AJSZRK6B', 'SB1TDSFT7V', 'T0YCKD1U14', '6NK3JLB1JX', 'HIYTYJL5XE', 'YDF74906H5', 'BI489DD6NU', 'SK65QTSCCC', 'UW9YBLBEX5', '2P9COY0PAV', 'EW7VSTK63L', '9TJC2P2263', 'X32SAYHNLQ', 'ZR8KY1ZXH2', 'NPB88M0TBQ', 'OJMATNEW0G', 'SJ8HM4FPWD', '9N8UMG19GJ', '69D3F64IFN', 'YX2DAT0OQU', '3PQXW1WB73', 'HQ6JV0ZVBQ', '0UZN6TPSQ5', 'IEO840MPYD', '7LHHPHJF0C', 'U76AYUL6KP', 'NMCHBAYQOK', 'OMDY87IRF9', '462NL5PRMY', 'FUHNQS9VWP', 'WHDKVH4LGW', '6W6LIG7BUE', 'NQYIRSDTGB', '2H01S82IT4', 'M6BHYMF7Z0', 'ZPYCD0O92V', 'I2XW04EHZU', 'BFA1DPPXHG', 'HQ0P1YOYJA', 'XHRVRKIJ32', 'KDSWKRTJHD', 'E9LOXIAUFE', 'LXP02PXLJ3', '6CQKEZHGFD', 'HL8TIFOBCJ', 'AFL86GVXKO', 'PHZ69H57Q5', 'STOANZ6LVK', 'MKI3JREQ0X', 'C11HFQHZZ6', 'T74FILDX1I', 'RKWN53FVVO', 'MBGM3JY8WY', '6VBIQIAED0', '6K4KTTIBGR', '1FY5BSSCYF', '39DXLNE65D', '0ZPZTI33JS', '994C1LKG1P', '3XCMCZFRRK', 'C27JG0Q90D', 'DENIVOESTS', 'X3M3ADTWFD', '3JCZXP04VP', 'Y9B68HNZDP', 'O56ZIYO9OB', 'IB35OSFPEV', '3KUND1HZC6', 'TEEA4KZNOY', '5R696DJ4D1', 'UAFPNLO3NV', 'GAMOQAY49V', '4EREKBC2CB', 'Z20LX3L2VJ', '77HC6BJ4YY', 'HY9QG5FWQ2', 'VM3FZLT8TV', 'SHOECVFXT6', '0DM63PHX9F', 'TQQHPZ3VX9', 'WA1IGOH6ZC', '6ZFLVVWSM6', 'N5TS2LW5IE', 'ZQULQ92DBK', 'Y7GGVB1KTM', '2413GQ98QC', 'KC6TVB0VHV', '89S6O54QAX', '8UZDIGKEF5', 'A2TS6J9HRZ', 'AXW3ZDTB5Q', 'OXLCBP5AP9', 'KT1BQ20J5V', '3AS3VARF0X', '9R1VSXNFO3', 'AWPJ3KI6B1', 'STLTSV896R', 'JJJTXZ37BC', 'KNGU202AVF', '7S6HSIX7XN', 'NNGFTEM8JC', 'PEBF97TJ07', '269LPQWK4K', 'NVDS1N9Y2W', 'R1UYROGM2T', 'HFW05YGIUQ', 'XV6R8H6HZP', 'SAYQYZNZGP', '5ZLCI8P463', '0K11AAGO1J', '524FAOT4Y6', 'WCO270BML2', 'OG985T5GQ2', 'OSBUXHPZFG', 'H0DMCV4QCO', 'CT2NX9M658', 'JKPCHS0SED', '0B61T1XHIQ', 'MMBYQ1P20I', 'XUV9E8JIPJ', '4V1ZPULXMF', 'ESEJZMQRT1', '3I564LG8Y9', 'FZQEP13995', 'XR9AF02A5Q', 'ZYW13YME3J', '8LF1C106AG', '7CHON5KJH7', 'GND602ZJSD', 'NOJGSTV1WG', 'D5XPIILUSR', 'LPQHEPE8W8', 'DT3F06MGYW', '2IOPZVNE71', 'HWJAYQSXS8', 'KAG8UCLO4S', 'EY22QVDLG9', 'M3KMKS8INO', 'K4JTVCQBO8', '3SDPFD7FQ3', 'VEC0O856LZ', 'Q6I2JKNOEP', 'M424T0W33K', 'AJWJ0DNNR4', 'PFTWLT2W2B', '2R91M8L4YB', '0X4IE54GGI', 'AQ3NWVTBVP', 'BYEBC8PPCD', '0RVTICQ3R2', '45NT1VC9GC', 'FJLRF46FJY', '6LQDJ2HBXY', 'TUIBQ740EQ', 'AX9QBLXLEX', '3ZONLN4RE8', 'V5AKR4D5TJ', 'DE07V1CKDY', '5OQPI1PH1K', 'E8FBEYAZTJ', 'L6QIJG09GE', 'ZVL52QBWTR', '68G9O37I6O', 'TX7Y25N0CU', 'IPJYC6AZ94', 'UCUSGZ8ABS', 'ZRK6YSBUW6', 'AJ5JIMGLMA', 'QQWJQ8ONT1', 'WUEJ44L8K3', 'DC5F1YFZBJ', 'DYPVSC7E4H', '5N07D0I4QQ', 'MVQLI0IUFI', 'K2MH8SLMY7', 'SU8Y9PXXMU', 'SNPAN4F53P', '0YUGW69EH4', 'A8938UTFEO', 'V7RHE6PYWL', 'MAE322M9IC', 'C32ZAL4UJQ', '36ABE30IOS', 'CPANXX8BNB', 'OEVX0GDOLJ', 'LF8VU1K9Q3', 'D2XGD6199Y', 'URPJ38O7VS', 'AMZ1AQUW3C', 'OQMW90QMNO', 'B6WS254Y8S', 'RKP01UVEO3', '10OZVO3AWS', 'KQLR9Z6HJ6', 'K6D1SOECG7', 'KOL2IOYUE1', 'EACKRSQQ8O', 'VSSS7KDLXD', 'UNTPIWVK8R', '3Z9P24752S', '6C4SA4EHJN', 'DHBEGML53L', '1AFFDLF565', 'H5Z620G50S', 'U2YXW80ECL', 'BLSS715PJT', 'YBNJJA2RNC', 'R84D6YVRD0', 'Y0WTZU7MIO', 'GQ00FV7LVP', '4OSH2B2JNW', '3QLCJRRYT3', 'M5S89YGCCG', 'ZS32HS0JXX', '3TRX4UWJG3', '8MMYHQG35L', 'CS1MZWLJKQ', 'R7LWCI7QV5', '4AEUJGDREA', 'AJFR9QAFYP', 'S1SP6T5M1V', 'SKFHHZ071Z', 'RK1BQDNNRB', 'FKMO0ROCR1', 'C5CWLDU0GS', 'NYXQBYSRNF', '47FMMLTLZU', 'DAEAZJTEDP', 'NVS82GYTJ0', 'LY7UFKVFM5', '0ADVXRVMJJ', 'RJFODFW9QQ', '4J5KLEF7ES',

### Check Distribution of Numerical Columns

In [12]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

Claim Amount
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ Claim Amount │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 34110.0      │
│ null_count ┆ 0.0          │
│ mean       ┆ 717.844178   │
│ std        ┆ 8290.881802  │
│ min        ┆ 0.0          │
│ 25%        ┆ 60.0         │
│ 50%        ┆ 175.0        │
│ 75%        ┆ 460.0        │
│ max        ┆ 900000.0     │
└────────────┴──────────────┘


Close Amount
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ Close Amount │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 34110.0      │
│ null_count ┆ 0.0          │
│ mean       ┆ 104.883016   │
│ std        ┆ 1393.564677  │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 75.0         │
│ max        ┆ 250000.0     │
└────────────┴──────────────┘