# Fix Date Values in Dataset

In [1]:
import sys

import pandas as pd

In [2]:
sys.version[0:6]
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv("mongodb_scripts/data-original.csv")

df

,order_number,sales_channel,warehouse_code,procured_date,order_date,ship_date,delivery_date,currency_code,sales_team_id,customer_id,store_id,product_id,order_quantity,discount_applied,unit_cost,unit_price
0,SO - 000101,In-Store,WARE-UHY1004,31/12/17,31/5/18,14/6/18,19/6/18,USD,6,15,259,12,5,0.08,"$1,001.18","$1,963.10"
1,SO - 000102,Online,WARE-NMK1003,31/12/17,31/5/18,22/6/18,2/7/2018,USD,14,20,196,27,3,0.08,"$3,348.66","$3,939.60"
2,SO - 000103,Distributor,WARE-UHY1004,31/12/17,31/5/18,21/6/18,1/7/2018,USD,21,16,213,16,1,0.05,$781.22,"$1,775.50"
3,SO - 000104,Wholesale,WARE-NMK1003,31/12/17,31/5/18,2/6/2018,7/6/2018,USD,28,48,107,23,8,0.08,"$1,464.69","$2,324.90"
4,SO - 000105,Distributor,WARE-NMK1003,10/4/2018,31/5/18,16/6/18,26/6/18,USD,22,49,111,26,8,0.10,"$1,476.14","$1,822.40"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,26/9/20,30/12/20,7/1/2021,14/1/21,USD,9,41,339,29,1,0.08,$121.94,$234.50
7987,SO - 0008088,Online,WARE-NMK1003,26/9/20,30/12/20,2/1/2021,4/1/2021,USD,14,29,202,3,6,0.05,"$1,921.56","$3,202.60"
7988,SO - 0008089,Online,WARE-UHY1004,26/9/20,30/12/20,23/1/21,26/1/21,USD,14,32,241,35,5,0.20,"$2,792.76","$3,825.70"
7989,SO - 0008090,Online,WARE-NMK1003,26/9/20,30/12/20,20/1/21,25/1/21,USD,20,42,112,36,8,0.10,$804.00,"$1,072.00"
7990,SO - 0008091,In-Store,WARE-UHY1004,26/9/20,30/12/20,13/1/21,19/1/21,USD,6,41,237,43,5,0.08,"$1,370.82","$2,211.00"

In [4]:
df['procured_date'].unique()

array(['31/12/17', '10/4/2018', '19/7/18', '27/10/18', '4/2/2019',
       '15/5/19', '23/8/19', '1/12/2019', '10/3/2020', '18/6/20',
       '26/9/20'], dtype=object)

In [5]:
def fix_dates(date):
    parts = date.split('/')
    if len(parts[-1]) == 2:  # 2-digit year
        parts[-1] = '20' + parts[-1]
    return '/'.join(str(int(part)) for part in parts)  # Remove leading zeros

df['procured_date'] = df['procured_date'].apply(fix_dates)

df['procured_date'].unique()

array(['31/12/2017', '10/4/2018', '19/7/2018', '27/10/2018', '4/2/2019',
       '15/5/2019', '23/8/2019', '1/12/2019', '10/3/2020', '18/6/2020',
       '26/9/2020'], dtype=object)

In [6]:
df['order_date'].unique()

array(['31/5/18', '01/06/2018', '02/06/2018', '03/06/2018', '04/06/2018',
       '05/06/2018', '06/06/2018', '07/06/2018', '08/06/2018',
       '09/06/2018', '10/06/2018', '11/06/2018', '12/06/2018', '13/6/18',
       '14/6/18', '15/6/18', '16/6/18', '17/6/18', '18/6/18', '19/6/18',
       '20/6/18', '21/6/18', '22/6/18', '23/6/18', '24/6/18', '25/6/18',
       '26/6/18', '27/6/18', '28/6/18', '29/6/18', '30/6/18',
       '01/07/2018', '02/07/2018', '03/07/2018', '04/07/2018',
       '05/07/2018', '06/07/2018', '07/07/2018', '08/07/2018',
       '09/07/2018', '10/07/2018', '11/07/2018', '12/07/2018', '13/7/18',
       '14/7/18', '15/7/18', '16/7/18', '17/7/18', '18/7/18', '19/7/18',
       '20/7/18', '21/7/18', '22/7/18', '23/7/18', '24/7/18', '25/7/18',
       '26/7/18', '27/7/18', '28/7/18', '29/7/18', '30/7/18', '31/7/18',
       '01/08/2018', '02/08/2018', '03/08/2018', '04/08/2018',
       '05/08/2018', '06/08/2018', '07/08/2018', '08/08/2018',
       '09/08/2018', '10/08/2018', '11/08/2018', '12/08/2018', '13/8/18',
       '14/8/18', '15/8/18', '16/8/18', '17/8/18', '18/8/18', '19/8/18',
       '20/8/18', '21/8/18', '22/8/18', '23/8/18', '24/8/18', '25/8/18',
       '26/8/18', '27/8/18', '28/8/18', '29/8/18', '30/8/18', '31/8/18',
       '01/09/2018', '02/09/2018', '03/09/2018', '04/09/2018',
       '05/09/2018', '06/09/2018', '07/09/2018', '08/09/2018',
       '09/09/2018', '10/09/2018', '11/09/2018', '12/09/2018', '13/9/18',
       '14/9/18', '15/9/18', '16/9/18', '17/9/18', '18/9/18', '19/9/18',
       '20/9/18', '21/9/18', '22/9/18', '23/9/18', '24/9/18', '25/9/18',
       '26/9/18', '27/9/18', '28/9/18', '29/9/18', '30/9/18',
       '01/10/2018', '02/10/2018', '03/10/2018', '04/10/2018',
       '05/10/2018', '06/10/2018', '07/10/2018', '08/10/2018',
       '09/10/2018', '10/10/2018', '11/10/2018', '12/10/2018', '13/10/18',
       '14/10/18', '15/10/18', '16/10/18', '17/10/18', '18/10/18',
       '19/10/18', '20/10/18', '21/10/18', '22/10/18', '23/10/18',
       '24/10/18', '25/10/18', '26/10/18', '27/10/18', '28/10/18',
       '29/10/18', '30/10/18', '31/10/18', '01/11/2018', '02/11/2018',
       '03/11/2018', '04/11/2018', '05/11/2018', '06/11/2018',
       '07/11/2018', '08/11/2018', '09/11/2018', '10/11/2018',
       '11/11/2018', '12/11/2018', '13/11/18', '14/11/18', '15/11/18',
       '16/11/18', '17/11/18', '18/11/18', '19/11/18', '20/11/18',
       '21/11/18', '22/11/18', '23/11/18', '24/11/18', '25/11/18',
       '26/11/18', '27/11/18', '28/11/18', '29/11/18', '30/11/18',
       '01/12/2018', '02/12/2018', '03/12/2018', '04/12/2018',
       '05/12/2018', '06/12/2018', '07/12/2018', '08/12/2018',
       '09/12/2018', '10/12/2018', '11/12/2018', '12/12/2018', '13/12/18',
       '14/12/18', '15/12/18', '16/12/18', '17/12/18', '18/12/18',
       '19/12/18', '20/12/18', '21/12/18', '22/12/18', '23/12/18',
       '24/12/18', '25/12/18', '26/12/18', '27/12/18', '28/12/18',
       '29/12/18', '30/12/18', '31/12/18', '01/01/2019', '02/01/2019',
       '03/01/2019', '04/01/2019', '05/01/2019', '06/01/2019',
       '07/01/2019', '08/01/2019', '09/01/2019', '10/01/2019',
       '11/01/2019', '12/01/2019', '13/1/19', '14/1/19', '15/1/19',
       '16/1/19', '17/1/19', '18/1/19', '19/1/19', '20/1/19', '21/1/19',
       '22/1/19', '23/1/19', '24/1/19', '25/1/19', '26/1/19', '27/1/19',
       '28/1/19', '29/1/19', '30/1/19', '31/1/19', '01/02/2019',
       '02/02/2019', '03/02/2019', '04/02/2019', '05/02/2019',
       '06/02/2019', '07/02/2019', '08/02/2019', '09/02/2019',
       '10/02/2019', '11/02/2019', '12/02/2019', '13/2/19', '14/2/19',
       '15/2/19', '16/2/19', '17/2/19', '18/2/19', '19/2/19', '20/2/19',
       '21/2/19', '22/2/19', '23/2/19', '24/2/19', '25/2/19', '26/2/19',
       '27/2/19', '28/2/19', '01/03/2019', '02/03/2019', '03/03/2019',
       '04/03/2019', '05/03/2019', '06/03/2019', '07/03/2019',
       '08/03/2019', '09/03/2019', '10/03/2019', '11/03/2019',
       '12/03/2019', '13/3/19', '14/3/19', '15/3/19', '16/3/19',
       '17/3/19', '18/3/19', '19/3/19', '20/3/19', '21/3/19', '22/3/19',
       '23/3/19', '24/3/19', '25/3/19', '26/3/19', '27/3/19', '28/3/19',
       '29/3/19', '30/3/19', '31/3/19', '01/04/2019', '02/04/2019',
       '03/04/2019', '04/04/2019', '05/04/2019', '06/04/2019',
       '07/04/2019', '08/04/2019', '09/04/2019', '10/04/2019',
       '11/04/2019', '12/04/2019', '13/4/19', '14/4/19', '15/4/19',
       '16/4/19', '17/4/19', '18/4/19', '19/4/19', '20/4/19', '21/4/19',
       '22/4/19', '23/4/19', '24/4/19', '25/4/19', '26/4/19', '27/4/19',
       '28/4/19', '29/4/19', '30/4/19', '01/05/2019', '02/05/2019',
       '03/05/2019', '04/05/2019', '05/05/2019', '06/05/2019',
       '07/05/2019', '08/05/2019', '09/05/2019', '10/05/2019',
       '11/05/2019', '12/05/2019', '13/5/19', '14/5/19', '15/5/19',
       '16/5/19', '17/5/19', '18/5/19', '19/5/19', '20/5/19', '21/5/19',
       '22/5/19', '23/5/19', '24/5/19', '25/5/19', '26/5/19', '27/5/19',
       '28/5/19', '29/5/19', '30/5/19', '31/5/19', '01/06/2019',
       '02/06/2019', '03/06/2019', '04/06/2019', '05/06/2019',
       '06/06/2019', '07/06/2019', '08/06/2019', '09/06/2019',
       '10/06/2019', '11/06/2019', '12/06/2019', '13/6/19', '14/6/19',
       '15/6/19', '16/6/19', '17/6/19', '18/6/19', '19/6/19', '20/6/19',
       '21/6/19', '22/6/19', '23/6/19', '24/6/19', '25/6/19', '26/6/19',
       '27/6/19', '28/6/19', '29/6/19', '30/6/19', '01/07/2019',
       '02/07/2019', '03/07/2019', '04/07/2019', '05/07/2019',
       '06/07/2019', '07/07/2019', '08/07/2019', '09/07/2019',
       '10/07/2019', '11/07/2019', '12/07/2019', '13/7/19', '14/7/19',
       '15/7/19', '16/7/19', '17/7/19', '18/7/19', '19/7/19', '20/7/19',
       '21/7/19', '22/7/19', '23/7/19', '24/7/19', '25/7/19', '26/7/19',
       '27/7/19', '28/7/19', '29/7/19', '30/7/19', '31/7/19',
       '01/08/2019', '02/08/2019', '03/08/2019', '04/08/2019',
       '05/08/2019', '06/08/2019', '07/08/2019', '08/08/2019',
       '09/08/2019', '10/08/2019', '11/08/2019', '12/08/2019', '13/8/19',
       '14/8/19', '15/8/19', '16/8/19', '17/8/19', '18/8/19', '19/8/19',
       '20/8/19', '21/8/19', '22/8/19', '23/8/19', '24/8/19', '25/8/19',
       '26/8/19', '27/8/19', '28/8/19', '29/8/19', '30/8/19', '31/8/19',
       '01/09/2019', '02/09/2019', '03/09/2019', '04/09/2019',
       '05/09/2019', '06/09/2019', '07/09/2019', '08/09/2019',
       '09/09/2019', '10/09/2019', '11/09/2019', '12/09/2019', '13/9/19',
       '14/9/19', '15/9/19', '16/9/19', '17/9/19', '18/9/19', '19/9/19',
       '20/9/19', '21/9/19', '22/9/19', '23/9/19', '24/9/19', '25/9/19',
       '26/9/19', '27/9/19', '28/9/19', '29/9/19', '30/9/19',
       '01/10/2019', '02/10/2019', '03/10/2019', '04/10/2019',
       '05/10/2019', '06/10/2019', '07/10/2019', '08/10/2019',
       '09/10/2019', '10/10/2019', '11/10/2019', '12/10/2019', '13/10/19',
       '14/10/19', '15/10/19', '16/10/19', '17/10/19', '18/10/19',
       '19/10/19', '20/10/19', '21/10/19', '22/10/19', '23/10/19',
       '24/10/19', '25/10/19', '26/10/19', '27/10/19', '28/10/19',
       '29/10/19', '30/10/19', '31/10/19', '01/11/2019', '02/11/2019',
       '03/11/2019', '04/11/2019', '05/11/2019', '06/11/2019',
       '07/11/2019', '08/11/2019', '09/11/2019', '10/11/2019',
       '11/11/2019', '12/11/2019', '13/11/19', '14/11/19', '15/11/19',
       '16/11/19', '17/11/19', '18/11/19', '19/11/19', '20/11/19',
       '21/11/19', '22/11/19', '23/11/19', '24/11/19', '25/11/19',
       '26/11/19', '27/11/19', '28/11/19', '29/11/19', '30/11/19',
       '01/12/2019', '02/12/2019', '03/12/2019', '04/12/2019',
       '05/12/2019', '06/12/2019', '07/12/2019', '08/12/2019',
       '09/12/2019', '10/12/2019', '11/12/2019', '12/12/2019', '13/12/19',
       '14/12/19', '15/12/19', '16/12/19', '17/12/19', '18/12/19',
       '19/12/19', '20/12/19', '21/12/19', '22/12/19', '23/12/19',
       '24/12/19', '25/12/19', '26/12/19', '27/12/19', '28/12/19',
       '29/12/19', '30/12/19', '31/12/19', '01/01/2020', '02/01/2020',
       '03/01/2020', '04/01/2020', '05/01/2020', '06/01/2020',
       '07/01/2020', '08/01/2020', '09/01/2020', '10/01/2020',
       '11/01/2020', '12/01/2020', '13/1/20', '14/1/20', '15/1/20',
       '16/1/20', '17/1/20', '18/1/20', '19/1/20', '20/1/20', '21/1/20',
       '22/1/20', '23/1/20', '24/1/20', '25/1/20', '26/1/20', '27/1/20',
       '28/1/20', '29/1/20', '30/1/20', '31/1/20', '01/02/2020',
       '02/02/2020', '03/02/2020', '04/02/2020', '05/02/2020',
       '06/02/2020', '07/02/2020', '08/02/2020', '09/02/2020',
       '10/02/2020', '11/02/2020', '12/02/2020', '13/2/20', '14/2/20',
       '15/2/20', '16/2/20', '17/2/20', '18/2/20', '19/2/20', '20/2/20',
       '21/2/20', '22/2/20', '23/2/20', '24/2/20', '25/2/20', '26/2/20',
       '27/2/20', '28/2/20', '29/2/20', '01/03/2020', '02/03/2020',
       '03/03/2020', '04/03/2020', '05/03/2020', '06/03/2020',
       '07/03/2020', '08/03/2020', '09/03/2020', '10/03/2020',
       '11/03/2020', '12/03/2020', '13/3/20', '14/3/20', '15/3/20',
       '16/3/20', '17/3/20', '18/3/20', '19/3/20', '20/3/20', '21/3/20',
       '22/3/20', '23/3/20', '24/3/20', '25/3/20', '26/3/20', '27/3/20',
       '28/3/20', '29/3/20', '30/3/20', '31/3/20', '01/04/2020',
       '02/04/2020', '03/04/2020', '04/04/2020', '05/04/2020',
       '06/04/2020', '07/04/2020', '08/04/2020', '09/04/2020',
       '10/04/2020', '11/04/2020', '12/04/2020', '13/4/20', '14/4/20',
       '15/4/20', '16/4/20', '17/4/20', '18/4/20', '19/4/20', '20/4/20',
       '21/4/20', '22/4/20', '23/4/20', '24/4/20', '25/4/20', '26/4/20',
       '27/4/20', '28/4/20', '29/4/20', '30/4/20', '01/05/2020',
       '02/05/2020', '03/05/2020', '04/05/2020', '05/05/2020',
       '06/05/2020', '07/05/2020', '08/05/2020', '09/05/2020',
       '10/05/2020', '11/05/2020', '12/05/2020', '13/5/20', '14/5/20',
       '15/5/20', '16/5/20', '17/5/20', '18/5/20', '19/5/20', '20/5/20',
       '21/5/20', '22/5/20', '23/5/20', '24/5/20', '25/5/20', '26/5/20',
       '27/5/20', '28/5/20', '29/5/20', '30/5/20', '31/5/20',
       '01/06/2020', '02/06/2020', '03/06/2020', '04/06/2020',
       '05/06/2020', '06/06/2020', '07/06/2020', '08/06/2020',
       '09/06/2020', '10/06/2020', '11/06/2020', '12/06/2020', '13/6/20',
       '14/6/20', '15/6/20', '16/6/20', '17/6/20', '18/6/20', '19/6/20',
       '20/6/20', '21/6/20', '22/6/20', '23/6/20', '24/6/20', '25/6/20',
       '26/6/20', '27/6/20', '28/6/20', '29/6/20', '30/6/20',
       '01/07/2020', '02/07/2020', '03/07/2020', '04/07/2020',
       '05/07/2020', '06/07/2020', '07/07/2020', '08/07/2020',
       '09/07/2020', '10/07/2020', '11/07/2020', '12/07/2020', '13/7/20',
       '14/7/20', '15/7/20', '16/7/20', '17/7/20', '18/7/20', '19/7/20',
       '20/7/20', '21/7/20', '22/7/20', '23/7/20', '24/7/20', '25/7/20',
       '26/7/20', '27/7/20', '28/7/20', '29/7/20', '30/7/20', '31/7/20',
       '01/08/2020', '02/08/2020', '03/08/2020', '04/08/2020',
       '05/08/2020', '06/08/2020', '07/08/2020', '08/08/2020',
       '09/08/2020', '10/08/2020', '11/08/2020', '12/08/2020', '13/8/20',
       '14/8/20', '15/8/20', '16/8/20', '17/8/20', '18/8/20', '19/8/20',
       '20/8/20', '21/8/20', '22/8/20', '23/8/20', '24/8/20', '25/8/20',
       '26/8/20', '27/8/20', '28/8/20', '29/8/20', '30/8/20', '31/8/20',
       '01/09/2020', '02/09/2020', '03/09/2020', '04/09/2020',
       '05/09/2020', '06/09/2020', '07/09/2020', '08/09/2020',
       '09/09/2020', '10/09/2020', '11/09/2020', '12/09/2020', '13/9/20',
       '14/9/20', '15/9/20', '16/9/20', '17/9/20', '18/9/20', '19/9/20',
       '20/9/20', '21/9/20', '22/9/20', '23/9/20', '24/9/20', '25/9/20',
       '26/9/20', '27/9/20', '28/9/20', '29/9/20', '30/9/20',
       '01/10/2020', '02/10/2020', '03/10/2020', '04/10/2020',
       '05/10/2020', '06/10/2020', '07/10/2020', '08/10/2020',
       '09/10/2020', '10/10/2020', '11/10/2020', '12/10/2020', '13/10/20',
       '14/10/20', '15/10/20', '16/10/20', '17/10/20', '18/10/20',
       '19/10/20', '20/10/20', '21/10/20', '22/10/20', '23/10/20',
       '24/10/20', '25/10/20', '26/10/20', '27/10/20', '28/10/20',
       '29/10/20', '30/10/20', '31/10/20', '01/11/2020', '02/11/2020',
       '03/11/2020', '04/11/2020', '05/11/2020', '06/11/2020',
       '07/11/2020', '08/11/2020', '09/11/2020', '10/11/2020',
       '11/11/2020', '12/11/2020', '13/11/20', '14/11/20', '15/11/20',
       '16/11/20', '17/11/20', '18/11/20', '19/11/20', '20/11/20',
       '21/11/20', '22/11/20', '23/11/20', '24/11/20', '25/11/20',
       '26/11/20', '27/11/20', '28/11/20', '29/11/20', '30/11/20',
       '01/12/2020', '02/12/2020', '03/12/2020', '04/12/2020',
       '05/12/2020', '06/12/2020', '07/12/2020', '08/12/2020',
       '09/12/2020', '10/12/2020', '11/12/2020', '12/12/2020', '13/12/20',
       '14/12/20', '15/12/20', '16/12/20', '17/12/20', '18/12/20',
       '19/12/20', '20/12/20', '21/12/20', '22/12/20', '23/12/20',
       '24/12/20', '25/12/20', '26/12/20', '27/12/20', '28/12/20',
       '29/12/20', '30/12/20'], dtype=object)

In [7]:
def fix_dates(date):
    parts = date.split('/')
    if len(parts[-1]) == 2:  # 2-digit year
        parts[-1] = '20' + parts[-1]
    return '/'.join(str(int(part)) for part in parts)  # Remove leading zeros

df['order_date'] = df['order_date'].apply(fix_dates)

df['order_date'].unique()

array(['31/5/2018', '1/6/2018', '2/6/2018', '3/6/2018', '4/6/2018',
       '5/6/2018', '6/6/2018', '7/6/2018', '8/6/2018', '9/6/2018',
       '10/6/2018', '11/6/2018', '12/6/2018', '13/6/2018', '14/6/2018',
       '15/6/2018', '16/6/2018', '17/6/2018', '18/6/2018', '19/6/2018',
       '20/6/2018', '21/6/2018', '22/6/2018', '23/6/2018', '24/6/2018',
       '25/6/2018', '26/6/2018', '27/6/2018', '28/6/2018', '29/6/2018',
       '30/6/2018', '1/7/2018', '2/7/2018', '3/7/2018', '4/7/2018',
       '5/7/2018', '6/7/2018', '7/7/2018', '8/7/2018', '9/7/2018',
       '10/7/2018', '11/7/2018', '12/7/2018', '13/7/2018', '14/7/2018',
       '15/7/2018', '16/7/2018', '17/7/2018', '18/7/2018', '19/7/2018',
       '20/7/2018', '21/7/2018', '22/7/2018', '23/7/2018', '24/7/2018',
       '25/7/2018', '26/7/2018', '27/7/2018', '28/7/2018', '29/7/2018',
       '30/7/2018', '31/7/2018', '1/8/2018', '2/8/2018', '3/8/2018',
       '4/8/2018', '5/8/2018', '6/8/2018', '7/8/2018', '8/8/2018',
       '9/8/2018', '10/8/2018', '11/8/2018', '12/8/2018', '13/8/2018',
       '14/8/2018', '15/8/2018', '16/8/2018', '17/8/2018', '18/8/2018',
       '19/8/2018', '20/8/2018', '21/8/2018', '22/8/2018', '23/8/2018',
       '24/8/2018', '25/8/2018', '26/8/2018', '27/8/2018', '28/8/2018',
       '29/8/2018', '30/8/2018', '31/8/2018', '1/9/2018', '2/9/2018',
       '3/9/2018', '4/9/2018', '5/9/2018', '6/9/2018', '7/9/2018',
       '8/9/2018', '9/9/2018', '10/9/2018', '11/9/2018', '12/9/2018',
       '13/9/2018', '14/9/2018', '15/9/2018', '16/9/2018', '17/9/2018',
       '18/9/2018', '19/9/2018', '20/9/2018', '21/9/2018', '22/9/2018',
       '23/9/2018', '24/9/2018', '25/9/2018', '26/9/2018', '27/9/2018',
       '28/9/2018', '29/9/2018', '30/9/2018', '1/10/2018', '2/10/2018',
       '3/10/2018', '4/10/2018', '5/10/2018', '6/10/2018', '7/10/2018',
       '8/10/2018', '9/10/2018', '10/10/2018', '11/10/2018', '12/10/2018',
       '13/10/2018', '14/10/2018', '15/10/2018', '16/10/2018',
       '17/10/2018', '18/10/2018', '19/10/2018', '20/10/2018',
       '21/10/2018', '22/10/2018', '23/10/2018', '24/10/2018',
       '25/10/2018', '26/10/2018', '27/10/2018', '28/10/2018',
       '29/10/2018', '30/10/2018', '31/10/2018', '1/11/2018', '2/11/2018',
       '3/11/2018', '4/11/2018', '5/11/2018', '6/11/2018', '7/11/2018',
       '8/11/2018', '9/11/2018', '10/11/2018', '11/11/2018', '12/11/2018',
       '13/11/2018', '14/11/2018', '15/11/2018', '16/11/2018',
       '17/11/2018', '18/11/2018', '19/11/2018', '20/11/2018',
       '21/11/2018', '22/11/2018', '23/11/2018', '24/11/2018',
       '25/11/2018', '26/11/2018', '27/11/2018', '28/11/2018',
       '29/11/2018', '30/11/2018', '1/12/2018', '2/12/2018', '3/12/2018',
       '4/12/2018', '5/12/2018', '6/12/2018', '7/12/2018', '8/12/2018',
       '9/12/2018', '10/12/2018', '11/12/2018', '12/12/2018',
       '13/12/2018', '14/12/2018', '15/12/2018', '16/12/2018',
       '17/12/2018', '18/12/2018', '19/12/2018', '20/12/2018',
       '21/12/2018', '22/12/2018', '23/12/2018', '24/12/2018',
       '25/12/2018', '26/12/2018', '27/12/2018', '28/12/2018',
       '29/12/2018', '30/12/2018', '31/12/2018', '1/1/2019', '2/1/2019',
       '3/1/2019', '4/1/2019', '5/1/2019', '6/1/2019', '7/1/2019',
       '8/1/2019', '9/1/2019', '10/1/2019', '11/1/2019', '12/1/2019',
       '13/1/2019', '14/1/2019', '15/1/2019', '16/1/2019', '17/1/2019',
       '18/1/2019', '19/1/2019', '20/1/2019', '21/1/2019', '22/1/2019',
       '23/1/2019', '24/1/2019', '25/1/2019', '26/1/2019', '27/1/2019',
       '28/1/2019', '29/1/2019', '30/1/2019', '31/1/2019', '1/2/2019',
       '2/2/2019', '3/2/2019', '4/2/2019', '5/2/2019', '6/2/2019',
       '7/2/2019', '8/2/2019', '9/2/2019', '10/2/2019', '11/2/2019',
       '12/2/2019', '13/2/2019', '14/2/2019', '15/2/2019', '16/2/2019',
       '17/2/2019', '18/2/2019', '19/2/2019', '20/2/2019', '21/2/2019',
       '22/2/2019', '23/2/2019', '24/2/2019', '25/2/2019', '26/2/2019',
       '27/2/2019', '28/2/2019', '1/3/2019', '2/3/2019', '3/3/2019',
       '4/3/2019', '5/3/2019', '6/3/2019', '7/3/2019', '8/3/2019',
       '9/3/2019', '10/3/2019', '11/3/2019', '12/3/2019', '13/3/2019',
       '14/3/2019', '15/3/2019', '16/3/2019', '17/3/2019', '18/3/2019',
       '19/3/2019', '20/3/2019', '21/3/2019', '22/3/2019', '23/3/2019',
       '24/3/2019', '25/3/2019', '26/3/2019', '27/3/2019', '28/3/2019',
       '29/3/2019', '30/3/2019', '31/3/2019', '1/4/2019', '2/4/2019',
       '3/4/2019', '4/4/2019', '5/4/2019', '6/4/2019', '7/4/2019',
       '8/4/2019', '9/4/2019', '10/4/2019', '11/4/2019', '12/4/2019',
       '13/4/2019', '14/4/2019', '15/4/2019', '16/4/2019', '17/4/2019',
       '18/4/2019', '19/4/2019', '20/4/2019', '21/4/2019', '22/4/2019',
       '23/4/2019', '24/4/2019', '25/4/2019', '26/4/2019', '27/4/2019',
       '28/4/2019', '29/4/2019', '30/4/2019', '1/5/2019', '2/5/2019',
       '3/5/2019', '4/5/2019', '5/5/2019', '6/5/2019', '7/5/2019',
       '8/5/2019', '9/5/2019', '10/5/2019', '11/5/2019', '12/5/2019',
       '13/5/2019', '14/5/2019', '15/5/2019', '16/5/2019', '17/5/2019',
       '18/5/2019', '19/5/2019', '20/5/2019', '21/5/2019', '22/5/2019',
       '23/5/2019', '24/5/2019', '25/5/2019', '26/5/2019', '27/5/2019',
       '28/5/2019', '29/5/2019', '30/5/2019', '31/5/2019', '1/6/2019',
       '2/6/2019', '3/6/2019', '4/6/2019', '5/6/2019', '6/6/2019',
       '7/6/2019', '8/6/2019', '9/6/2019', '10/6/2019', '11/6/2019',
       '12/6/2019', '13/6/2019', '14/6/2019', '15/6/2019', '16/6/2019',
       '17/6/2019', '18/6/2019', '19/6/2019', '20/6/2019', '21/6/2019',
       '22/6/2019', '23/6/2019', '24/6/2019', '25/6/2019', '26/6/2019',
       '27/6/2019', '28/6/2019', '29/6/2019', '30/6/2019', '1/7/2019',
       '2/7/2019', '3/7/2019', '4/7/2019', '5/7/2019', '6/7/2019',
       '7/7/2019', '8/7/2019', '9/7/2019', '10/7/2019', '11/7/2019',
       '12/7/2019', '13/7/2019', '14/7/2019', '15/7/2019', '16/7/2019',
       '17/7/2019', '18/7/2019', '19/7/2019', '20/7/2019', '21/7/2019',
       '22/7/2019', '23/7/2019', '24/7/2019', '25/7/2019', '26/7/2019',
       '27/7/2019', '28/7/2019', '29/7/2019', '30/7/2019', '31/7/2019',
       '1/8/2019', '2/8/2019', '3/8/2019', '4/8/2019', '5/8/2019',
       '6/8/2019', '7/8/2019', '8/8/2019', '9/8/2019', '10/8/2019',
       '11/8/2019', '12/8/2019', '13/8/2019', '14/8/2019', '15/8/2019',
       '16/8/2019', '17/8/2019', '18/8/2019', '19/8/2019', '20/8/2019',
       '21/8/2019', '22/8/2019', '23/8/2019', '24/8/2019', '25/8/2019',
       '26/8/2019', '27/8/2019', '28/8/2019', '29/8/2019', '30/8/2019',
       '31/8/2019', '1/9/2019', '2/9/2019', '3/9/2019', '4/9/2019',
       '5/9/2019', '6/9/2019', '7/9/2019', '8/9/2019', '9/9/2019',
       '10/9/2019', '11/9/2019', '12/9/2019', '13/9/2019', '14/9/2019',
       '15/9/2019', '16/9/2019', '17/9/2019', '18/9/2019', '19/9/2019',
       '20/9/2019', '21/9/2019', '22/9/2019', '23/9/2019', '24/9/2019',
       '25/9/2019', '26/9/2019', '27/9/2019', '28/9/2019', '29/9/2019',
       '30/9/2019', '1/10/2019', '2/10/2019', '3/10/2019', '4/10/2019',
       '5/10/2019', '6/10/2019', '7/10/2019', '8/10/2019', '9/10/2019',
       '10/10/2019', '11/10/2019', '12/10/2019', '13/10/2019',
       '14/10/2019', '15/10/2019', '16/10/2019', '17/10/2019',
       '18/10/2019', '19/10/2019', '20/10/2019', '21/10/2019',
       '22/10/2019', '23/10/2019', '24/10/2019', '25/10/2019',
       '26/10/2019', '27/10/2019', '28/10/2019', '29/10/2019',
       '30/10/2019', '31/10/2019', '1/11/2019', '2/11/2019', '3/11/2019',
       '4/11/2019', '5/11/2019', '6/11/2019', '7/11/2019', '8/11/2019',
       '9/11/2019', '10/11/2019', '11/11/2019', '12/11/2019',
       '13/11/2019', '14/11/2019', '15/11/2019', '16/11/2019',
       '17/11/2019', '18/11/2019', '19/11/2019', '20/11/2019',
       '21/11/2019', '22/11/2019', '23/11/2019', '24/11/2019',
       '25/11/2019', '26/11/2019', '27/11/2019', '28/11/2019',
       '29/11/2019', '30/11/2019', '1/12/2019', '2/12/2019', '3/12/2019',
       '4/12/2019', '5/12/2019', '6/12/2019', '7/12/2019', '8/12/2019',
       '9/12/2019', '10/12/2019', '11/12/2019', '12/12/2019',
       '13/12/2019', '14/12/2019', '15/12/2019', '16/12/2019',
       '17/12/2019', '18/12/2019', '19/12/2019', '20/12/2019',
       '21/12/2019', '22/12/2019', '23/12/2019', '24/12/2019',
       '25/12/2019', '26/12/2019', '27/12/2019', '28/12/2019',
       '29/12/2019', '30/12/2019', '31/12/2019', '1/1/2020', '2/1/2020',
       '3/1/2020', '4/1/2020', '5/1/2020', '6/1/2020', '7/1/2020',
       '8/1/2020', '9/1/2020', '10/1/2020', '11/1/2020', '12/1/2020',
       '13/1/2020', '14/1/2020', '15/1/2020', '16/1/2020', '17/1/2020',
       '18/1/2020', '19/1/2020', '20/1/2020', '21/1/2020', '22/1/2020',
       '23/1/2020', '24/1/2020', '25/1/2020', '26/1/2020', '27/1/2020',
       '28/1/2020', '29/1/2020', '30/1/2020', '31/1/2020', '1/2/2020',
       '2/2/2020', '3/2/2020', '4/2/2020', '5/2/2020', '6/2/2020',
       '7/2/2020', '8/2/2020', '9/2/2020', '10/2/2020', '11/2/2020',
       '12/2/2020', '13/2/2020', '14/2/2020', '15/2/2020', '16/2/2020',
       '17/2/2020', '18/2/2020', '19/2/2020', '20/2/2020', '21/2/2020',
       '22/2/2020', '23/2/2020', '24/2/2020', '25/2/2020', '26/2/2020',
       '27/2/2020', '28/2/2020', '29/2/2020', '1/3/2020', '2/3/2020',
       '3/3/2020', '4/3/2020', '5/3/2020', '6/3/2020', '7/3/2020',
       '8/3/2020', '9/3/2020', '10/3/2020', '11/3/2020', '12/3/2020',
       '13/3/2020', '14/3/2020', '15/3/2020', '16/3/2020', '17/3/2020',
       '18/3/2020', '19/3/2020', '20/3/2020', '21/3/2020', '22/3/2020',
       '23/3/2020', '24/3/2020', '25/3/2020', '26/3/2020', '27/3/2020',
       '28/3/2020', '29/3/2020', '30/3/2020', '31/3/2020', '1/4/2020',
       '2/4/2020', '3/4/2020', '4/4/2020', '5/4/2020', '6/4/2020',
       '7/4/2020', '8/4/2020', '9/4/2020', '10/4/2020', '11/4/2020',
       '12/4/2020', '13/4/2020', '14/4/2020', '15/4/2020', '16/4/2020',
       '17/4/2020', '18/4/2020', '19/4/2020', '20/4/2020', '21/4/2020',
       '22/4/2020', '23/4/2020', '24/4/2020', '25/4/2020', '26/4/2020',
       '27/4/2020', '28/4/2020', '29/4/2020', '30/4/2020', '1/5/2020',
       '2/5/2020', '3/5/2020', '4/5/2020', '5/5/2020', '6/5/2020',
       '7/5/2020', '8/5/2020', '9/5/2020', '10/5/2020', '11/5/2020',
       '12/5/2020', '13/5/2020', '14/5/2020', '15/5/2020', '16/5/2020',
       '17/5/2020', '18/5/2020', '19/5/2020', '20/5/2020', '21/5/2020',
       '22/5/2020', '23/5/2020', '24/5/2020', '25/5/2020', '26/5/2020',
       '27/5/2020', '28/5/2020', '29/5/2020', '30/5/2020', '31/5/2020',
       '1/6/2020', '2/6/2020', '3/6/2020', '4/6/2020', '5/6/2020',
       '6/6/2020', '7/6/2020', '8/6/2020', '9/6/2020', '10/6/2020',
       '11/6/2020', '12/6/2020', '13/6/2020', '14/6/2020', '15/6/2020',
       '16/6/2020', '17/6/2020', '18/6/2020', '19/6/2020', '20/6/2020',
       '21/6/2020', '22/6/2020', '23/6/2020', '24/6/2020', '25/6/2020',
       '26/6/2020', '27/6/2020', '28/6/2020', '29/6/2020', '30/6/2020',
       '1/7/2020', '2/7/2020', '3/7/2020', '4/7/2020', '5/7/2020',
       '6/7/2020', '7/7/2020', '8/7/2020', '9/7/2020', '10/7/2020',
       '11/7/2020', '12/7/2020', '13/7/2020', '14/7/2020', '15/7/2020',
       '16/7/2020', '17/7/2020', '18/7/2020', '19/7/2020', '20/7/2020',
       '21/7/2020', '22/7/2020', '23/7/2020', '24/7/2020', '25/7/2020',
       '26/7/2020', '27/7/2020', '28/7/2020', '29/7/2020', '30/7/2020',
       '31/7/2020', '1/8/2020', '2/8/2020', '3/8/2020', '4/8/2020',
       '5/8/2020', '6/8/2020', '7/8/2020', '8/8/2020', '9/8/2020',
       '10/8/2020', '11/8/2020', '12/8/2020', '13/8/2020', '14/8/2020',
       '15/8/2020', '16/8/2020', '17/8/2020', '18/8/2020', '19/8/2020',
       '20/8/2020', '21/8/2020', '22/8/2020', '23/8/2020', '24/8/2020',
       '25/8/2020', '26/8/2020', '27/8/2020', '28/8/2020', '29/8/2020',
       '30/8/2020', '31/8/2020', '1/9/2020', '2/9/2020', '3/9/2020',
       '4/9/2020', '5/9/2020', '6/9/2020', '7/9/2020', '8/9/2020',
       '9/9/2020', '10/9/2020', '11/9/2020', '12/9/2020', '13/9/2020',
       '14/9/2020', '15/9/2020', '16/9/2020', '17/9/2020', '18/9/2020',
       '19/9/2020', '20/9/2020', '21/9/2020', '22/9/2020', '23/9/2020',
       '24/9/2020', '25/9/2020', '26/9/2020', '27/9/2020', '28/9/2020',
       '29/9/2020', '30/9/2020', '1/10/2020', '2/10/2020', '3/10/2020',
       '4/10/2020', '5/10/2020', '6/10/2020', '7/10/2020', '8/10/2020',
       '9/10/2020', '10/10/2020', '11/10/2020', '12/10/2020',
       '13/10/2020', '14/10/2020', '15/10/2020', '16/10/2020',
       '17/10/2020', '18/10/2020', '19/10/2020', '20/10/2020',
       '21/10/2020', '22/10/2020', '23/10/2020', '24/10/2020',
       '25/10/2020', '26/10/2020', '27/10/2020', '28/10/2020',
       '29/10/2020', '30/10/2020', '31/10/2020', '1/11/2020', '2/11/2020',
       '3/11/2020', '4/11/2020', '5/11/2020', '6/11/2020', '7/11/2020',
       '8/11/2020', '9/11/2020', '10/11/2020', '11/11/2020', '12/11/2020',
       '13/11/2020', '14/11/2020', '15/11/2020', '16/11/2020',
       '17/11/2020', '18/11/2020', '19/11/2020', '20/11/2020',
       '21/11/2020', '22/11/2020', '23/11/2020', '24/11/2020',
       '25/11/2020', '26/11/2020', '27/11/2020', '28/11/2020',
       '29/11/2020', '30/11/2020', '1/12/2020', '2/12/2020', '3/12/2020',
       '4/12/2020', '5/12/2020', '6/12/2020', '7/12/2020', '8/12/2020',
       '9/12/2020', '10/12/2020', '11/12/2020', '12/12/2020',
       '13/12/2020', '14/12/2020', '15/12/2020', '16/12/2020',
       '17/12/2020', '18/12/2020', '19/12/2020', '20/12/2020',
       '21/12/2020', '22/12/2020', '23/12/2020', '24/12/2020',
       '25/12/2020', '26/12/2020', '27/12/2020', '28/12/2020',
       '29/12/2020', '30/12/2020'], dtype=object)

In [8]:
df['ship_date'].unique()

array(['14/6/18', '22/6/18', '21/6/18', '2/6/2018', '16/6/18', '8/6/2018',
       '26/6/18', '29/6/18', '15/6/18', '7/6/2018', '24/6/18', '19/6/18',
       '6/6/2018', '11/6/2018', '18/6/18', '10/6/2018', '20/6/18',
       '27/6/18', '5/6/2018', '30/6/18', '28/6/18', '13/6/18', '9/6/2018',
       '12/6/2018', '25/6/18', '3/7/2018', '2/7/2018', '1/7/2018',
       '23/6/18', '5/7/2018', '7/7/2018', '9/7/2018', '10/7/2018',
       '17/6/18', '8/7/2018', '6/7/2018', '12/7/2018', '13/7/18',
       '14/7/18', '4/7/2018', '15/7/18', '11/7/2018', '16/7/18',
       '17/7/18', '18/7/18', '20/7/18', '19/7/18', '24/7/18', '21/7/18',
       '25/7/18', '27/7/18', '29/7/18', '31/7/18', '1/8/2018', '30/7/18',
       '23/7/18', '2/8/2018', '26/7/18', '22/7/18', '4/8/2018',
       '6/8/2018', '5/8/2018', '7/8/2018', '3/8/2018', '8/8/2018',
       '10/8/2018', '12/8/2018', '13/8/18', '11/8/2018', '14/8/18',
       '17/8/18', '28/7/18', '16/8/18', '15/8/18', '18/8/18', '20/8/18',
       '19/8/18', '21/8/18', '9/8/2018', '22/8/18', '26/8/18', '25/8/18',
       '24/8/18', '23/8/18', '28/8/18', '27/8/18', '31/8/18', '29/8/18',
       '30/8/18', '5/9/2018', '1/9/2018', '6/9/2018', '7/9/2018',
       '2/9/2018', '3/9/2018', '4/9/2018', '8/9/2018', '9/9/2018',
       '10/9/2018', '12/9/2018', '13/9/18', '11/9/2018', '14/9/18',
       '15/9/18', '17/9/18', '18/9/18', '20/9/18', '16/9/18', '19/9/18',
       '23/9/18', '21/9/18', '22/9/18', '25/9/18', '27/9/18', '28/9/18',
       '29/9/18', '1/10/2018', '26/9/18', '3/10/2018', '30/9/18',
       '2/10/2018', '4/10/2018', '6/10/2018', '24/9/18', '5/10/2018',
       '9/10/2018', '8/10/2018', '11/10/2018', '10/10/2018', '12/10/2018',
       '13/10/18', '7/10/2018', '14/10/18', '15/10/18', '16/10/18',
       '17/10/18', '20/10/18', '21/10/18', '22/10/18', '18/10/18',
       '24/10/18', '19/10/18', '23/10/18', '27/10/18', '26/10/18',
       '28/10/18', '25/10/18', '29/10/18', '31/10/18', '4/11/2018',
       '30/10/18', '7/11/2018', '5/11/2018', '2/11/2018', '6/11/2018',
       '1/11/2018', '3/11/2018', '8/11/2018', '10/11/2018', '12/11/2018',
       '9/11/2018', '11/11/2018', '14/11/18', '17/11/18', '16/11/18',
       '15/11/18', '18/11/18', '13/11/18', '20/11/18', '21/11/18',
       '26/11/18', '24/11/18', '23/11/18', '22/11/18', '27/11/18',
       '28/11/18', '29/11/18', '25/11/18', '30/11/18', '1/12/2018',
       '19/11/18', '2/12/2018', '4/12/2018', '3/12/2018', '5/12/2018',
       '6/12/2018', '8/12/2018', '7/12/2018', '10/12/2018', '11/12/2018',
       '13/12/18', '9/12/2018', '12/12/2018', '16/12/18', '14/12/18',
       '17/12/18', '19/12/18', '20/12/18', '23/12/18', '18/12/18',
       '24/12/18', '21/12/18', '26/12/18', '25/12/18', '27/12/18',
       '22/12/18', '15/12/18', '29/12/18', '30/12/18', '28/12/18',
       '31/12/18', '2/1/2019', '1/1/2019', '3/1/2019', '4/1/2019',
       '7/1/2019', '5/1/2019', '8/1/2019', '6/1/2019', '9/1/2019',
       '10/1/2019', '13/1/19', '12/1/2019', '11/1/2019', '15/1/19',
       '14/1/19', '17/1/19', '19/1/19', '16/1/19', '18/1/19', '21/1/19',
       '20/1/19', '23/1/19', '24/1/19', '22/1/19', '25/1/19', '27/1/19',
       '26/1/19', '30/1/19', '28/1/19', '1/2/2019', '31/1/19', '29/1/19',
       '3/2/2019', '5/2/2019', '6/2/2019', '4/2/2019', '7/2/2019',
       '8/2/2019', '9/2/2019', '11/2/2019', '12/2/2019', '13/2/19',
       '14/2/19', '2/2/2019', '17/2/19', '16/2/19', '19/2/19', '20/2/19',
       '10/2/2019', '15/2/19', '21/2/19', '23/2/19', '18/2/19', '22/2/19',
       '24/2/19', '25/2/19', '1/3/2019', '28/2/19', '26/2/19', '3/3/2019',
       '4/3/2019', '27/2/19', '5/3/2019', '2/3/2019', '6/3/2019',
       '8/3/2019', '9/3/2019', '10/3/2019', '7/3/2019', '11/3/2019',
       '14/3/19', '13/3/19', '16/3/19', '12/3/2019', '17/3/19', '19/3/19',
       '15/3/19', '20/3/19', '18/3/19', '23/3/19', '22/3/19', '27/3/19',
       '24/3/19', '28/3/19', '25/3/19', '21/3/19', '30/3/19', '31/3/19',
       '1/4/2019', '3/4/2019', '26/3/19', '2/4/2019', '5/4/2019',
       '6/4/2019', '8/4/2019', '29/3/19', '4/4/2019', '9/4/2019',
       '7/4/2019', '10/4/2019', '12/4/2019', '14/4/19', '16/4/19',
       '17/4/19', '18/4/19', '13/4/19', '15/4/19', '19/4/19', '20/4/19',
       '23/4/19', '21/4/19', '11/4/2019', '24/4/19', '22/4/19', '29/4/19',
       '26/4/19', '25/4/19', '1/5/2019', '27/4/19', '3/5/2019', '30/4/19',
       '5/5/2019', '6/5/2019', '2/5/2019', '7/5/2019', '8/5/2019',
       '10/5/2019', '12/5/2019', '4/5/2019', '13/5/19', '11/5/2019',
       '9/5/2019', '28/4/19', '16/5/19', '15/5/19', '18/5/19', '20/5/19',
       '14/5/19', '17/5/19', '19/5/19', '23/5/19', '24/5/19', '25/5/19',
       '21/5/19', '26/5/19', '27/5/19', '30/5/19', '22/5/19', '29/5/19',
       '28/5/19', '3/6/2019', '2/6/2019', '1/6/2019', '31/5/19',
       '5/6/2019', '8/6/2019', '4/6/2019', '6/6/2019', '12/6/2019',
       '9/6/2019', '14/6/19', '7/6/2019', '13/6/19', '10/6/2019',
       '16/6/19', '15/6/19', '17/6/19', '11/6/2019', '18/6/19', '20/6/19',
       '22/6/19', '26/6/19', '27/6/19', '25/6/19', '21/6/19', '28/6/19',
       '30/6/19', '19/6/19', '23/6/19', '3/7/2019', '2/7/2019', '24/6/19',
       '8/7/2019', '1/7/2019', '9/7/2019', '29/6/19', '5/7/2019',
       '10/7/2019', '6/7/2019', '11/7/2019', '7/7/2019', '12/7/2019',
       '14/7/19', '16/7/19', '4/7/2019', '17/7/19', '21/7/19', '13/7/19',
       '15/7/19', '20/7/19', '19/7/19', '22/7/19', '26/7/19', '24/7/19',
       '25/7/19', '27/7/19', '18/7/19', '28/7/19', '23/7/19', '31/7/19',
       '29/7/19', '2/8/2019', '3/8/2019', '4/8/2019', '1/8/2019',
       '30/7/19', '5/8/2019', '7/8/2019', '8/8/2019', '9/8/2019',
       '12/8/2019', '13/8/19', '11/8/2019', '15/8/19', '14/8/19',
       '17/8/19', '18/8/19', '10/8/2019', '16/8/19', '6/8/2019',
       '19/8/19', '21/8/19', '20/8/19', '25/8/19', '24/8/19', '27/8/19',
       '29/8/19', '26/8/19', '22/8/19', '28/8/19', '23/8/19', '30/8/19',
       '31/8/19', '3/9/2019', '1/9/2019', '5/9/2019', '6/9/2019',
       '4/9/2019', '2/9/2019', '11/9/2019', '7/9/2019', '9/9/2019',
       '10/9/2019', '14/9/19', '15/9/19', '13/9/19', '8/9/2019',
       '18/9/19', '12/9/2019', '22/9/19', '19/9/19', '16/9/19', '17/9/19',
       '21/9/19', '25/9/19', '20/9/19', '23/9/19', '27/9/19', '26/9/19',
       '29/9/19', '1/10/2019', '24/9/19', '4/10/2019', '6/10/2019',
       '28/9/19', '7/10/2019', '2/10/2019', '5/10/2019', '9/10/2019',
       '3/10/2019', '8/10/2019', '30/9/19', '12/10/2019', '10/10/2019',
       '11/10/2019', '15/10/19', '16/10/19', '21/10/19', '18/10/19',
       '14/10/19', '20/10/19', '22/10/19', '17/10/19', '23/10/19',
       '13/10/19', '24/10/19', '25/10/19', '19/10/19', '27/10/19',
       '28/10/19', '30/10/19', '26/10/19', '31/10/19', '3/11/2019',
       '1/11/2019', '29/10/19', '4/11/2019', '6/11/2019', '5/11/2019',
       '2/11/2019', '8/11/2019', '9/11/2019', '10/11/2019', '11/11/2019',
       '14/11/19', '15/11/19', '13/11/19', '16/11/19', '12/11/2019',
       '7/11/2019', '18/11/19', '21/11/19', '23/11/19', '17/11/19',
       '22/11/19', '19/11/19', '25/11/19', '24/11/19', '26/11/19',
       '27/11/19', '20/11/19', '29/11/19', '1/12/2019', '3/12/2019',
       '2/12/2019', '30/11/19', '28/11/19', '4/12/2019', '5/12/2019',
       '8/12/2019', '9/12/2019', '7/12/2019', '10/12/2019', '12/12/2019',
       '13/12/19', '6/12/2019', '15/12/19', '17/12/19', '14/12/19',
       '18/12/19', '16/12/19', '20/12/19', '11/12/2019', '19/12/19',
       '22/12/19', '21/12/19', '24/12/19', '23/12/19', '26/12/19',
       '25/12/19', '29/12/19', '30/12/19', '28/12/19', '31/12/19',
       '2/1/2020', '3/1/2020', '27/12/19', '6/1/2020', '8/1/2020',
       '1/1/2020', '7/1/2020', '4/1/2020', '9/1/2020', '10/1/2020',
       '11/1/2020', '12/1/2020', '5/1/2020', '13/1/20', '16/1/20',
       '18/1/20', '19/1/20', '20/1/20', '21/1/20', '17/1/20', '15/1/20',
       '24/1/20', '22/1/20', '26/1/20', '25/1/20', '14/1/20', '23/1/20',
       '31/1/20', '29/1/20', '30/1/20', '27/1/20', '1/2/2020', '3/2/2020',
       '2/2/2020', '4/2/2020', '28/1/20', '7/2/2020', '9/2/2020',
       '10/2/2020', '11/2/2020', '12/2/2020', '6/2/2020', '8/2/2020',
       '5/2/2020', '13/2/20', '17/2/20', '16/2/20', '15/2/20', '24/2/20',
       '23/2/20', '19/2/20', '14/2/20', '25/2/20', '20/2/20', '27/2/20',
       '22/2/20', '18/2/20', '21/2/20', '1/3/2020', '2/3/2020',
       '3/3/2020', '29/2/20', '28/2/20', '5/3/2020', '26/2/20',
       '7/3/2020', '9/3/2020', '8/3/2020', '6/3/2020', '4/3/2020',
       '12/3/2020', '10/3/2020', '13/3/20', '16/3/20', '15/3/20',
       '14/3/20', '18/3/20', '11/3/2020', '19/3/20', '17/3/20', '23/3/20',
       '22/3/20', '24/3/20', '21/3/20', '20/3/20', '26/3/20', '29/3/20',
       '31/3/20', '30/3/20', '1/4/2020', '28/3/20', '2/4/2020', '25/3/20',
       '5/4/2020', '4/4/2020', '6/4/2020', '3/4/2020', '27/3/20',
       '7/4/2020', '11/4/2020', '10/4/2020', '8/4/2020', '14/4/20',
       '13/4/20', '15/4/20', '12/4/2020', '9/4/2020', '17/4/20',
       '19/4/20', '18/4/20', '20/4/20', '16/4/20', '24/4/20', '26/4/20',
       '25/4/20', '21/4/20', '22/4/20', '29/4/20', '23/4/20', '27/4/20',
       '30/4/20', '2/5/2020', '28/4/20', '3/5/2020', '5/5/2020',
       '4/5/2020', '7/5/2020', '6/5/2020', '1/5/2020', '9/5/2020',
       '11/5/2020', '8/5/2020', '12/5/2020', '15/5/20', '14/5/20',
       '10/5/2020', '13/5/20', '17/5/20', '18/5/20', '16/5/20', '19/5/20',
       '20/5/20', '23/5/20', '21/5/20', '22/5/20', '25/5/20', '26/5/20',
       '27/5/20', '24/5/20', '28/5/20', '29/5/20', '31/5/20', '30/5/20',
       '5/6/2020', '4/6/2020', '1/6/2020', '6/6/2020', '3/6/2020',
       '8/6/2020', '9/6/2020', '11/6/2020', '7/6/2020', '12/6/2020',
       '2/6/2020', '13/6/20', '10/6/2020', '16/6/20', '15/6/20',
       '17/6/20', '18/6/20', '19/6/20', '14/6/20', '21/6/20', '20/6/20',
       '24/6/20', '22/6/20', '25/6/20', '26/6/20', '28/6/20', '23/6/20',
       '27/6/20', '29/6/20', '30/6/20', '1/7/2020', '3/7/2020',
       '5/7/2020', '4/7/2020', '8/7/2020', '6/7/2020', '2/7/2020',
       '7/7/2020', '9/7/2020', '11/7/2020', '13/7/20', '14/7/20',
       '15/7/20', '12/7/2020', '16/7/20', '18/7/20', '19/7/20', '17/7/20',
       '20/7/20', '10/7/2020', '21/7/20', '23/7/20', '22/7/20', '25/7/20',
       '24/7/20', '29/7/20', '1/8/2020', '27/7/20', '28/7/20', '30/7/20',
       '2/8/2020', '26/7/20', '3/8/2020', '4/8/2020', '5/8/2020',
       '6/8/2020', '9/8/2020', '10/8/2020', '8/8/2020', '11/8/2020',
       '12/8/2020', '31/7/20', '13/8/20', '7/8/2020', '15/8/20',
       '17/8/20', '18/8/20', '14/8/20', '19/8/20', '16/8/20', '20/8/20',
       '22/8/20', '23/8/20', '21/8/20', '26/8/20', '24/8/20', '27/8/20',
       '25/8/20', '28/8/20', '29/8/20', '30/8/20', '31/8/20', '3/9/2020',
       '1/9/2020', '2/9/2020', '6/9/2020', '4/9/2020', '7/9/2020',
       '9/9/2020', '10/9/2020', '8/9/2020', '11/9/2020', '14/9/20',
       '5/9/2020', '16/9/20', '13/9/20', '19/9/20', '12/9/2020',
       '18/9/20', '20/9/20', '22/9/20', '15/9/20', '17/9/20', '24/9/20',
       '21/9/20', '27/9/20', '28/9/20', '25/9/20', '29/9/20', '26/9/20',
       '1/10/2020', '3/10/2020', '30/9/20', '2/10/2020', '23/9/20',
       '4/10/2020', '5/10/2020', '10/10/2020', '9/10/2020', '7/10/2020',
       '6/10/2020', '11/10/2020', '12/10/2020', '14/10/20', '13/10/20',
       '16/10/20', '18/10/20', '19/10/20', '15/10/20', '8/10/2020',
       '17/10/20', '20/10/20', '23/10/20', '25/10/20', '21/10/20',
       '22/10/20', '26/10/20', '28/10/20', '30/10/20', '24/10/20',
       '1/11/2020', '27/10/20', '29/10/20', '31/10/20', '4/11/2020',
       '2/11/2020', '8/11/2020', '5/11/2020', '10/11/2020', '9/11/2020',
       '6/11/2020', '7/11/2020', '11/11/2020', '3/11/2020', '13/11/20',
       '17/11/20', '16/11/20', '14/11/20', '19/11/20', '15/11/20',
       '12/11/2020', '20/11/20', '22/11/20', '21/11/20', '18/11/20',
       '26/11/20', '23/11/20', '27/11/20', '25/11/20', '24/11/20',
       '28/11/20', '29/11/20', '30/11/20', '1/12/2020', '2/12/2020',
       '4/12/2020', '7/12/2020', '3/12/2020', '9/12/2020', '6/12/2020',
       '5/12/2020', '10/12/2020', '11/12/2020', '8/12/2020', '12/12/2020',
       '13/12/20', '15/12/20', '14/12/20', '18/12/20', '16/12/20',
       '19/12/20', '20/12/20', '17/12/20', '24/12/20', '26/12/20',
       '22/12/20', '21/12/20', '25/12/20', '23/12/20', '27/12/20',
       '31/12/20', '30/12/20', '28/12/20', '1/1/2021', '29/12/20',
       '3/1/2021', '2/1/2021', '6/1/2021', '7/1/2021', '10/1/2021',
       '9/1/2021', '5/1/2021', '11/1/2021', '13/1/21', '8/1/2021',
       '12/1/2021', '14/1/21', '4/1/2021', '15/1/21', '17/1/21',
       '20/1/21', '16/1/21', '19/1/21', '18/1/21', '21/1/21', '22/1/21',
       '24/1/21', '23/1/21'], dtype=object)

In [9]:
def fix_dates(date):
    parts = date.split('/')
    if len(parts[-1]) == 2:  # 2-digit year
        parts[-1] = '20' + parts[-1]
    return '/'.join(str(int(part)) for part in parts)  # Remove leading zeros

df['ship_date'] = df['ship_date'].apply(fix_dates)

df['ship_date'].unique()

array(['14/6/2018', '22/6/2018', '21/6/2018', '2/6/2018', '16/6/2018',
       '8/6/2018', '26/6/2018', '29/6/2018', '15/6/2018', '7/6/2018',
       '24/6/2018', '19/6/2018', '6/6/2018', '11/6/2018', '18/6/2018',
       '10/6/2018', '20/6/2018', '27/6/2018', '5/6/2018', '30/6/2018',
       '28/6/2018', '13/6/2018', '9/6/2018', '12/6/2018', '25/6/2018',
       '3/7/2018', '2/7/2018', '1/7/2018', '23/6/2018', '5/7/2018',
       '7/7/2018', '9/7/2018', '10/7/2018', '17/6/2018', '8/7/2018',
       '6/7/2018', '12/7/2018', '13/7/2018', '14/7/2018', '4/7/2018',
       '15/7/2018', '11/7/2018', '16/7/2018', '17/7/2018', '18/7/2018',
       '20/7/2018', '19/7/2018', '24/7/2018', '21/7/2018', '25/7/2018',
       '27/7/2018', '29/7/2018', '31/7/2018', '1/8/2018', '30/7/2018',
       '23/7/2018', '2/8/2018', '26/7/2018', '22/7/2018', '4/8/2018',
       '6/8/2018', '5/8/2018', '7/8/2018', '3/8/2018', '8/8/2018',
       '10/8/2018', '12/8/2018', '13/8/2018', '11/8/2018', '14/8/2018',
       '17/8/2018', '28/7/2018', '16/8/2018', '15/8/2018', '18/8/2018',
       '20/8/2018', '19/8/2018', '21/8/2018', '9/8/2018', '22/8/2018',
       '26/8/2018', '25/8/2018', '24/8/2018', '23/8/2018', '28/8/2018',
       '27/8/2018', '31/8/2018', '29/8/2018', '30/8/2018', '5/9/2018',
       '1/9/2018', '6/9/2018', '7/9/2018', '2/9/2018', '3/9/2018',
       '4/9/2018', '8/9/2018', '9/9/2018', '10/9/2018', '12/9/2018',
       '13/9/2018', '11/9/2018', '14/9/2018', '15/9/2018', '17/9/2018',
       '18/9/2018', '20/9/2018', '16/9/2018', '19/9/2018', '23/9/2018',
       '21/9/2018', '22/9/2018', '25/9/2018', '27/9/2018', '28/9/2018',
       '29/9/2018', '1/10/2018', '26/9/2018', '3/10/2018', '30/9/2018',
       '2/10/2018', '4/10/2018', '6/10/2018', '24/9/2018', '5/10/2018',
       '9/10/2018', '8/10/2018', '11/10/2018', '10/10/2018', '12/10/2018',
       '13/10/2018', '7/10/2018', '14/10/2018', '15/10/2018',
       '16/10/2018', '17/10/2018', '20/10/2018', '21/10/2018',
       '22/10/2018', '18/10/2018', '24/10/2018', '19/10/2018',
       '23/10/2018', '27/10/2018', '26/10/2018', '28/10/2018',
       '25/10/2018', '29/10/2018', '31/10/2018', '4/11/2018',
       '30/10/2018', '7/11/2018', '5/11/2018', '2/11/2018', '6/11/2018',
       '1/11/2018', '3/11/2018', '8/11/2018', '10/11/2018', '12/11/2018',
       '9/11/2018', '11/11/2018', '14/11/2018', '17/11/2018',
       '16/11/2018', '15/11/2018', '18/11/2018', '13/11/2018',
       '20/11/2018', '21/11/2018', '26/11/2018', '24/11/2018',
       '23/11/2018', '22/11/2018', '27/11/2018', '28/11/2018',
       '29/11/2018', '25/11/2018', '30/11/2018', '1/12/2018',
       '19/11/2018', '2/12/2018', '4/12/2018', '3/12/2018', '5/12/2018',
       '6/12/2018', '8/12/2018', '7/12/2018', '10/12/2018', '11/12/2018',
       '13/12/2018', '9/12/2018', '12/12/2018', '16/12/2018',
       '14/12/2018', '17/12/2018', '19/12/2018', '20/12/2018',
       '23/12/2018', '18/12/2018', '24/12/2018', '21/12/2018',
       '26/12/2018', '25/12/2018', '27/12/2018', '22/12/2018',
       '15/12/2018', '29/12/2018', '30/12/2018', '28/12/2018',
       '31/12/2018', '2/1/2019', '1/1/2019', '3/1/2019', '4/1/2019',
       '7/1/2019', '5/1/2019', '8/1/2019', '6/1/2019', '9/1/2019',
       '10/1/2019', '13/1/2019', '12/1/2019', '11/1/2019', '15/1/2019',
       '14/1/2019', '17/1/2019', '19/1/2019', '16/1/2019', '18/1/2019',
       '21/1/2019', '20/1/2019', '23/1/2019', '24/1/2019', '22/1/2019',
       '25/1/2019', '27/1/2019', '26/1/2019', '30/1/2019', '28/1/2019',
       '1/2/2019', '31/1/2019', '29/1/2019', '3/2/2019', '5/2/2019',
       '6/2/2019', '4/2/2019', '7/2/2019', '8/2/2019', '9/2/2019',
       '11/2/2019', '12/2/2019', '13/2/2019', '14/2/2019', '2/2/2019',
       '17/2/2019', '16/2/2019', '19/2/2019', '20/2/2019', '10/2/2019',
       '15/2/2019', '21/2/2019', '23/2/2019', '18/2/2019', '22/2/2019',
       '24/2/2019', '25/2/2019', '1/3/2019', '28/2/2019', '26/2/2019',
       '3/3/2019', '4/3/2019', '27/2/2019', '5/3/2019', '2/3/2019',
       '6/3/2019', '8/3/2019', '9/3/2019', '10/3/2019', '7/3/2019',
       '11/3/2019', '14/3/2019', '13/3/2019', '16/3/2019', '12/3/2019',
       '17/3/2019', '19/3/2019', '15/3/2019', '20/3/2019', '18/3/2019',
       '23/3/2019', '22/3/2019', '27/3/2019', '24/3/2019', '28/3/2019',
       '25/3/2019', '21/3/2019', '30/3/2019', '31/3/2019', '1/4/2019',
       '3/4/2019', '26/3/2019', '2/4/2019', '5/4/2019', '6/4/2019',
       '8/4/2019', '29/3/2019', '4/4/2019', '9/4/2019', '7/4/2019',
       '10/4/2019', '12/4/2019', '14/4/2019', '16/4/2019', '17/4/2019',
       '18/4/2019', '13/4/2019', '15/4/2019', '19/4/2019', '20/4/2019',
       '23/4/2019', '21/4/2019', '11/4/2019', '24/4/2019', '22/4/2019',
       '29/4/2019', '26/4/2019', '25/4/2019', '1/5/2019', '27/4/2019',
       '3/5/2019', '30/4/2019', '5/5/2019', '6/5/2019', '2/5/2019',
       '7/5/2019', '8/5/2019', '10/5/2019', '12/5/2019', '4/5/2019',
       '13/5/2019', '11/5/2019', '9/5/2019', '28/4/2019', '16/5/2019',
       '15/5/2019', '18/5/2019', '20/5/2019', '14/5/2019', '17/5/2019',
       '19/5/2019', '23/5/2019', '24/5/2019', '25/5/2019', '21/5/2019',
       '26/5/2019', '27/5/2019', '30/5/2019', '22/5/2019', '29/5/2019',
       '28/5/2019', '3/6/2019', '2/6/2019', '1/6/2019', '31/5/2019',
       '5/6/2019', '8/6/2019', '4/6/2019', '6/6/2019', '12/6/2019',
       '9/6/2019', '14/6/2019', '7/6/2019', '13/6/2019', '10/6/2019',
       '16/6/2019', '15/6/2019', '17/6/2019', '11/6/2019', '18/6/2019',
       '20/6/2019', '22/6/2019', '26/6/2019', '27/6/2019', '25/6/2019',
       '21/6/2019', '28/6/2019', '30/6/2019', '19/6/2019', '23/6/2019',
       '3/7/2019', '2/7/2019', '24/6/2019', '8/7/2019', '1/7/2019',
       '9/7/2019', '29/6/2019', '5/7/2019', '10/7/2019', '6/7/2019',
       '11/7/2019', '7/7/2019', '12/7/2019', '14/7/2019', '16/7/2019',
       '4/7/2019', '17/7/2019', '21/7/2019', '13/7/2019', '15/7/2019',
       '20/7/2019', '19/7/2019', '22/7/2019', '26/7/2019', '24/7/2019',
       '25/7/2019', '27/7/2019', '18/7/2019', '28/7/2019', '23/7/2019',
       '31/7/2019', '29/7/2019', '2/8/2019', '3/8/2019', '4/8/2019',
       '1/8/2019', '30/7/2019', '5/8/2019', '7/8/2019', '8/8/2019',
       '9/8/2019', '12/8/2019', '13/8/2019', '11/8/2019', '15/8/2019',
       '14/8/2019', '17/8/2019', '18/8/2019', '10/8/2019', '16/8/2019',
       '6/8/2019', '19/8/2019', '21/8/2019', '20/8/2019', '25/8/2019',
       '24/8/2019', '27/8/2019', '29/8/2019', '26/8/2019', '22/8/2019',
       '28/8/2019', '23/8/2019', '30/8/2019', '31/8/2019', '3/9/2019',
       '1/9/2019', '5/9/2019', '6/9/2019', '4/9/2019', '2/9/2019',
       '11/9/2019', '7/9/2019', '9/9/2019', '10/9/2019', '14/9/2019',
       '15/9/2019', '13/9/2019', '8/9/2019', '18/9/2019', '12/9/2019',
       '22/9/2019', '19/9/2019', '16/9/2019', '17/9/2019', '21/9/2019',
       '25/9/2019', '20/9/2019', '23/9/2019', '27/9/2019', '26/9/2019',
       '29/9/2019', '1/10/2019', '24/9/2019', '4/10/2019', '6/10/2019',
       '28/9/2019', '7/10/2019', '2/10/2019', '5/10/2019', '9/10/2019',
       '3/10/2019', '8/10/2019', '30/9/2019', '12/10/2019', '10/10/2019',
       '11/10/2019', '15/10/2019', '16/10/2019', '21/10/2019',
       '18/10/2019', '14/10/2019', '20/10/2019', '22/10/2019',
       '17/10/2019', '23/10/2019', '13/10/2019', '24/10/2019',
       '25/10/2019', '19/10/2019', '27/10/2019', '28/10/2019',
       '30/10/2019', '26/10/2019', '31/10/2019', '3/11/2019', '1/11/2019',
       '29/10/2019', '4/11/2019', '6/11/2019', '5/11/2019', '2/11/2019',
       '8/11/2019', '9/11/2019', '10/11/2019', '11/11/2019', '14/11/2019',
       '15/11/2019', '13/11/2019', '16/11/2019', '12/11/2019',
       '7/11/2019', '18/11/2019', '21/11/2019', '23/11/2019',
       '17/11/2019', '22/11/2019', '19/11/2019', '25/11/2019',
       '24/11/2019', '26/11/2019', '27/11/2019', '20/11/2019',
       '29/11/2019', '1/12/2019', '3/12/2019', '2/12/2019', '30/11/2019',
       '28/11/2019', '4/12/2019', '5/12/2019', '8/12/2019', '9/12/2019',
       '7/12/2019', '10/12/2019', '12/12/2019', '13/12/2019', '6/12/2019',
       '15/12/2019', '17/12/2019', '14/12/2019', '18/12/2019',
       '16/12/2019', '20/12/2019', '11/12/2019', '19/12/2019',
       '22/12/2019', '21/12/2019', '24/12/2019', '23/12/2019',
       '26/12/2019', '25/12/2019', '29/12/2019', '30/12/2019',
       '28/12/2019', '31/12/2019', '2/1/2020', '3/1/2020', '27/12/2019',
       '6/1/2020', '8/1/2020', '1/1/2020', '7/1/2020', '4/1/2020',
       '9/1/2020', '10/1/2020', '11/1/2020', '12/1/2020', '5/1/2020',
       '13/1/2020', '16/1/2020', '18/1/2020', '19/1/2020', '20/1/2020',
       '21/1/2020', '17/1/2020', '15/1/2020', '24/1/2020', '22/1/2020',
       '26/1/2020', '25/1/2020', '14/1/2020', '23/1/2020', '31/1/2020',
       '29/1/2020', '30/1/2020', '27/1/2020', '1/2/2020', '3/2/2020',
       '2/2/2020', '4/2/2020', '28/1/2020', '7/2/2020', '9/2/2020',
       '10/2/2020', '11/2/2020', '12/2/2020', '6/2/2020', '8/2/2020',
       '5/2/2020', '13/2/2020', '17/2/2020', '16/2/2020', '15/2/2020',
       '24/2/2020', '23/2/2020', '19/2/2020', '14/2/2020', '25/2/2020',
       '20/2/2020', '27/2/2020', '22/2/2020', '18/2/2020', '21/2/2020',
       '1/3/2020', '2/3/2020', '3/3/2020', '29/2/2020', '28/2/2020',
       '5/3/2020', '26/2/2020', '7/3/2020', '9/3/2020', '8/3/2020',
       '6/3/2020', '4/3/2020', '12/3/2020', '10/3/2020', '13/3/2020',
       '16/3/2020', '15/3/2020', '14/3/2020', '18/3/2020', '11/3/2020',
       '19/3/2020', '17/3/2020', '23/3/2020', '22/3/2020', '24/3/2020',
       '21/3/2020', '20/3/2020', '26/3/2020', '29/3/2020', '31/3/2020',
       '30/3/2020', '1/4/2020', '28/3/2020', '2/4/2020', '25/3/2020',
       '5/4/2020', '4/4/2020', '6/4/2020', '3/4/2020', '27/3/2020',
       '7/4/2020', '11/4/2020', '10/4/2020', '8/4/2020', '14/4/2020',
       '13/4/2020', '15/4/2020', '12/4/2020', '9/4/2020', '17/4/2020',
       '19/4/2020', '18/4/2020', '20/4/2020', '16/4/2020', '24/4/2020',
       '26/4/2020', '25/4/2020', '21/4/2020', '22/4/2020', '29/4/2020',
       '23/4/2020', '27/4/2020', '30/4/2020', '2/5/2020', '28/4/2020',
       '3/5/2020', '5/5/2020', '4/5/2020', '7/5/2020', '6/5/2020',
       '1/5/2020', '9/5/2020', '11/5/2020', '8/5/2020', '12/5/2020',
       '15/5/2020', '14/5/2020', '10/5/2020', '13/5/2020', '17/5/2020',
       '18/5/2020', '16/5/2020', '19/5/2020', '20/5/2020', '23/5/2020',
       '21/5/2020', '22/5/2020', '25/5/2020', '26/5/2020', '27/5/2020',
       '24/5/2020', '28/5/2020', '29/5/2020', '31/5/2020', '30/5/2020',
       '5/6/2020', '4/6/2020', '1/6/2020', '6/6/2020', '3/6/2020',
       '8/6/2020', '9/6/2020', '11/6/2020', '7/6/2020', '12/6/2020',
       '2/6/2020', '13/6/2020', '10/6/2020', '16/6/2020', '15/6/2020',
       '17/6/2020', '18/6/2020', '19/6/2020', '14/6/2020', '21/6/2020',
       '20/6/2020', '24/6/2020', '22/6/2020', '25/6/2020', '26/6/2020',
       '28/6/2020', '23/6/2020', '27/6/2020', '29/6/2020', '30/6/2020',
       '1/7/2020', '3/7/2020', '5/7/2020', '4/7/2020', '8/7/2020',
       '6/7/2020', '2/7/2020', '7/7/2020', '9/7/2020', '11/7/2020',
       '13/7/2020', '14/7/2020', '15/7/2020', '12/7/2020', '16/7/2020',
       '18/7/2020', '19/7/2020', '17/7/2020', '20/7/2020', '10/7/2020',
       '21/7/2020', '23/7/2020', '22/7/2020', '25/7/2020', '24/7/2020',
       '29/7/2020', '1/8/2020', '27/7/2020', '28/7/2020', '30/7/2020',
       '2/8/2020', '26/7/2020', '3/8/2020', '4/8/2020', '5/8/2020',
       '6/8/2020', '9/8/2020', '10/8/2020', '8/8/2020', '11/8/2020',
       '12/8/2020', '31/7/2020', '13/8/2020', '7/8/2020', '15/8/2020',
       '17/8/2020', '18/8/2020', '14/8/2020', '19/8/2020', '16/8/2020',
       '20/8/2020', '22/8/2020', '23/8/2020', '21/8/2020', '26/8/2020',
       '24/8/2020', '27/8/2020', '25/8/2020', '28/8/2020', '29/8/2020',
       '30/8/2020', '31/8/2020', '3/9/2020', '1/9/2020', '2/9/2020',
       '6/9/2020', '4/9/2020', '7/9/2020', '9/9/2020', '10/9/2020',
       '8/9/2020', '11/9/2020', '14/9/2020', '5/9/2020', '16/9/2020',
       '13/9/2020', '19/9/2020', '12/9/2020', '18/9/2020', '20/9/2020',
       '22/9/2020', '15/9/2020', '17/9/2020', '24/9/2020', '21/9/2020',
       '27/9/2020', '28/9/2020', '25/9/2020', '29/9/2020', '26/9/2020',
       '1/10/2020', '3/10/2020', '30/9/2020', '2/10/2020', '23/9/2020',
       '4/10/2020', '5/10/2020', '10/10/2020', '9/10/2020', '7/10/2020',
       '6/10/2020', '11/10/2020', '12/10/2020', '14/10/2020',
       '13/10/2020', '16/10/2020', '18/10/2020', '19/10/2020',
       '15/10/2020', '8/10/2020', '17/10/2020', '20/10/2020',
       '23/10/2020', '25/10/2020', '21/10/2020', '22/10/2020',
       '26/10/2020', '28/10/2020', '30/10/2020', '24/10/2020',
       '1/11/2020', '27/10/2020', '29/10/2020', '31/10/2020', '4/11/2020',
       '2/11/2020', '8/11/2020', '5/11/2020', '10/11/2020', '9/11/2020',
       '6/11/2020', '7/11/2020', '11/11/2020', '3/11/2020', '13/11/2020',
       '17/11/2020', '16/11/2020', '14/11/2020', '19/11/2020',
       '15/11/2020', '12/11/2020', '20/11/2020', '22/11/2020',
       '21/11/2020', '18/11/2020', '26/11/2020', '23/11/2020',
       '27/11/2020', '25/11/2020', '24/11/2020', '28/11/2020',
       '29/11/2020', '30/11/2020', '1/12/2020', '2/12/2020', '4/12/2020',
       '7/12/2020', '3/12/2020', '9/12/2020', '6/12/2020', '5/12/2020',
       '10/12/2020', '11/12/2020', '8/12/2020', '12/12/2020',
       '13/12/2020', '15/12/2020', '14/12/2020', '18/12/2020',
       '16/12/2020', '19/12/2020', '20/12/2020', '17/12/2020',
       '24/12/2020', '26/12/2020', '22/12/2020', '21/12/2020',
       '25/12/2020', '23/12/2020', '27/12/2020', '31/12/2020',
       '30/12/2020', '28/12/2020', '1/1/2021', '29/12/2020', '3/1/2021',
       '2/1/2021', '6/1/2021', '7/1/2021', '10/1/2021', '9/1/2021',
       '5/1/2021', '11/1/2021', '13/1/2021', '8/1/2021', '12/1/2021',
       '14/1/2021', '4/1/2021', '15/1/2021', '17/1/2021', '20/1/2021',
       '16/1/2021', '19/1/2021', '18/1/2021', '21/1/2021', '22/1/2021',
       '24/1/2021', '23/1/2021'], dtype=object)

In [10]:
df['delivery_date'].unique()

array(['19/6/18', '2/7/2018', '1/7/2018', '7/6/2018', '26/6/18',
       '13/6/18', '14/6/18', '21/6/18', '20/6/18', '17/6/18', '15/6/18',
       '27/6/18', '16/6/18', '28/6/18', '24/6/18', '6/7/2018', '29/6/18',
       '22/6/18', '5/7/2018', '10/6/2018', '10/7/2018', '8/7/2018',
       '3/7/2018', '4/7/2018', '7/7/2018', '18/6/18', '23/6/18',
       '12/6/2018', '25/6/18', '9/7/2018', '13/7/18', '16/7/18',
       '14/7/18', '18/7/18', '30/6/18', '20/7/18', '12/7/2018', '15/7/18',
       '17/7/18', '24/7/18', '19/7/18', '11/7/2018', '26/7/18', '21/7/18',
       '22/7/18', '25/7/18', '3/8/2018', '23/7/18', '27/7/18', '1/8/2018',
       '29/7/18', '6/8/2018', '28/7/18', '8/8/2018', '31/7/18',
       '9/8/2018', '12/8/2018', '4/8/2018', '30/7/18', '5/8/2018',
       '13/8/18', '7/8/2018', '2/8/2018', '11/8/2018', '15/8/18',
       '17/8/18', '10/8/2018', '21/8/18', '20/8/18', '16/8/18', '22/8/18',
       '18/8/18', '19/8/18', '14/8/18', '24/8/18', '25/8/18', '26/8/18',
       '27/8/18', '23/8/18', '28/8/18', '29/8/18', '30/8/18', '2/9/2018',
       '1/9/2018', '4/9/2018', '3/9/2018', '5/9/2018', '8/9/2018',
       '6/9/2018', '31/8/18', '7/9/2018', '11/9/2018', '9/9/2018',
       '10/9/2018', '13/9/18', '12/9/2018', '14/9/18', '16/9/18',
       '18/9/18', '17/9/18', '20/9/18', '19/9/18', '24/9/18', '21/9/18',
       '23/9/18', '15/9/18', '22/9/18', '26/9/18', '25/9/18', '28/9/18',
       '29/9/18', '27/9/18', '3/10/2018', '30/9/18', '2/10/2018',
       '1/10/2018', '8/10/2018', '6/10/2018', '7/10/2018', '4/10/2018',
       '10/10/2018', '9/10/2018', '11/10/2018', '19/10/18', '12/10/2018',
       '15/10/18', '13/10/18', '5/10/2018', '18/10/18', '21/10/18',
       '17/10/18', '16/10/18', '14/10/18', '24/10/18', '26/10/18',
       '22/10/18', '25/10/18', '23/10/18', '28/10/18', '30/10/18',
       '31/10/18', '3/11/2018', '29/10/18', '27/10/18', '2/11/2018',
       '20/10/18', '6/11/2018', '1/11/2018', '14/11/18', '4/11/2018',
       '9/11/2018', '5/11/2018', '13/11/18', '7/11/2018', '15/11/18',
       '12/11/2018', '11/11/2018', '8/11/2018', '17/11/18', '10/11/2018',
       '20/11/18', '23/11/18', '18/11/18', '16/11/18', '19/11/18',
       '24/11/18', '22/11/18', '27/11/18', '21/11/18', '25/11/18',
       '26/11/18', '30/11/18', '1/12/2018', '3/12/2018', '28/11/18',
       '29/11/18', '5/12/2018', '2/12/2018', '7/12/2018', '10/12/2018',
       '4/12/2018', '12/12/2018', '6/12/2018', '8/12/2018', '14/12/18',
       '15/12/18', '19/12/18', '16/12/18', '13/12/18', '22/12/18',
       '11/12/2018', '18/12/18', '17/12/18', '24/12/18', '23/12/18',
       '9/12/2018', '27/12/18', '25/12/18', '20/12/18', '29/12/18',
       '21/12/18', '26/12/18', '3/1/2019', '2/1/2019', '30/12/18',
       '28/12/18', '5/1/2019', '4/1/2019', '8/1/2019', '6/1/2019',
       '7/1/2019', '11/1/2019', '31/12/18', '13/1/19', '1/1/2019',
       '9/1/2019', '10/1/2019', '14/1/19', '12/1/2019', '17/1/19',
       '15/1/19', '21/1/19', '22/1/19', '24/1/19', '20/1/19', '16/1/19',
       '23/1/19', '19/1/19', '26/1/19', '18/1/19', '31/1/19', '28/1/19',
       '27/1/19', '25/1/19', '30/1/19', '29/1/19', '3/2/2019', '4/2/2019',
       '1/2/2019', '7/2/2019', '10/2/2019', '2/2/2019', '11/2/2019',
       '5/2/2019', '9/2/2019', '13/2/19', '8/2/2019', '12/2/2019',
       '17/2/19', '6/2/2019', '15/2/19', '19/2/19', '14/2/19', '23/2/19',
       '18/2/19', '24/2/19', '16/2/19', '26/2/19', '25/2/19', '20/2/19',
       '5/3/2019', '27/2/19', '4/3/2019', '28/2/19', '1/3/2019',
       '21/2/19', '7/3/2019', '3/3/2019', '2/3/2019', '10/3/2019',
       '8/3/2019', '9/3/2019', '6/3/2019', '13/3/19', '18/3/19',
       '12/3/2019', '14/3/19', '15/3/19', '16/3/19', '22/3/19', '17/3/19',
       '11/3/2019', '27/3/19', '19/3/19', '20/3/19', '25/3/19', '21/3/19',
       '26/3/19', '28/3/19', '6/4/2019', '24/3/19', '3/4/2019', '31/3/19',
       '2/4/2019', '1/4/2019', '23/3/19', '4/4/2019', '7/4/2019',
       '29/3/19', '5/4/2019', '30/3/19', '8/4/2019', '9/4/2019',
       '12/4/2019', '14/4/19', '13/4/19', '11/4/2019', '15/4/19',
       '18/4/19', '17/4/19', '23/4/19', '19/4/19', '24/4/19', '27/4/19',
       '10/4/2019', '22/4/19', '20/4/19', '30/4/19', '26/4/19', '28/4/19',
       '21/4/19', '16/4/19', '1/5/2019', '25/4/19', '5/5/2019', '29/4/19',
       '6/5/2019', '9/5/2019', '8/5/2019', '4/5/2019', '2/5/2019',
       '3/5/2019', '10/5/2019', '11/5/2019', '13/5/19', '12/5/2019',
       '18/5/19', '14/5/19', '20/5/19', '7/5/2019', '16/5/19', '17/5/19',
       '15/5/19', '23/5/19', '19/5/19', '24/5/19', '26/5/19', '22/5/19',
       '29/5/19', '25/5/19', '30/5/19', '21/5/19', '27/5/19', '31/5/19',
       '4/6/2019', '3/6/2019', '2/6/2019', '28/5/19', '1/6/2019',
       '7/6/2019', '5/6/2019', '11/6/2019', '8/6/2019', '6/6/2019',
       '9/6/2019', '12/6/2019', '10/6/2019', '14/6/19', '18/6/19',
       '15/6/19', '16/6/19', '19/6/19', '24/6/19', '22/6/19', '13/6/19',
       '27/6/19', '25/6/19', '17/6/19', '20/6/19', '23/6/19', '21/6/19',
       '26/6/19', '29/6/19', '3/7/2019', '4/7/2019', '1/7/2019',
       '28/6/19', '8/7/2019', '30/6/19', '2/7/2019', '5/7/2019',
       '6/7/2019', '12/7/2019', '7/7/2019', '9/7/2019', '11/7/2019',
       '15/7/19', '14/7/19', '18/7/19', '13/7/19', '10/7/2019', '19/7/19',
       '17/7/19', '20/7/19', '23/7/19', '16/7/19', '22/7/19', '24/7/19',
       '30/7/19', '21/7/19', '26/7/19', '28/7/19', '25/7/19', '29/7/19',
       '31/7/19', '2/8/2019', '27/7/19', '1/8/2019', '4/8/2019',
       '3/8/2019', '5/8/2019', '6/8/2019', '8/8/2019', '12/8/2019',
       '7/8/2019', '15/8/19', '11/8/2019', '14/8/19', '13/8/19',
       '9/8/2019', '10/8/2019', '17/8/19', '21/8/19', '16/8/19',
       '19/8/19', '23/8/19', '28/8/19', '26/8/19', '18/8/19', '20/8/19',
       '22/8/19', '24/8/19', '30/8/19', '29/8/19', '25/8/19', '27/8/19',
       '31/8/19', '2/9/2019', '4/9/2019', '7/9/2019', '1/9/2019',
       '3/9/2019', '10/9/2019', '5/9/2019', '8/9/2019', '12/9/2019',
       '13/9/19', '16/9/19', '11/9/2019', '6/9/2019', '15/9/19',
       '14/9/19', '18/9/19', '19/9/19', '20/9/19', '9/9/2019', '17/9/19',
       '21/9/19', '22/9/19', '25/9/19', '23/9/19', '30/9/19', '24/9/19',
       '27/9/19', '28/9/19', '1/10/2019', '26/9/19', '5/10/2019',
       '4/10/2019', '3/10/2019', '2/10/2019', '7/10/2019', '29/9/19',
       '6/10/2019', '16/10/19', '9/10/2019', '10/10/2019', '8/10/2019',
       '13/10/19', '15/10/19', '11/10/2019', '18/10/19', '12/10/2019',
       '20/10/19', '19/10/19', '17/10/19', '24/10/19', '23/10/19',
       '26/10/19', '21/10/19', '1/11/2019', '30/10/19', '29/10/19',
       '14/10/19', '2/11/2019', '22/10/19', '25/10/19', '28/10/19',
       '27/10/19', '4/11/2019', '6/11/2019', '31/10/19', '7/11/2019',
       '3/11/2019', '5/11/2019', '11/11/2019', '8/11/2019', '16/11/19',
       '10/11/2019', '14/11/19', '9/11/2019', '15/11/19', '13/11/19',
       '12/11/2019', '18/11/19', '23/11/19', '22/11/19', '26/11/19',
       '19/11/19', '21/11/19', '24/11/19', '20/11/19', '25/11/19',
       '30/11/19', '28/11/19', '1/12/2019', '3/12/2019', '29/11/19',
       '17/11/19', '27/11/19', '7/12/2019', '9/12/2019', '4/12/2019',
       '11/12/2019', '5/12/2019', '12/12/2019', '10/12/2019', '2/12/2019',
       '6/12/2019', '13/12/19', '18/12/19', '16/12/19', '17/12/19',
       '19/12/19', '20/12/19', '15/12/19', '8/12/2019', '14/12/19',
       '23/12/19', '22/12/19', '21/12/19', '25/12/19', '27/12/19',
       '26/12/19', '24/12/19', '31/12/19', '29/12/19', '28/12/19',
       '30/12/19', '3/1/2020', '4/1/2020', '2/1/2020', '1/1/2020',
       '9/1/2020', '8/1/2020', '6/1/2020', '7/1/2020', '5/1/2020',
       '16/1/20', '17/1/20', '10/1/2020', '15/1/20', '18/1/20', '13/1/20',
       '11/1/2020', '14/1/20', '19/1/20', '22/1/20', '24/1/20', '23/1/20',
       '26/1/20', '28/1/20', '30/1/20', '21/1/20', '12/1/2020', '29/1/20',
       '27/1/20', '25/1/20', '20/1/20', '2/2/2020', '31/1/20', '7/2/2020',
       '1/2/2020', '4/2/2020', '6/2/2020', '10/2/2020', '3/2/2020',
       '5/2/2020', '13/2/20', '9/2/2020', '8/2/2020', '11/2/2020',
       '12/2/2020', '15/2/20', '14/2/20', '16/2/20', '19/2/20', '17/2/20',
       '18/2/20', '21/2/20', '23/2/20', '20/2/20', '22/2/20', '26/2/20',
       '4/3/2020', '1/3/2020', '29/2/20', '28/2/20', '24/2/20',
       '2/3/2020', '25/2/20', '5/3/2020', '27/2/20', '6/3/2020',
       '7/3/2020', '11/3/2020', '9/3/2020', '3/3/2020', '13/3/20',
       '8/3/2020', '15/3/20', '14/3/20', '16/3/20', '17/3/20',
       '10/3/2020', '21/3/20', '12/3/2020', '18/3/20', '19/3/20',
       '20/3/20', '24/3/20', '25/3/20', '23/3/20', '22/3/20', '27/3/20',
       '29/3/20', '26/3/20', '1/4/2020', '28/3/20', '30/3/20', '7/4/2020',
       '4/4/2020', '5/4/2020', '31/3/20', '3/4/2020', '8/4/2020',
       '12/4/2020', '2/4/2020', '13/4/20', '11/4/2020', '6/4/2020',
       '9/4/2020', '10/4/2020', '16/4/20', '17/4/20', '15/4/20',
       '18/4/20', '14/4/20', '25/4/20', '19/4/20', '21/4/20', '22/4/20',
       '20/4/20', '24/4/20', '26/4/20', '23/4/20', '30/4/20', '27/4/20',
       '29/4/20', '1/5/2020', '2/5/2020', '3/5/2020', '28/4/20',
       '4/5/2020', '5/5/2020', '12/5/2020', '8/5/2020', '9/5/2020',
       '7/5/2020', '10/5/2020', '14/5/20', '11/5/2020', '13/5/20',
       '6/5/2020', '19/5/20', '16/5/20', '17/5/20', '25/5/20', '20/5/20',
       '22/5/20', '18/5/20', '21/5/20', '23/5/20', '27/5/20', '26/5/20',
       '29/5/20', '24/5/20', '30/5/20', '4/6/2020', '28/5/20', '31/5/20',
       '3/6/2020', '1/6/2020', '6/6/2020', '15/5/20', '7/6/2020',
       '9/6/2020', '5/6/2020', '13/6/20', '8/6/2020', '10/6/2020',
       '14/6/20', '17/6/20', '12/6/2020', '16/6/20', '11/6/2020',
       '22/6/20', '18/6/20', '2/6/2020', '15/6/20', '23/6/20', '21/6/20',
       '25/6/20', '19/6/20', '26/6/20', '24/6/20', '1/7/2020', '27/6/20',
       '20/6/20', '28/6/20', '29/6/20', '30/6/20', '3/7/2020', '6/7/2020',
       '5/7/2020', '2/7/2020', '10/7/2020', '4/7/2020', '9/7/2020',
       '12/7/2020', '14/7/20', '7/7/2020', '17/7/20', '8/7/2020',
       '16/7/20', '18/7/20', '11/7/2020', '13/7/20', '19/7/20', '23/7/20',
       '25/7/20', '15/7/20', '24/7/20', '27/7/20', '20/7/20', '26/7/20',
       '30/7/20', '22/7/20', '21/7/20', '31/7/20', '29/7/20', '4/8/2020',
       '28/7/20', '1/8/2020', '11/8/2020', '5/8/2020', '2/8/2020',
       '6/8/2020', '3/8/2020', '9/8/2020', '10/8/2020', '12/8/2020',
       '13/8/20', '8/8/2020', '7/8/2020', '16/8/20', '14/8/20', '17/8/20',
       '19/8/20', '21/8/20', '20/8/20', '15/8/20', '18/8/20', '25/8/20',
       '22/8/20', '26/8/20', '23/8/20', '29/8/20', '24/8/20', '30/8/20',
       '3/9/2020', '2/9/2020', '28/8/20', '7/9/2020', '5/9/2020',
       '1/9/2020', '31/8/20', '27/8/20', '8/9/2020', '4/9/2020',
       '6/9/2020', '12/9/2020', '9/9/2020', '15/9/20', '10/9/2020',
       '16/9/20', '18/9/20', '13/9/20', '22/9/20', '19/9/20', '24/9/20',
       '21/9/20', '23/9/20', '11/9/2020', '14/9/20', '20/9/20', '17/9/20',
       '25/9/20', '28/9/20', '29/9/20', '26/9/20', '27/9/20', '5/10/2020',
       '7/10/2020', '1/10/2020', '30/9/20', '6/10/2020', '4/10/2020',
       '2/10/2020', '11/10/2020', '13/10/20', '9/10/2020', '3/10/2020',
       '10/10/2020', '16/10/20', '12/10/2020', '8/10/2020', '19/10/20',
       '22/10/20', '21/10/20', '14/10/20', '15/10/20', '23/10/20',
       '17/10/20', '26/10/20', '25/10/20', '27/10/20', '20/10/20',
       '24/10/20', '18/10/20', '29/10/20', '28/10/20', '1/11/2020',
       '31/10/20', '3/11/2020', '4/11/2020', '7/11/2020', '30/10/20',
       '2/11/2020', '8/11/2020', '6/11/2020', '14/11/20', '13/11/20',
       '5/11/2020', '18/11/20', '15/11/20', '17/11/20', '16/11/20',
       '11/11/2020', '9/11/2020', '21/11/20', '12/11/2020', '10/11/2020',
       '23/11/20', '22/11/20', '19/11/20', '20/11/20', '30/11/20',
       '27/11/20', '26/11/20', '2/12/2020', '3/12/2020', '1/12/2020',
       '7/12/2020', '24/11/20', '29/11/20', '28/11/20', '5/12/2020',
       '9/12/2020', '10/12/2020', '25/11/20', '11/12/2020', '8/12/2020',
       '6/12/2020', '17/12/20', '4/12/2020', '18/12/20', '15/12/20',
       '16/12/20', '13/12/20', '12/12/2020', '14/12/20', '19/12/20',
       '20/12/20', '24/12/20', '21/12/20', '22/12/20', '27/12/20',
       '26/12/20', '30/12/20', '28/12/20', '1/1/2021', '29/12/20',
       '4/1/2021', '25/12/20', '31/12/20', '7/1/2021', '23/12/20',
       '6/1/2021', '5/1/2021', '11/1/2021', '9/1/2021', '14/1/21',
       '12/1/2021', '8/1/2021', '3/1/2021', '17/1/21', '10/1/2021',
       '2/1/2021', '15/1/21', '20/1/21', '13/1/21', '16/1/21', '19/1/21',
       '21/1/21', '23/1/21', '18/1/21', '24/1/21', '30/1/21', '22/1/21',
       '25/1/21', '28/1/21', '29/1/21', '27/1/21', '26/1/21', '2/2/2021'],
      dtype=object)

In [11]:
def fix_dates(date):
    parts = date.split('/')
    if len(parts[-1]) == 2:  # 2-digit year
        parts[-1] = '20' + parts[-1]
    return '/'.join(str(int(part)) for part in parts)  # Remove leading zeros

df['delivery_date'] = df['delivery_date'].apply(fix_dates)

df['delivery_date'].unique()

array(['19/6/2018', '2/7/2018', '1/7/2018', '7/6/2018', '26/6/2018',
       '13/6/2018', '14/6/2018', '21/6/2018', '20/6/2018', '17/6/2018',
       '15/6/2018', '27/6/2018', '16/6/2018', '28/6/2018', '24/6/2018',
       '6/7/2018', '29/6/2018', '22/6/2018', '5/7/2018', '10/6/2018',
       '10/7/2018', '8/7/2018', '3/7/2018', '4/7/2018', '7/7/2018',
       '18/6/2018', '23/6/2018', '12/6/2018', '25/6/2018', '9/7/2018',
       '13/7/2018', '16/7/2018', '14/7/2018', '18/7/2018', '30/6/2018',
       '20/7/2018', '12/7/2018', '15/7/2018', '17/7/2018', '24/7/2018',
       '19/7/2018', '11/7/2018', '26/7/2018', '21/7/2018', '22/7/2018',
       '25/7/2018', '3/8/2018', '23/7/2018', '27/7/2018', '1/8/2018',
       '29/7/2018', '6/8/2018', '28/7/2018', '8/8/2018', '31/7/2018',
       '9/8/2018', '12/8/2018', '4/8/2018', '30/7/2018', '5/8/2018',
       '13/8/2018', '7/8/2018', '2/8/2018', '11/8/2018', '15/8/2018',
       '17/8/2018', '10/8/2018', '21/8/2018', '20/8/2018', '16/8/2018',
       '22/8/2018', '18/8/2018', '19/8/2018', '14/8/2018', '24/8/2018',
       '25/8/2018', '26/8/2018', '27/8/2018', '23/8/2018', '28/8/2018',
       '29/8/2018', '30/8/2018', '2/9/2018', '1/9/2018', '4/9/2018',
       '3/9/2018', '5/9/2018', '8/9/2018', '6/9/2018', '31/8/2018',
       '7/9/2018', '11/9/2018', '9/9/2018', '10/9/2018', '13/9/2018',
       '12/9/2018', '14/9/2018', '16/9/2018', '18/9/2018', '17/9/2018',
       '20/9/2018', '19/9/2018', '24/9/2018', '21/9/2018', '23/9/2018',
       '15/9/2018', '22/9/2018', '26/9/2018', '25/9/2018', '28/9/2018',
       '29/9/2018', '27/9/2018', '3/10/2018', '30/9/2018', '2/10/2018',
       '1/10/2018', '8/10/2018', '6/10/2018', '7/10/2018', '4/10/2018',
       '10/10/2018', '9/10/2018', '11/10/2018', '19/10/2018',
       '12/10/2018', '15/10/2018', '13/10/2018', '5/10/2018',
       '18/10/2018', '21/10/2018', '17/10/2018', '16/10/2018',
       '14/10/2018', '24/10/2018', '26/10/2018', '22/10/2018',
       '25/10/2018', '23/10/2018', '28/10/2018', '30/10/2018',
       '31/10/2018', '3/11/2018', '29/10/2018', '27/10/2018', '2/11/2018',
       '20/10/2018', '6/11/2018', '1/11/2018', '14/11/2018', '4/11/2018',
       '9/11/2018', '5/11/2018', '13/11/2018', '7/11/2018', '15/11/2018',
       '12/11/2018', '11/11/2018', '8/11/2018', '17/11/2018',
       '10/11/2018', '20/11/2018', '23/11/2018', '18/11/2018',
       '16/11/2018', '19/11/2018', '24/11/2018', '22/11/2018',
       '27/11/2018', '21/11/2018', '25/11/2018', '26/11/2018',
       '30/11/2018', '1/12/2018', '3/12/2018', '28/11/2018', '29/11/2018',
       '5/12/2018', '2/12/2018', '7/12/2018', '10/12/2018', '4/12/2018',
       '12/12/2018', '6/12/2018', '8/12/2018', '14/12/2018', '15/12/2018',
       '19/12/2018', '16/12/2018', '13/12/2018', '22/12/2018',
       '11/12/2018', '18/12/2018', '17/12/2018', '24/12/2018',
       '23/12/2018', '9/12/2018', '27/12/2018', '25/12/2018',
       '20/12/2018', '29/12/2018', '21/12/2018', '26/12/2018', '3/1/2019',
       '2/1/2019', '30/12/2018', '28/12/2018', '5/1/2019', '4/1/2019',
       '8/1/2019', '6/1/2019', '7/1/2019', '11/1/2019', '31/12/2018',
       '13/1/2019', '1/1/2019', '9/1/2019', '10/1/2019', '14/1/2019',
       '12/1/2019', '17/1/2019', '15/1/2019', '21/1/2019', '22/1/2019',
       '24/1/2019', '20/1/2019', '16/1/2019', '23/1/2019', '19/1/2019',
       '26/1/2019', '18/1/2019', '31/1/2019', '28/1/2019', '27/1/2019',
       '25/1/2019', '30/1/2019', '29/1/2019', '3/2/2019', '4/2/2019',
       '1/2/2019', '7/2/2019', '10/2/2019', '2/2/2019', '11/2/2019',
       '5/2/2019', '9/2/2019', '13/2/2019', '8/2/2019', '12/2/2019',
       '17/2/2019', '6/2/2019', '15/2/2019', '19/2/2019', '14/2/2019',
       '23/2/2019', '18/2/2019', '24/2/2019', '16/2/2019', '26/2/2019',
       '25/2/2019', '20/2/2019', '5/3/2019', '27/2/2019', '4/3/2019',
       '28/2/2019', '1/3/2019', '21/2/2019', '7/3/2019', '3/3/2019',
       '2/3/2019', '10/3/2019', '8/3/2019', '9/3/2019', '6/3/2019',
       '13/3/2019', '18/3/2019', '12/3/2019', '14/3/2019', '15/3/2019',
       '16/3/2019', '22/3/2019', '17/3/2019', '11/3/2019', '27/3/2019',
       '19/3/2019', '20/3/2019', '25/3/2019', '21/3/2019', '26/3/2019',
       '28/3/2019', '6/4/2019', '24/3/2019', '3/4/2019', '31/3/2019',
       '2/4/2019', '1/4/2019', '23/3/2019', '4/4/2019', '7/4/2019',
       '29/3/2019', '5/4/2019', '30/3/2019', '8/4/2019', '9/4/2019',
       '12/4/2019', '14/4/2019', '13/4/2019', '11/4/2019', '15/4/2019',
       '18/4/2019', '17/4/2019', '23/4/2019', '19/4/2019', '24/4/2019',
       '27/4/2019', '10/4/2019', '22/4/2019', '20/4/2019', '30/4/2019',
       '26/4/2019', '28/4/2019', '21/4/2019', '16/4/2019', '1/5/2019',
       '25/4/2019', '5/5/2019', '29/4/2019', '6/5/2019', '9/5/2019',
       '8/5/2019', '4/5/2019', '2/5/2019', '3/5/2019', '10/5/2019',
       '11/5/2019', '13/5/2019', '12/5/2019', '18/5/2019', '14/5/2019',
       '20/5/2019', '7/5/2019', '16/5/2019', '17/5/2019', '15/5/2019',
       '23/5/2019', '19/5/2019', '24/5/2019', '26/5/2019', '22/5/2019',
       '29/5/2019', '25/5/2019', '30/5/2019', '21/5/2019', '27/5/2019',
       '31/5/2019', '4/6/2019', '3/6/2019', '2/6/2019', '28/5/2019',
       '1/6/2019', '7/6/2019', '5/6/2019', '11/6/2019', '8/6/2019',
       '6/6/2019', '9/6/2019', '12/6/2019', '10/6/2019', '14/6/2019',
       '18/6/2019', '15/6/2019', '16/6/2019', '19/6/2019', '24/6/2019',
       '22/6/2019', '13/6/2019', '27/6/2019', '25/6/2019', '17/6/2019',
       '20/6/2019', '23/6/2019', '21/6/2019', '26/6/2019', '29/6/2019',
       '3/7/2019', '4/7/2019', '1/7/2019', '28/6/2019', '8/7/2019',
       '30/6/2019', '2/7/2019', '5/7/2019', '6/7/2019', '12/7/2019',
       '7/7/2019', '9/7/2019', '11/7/2019', '15/7/2019', '14/7/2019',
       '18/7/2019', '13/7/2019', '10/7/2019', '19/7/2019', '17/7/2019',
       '20/7/2019', '23/7/2019', '16/7/2019', '22/7/2019', '24/7/2019',
       '30/7/2019', '21/7/2019', '26/7/2019', '28/7/2019', '25/7/2019',
       '29/7/2019', '31/7/2019', '2/8/2019', '27/7/2019', '1/8/2019',
       '4/8/2019', '3/8/2019', '5/8/2019', '6/8/2019', '8/8/2019',
       '12/8/2019', '7/8/2019', '15/8/2019', '11/8/2019', '14/8/2019',
       '13/8/2019', '9/8/2019', '10/8/2019', '17/8/2019', '21/8/2019',
       '16/8/2019', '19/8/2019', '23/8/2019', '28/8/2019', '26/8/2019',
       '18/8/2019', '20/8/2019', '22/8/2019', '24/8/2019', '30/8/2019',
       '29/8/2019', '25/8/2019', '27/8/2019', '31/8/2019', '2/9/2019',
       '4/9/2019', '7/9/2019', '1/9/2019', '3/9/2019', '10/9/2019',
       '5/9/2019', '8/9/2019', '12/9/2019', '13/9/2019', '16/9/2019',
       '11/9/2019', '6/9/2019', '15/9/2019', '14/9/2019', '18/9/2019',
       '19/9/2019', '20/9/2019', '9/9/2019', '17/9/2019', '21/9/2019',
       '22/9/2019', '25/9/2019', '23/9/2019', '30/9/2019', '24/9/2019',
       '27/9/2019', '28/9/2019', '1/10/2019', '26/9/2019', '5/10/2019',
       '4/10/2019', '3/10/2019', '2/10/2019', '7/10/2019', '29/9/2019',
       '6/10/2019', '16/10/2019', '9/10/2019', '10/10/2019', '8/10/2019',
       '13/10/2019', '15/10/2019', '11/10/2019', '18/10/2019',
       '12/10/2019', '20/10/2019', '19/10/2019', '17/10/2019',
       '24/10/2019', '23/10/2019', '26/10/2019', '21/10/2019',
       '1/11/2019', '30/10/2019', '29/10/2019', '14/10/2019', '2/11/2019',
       '22/10/2019', '25/10/2019', '28/10/2019', '27/10/2019',
       '4/11/2019', '6/11/2019', '31/10/2019', '7/11/2019', '3/11/2019',
       '5/11/2019', '11/11/2019', '8/11/2019', '16/11/2019', '10/11/2019',
       '14/11/2019', '9/11/2019', '15/11/2019', '13/11/2019',
       '12/11/2019', '18/11/2019', '23/11/2019', '22/11/2019',
       '26/11/2019', '19/11/2019', '21/11/2019', '24/11/2019',
       '20/11/2019', '25/11/2019', '30/11/2019', '28/11/2019',
       '1/12/2019', '3/12/2019', '29/11/2019', '17/11/2019', '27/11/2019',
       '7/12/2019', '9/12/2019', '4/12/2019', '11/12/2019', '5/12/2019',
       '12/12/2019', '10/12/2019', '2/12/2019', '6/12/2019', '13/12/2019',
       '18/12/2019', '16/12/2019', '17/12/2019', '19/12/2019',
       '20/12/2019', '15/12/2019', '8/12/2019', '14/12/2019',
       '23/12/2019', '22/12/2019', '21/12/2019', '25/12/2019',
       '27/12/2019', '26/12/2019', '24/12/2019', '31/12/2019',
       '29/12/2019', '28/12/2019', '30/12/2019', '3/1/2020', '4/1/2020',
       '2/1/2020', '1/1/2020', '9/1/2020', '8/1/2020', '6/1/2020',
       '7/1/2020', '5/1/2020', '16/1/2020', '17/1/2020', '10/1/2020',
       '15/1/2020', '18/1/2020', '13/1/2020', '11/1/2020', '14/1/2020',
       '19/1/2020', '22/1/2020', '24/1/2020', '23/1/2020', '26/1/2020',
       '28/1/2020', '30/1/2020', '21/1/2020', '12/1/2020', '29/1/2020',
       '27/1/2020', '25/1/2020', '20/1/2020', '2/2/2020', '31/1/2020',
       '7/2/2020', '1/2/2020', '4/2/2020', '6/2/2020', '10/2/2020',
       '3/2/2020', '5/2/2020', '13/2/2020', '9/2/2020', '8/2/2020',
       '11/2/2020', '12/2/2020', '15/2/2020', '14/2/2020', '16/2/2020',
       '19/2/2020', '17/2/2020', '18/2/2020', '21/2/2020', '23/2/2020',
       '20/2/2020', '22/2/2020', '26/2/2020', '4/3/2020', '1/3/2020',
       '29/2/2020', '28/2/2020', '24/2/2020', '2/3/2020', '25/2/2020',
       '5/3/2020', '27/2/2020', '6/3/2020', '7/3/2020', '11/3/2020',
       '9/3/2020', '3/3/2020', '13/3/2020', '8/3/2020', '15/3/2020',
       '14/3/2020', '16/3/2020', '17/3/2020', '10/3/2020', '21/3/2020',
       '12/3/2020', '18/3/2020', '19/3/2020', '20/3/2020', '24/3/2020',
       '25/3/2020', '23/3/2020', '22/3/2020', '27/3/2020', '29/3/2020',
       '26/3/2020', '1/4/2020', '28/3/2020', '30/3/2020', '7/4/2020',
       '4/4/2020', '5/4/2020', '31/3/2020', '3/4/2020', '8/4/2020',
       '12/4/2020', '2/4/2020', '13/4/2020', '11/4/2020', '6/4/2020',
       '9/4/2020', '10/4/2020', '16/4/2020', '17/4/2020', '15/4/2020',
       '18/4/2020', '14/4/2020', '25/4/2020', '19/4/2020', '21/4/2020',
       '22/4/2020', '20/4/2020', '24/4/2020', '26/4/2020', '23/4/2020',
       '30/4/2020', '27/4/2020', '29/4/2020', '1/5/2020', '2/5/2020',
       '3/5/2020', '28/4/2020', '4/5/2020', '5/5/2020', '12/5/2020',
       '8/5/2020', '9/5/2020', '7/5/2020', '10/5/2020', '14/5/2020',
       '11/5/2020', '13/5/2020', '6/5/2020', '19/5/2020', '16/5/2020',
       '17/5/2020', '25/5/2020', '20/5/2020', '22/5/2020', '18/5/2020',
       '21/5/2020', '23/5/2020', '27/5/2020', '26/5/2020', '29/5/2020',
       '24/5/2020', '30/5/2020', '4/6/2020', '28/5/2020', '31/5/2020',
       '3/6/2020', '1/6/2020', '6/6/2020', '15/5/2020', '7/6/2020',
       '9/6/2020', '5/6/2020', '13/6/2020', '8/6/2020', '10/6/2020',
       '14/6/2020', '17/6/2020', '12/6/2020', '16/6/2020', '11/6/2020',
       '22/6/2020', '18/6/2020', '2/6/2020', '15/6/2020', '23/6/2020',
       '21/6/2020', '25/6/2020', '19/6/2020', '26/6/2020', '24/6/2020',
       '1/7/2020', '27/6/2020', '20/6/2020', '28/6/2020', '29/6/2020',
       '30/6/2020', '3/7/2020', '6/7/2020', '5/7/2020', '2/7/2020',
       '10/7/2020', '4/7/2020', '9/7/2020', '12/7/2020', '14/7/2020',
       '7/7/2020', '17/7/2020', '8/7/2020', '16/7/2020', '18/7/2020',
       '11/7/2020', '13/7/2020', '19/7/2020', '23/7/2020', '25/7/2020',
       '15/7/2020', '24/7/2020', '27/7/2020', '20/7/2020', '26/7/2020',
       '30/7/2020', '22/7/2020', '21/7/2020', '31/7/2020', '29/7/2020',
       '4/8/2020', '28/7/2020', '1/8/2020', '11/8/2020', '5/8/2020',
       '2/8/2020', '6/8/2020', '3/8/2020', '9/8/2020', '10/8/2020',
       '12/8/2020', '13/8/2020', '8/8/2020', '7/8/2020', '16/8/2020',
       '14/8/2020', '17/8/2020', '19/8/2020', '21/8/2020', '20/8/2020',
       '15/8/2020', '18/8/2020', '25/8/2020', '22/8/2020', '26/8/2020',
       '23/8/2020', '29/8/2020', '24/8/2020', '30/8/2020', '3/9/2020',
       '2/9/2020', '28/8/2020', '7/9/2020', '5/9/2020', '1/9/2020',
       '31/8/2020', '27/8/2020', '8/9/2020', '4/9/2020', '6/9/2020',
       '12/9/2020', '9/9/2020', '15/9/2020', '10/9/2020', '16/9/2020',
       '18/9/2020', '13/9/2020', '22/9/2020', '19/9/2020', '24/9/2020',
       '21/9/2020', '23/9/2020', '11/9/2020', '14/9/2020', '20/9/2020',
       '17/9/2020', '25/9/2020', '28/9/2020', '29/9/2020', '26/9/2020',
       '27/9/2020', '5/10/2020', '7/10/2020', '1/10/2020', '30/9/2020',
       '6/10/2020', '4/10/2020', '2/10/2020', '11/10/2020', '13/10/2020',
       '9/10/2020', '3/10/2020', '10/10/2020', '16/10/2020', '12/10/2020',
       '8/10/2020', '19/10/2020', '22/10/2020', '21/10/2020',
       '14/10/2020', '15/10/2020', '23/10/2020', '17/10/2020',
       '26/10/2020', '25/10/2020', '27/10/2020', '20/10/2020',
       '24/10/2020', '18/10/2020', '29/10/2020', '28/10/2020',
       '1/11/2020', '31/10/2020', '3/11/2020', '4/11/2020', '7/11/2020',
       '30/10/2020', '2/11/2020', '8/11/2020', '6/11/2020', '14/11/2020',
       '13/11/2020', '5/11/2020', '18/11/2020', '15/11/2020',
       '17/11/2020', '16/11/2020', '11/11/2020', '9/11/2020',
       '21/11/2020', '12/11/2020', '10/11/2020', '23/11/2020',
       '22/11/2020', '19/11/2020', '20/11/2020', '30/11/2020',
       '27/11/2020', '26/11/2020', '2/12/2020', '3/12/2020', '1/12/2020',
       '7/12/2020', '24/11/2020', '29/11/2020', '28/11/2020', '5/12/2020',
       '9/12/2020', '10/12/2020', '25/11/2020', '11/12/2020', '8/12/2020',
       '6/12/2020', '17/12/2020', '4/12/2020', '18/12/2020', '15/12/2020',
       '16/12/2020', '13/12/2020', '12/12/2020', '14/12/2020',
       '19/12/2020', '20/12/2020', '24/12/2020', '21/12/2020',
       '22/12/2020', '27/12/2020', '26/12/2020', '30/12/2020',
       '28/12/2020', '1/1/2021', '29/12/2020', '4/1/2021', '25/12/2020',
       '31/12/2020', '7/1/2021', '23/12/2020', '6/1/2021', '5/1/2021',
       '11/1/2021', '9/1/2021', '14/1/2021', '12/1/2021', '8/1/2021',
       '3/1/2021', '17/1/2021', '10/1/2021', '2/1/2021', '15/1/2021',
       '20/1/2021', '13/1/2021', '16/1/2021', '19/1/2021', '21/1/2021',
       '23/1/2021', '18/1/2021', '24/1/2021', '30/1/2021', '22/1/2021',
       '25/1/2021', '28/1/2021', '29/1/2021', '27/1/2021', '26/1/2021',
       '2/2/2021'], dtype=object)

In [12]:
df

,order_number,sales_channel,warehouse_code,procured_date,order_date,ship_date,delivery_date,currency_code,sales_team_id,customer_id,store_id,product_id,order_quantity,discount_applied,unit_cost,unit_price
0,SO - 000101,In-Store,WARE-UHY1004,31/12/2017,31/5/2018,14/6/2018,19/6/2018,USD,6,15,259,12,5,0.08,"$1,001.18","$1,963.10"
1,SO - 000102,Online,WARE-NMK1003,31/12/2017,31/5/2018,22/6/2018,2/7/2018,USD,14,20,196,27,3,0.08,"$3,348.66","$3,939.60"
2,SO - 000103,Distributor,WARE-UHY1004,31/12/2017,31/5/2018,21/6/2018,1/7/2018,USD,21,16,213,16,1,0.05,$781.22,"$1,775.50"
3,SO - 000104,Wholesale,WARE-NMK1003,31/12/2017,31/5/2018,2/6/2018,7/6/2018,USD,28,48,107,23,8,0.08,"$1,464.69","$2,324.90"
4,SO - 000105,Distributor,WARE-NMK1003,10/4/2018,31/5/2018,16/6/2018,26/6/2018,USD,22,49,111,26,8,0.10,"$1,476.14","$1,822.40"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,SO - 0008087,In-Store,WARE-MKL1006,26/9/2020,30/12/2020,7/1/2021,14/1/2021,USD,9,41,339,29,1,0.08,$121.94,$234.50
7987,SO - 0008088,Online,WARE-NMK1003,26/9/2020,30/12/2020,2/1/2021,4/1/2021,USD,14,29,202,3,6,0.05,"$1,921.56","$3,202.60"
7988,SO - 0008089,Online,WARE-UHY1004,26/9/2020,30/12/2020,23/1/2021,26/1/2021,USD,14,32,241,35,5,0.20,"$2,792.76","$3,825.70"
7989,SO - 0008090,Online,WARE-NMK1003,26/9/2020,30/12/2020,20/1/2021,25/1/2021,USD,20,42,112,36,8,0.10,$804.00,"$1,072.00"
7990,SO - 0008091,In-Store,WARE-UHY1004,26/9/2020,30/12/2020,13/1/2021,19/1/2021,USD,6,41,237,43,5,0.08,"$1,370.82","$2,211.00"

In [13]:
df.to_csv("mongodb_scripts/data.csv", index=False)