## Exploratory Data Analysis

### Import Libraries

In [3]:
import sys, os
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [4]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

## Exploratory Data Analysis with Polars

### Load CSV File into Polars DataFrame

In [9]:
# Path to the folder containing the files
folder_path = "samba/data"


# List all files in the folder
files = [f for f in os.listdir(folder_path) if f.endswith(".csv")]  # Modify this if using other formats

# Function to load and dynamically cast numeric columns to Float64
def load_and_cast(file_path):
    # Read CSV file
    df = pl.read_csv(file_path)
    
    # Identify numeric columns (both Float64 and Int64)
    numeric_columns = [col for col, dtype in zip(df.columns, df.dtypes) if dtype in [pl.Float64, pl.Int64]]
    
    # Cast these numeric columns to Float64
    df = df.with_columns([
        pl.col(col).cast(pl.Float64) for col in numeric_columns
    ])
    
    return df

# Load the CSV files and cast numeric columns
dfs = [load_and_cast(os.path.join(folder_path, file)) for file in files]

# Concatenate the DataFrames
df = pl.concat(dfs)

In [10]:
df

shape: (61_556_964, 28)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ FL_DATE    ┆ OP_CARRIER ┆ OP_CARRIE ┆ ORIGIN ┆ … ┆ NAS_DELAY ┆ SECURITY_ ┆ LATE_AIRC ┆ Unnamed:  │
│ ---        ┆ ---        ┆ R_FL_NUM  ┆ ---    ┆   ┆ ---       ┆ DELAY     ┆ RAFT_DELA ┆ 27        │
│ str        ┆ str        ┆ ---       ┆ str    ┆   ┆ f64       ┆ ---       ┆ Y         ┆ ---       │
│            ┆            ┆ f64       ┆        ┆   ┆           ┆ f64       ┆ ---       ┆ str       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2009-01-01 ┆ XE         ┆ 1204.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1206.0    ┆ EWR    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1207.0    ┆ EWR    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1208.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1209.0    ┆ IAD    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …          ┆ …          ┆ …         ┆ …      ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2011-12-31 ┆ US         ┆ 2138.0    ┆ LGA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2011-12-31 ┆ US         ┆ 2168.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2011-12-31 ┆ US         ┆ 2175.0    ┆ LGA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2011-12-31 ┆ US         ┆ 2176.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2011-12-31 ┆ US         ┆ 2183.0    ┆ LGA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
column_data_types = zip(df.columns, df.dtypes)

for column, dtype in column_data_types:
    print(f"{column}:\t\t{dtype}")

FL_DATE:		String
OP_CARRIER:		String
OP_CARRIER_FL_NUM:		Float64
ORIGIN:		String
DEST:		String
CRS_DEP_TIME:		Float64
DEP_TIME:		Float64
DEP_DELAY:		Float64
TAXI_OUT:		Float64
WHEELS_OFF:		Float64
WHEELS_ON:		Float64
TAXI_IN:		Float64
CRS_ARR_TIME:		Float64
ARR_TIME:		Float64
ARR_DELAY:		Float64
CANCELLED:		Float64
CANCELLATION_CODE:		String
DIVERTED:		Float64
CRS_ELAPSED_TIME:		Float64
ACTUAL_ELAPSED_TIME:		Float64
AIR_TIME:		Float64
DISTANCE:		Float64
CARRIER_DELAY:		Float64
WEATHER_DELAY:		Float64
NAS_DELAY:		Float64
SECURITY_DELAY:		Float64
LATE_AIRCRAFT_DELAY:		Float64
Unnamed: 27:		String

### Display First Few Rows to Understand Structure of Data

In [12]:
print(df.head())

shape: (5, 28)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ FL_DATE    ┆ OP_CARRIER ┆ OP_CARRIE ┆ ORIGIN ┆ … ┆ NAS_DELAY ┆ SECURITY_ ┆ LATE_AIRC ┆ Unnamed:  │
│ ---        ┆ ---        ┆ R_FL_NUM  ┆ ---    ┆   ┆ ---       ┆ DELAY     ┆ RAFT_DELA ┆ 27        │
│ str        ┆ str        ┆ ---       ┆ str    ┆   ┆ f64       ┆ ---       ┆ Y         ┆ ---       │
│            ┆            ┆ f64       ┆        ┆   ┆           ┆ f64       ┆ ---       ┆ str       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2009-01-01 ┆ XE         ┆ 1204.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1206.0    ┆ EWR    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1207.0    ┆ EWR    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1208.0    ┆ DCA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2009-01-01 ┆ XE         ┆ 1209.0    ┆ IAD    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Retrieve Basic Information About DataFrame

In [13]:
print(df.shape)
print(df.dtypes)

(61556964, 28)
[String, String, Float64, String, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String]

### Display Summary Statistics for All Columns

In [14]:
summary = df.describe()
print(summary)

shape: (9, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ FL_DATE   ┆ OP_CARRIE ┆ OP_CARRIE ┆ … ┆ NAS_DELAY ┆ SECURITY_ ┆ LATE_AIRC ┆ Unnamed: │
│ ---       ┆ ---       ┆ R         ┆ R_FL_NUM  ┆   ┆ ---       ┆ DELAY     ┆ RAFT_DELA ┆ 27       │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ Y         ┆ ---      │
│           ┆           ┆ str       ┆ f64       ┆   ┆           ┆ f64       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 61556964  ┆ 61556964  ┆ 6.1556964 ┆ … ┆ 1.139074e ┆ 1.139074e ┆ 1.139074e ┆ 0        │
│           ┆           ┆           ┆ e7        ┆   ┆ 7         ┆ 7         ┆ 7         ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 5.0166224 ┆ 5.0166224 ┆ 5.0166224 ┆ 61556964 │
│ t         ┆           ┆           ┆           ┆   ┆ e7        ┆ e7        ┆ e7        ┆          │
│ mean      ┆ null      ┆ null      ┆ 2300.2412 ┆ … ┆ 14.403737 ┆ 0.078529  ┆ 23.283611 ┆ null     │
│           ┆           ┆           ┆ 57        ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ 1886.5572 ┆ … ┆ 29.667234 ┆ 2.387902  ┆ 42.740054 ┆ null     │
│           ┆           ┆           ┆ 11        ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 2009-01-0 ┆ 9E        ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ null     │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 725.0     ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ 1741.0    ┆ … ┆ 3.0       ┆ 0.0       ┆ 3.0       ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ 3606.0    ┆ … ┆ 18.0      ┆ 0.0       ┆ 29.0      ┆ null     │
│ max       ┆ 2018-12-3 ┆ YX        ┆ 9855.0    ┆ … ┆ 1848.0    ┆ 987.0     ┆ 2454.0    ┆ null     │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
for col in df.columns:
    print(f"{col} : {df[col].is_null().sum()}")

FL_DATE : 0
OP_CARRIER : 0
OP_CARRIER_FL_NUM : 0
ORIGIN : 0
DEST : 0
CRS_DEP_TIME : 1
DEP_TIME : 935723
DEP_DELAY : 940675
TAXI_OUT : 963901
WHEELS_OFF : 963896
WHEELS_ON : 997016
TAXI_IN : 997015
CRS_ARR_TIME : 2
ARR_TIME : 997015
ARR_DELAY : 1121351
CANCELLED : 0
CANCELLATION_CODE : 60583755
DIVERTED : 0
CRS_ELAPSED_TIME : 60
ACTUAL_ELAPSED_TIME : 1118754
AIR_TIME : 1118753
DISTANCE : 0
CARRIER_DELAY : 50166224
WEATHER_DELAY : 50166224
NAS_DELAY : 50166224
SECURITY_DELAY : 50166224
LATE_AIRCRAFT_DELAY : 50166224
Unnamed: 27 : 61556964

### Find Longest Text Length in Each Column

In [16]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 6)
┌─────────┬────────────┬────────┬──────┬───────────────────┬─────────────┐
│ FL_DATE ┆ OP_CARRIER ┆ ORIGIN ┆ DEST ┆ CANCELLATION_CODE ┆ Unnamed: 27 │
│ ---     ┆ ---        ┆ ---    ┆ ---  ┆ ---               ┆ ---         │
│ u32     ┆ u32        ┆ u32    ┆ u32  ┆ u32               ┆ f64         │
╞═════════╪════════════╪════════╪══════╪═══════════════════╪═════════════╡
│ 10      ┆ 2          ┆ 3      ┆ 3    ┆ 1                 ┆ NaN         │
└─────────┴────────────┴────────┴──────┴───────────────────┴─────────────┘

### Retrieve Data Types of All Columns

In [18]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, Float64, String, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, String]

### Count Unique Values in Each Column

In [19]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                      Unique values in FL_DATE : 3590
                   Unique values in OP_CARRIER : 23
            Unique values in OP_CARRIER_FL_NUM : 7605
                       Unique values in ORIGIN : 380
                         Unique values in DEST : 378
                 Unique values in CRS_DEP_TIME : 1433
                     Unique values in DEP_TIME : 1441
                    Unique values in DEP_DELAY : 1744
                     Unique values in TAXI_OUT : 288
                   Unique values in WHEELS_OFF : 1441
                    Unique values in WHEELS_ON : 1441
                      Unique values in TAXI_IN : 298
                 Unique values in CRS_ARR_TIME : 1441
                     Unique values in ARR_TIME : 1441
                    Unique values in ARR_DELAY : 1750
                    Unique values in CANCELLED : 2
            Unique values in CANCELLATION_CODE : 5
                     Unique values in DIVERTED : 2
             Unique values in CRS_ELAPSED_TIME : 676
          Unique values in ACTUAL_ELAPSED_TIME : 745
                     Unique values in AIR_TIME : 707
                     Unique values in DISTANCE : 1801
                Unique values in CARRIER_DELAY : 1586
                Unique values in WEATHER_DELAY : 1173
                    Unique values in NAS_DELAY : 1162
               Unique values in SECURITY_DELAY : 328
          Unique values in LATE_AIRCRAFT_DELAY : 1186
                  Unique values in Unnamed: 27 : 1

### Retrieve Unique Values in Column If There Are Fewer Than 100

In [22]:
for col in df.columns:
    # Get unique values for the column
    unique_values = df[col].unique().to_list()  # Convert to a list
    if len(unique_values) < 100:
        print(f"'{col}' {len(unique_values)}: {unique_values}")

'OP_CARRIER' 23: ['OO', 'OH', 'HA', 'FL', 'YX', 'AS', 'MQ', 'YV', 'WN', 'AA', 'XE', 'CO', 'EV', 'NW', 'VX', 'UA', 'F9', '9E', 'B6', 'G4', 'DL', 'NK', 'US']
'CANCELLED' 2: [0.0, 1.0]
'CANCELLATION_CODE' 5: ['B', 'A', 'C', None, 'D']
'DIVERTED' 2: [0.0, 1.0]
'Unnamed: 27' 1: [None]

### Check Distribution of Numerical Columns

In [24]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

OP_CARRIER_FL_NUM
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ OP_CARRIER_FL_NUM │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 6.1556964e7       │
│ null_count ┆ 0.0               │
│ mean       ┆ 2300.241257       │
│ std        ┆ 1886.557211       │
│ min        ┆ 0.0               │
│ 25%        ┆ 725.0             │
│ 50%        ┆ 1741.0            │
│ 75%        ┆ 3606.0            │
│ max        ┆ 9855.0            │
└────────────┴───────────────────┘


CRS_DEP_TIME
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ CRS_DEP_TIME │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 6.1556963e7  │
│ null_count ┆ 1.0          │
│ mean       ┆ 1327.202589  │
│ std        ┆ 474.893502   │
│ min        ┆ 1.0          │
│ 25%        ┆ 921.0        │
│ 50%        ┆ 1320.0       │
│ 75%        ┆ 1725.0       │
│ max        ┆ 2359.0       │
└────────────┴──────────────┘


DEP_TIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DEP_TIME    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0621241e7 │
│ null_count ┆ 935723.0    │
│ mean       ┆ 1333.141072 │
│ std        ┆ 487.487783  │
│ min        ┆ 1.0         │
│ 25%        ┆ 925.0       │
│ 50%        ┆ 1327.0      │
│ 75%        ┆ 1734.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


DEP_DELAY
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DEP_DELAY   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0616289e7 │
│ null_count ┆ 940675.0    │
│ mean       ┆ 9.044879    │
│ std        ┆ 37.137427   │
│ min        ┆ -251.0      │
│ 25%        ┆ -5.0        │
│ 50%        ┆ -2.0        │
│ 75%        ┆ 7.0         │
│ max        ┆ 2755.0      │
└────────────┴─────────────┘


TAXI_OUT
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ TAXI_OUT    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0593063e7 │
│ null_count ┆ 963901.0    │
│ mean       ┆ 15.991963   │
│ std        ┆ 9.31189     │
│ min        ┆ 0.0         │
│ 25%        ┆ 10.0        │
│ 50%        ┆ 14.0        │
│ 75%        ┆ 19.0        │
│ max        ┆ 458.0       │
└────────────┴─────────────┘


WHEELS_OFF
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WHEELS_OFF  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0593068e7 │
│ null_count ┆ 963896.0    │
│ mean       ┆ 1356.017721 │
│ std        ┆ 488.836959  │
│ min        ┆ 1.0         │
│ 25%        ┆ 939.0       │
│ 50%        ┆ 1340.0      │
│ 75%        ┆ 1748.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


WHEELS_ON
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WHEELS_ON   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0559948e7 │
│ null_count ┆ 997016.0    │
│ mean       ┆ 1473.756664 │
│ std        ┆ 511.512451  │
│ min        ┆ 1.0         │
│ 25%        ┆ 1059.0      │
│ 50%        ┆ 1509.0      │
│ 75%        ┆ 1907.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


TAXI_IN
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ TAXI_IN     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0559949e7 │
│ null_count ┆ 997015.0    │
│ mean       ┆ 7.118817    │
│ std        ┆ 5.304306    │
│ min        ┆ 0.0         │
│ 25%        ┆ 4.0         │
│ 50%        ┆ 6.0         │
│ 75%        ┆ 8.0         │
│ max        ┆ 414.0       │
└────────────┴─────────────┘


CRS_ARR_TIME
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ CRS_ARR_TIME │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 6.1556962e7  │
│ null_count ┆ 2.0          │
│ mean       ┆ 1495.146887  │
│ std        ┆ 495.78675    │
│ min        ┆ 1.0          │
│ 25%        ┆ 1113.0       │
│ 50%        ┆ 1520.0       │
│ 75%        ┆ 1913.0       │
│ max        ┆ 2400.0       │
└────────────┴──────────────┘


ARR_TIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ ARR_TIME    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0559949e7 │
│ null_count ┆ 997015.0    │
│ mean       ┆ 1479.336885 │
│ std        ┆ 515.097029  │
│ min        ┆ 1.0         │
│ 25%        ┆ 1103.0      │
│ 50%        ┆ 1513.0      │
│ 75%        ┆ 1912.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


ARR_DELAY
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ ARR_DELAY   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0435613e7 │
│ null_count ┆ 1.121351e6  │
│ mean       ┆ 4.700336    │
│ std        ┆ 39.437402   │
│ min        ┆ -411.0      │
│ 25%        ┆ -13.0       │
│ 50%        ┆ -4.0        │
│ 75%        ┆ 8.0         │
│ max        ┆ 2692.0      │
└────────────┴─────────────┘


CANCELLED
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ CANCELLED   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.1556964e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 0.01581     │
│ std        ┆ 0.124739    │
│ min        ┆ 0.0         │
│ 25%        ┆ 0.0         │
│ 50%        ┆ 0.0         │
│ 75%        ┆ 0.0         │
│ max        ┆ 1.0         │
└────────────┴─────────────┘


DIVERTED
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DIVERTED    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.1556964e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 0.002365    │
│ std        ┆ 0.04857     │
│ min        ┆ 0.0         │
│ 25%        ┆ 0.0         │
│ 50%        ┆ 0.0         │
│ 75%        ┆ 0.0         │
│ max        ┆ 1.0         │
└────────────┴─────────────┘


CRS_ELAPSED_TIME
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ CRS_ELAPSED_TIME │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 6.1556904e7      │
│ null_count ┆ 60.0             │
│ mean       ┆ 136.956423       │
│ std        ┆ 73.370602        │
│ min        ┆ -99.0            │
│ 25%        ┆ 84.0             │
│ 50%        ┆ 118.0            │
│ 75%        ┆ 167.0            │
│ max        ┆ 1865.0           │
└────────────┴──────────────────┘


ACTUAL_ELAPSED_TIME
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ ACTUAL_ELAPSED_TIME │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 6.043821e7          │
│ null_count ┆ 1.118754e6          │
│ mean       ┆ 132.87662           │
│ std        ┆ 72.840335           │
│ min        ┆ 11.0                │
│ 25%        ┆ 80.0                │
│ 50%        ┆ 114.0               │
│ 75%        ┆ 163.0               │
│ max        ┆ 799.0               │
└────────────┴─────────────────────┘


AIR_TIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ AIR_TIME    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.0438211e7 │
│ null_count ┆ 1.118753e6  │
│ mean       ┆ 109.776974  │
│ std        ┆ 70.679545   │
│ min        ┆ 0.0         │
│ 25%        ┆ 58.0        │
│ 50%        ┆ 91.0        │
│ 75%        ┆ 139.0       │
│ max        ┆ 723.0       │
└────────────┴─────────────┘


DISTANCE
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DISTANCE    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 6.1556964e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 786.676109  │
│ std        ┆ 593.67008   │
│ min        ┆ 11.0        │
│ 25%        ┆ 352.0       │
│ 50%        ┆ 620.0       │
│ 75%        ┆ 1020.0      │
│ max        ┆ 4983.0      │
└────────────┴─────────────┘


CARRIER_DELAY
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ CARRIER_DELAY │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1.139074e7    │
│ null_count ┆ 5.0166224e7   │
│ mean       ┆ 17.82056      │
│ std        ┆ 48.544779     │
│ min        ┆ 0.0           │
│ 25%        ┆ 0.0           │
│ 50%        ┆ 0.0           │
│ 75%        ┆ 17.0          │
│ max        ┆ 2439.0        │
└────────────┴───────────────┘


WEATHER_DELAY
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ WEATHER_DELAY │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1.139074e7    │
│ null_count ┆ 5.0166224e7   │
│ mean       ┆ 2.657591      │
│ std        ┆ 20.600631     │
│ min        ┆ 0.0           │
│ 25%        ┆ 0.0           │
│ 50%        ┆ 0.0           │
│ 75%        ┆ 0.0           │
│ max        ┆ 2692.0        │
└────────────┴───────────────┘


NAS_DELAY
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ NAS_DELAY   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.139074e7  │
│ null_count ┆ 5.0166224e7 │
│ mean       ┆ 14.403737   │
│ std        ┆ 29.667234   │
│ min        ┆ 0.0         │
│ 25%        ┆ 0.0         │
│ 50%        ┆ 3.0         │
│ 75%        ┆ 18.0        │
│ max        ┆ 1848.0      │
└────────────┴─────────────┘


SECURITY_DELAY
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ SECURITY_DELAY │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 1.139074e7     │
│ null_count ┆ 5.0166224e7    │
│ mean       ┆ 0.078529       │
│ std        ┆ 2.387902       │
│ min        ┆ 0.0            │
│ 25%        ┆ 0.0            │
│ 50%        ┆ 0.0            │
│ 75%        ┆ 0.0            │
│ max        ┆ 987.0          │
└────────────┴────────────────┘


LATE_AIRCRAFT_DELAY
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ LATE_AIRCRAFT_DELAY │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 1.139074e7          │
│ null_count ┆ 5.0166224e7         │
│ mean       ┆ 23.283611           │
│ std        ┆ 42.740054           │
│ min        ┆ 0.0                 │
│ 25%        ┆ 0.0                 │
│ 50%        ┆ 3.0                 │
│ 75%        ┆ 29.0                │
│ max        ┆ 2454.0              │
└────────────┴─────────────────────┘