## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/flights.txt", separator="|")

df

shape: (1_191_805, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ TRANSACTI ┆ FLIGHTDAT ┆ AIRLINECO ┆ AIRLINENA ┆ … ┆ ACTUALELA ┆ CANCELLED ┆ DIVERTED ┆ DISTANCE  │
│ ONID      ┆ E         ┆ DE        ┆ ME        ┆   ┆ PSEDTIME  ┆ ---       ┆ ---      ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str      ┆ str       │
│ i64       ┆ i64       ┆ str       ┆ str       ┆   ┆ i64       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 54548800  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 87        ┆ F         ┆ False    ┆ 580 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 55872300  ┆ 20020101  ┆ CO        ┆ Continent ┆ … ┆ 119       ┆ False     ┆ F        ┆ 744 miles │
│           ┆           ┆           ┆ al Air    ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: CO  ┆   ┆           ┆           ┆          ┆           │
│ 54388800  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 102       ┆ F         ┆ False    ┆ 718 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 54486500  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 83        ┆ 0         ┆ 0        ┆ 487 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 55878700  ┆ 20020103  ┆ CO        ┆ Continent ┆ … ┆ 114       ┆ F         ┆ False    ┆ 744 miles │
│           ┆           ┆           ┆ al Air    ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: CO  ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 126750200 ┆ 20130106  ┆ EV        ┆ ExpressJe ┆ … ┆ 135       ┆ 0         ┆ 0        ┆ 721 miles │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: EV  ┆   ┆           ┆           ┆          ┆           │
│ 127294500 ┆ 20130106  ┆ DL        ┆ Delta Air ┆ … ┆ 150       ┆ False     ┆ F        ┆ 731 miles │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: DL  ┆   ┆           ┆           ┆          ┆           │
│ 127294900 ┆ 20130106  ┆ DL        ┆ Delta Air ┆ … ┆ 140       ┆ F         ┆ False    ┆ 731 miles │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: DL  ┆   ┆           ┆           ┆          ┆           │
│ 126594900 ┆ 20130106  ┆ EV        ┆ ExpressJe ┆ … ┆ 101       ┆ False     ┆ F        ┆ 508 miles │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: EV  ┆   ┆           ┆           ┆          ┆           │
│ 126620300 ┆ 20130106  ┆ EV        ┆ ExpressJe ┆ … ┆ 77        ┆ False     ┆ False    ┆ 306 miles │
│           ┆           ┆           ┆ t         ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: EV  ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 31)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ TRANSACTI ┆ FLIGHTDAT ┆ AIRLINECO ┆ AIRLINENA ┆ … ┆ ACTUALELA ┆ CANCELLED ┆ DIVERTED ┆ DISTANCE  │
│ ONID      ┆ E         ┆ DE        ┆ ME        ┆   ┆ PSEDTIME  ┆ ---       ┆ ---      ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str      ┆ str       │
│ i64       ┆ i64       ┆ str       ┆ str       ┆   ┆ i64       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 54548800  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 87        ┆ F         ┆ False    ┆ 580 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 55872300  ┆ 20020101  ┆ CO        ┆ Continent ┆ … ┆ 119       ┆ False     ┆ F        ┆ 744 miles │
│           ┆           ┆           ┆ al Air    ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: CO  ┆   ┆           ┆           ┆          ┆           │
│ 54388800  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 102       ┆ F         ┆ False    ┆ 718 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 54486500  ┆ 20020101  ┆ WN        ┆ Southwest ┆ … ┆ 83        ┆ 0         ┆ 0        ┆ 487 miles │
│           ┆           ┆           ┆ Airlines  ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Co.: WN   ┆   ┆           ┆           ┆          ┆           │
│ 55878700  ┆ 20020103  ┆ CO        ┆ Continent ┆ … ┆ 114       ┆ F         ┆ False    ┆ 744 miles │
│           ┆           ┆           ┆ al Air    ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Lines     ┆   ┆           ┆           ┆          ┆           │
│           ┆           ┆           ┆ Inc.: CO  ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

### Display Summary Statistics for All Columns

In [5]:
summary = df.describe()
print(summary)

shape: (9, 32)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ statistic ┆ TRANSACTI ┆ FLIGHTDAT ┆ AIRLINECO ┆ … ┆ ACTUALELA ┆ CANCELLED ┆ DIVERTED ┆ DISTANCE  │
│ ---       ┆ ONID      ┆ E         ┆ DE        ┆   ┆ PSEDTIME  ┆ ---       ┆ ---      ┆ ---       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str      ┆ str       │
│           ┆ f64       ┆ f64       ┆ str       ┆   ┆ f64       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ count     ┆ 1.191805e ┆ 1.191805e ┆ 1191805   ┆ … ┆ 1.160545e ┆ 1191805   ┆ 1191805  ┆ 1191805   │
│           ┆ 6         ┆ 6         ┆           ┆   ┆ 6         ┆           ┆          ┆           │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 31260.0   ┆ 0         ┆ 0        ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ mean      ┆ 7.0687e7  ┆ 2.0038e7  ┆ null      ┆ … ┆ 124.48739 ┆ null      ┆ null     ┆ null      │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆          ┆           │
│ std       ┆ 4.6780e7  ┆ 75409.764 ┆ null      ┆ … ┆ 69.827749 ┆ null      ┆ null     ┆ null      │
│           ┆           ┆ 506       ┆           ┆   ┆           ┆           ┆          ┆           │
│ min       ┆ 100.0     ┆ 1.9920101 ┆ 9E        ┆ … ┆ 6.0       ┆ 0         ┆ 0        ┆ 100 miles │
│           ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 25%       ┆ 2.97952e7 ┆ 1.9970902 ┆ null      ┆ … ┆ 73.0      ┆ null      ┆ null     ┆ null      │
│           ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 50%       ┆ 5.95903e7 ┆ 2.0030102 ┆ null      ┆ … ┆ 106.0     ┆ null      ┆ null     ┆ null      │
│           ┆           ┆ e7        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 75%       ┆ 1.180231e ┆ 2.0110525 ┆ null      ┆ … ┆ 156.0     ┆ null      ┆ null     ┆ null      │
│           ┆ 8         ┆ e7        ┆           ┆   ┆           ┆           ┆          ┆           │
│ max       ┆ 1.478182e ┆ 2.0160531 ┆ YV        ┆ … ┆ 700.0     ┆ True      ┆ True     ┆ 999 miles │
│           ┆ 8         ┆ e7        ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

### Find Longest Text Length in Each Column

In [6]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 16)
┌────────────┬────────────┬─────────┬────────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ AIRLINECOD ┆ AIRLINENAM ┆ TAILNUM ┆ ORIGINAIRP ┆ … ┆ DESTSTATE ┆ CANCELLED ┆ DIVERTED ┆ DISTANCE │
│ E          ┆ E          ┆ ---     ┆ ORTCODE    ┆   ┆ NAME      ┆ ---       ┆ ---      ┆ ---      │
│ ---        ┆ ---        ┆ u32     ┆ ---        ┆   ┆ ---       ┆ u32       ┆ u32      ┆ u32      │
│ u32        ┆ u32        ┆         ┆ u32        ┆   ┆ u32       ┆           ┆          ┆          │
╞════════════╪════════════╪═════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ 2          ┆ 87         ┆ 6       ┆ 3          ┆ … ┆ 46        ┆ 5         ┆ 5        ┆ 10       │
└────────────┴────────────┴─────────┴────────────┴───┴───────────┴───────────┴──────────┴──────────┘

### Retrieve Data Types of All Columns

In [7]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Int64, Int64, String, String, String, Int64, String, String, String, String, String, String, String, String, String, String, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, String, String, String]

### Count Unique Values in Each Column

In [8]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                Unique values in TRANSACTIONID : 1191805
                   Unique values in FLIGHTDATE : 1902
                  Unique values in AIRLINECODE : 26
                  Unique values in AIRLINENAME : 26
                      Unique values in TAILNUM : 13870
                    Unique values in FLIGHTNUM : 8034
            Unique values in ORIGINAIRPORTCODE : 363
              Unique values in ORIGAIRPORTNAME : 363
               Unique values in ORIGINCITYNAME : 344
                  Unique values in ORIGINSTATE : 52
              Unique values in ORIGINSTATENAME : 52
              Unique values in DESTAIRPORTCODE : 364
              Unique values in DESTAIRPORTNAME : 364
                 Unique values in DESTCITYNAME : 345
                    Unique values in DESTSTATE : 52
                Unique values in DESTSTATENAME : 52
                   Unique values in CRSDEPTIME : 1344
                      Unique values in DEPTIME : 1413
                     Unique values in DEPDELAY : 692
                      Unique values in TAXIOUT : 255
                    Unique values in WHEELSOFF : 1407
                     Unique values in WHEELSON : 1440
                       Unique values in TAXIIN : 190
                   Unique values in CRSARRTIME : 1433
                      Unique values in ARRTIME : 1441
                     Unique values in ARRDELAY : 705
               Unique values in CRSELAPSEDTIME : 600
            Unique values in ACTUALELAPSEDTIME : 646
                    Unique values in CANCELLED : 6
                     Unique values in DIVERTED : 6
                     Unique values in DISTANCE : 1706

### Check Distribution of Numerical Columns

In [9]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

TRANSACTIONID
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ TRANSACTIONID │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 1.191805e6    │
│ null_count ┆ 0.0           │
│ mean       ┆ 7.0687e7      │
│ std        ┆ 4.6780e7      │
│ min        ┆ 100.0         │
│ 25%        ┆ 2.97952e7     │
│ 50%        ┆ 5.95903e7     │
│ 75%        ┆ 1.180231e8    │
│ max        ┆ 1.478182e8    │
└────────────┴───────────────┘


FLIGHTDATE
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ FLIGHTDATE   │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 1.191805e6   │
│ null_count ┆ 0.0          │
│ mean       ┆ 2.0038e7     │
│ std        ┆ 75409.764506 │
│ min        ┆ 1.9920101e7  │
│ 25%        ┆ 1.9970902e7  │
│ 50%        ┆ 2.0030102e7  │
│ 75%        ┆ 2.0110525e7  │
│ max        ┆ 2.0160531e7  │
└────────────┴──────────────┘


FLIGHTNUM
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ FLIGHTNUM   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.191805e6  │
│ null_count ┆ 0.0         │
│ mean       ┆ 1641.100645 │
│ std        ┆ 1588.957597 │
│ min        ┆ 1.0         │
│ 25%        ┆ 521.0       │
│ 50%        ┆ 1159.0      │
│ 75%        ┆ 2039.0      │
│ max        ┆ 9899.0      │
└────────────┴─────────────┘


CRSDEPTIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ CRSDEPTIME  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.191805e6  │
│ null_count ┆ 0.0         │
│ mean       ┆ 1326.644589 │
│ std        ┆ 477.674894  │
│ min        ┆ 0.0         │
│ 25%        ┆ 925.0       │
│ 50%        ┆ 1325.0      │
│ 75%        ┆ 1725.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


DEPTIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ DEPTIME     │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.16347e6   │
│ null_count ┆ 28335.0     │
│ mean       ┆ 1341.898961 │
│ std        ┆ 475.536395  │
│ min        ┆ 1.0         │
│ 25%        ┆ 932.0       │
│ 50%        ┆ 1331.0      │
│ 75%        ┆ 1732.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


DEPDELAY
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ DEPDELAY  │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 1.16347e6 │
│ null_count ┆ 28335.0   │
│ mean       ┆ 7.28634   │
│ std        ┆ 29.746719 │
│ min        ┆ -120.0    │
│ 25%        ┆ -3.0      │
│ 50%        ┆ 0.0       │
│ 75%        ┆ 5.0       │
│ max        ┆ 1477.0    │
└────────────┴───────────┘


TAXIOUT
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ TAXIOUT    │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 1.011833e6 │
│ null_count ┆ 179972.0   │
│ mean       ┆ 15.336503  │
│ std        ┆ 10.389719  │
│ min        ┆ 0.0        │
│ 25%        ┆ 10.0       │
│ 50%        ┆ 13.0       │
│ 75%        ┆ 18.0       │
│ max        ┆ 1439.0     │
└────────────┴────────────┘


WHEELSOFF
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WHEELSOFF   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.011791e6  │
│ null_count ┆ 180014.0    │
│ mean       ┆ 1363.798254 │
│ std        ┆ 478.143338  │
│ min        ┆ 1.0         │
│ 25%        ┆ 947.0       │
│ 50%        ┆ 1345.0      │
│ 75%        ┆ 1748.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


WHEELSON
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ WHEELSON    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.010225e6  │
│ null_count ┆ 181580.0    │
│ mean       ┆ 1486.797567 │
│ std        ┆ 496.289963  │
│ min        ┆ 1.0         │
│ 25%        ┆ 1112.0      │
│ 50%        ┆ 1517.0      │
│ 75%        ┆ 1910.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


TAXIIN
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ TAXIIN    │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 1.01032e6 │
│ null_count ┆ 181485.0  │
│ mean       ┆ 6.462265  │
│ std        ┆ 8.397914  │
│ min        ┆ 0.0       │
│ 25%        ┆ 4.0       │
│ 50%        ┆ 5.0       │
│ 75%        ┆ 8.0       │
│ max        ┆ 1439.0    │
└────────────┴───────────┘


CRSARRTIME
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ CRSARRTIME  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 1.191805e6  │
│ null_count ┆ 0.0         │
│ mean       ┆ 1490.941551 │
│ std        ┆ 495.867298  │
│ min        ┆ 0.0         │
│ 25%        ┆ 1115.0      │
│ 50%        ┆ 1520.0      │
│ 75%        ┆ 1911.0      │
│ max        ┆ 2400.0      │
└────────────┴─────────────┘


ARRTIME
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ ARRTIME    │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 1.161439e6 │
│ null_count ┆ 30366.0    │
│ mean       ┆ 1493.24412 │
│ std        ┆ 497.000402 │
│ min        ┆ 1.0        │
│ 25%        ┆ 1116.0     │
│ 50%        ┆ 1522.0     │
│ 75%        ┆ 1915.0     │
│ max        ┆ 2400.0     │
└────────────┴────────────┘


ARRDELAY
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ ARRDELAY   │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 1.160545e6 │
│ null_count ┆ 31260.0    │
│ mean       ┆ 4.836588   │
│ std        ┆ 31.826196  │
│ min        ┆ -95.0      │
│ 25%        ┆ -10.0      │
│ 50%        ┆ -2.0       │
│ 75%        ┆ 9.0        │
│ max        ┆ 1473.0     │
└────────────┴────────────┘


CRSELAPSEDTIME
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ CRSELAPSEDTIME │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 1.191383e6     │
│ null_count ┆ 422.0          │
│ mean       ┆ 126.677038     │
│ std        ┆ 69.911843      │
│ min        ┆ 14.0           │
│ 25%        ┆ 75.0           │
│ 50%        ┆ 108.0          │
│ 75%        ┆ 158.0          │
│ max        ┆ 705.0          │
└────────────┴────────────────┘


ACTUALELAPSEDTIME
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ ACTUALELAPSEDTIME │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 1.160545e6        │
│ null_count ┆ 31260.0           │
│ mean       ┆ 124.487399        │
│ std        ┆ 69.827749         │
│ min        ┆ 6.0               │
│ 25%        ┆ 73.0              │
│ 50%        ┆ 106.0             │
│ 75%        ┆ 156.0             │
│ max        ┆ 700.0             │
└────────────┴───────────────────┘

### Retrieve Count of Nulls For Each Feature

In [11]:
null_counts = df.null_count().to_dict(as_series=False)

print("Null counts per column:")
for column, count in null_counts.items():
    print(f"{column}: {count[0]}")

Null counts per column:
TRANSACTIONID: 0
FLIGHTDATE: 0
AIRLINECODE: 0
AIRLINENAME: 0
TAILNUM: 156817
FLIGHTNUM: 0
ORIGINAIRPORTCODE: 0
ORIGAIRPORTNAME: 0
ORIGINCITYNAME: 0
ORIGINSTATE: 10842
ORIGINSTATENAME: 10842
DESTAIRPORTCODE: 0
DESTAIRPORTNAME: 0
DESTCITYNAME: 0
DESTSTATE: 10838
DESTSTATENAME: 10838
CRSDEPTIME: 0
DEPTIME: 28335
DEPDELAY: 28335
TAXIOUT: 179972
WHEELSOFF: 180014
WHEELSON: 181580
TAXIIN: 181485
CRSARRTIME: 0
ARRTIME: 30366
ARRDELAY: 31260
CRSELAPSEDTIME: 422
ACTUALELAPSEDTIME: 31260
CANCELLED: 0
DIVERTED: 0
DISTANCE: 0