## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [14]:
df = pl.read_csv(
    "data/flixpatrol.csv", 
    ignore_errors=True, 
    truncate_ragged_lines=True
    )

df

shape: (18_164, 7)
┌─────────┬───────────────────────┬─────────┬──────────┬──────────────┬─────────────┬──────────────┐
│ Rank    ┆ Title                 ┆ Type    ┆ Premiere ┆ Genre        ┆ Watchtime   ┆ Watchtime in │
│ ---     ┆ ---                   ┆ ---     ┆ ---      ┆ ---          ┆ ---         ┆ Million      │
│ f64     ┆ str                   ┆ str     ┆ i64      ┆ str          ┆ str         ┆ ---          │
│         ┆                       ┆         ┆          ┆              ┆             ┆ str          │
╞═════════╪═══════════════════════╪═════════╪══════════╪══════════════╪═════════════╪══════════════╡
│ 1.0     ┆ The Night Agent       ┆ TV Show ┆ 2023     ┆ Action       ┆ 812,100,000 ┆ 812.1M       │
│ 2.0     ┆ Ginny & Georgia       ┆ TV Show ┆ 2021     ┆ Drama        ┆ 665,100,000 ┆ 665.1M       │
│ 3.0     ┆ The Glory             ┆ TV Show ┆ 2022     ┆ Thriller     ┆ 622,800,000 ┆ 622.8M       │
│ 4.0     ┆ Wednesday             ┆ TV Show ┆ 2022     ┆ Fantasy      ┆ 507,700,000 ┆ 507.7M       │
│ 5.0     ┆ Queen Charlotte: A    ┆ TV Show ┆ 2023     ┆ Drama        ┆ 503,000,000 ┆ 503.0M       │
│         ┆ Bridgerton …          ┆         ┆          ┆              ┆             ┆              │
│ 6.0     ┆ You                   ┆ TV Show ┆ 2018     ┆ Crime        ┆ 440,600,000 ┆ 440.6M       │
│ 7.0     ┆ La Reina del Sur      ┆ TV Show ┆ 2011     ┆ Drama        ┆ 429,600,000 ┆ 429.6M       │
│ 8.0     ┆ Outer Banks           ┆ TV Show ┆ 2020     ┆ Drama        ┆ 402,500,000 ┆ 402.5M       │
│ 9.0     ┆ Ginny & Georgia       ┆ TV Show ┆ 2021     ┆ Drama        ┆ 302,100,000 ┆ 302.1M       │
│ 10.0    ┆ FUBAR                 ┆ TV Show ┆ 2023     ┆ Action       ┆ 266,200,000 ┆ 266.2M       │
│ 11.0    ┆ Manifest              ┆ TV Show ┆ 2018     ┆ Thriller     ┆ 262,600,000 ┆ 262.6M       │
│ 12.0    ┆ Kaleidoscope          ┆ TV Show ┆ 2023     ┆ Crime        ┆ 252,500,000 ┆ 252.5M       │
│ 13.0    ┆ Firefly Lane          ┆ TV Show ┆ 2021     ┆ Drama        ┆ 251,500,000 ┆ 251.5M       │
│ 14.0    ┆ The Mother            ┆ Movie   ┆ 2023     ┆ Thriller     ┆ 249,900,000 ┆ 249.9M       │
│ 15.0    ┆ Physical: 100         ┆ TV Show ┆ 2023     ┆ Reality-Show ┆ 235,000,000 ┆ 235.0M       │
│ 16.0    ┆ Crash Course In       ┆ TV Show ┆ 2023     ┆ Comedy       ┆ 234,800,000 ┆ 234.8M       │
│         ┆ Romance               ┆         ┆          ┆              ┆             ┆              │
│ 17.0    ┆ Love Is Blind         ┆ TV Show ┆ 2020     ┆ Reality-Show ┆ 229,700,000 ┆ 229.7M       │
│ 18.0    ┆ Beef                  ┆ TV Show ┆ 2023     ┆ Comedy       ┆ 221,100,000 ┆ 221.1M       │
│ …       ┆ …                     ┆ …       ┆ …        ┆ …            ┆ …           ┆ …            │
│ 18198.0 ┆ Fueled: The Man They  ┆ Movie   ┆ 2016     ┆ Drama        ┆ 100,000     ┆ 0.1M         │
│         ┆ Called Pi…            ┆         ┆          ┆              ┆             ┆              │
│ 18199.0 ┆ Born to be a Flower   ┆ TV Show ┆ 2018     ┆ Romance      ┆ 100,000     ┆ 0.1M         │
│ 18200.0 ┆ City Hunter           ┆ Movie   ┆ 2018     ┆ Adventure    ┆ 100,000     ┆ 0.1M         │
│ 18201.0 ┆ Al-Khawaga's Dilemma  ┆ Movie   ┆ 2018     ┆ Drama        ┆ 100,000     ┆ 0.1M         │
│ 18202.0 ┆ Feel-Good Fitness     ┆ TV Show ┆ null     ┆ Broadcast    ┆ 100,000     ┆ 0.1M         │
│ 18203.0 ┆ My best enemy         ┆ Movie   ┆ 2006     ┆ Comedy       ┆ 100,000     ┆ 0.1M         │
│ 18204.0 ┆ Kidnap - Bo's Most    ┆ Movie   ┆ 2015     ┆ Adventure    ┆ 100,000     ┆ 0.1M         │
│         ┆ Exciting Ho…          ┆         ┆          ┆              ┆             ┆              │
│ 18205.0 ┆ Maksym Osa: The Gold  ┆ Movie   ┆ 2022     ┆ History      ┆ 100,000     ┆ 0.1M         │
│         ┆ of Werewo…            ┆         ┆          ┆              ┆             ┆              │
│ 18206.0 ┆ Out of Sight          ┆ Movie   ┆ 1998     ┆ Crime        ┆ 100,000     ┆ 0.1M         │
│ 18207.0 ┆ Overprotected Kahoko  ┆ TV Show ┆ 2017     ┆ Family       ┆ 100,000     ┆ 0.1M         │
│ 18208.0 ┆ Patton Oswalt: I Love ┆ Movie   ┆ 2020     ┆ Comedy       ┆ 100,000     ┆ 0.1M         │
│         ┆ Everythi…             ┆         ┆          ┆              ┆             ┆              │
│ 18209.0 ┆ Rules of Dating       ┆ Movie   ┆ 2005     ┆ Comedy       ┆ 100,000     ┆ 0.1M         │
│ 18210.0 ┆ Spiritual House       ┆ TV Show ┆ 2017     ┆ Talk Show    ┆ 100,000     ┆ 0.1M         │
│ 18211.0 ┆ Suite Francaise       ┆ Movie   ┆ 2014     ┆ War          ┆ 100,000     ┆ 0.1M         │
│ 18212.0 ┆ The Bishop's Bedroom  ┆ Movie   ┆ 1977     ┆ Comedy       ┆ 100,000     ┆ 0.1M         │
│ 18213.0 ┆ 30 Chưa Phải Tết      ┆ Movie   ┆ 2020     ┆ Comedy       ┆ 100,000     ┆ 0.1M         │
│ 18214.0 ┆ The Promised Land     ┆ Movie   ┆ 2019     ┆ Crime        ┆ 100,000     ┆ 0.1M         │
└─────────┴───────────────────────┴─────────┴──────────┴──────────────┴─────────────┴──────────────┘

### Retrieve Number of Nulls in Each Feature

In [15]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (7, 2)
┌──────────────────────┬────────────┐
│ feature              ┆ null_count │
│ ---                  ┆ ---        │
│ str                  ┆ i64        │
╞══════════════════════╪════════════╡
│ Rank                 ┆ 0          │
│ Title                ┆ 0          │
│ Type                 ┆ 0          │
│ Premiere             ┆ 134        │
│ Genre                ┆ 0          │
│ Watchtime            ┆ 0          │
│ Watchtime in Million ┆ 0          │
└──────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [16]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
Rank                           | Float64
Title                          | String
Type                           | String
Premiere                       | Int64
Genre                          | String
Watchtime                      | String
Watchtime in Million           | String

### Display Summary Statistics for All Columns

In [17]:
summary = df.describe()
print(summary)

shape: (9, 8)
┌────────────┬─────────────┬────────────┬─────────┬────────────┬─────────┬────────────┬────────────┐
│ statistic  ┆ Rank        ┆ Title      ┆ Type    ┆ Premiere   ┆ Genre   ┆ Watchtime  ┆ Watchtime  │
│ ---        ┆ ---         ┆ ---        ┆ ---     ┆ ---        ┆ ---     ┆ ---        ┆ in Million │
│ str        ┆ f64         ┆ str        ┆ str     ┆ f64        ┆ str     ┆ str        ┆ ---        │
│            ┆             ┆            ┆         ┆            ┆         ┆            ┆ str        │
╞════════════╪═════════════╪════════════╪═════════╪════════════╪═════════╪════════════╪════════════╡
│ count      ┆ 18164.0     ┆ 18164      ┆ 18164   ┆ 18030.0    ┆ 18164   ┆ 18164      ┆ 18164      │
│ null_count ┆ 0.0         ┆ 0          ┆ 0       ┆ 134.0      ┆ 0       ┆ 0          ┆ 0          │
│ mean       ┆ 9126.719335 ┆ null       ┆ null    ┆ 2014.18829 ┆ null    ┆ null       ┆ null       │
│            ┆             ┆            ┆         ┆ 7          ┆         ┆            ┆            │
│ std        ┆ 5252.511432 ┆ null       ┆ null    ┆ 8.844017   ┆ null    ┆ null       ┆ null       │
│ min        ┆ 1.0         ┆ #Alive     ┆ Movie   ┆ 1940.0     ┆         ┆ 1,000,000  ┆ 0.1M       │
│ 25%        ┆ 4592.0      ┆ null       ┆ null    ┆ 2012.0     ┆ null    ┆ null       ┆ null       │
│ 50%        ┆ 9133.0      ┆ null       ┆ null    ┆ 2017.0     ┆ null    ┆ null       ┆ null       │
│ 75%        ┆ 13673.0     ┆ null       ┆ null    ┆ 2020.0     ┆ null    ┆ null       ┆ null       │
│ max        ┆ 18214.0     ┆ 한글용사   ┆ TV Show ┆ 2023.0     ┆ Western ┆ 99,900,000 ┆ 99.9M      │
│            ┆             ┆ 아이야     ┆         ┆            ┆         ┆            ┆            │
└────────────┴─────────────┴────────────┴─────────┴────────────┴─────────┴────────────┴────────────┘

### Find Longest Text Length in Each Column

In [18]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 5)
┌───────┬──────┬───────┬───────────┬──────────────────────┐
│ Title ┆ Type ┆ Genre ┆ Watchtime ┆ Watchtime in Million │
│ ---   ┆ ---  ┆ ---   ┆ ---       ┆ ---                  │
│ u32   ┆ u32  ┆ u32   ┆ u32       ┆ u32                  │
╞═══════╪══════╪═══════╪═══════════╪══════════════════════╡
│ 104   ┆ 7    ┆ 15    ┆ 11        ┆ 6                    │
└───────┴──────┴───────┴───────────┴──────────────────────┘

### Retrieve Data Types of All Columns

In [19]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Float64, String, String, Int64, String, String, String]

### Count Unique Values in Each Column

In [20]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                         Unique values in Rank : 18164
                        Unique values in Title : 14509
                         Unique values in Type : 2
                     Unique values in Premiere : 74
                        Unique values in Genre : 29
                    Unique values in Watchtime : 710
         Unique values in Watchtime in Million : 710

### Check Distribution of Numerical Columns

In [21]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

Rank
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Rank        │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 18164.0     │
│ null_count ┆ 0.0         │
│ mean       ┆ 9126.719335 │
│ std        ┆ 5252.511432 │
│ min        ┆ 1.0         │
│ 25%        ┆ 4592.0      │
│ 50%        ┆ 9133.0      │
│ 75%        ┆ 13673.0     │
│ max        ┆ 18214.0     │
└────────────┴─────────────┘


Premiere
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Premiere    │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 18030.0     │
│ null_count ┆ 134.0       │
│ mean       ┆ 2014.188297 │
│ std        ┆ 8.844017    │
│ min        ┆ 1940.0      │
│ 25%        ┆ 2012.0      │
│ 50%        ┆ 2017.0      │
│ 75%        ┆ 2020.0      │
│ max        ┆ 2023.0      │
└────────────┴─────────────┘

### List Unique Values For Certain Features

In [22]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: Type (2 unique values)
shape: (2,)
Series: 'Type' [str]
[
	"Movie"
	"TV Show"
]
--------------------------------------------------
Column: Premiere (74 unique values)
shape: (74,)
Series: 'Premiere' [i64]
[
	null
	1940
	1951
	1952
	1953
	1954
	1955
	1956
	1957
	1958
	1960
	1961
	1962
	1963
	1964
	1965
	1966
	1967
	…
	2007
	2008
	2009
	2010
	2011
	2012
	2013
	2014
	2015
	2016
	2017
	2018
	2019
	2020
	2021
	2022
	2023
]
--------------------------------------------------
Column: Genre (29 unique values)
shape: (29,)
Series: 'Genre' [str]
[
	""
	"Action"
	"Adventure"
	"Animation"
	"Biography"
	"Broadcast"
	"Comedy"
	"Concerts"
	"Crime"
	"Documentary"
	"Drama"
	"Fairy Tale"
	"Family"
	"Fantasy"
	"Game-Show"
	"History"
	"Horror"
	"Musical"
	"News"
	"Reality-Show"
	"Romance"
	"Science Fiction"
	"Sports"
	"Stand-Up"
	"Superhero"
	"Talk Show"
	"Thriller"
	"War"
	"Western"
]
--------------------------------------------------
Column: Watchtime (710 unique values)
shape: (710,)
Series: 'Watchtime' [str]
[
	"1,000,000"
	"1,100,000"
	"1,200,000"
	"1,300,000"
	"1,400,000"
	"1,500,000"
	"1,600,000"
	"1,700,000"
	"1,800,000"
	"1,900,000"
	"10,000,000"
	"10,100,000"
	"10,200,000"
	"10,300,000"
	"10,400,000"
	"10,500,000"
	"10,600,000"
	"10,700,000"
	…
	"92,900,000"
	"94,200,000"
	"94,300,000"
	"94,400,000"
	"94,600,000"
	"94,700,000"
	"95,000,000"
	"95,100,000"
	"95,700,000"
	"95,800,000"
	"96,400,000"
	"97,600,000"
	"97,800,000"
	"98,500,000"
	"99,000,000"
	"99,500,000"
	"99,900,000"
]
--------------------------------------------------
Column: Watchtime in Million (710 unique values)
shape: (710,)
Series: 'Watchtime in Million' [str]
[
	"0.1M"
	"0.2M"
	"0.3M"
	"0.4M"
	"0.5M"
	"0.6M"
	"0.7M"
	"0.8M"
	"0.9M"
	"1.0M"
	"1.1M"
	"1.2M"
	"1.3M"
	"1.4M"
	"1.5M"
	"1.6M"
	"1.7M"
	"1.8M"
	…
	"92.9M"
	"94.2M"
	"94.3M"
	"94.4M"
	"94.6M"
	"94.7M"
	"95.0M"
	"95.1M"
	"95.7M"
	"95.8M"
	"96.4M"
	"97.6M"
	"97.8M"
	"98.5M"
	"99.0M"
	"99.5M"
	"99.9M"
]
--------------------------------------------------

In [23]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

Column: Rank (18164 unique values)
shape: (18_164,)
Series: 'Rank' [f64]
[
	1.0
	2.0
	3.0
	4.0
	5.0
	6.0
	7.0
	8.0
	9.0
	10.0
	11.0
	12.0
	13.0
	14.0
	15.0
	16.0
	17.0
	18.0
	…
	18198.0
	18199.0
	18200.0
	18201.0
	18202.0
	18203.0
	18204.0
	18205.0
	18206.0
	18207.0
	18208.0
	18209.0
	18210.0
	18211.0
	18212.0
	18213.0
	18214.0
]
--------------------------------------------------
Column: Title (14509 unique values)
shape: (14_509,)
Series: 'Title' [str]
[
	"#Alive"
	"#FriendButMarried"
	"#FriendButMarried 2"
	"#Jowable"
	"#LadyRancho"
	"#NoFilter"
	"#SquadGoals"
	"#blackAF"
	"#realityhigh"
	"'71"
	"'Golden Hour' Billkin The Firs…
	"(Un)Well"
	"...altrimenti ci arrabbiamo!"
	"1 Woman 1 Man"
	"10 Cloverfield Lane"
	"10 Days of a Good Man"
	"10 Minute Workouts"
	"10 Minutes Gone"
	…
	"Üç Harfliler: Beddua"
	"Čertoviny"
	"Červený kapitán"
	"Čtyřlístek ve službách krále"
	"Ōoku: The Inner Chambers"
	"Święty interes"
	"Şahane Hayaller"
	"Špindl"
	"Żyć nie umierać"
	"Ženská na vrcholu"
	"Козаки. Абсолютно брехлива іст…
	"恋愛観察バラエティー あいのり"
	"恋愛観察バラエティー あいのり2"
	"대한민국 치킨대전"
	"뽀로로 동화나라"
	"최고다! 호기심딱지"
	"한글용사 아이야"
]
--------------------------------------------------