## Exploratory Data Analysis

### Import Libraries

In [5]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [6]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [7]:
df = pl.read_csv(
    "../couchbase_scripts/data/Customer.csv", 
    ignore_errors=True, 
    truncate_ragged_lines=True
    )

df

shape: (2_000, 19)
┌────────────┬────────┬────────────┬───────────┬───┬────────────┬────────────┬────────┬────────────┐
│ CUST_ID    ┆ GENDER ┆ FIRST_NAME ┆ LAST_NAME ┆ … ┆ PROFESSION ┆ RETIREMENT ┆ STATUS ┆ WALLET_SHA │
│ ---        ┆ ---    ┆ ---        ┆ ---       ┆   ┆ ---        ┆ _AGE       ┆ ---    ┆ RE_PERCENT │
│ str        ┆ str    ┆ str        ┆ str       ┆   ┆ str        ┆ ---        ┆ str    ┆ AGE        │
│            ┆        ┆            ┆           ┆   ┆            ┆ i64        ┆        ┆ ---        │
│            ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆ i64        │
╞════════════╪════════╪════════════╪═══════════╪═══╪════════════╪════════════╪════════╪════════════╡
│ CUST-41791 ┆ Male   ┆ Tiphanie   ┆ Dakin     ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 78         │
│ 1          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-75889 ┆ Male   ┆ Michael    ┆ Simpson   ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 76         │
│ 8          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-95868 ┆ Male   ┆ Denise     ┆ Lopez     ┆ … ┆ Data       ┆ 67         ┆ Active ┆ 30         │
│ 4          ┆        ┆            ┆           ┆   ┆ Scientist  ┆            ┆        ┆            │
│ CUST-12457 ┆ Male   ┆ Amanda     ┆ Taylor    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 19         │
│ 4          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-19878 ┆ Male   ┆ Lonnard    ┆ Deware    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 21         │
│ 1          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …          ┆ …          ┆ …      ┆ …          │
│ CUST-71729 ┆ Female ┆ Hill       ┆ Kerwood   ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 50         │
│ 6          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-78069 ┆ Female ┆ Jimmy      ┆ Maldonado ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 48         │
│ 4          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-78742 ┆ Female ┆ Ann        ┆ Ochoa     ┆ … ┆ Software   ┆ 67         ┆ Active ┆ 19         │
│ 0          ┆        ┆            ┆           ┆   ┆ Developer  ┆            ┆        ┆            │
│ CUST-34648 ┆ Male   ┆ William    ┆ Gonzalez  ┆ … ┆ Physician  ┆ 67         ┆ Active ┆ 24         │
│ 5          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
│ CUST-34013 ┆ Male   ┆ Piper      ┆ Menary    ┆ … ┆ Physician  ┆ 67         ┆ Closed ┆ 23         │
│ 7          ┆        ┆            ┆           ┆   ┆            ┆            ┆        ┆            │
└────────────┴────────┴────────────┴───────────┴───┴────────────┴────────────┴────────┴────────────┘

### Retrieve Number of Nulls in Each Feature

In [8]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (19, 2)
┌───────────────────────────────┬────────────┐
│ feature                       ┆ null_count │
│ ---                           ┆ ---        │
│ str                           ┆ i64        │
╞═══════════════════════════════╪════════════╡
│ CUST_ID                       ┆ 0          │
│ GENDER                        ┆ 0          │
│ FIRST_NAME                    ┆ 0          │
│ LAST_NAME                     ┆ 0          │
│ EMAIL                         ┆ 0          │
│ SSN                           ┆ 0          │
│ AGE_RANGE                     ┆ 0          │
│ ANNUAL_INCOME                 ┆ 0          │
│ BIRTH_YEAR                    ┆ 0          │
│ CURRENT_EMPLOYMENT_START_DATE ┆ 0          │
│ CUSTOMER_BEHAVIOR             ┆ 0          │
│ EDUCATION_LEVEL               ┆ 0          │
│ EMPLOYMENT_STATUS             ┆ 0          │
│ MARITAL_STATUS                ┆ 0          │
│ MONTHLY_NET_INCOME            ┆ 0          │
│ PROFESSION                    ┆ 0          │
│ RETIREMENT_AGE                ┆ 0          │
│ STATUS                        ┆ 0          │
│ WALLET_SHARE_PERCENTAGE       ┆ 0          │
└───────────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [9]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
CUST_ID                        | String
GENDER                         | String
FIRST_NAME                     | String
LAST_NAME                      | String
EMAIL                          | String
SSN                            | String
AGE_RANGE                      | String
ANNUAL_INCOME                  | String
BIRTH_YEAR                     | Int64
CURRENT_EMPLOYMENT_START_DATE  | String
CUSTOMER_BEHAVIOR              | String
EDUCATION_LEVEL                | String
EMPLOYMENT_STATUS              | String
MARITAL_STATUS                 | String
MONTHLY_NET_INCOME             | Int64
PROFESSION                     | String
RETIREMENT_AGE                 | Int64
STATUS                         | String
WALLET_SHARE_PERCENTAGE        | Int64

### Display Summary Statistics for All Columns

In [10]:
summary = df.describe()
print(summary)

shape: (9, 20)
┌────────────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬────────┬───────────┐
│ statistic  ┆ CUST_ID    ┆ GENDER ┆ FIRST_NAME ┆ … ┆ PROFESSION ┆ RETIREMENT ┆ STATUS ┆ WALLET_SH │
│ ---        ┆ ---        ┆ ---    ┆ ---        ┆   ┆ ---        ┆ _AGE       ┆ ---    ┆ ARE_PERCE │
│ str        ┆ str        ┆ str    ┆ str        ┆   ┆ str        ┆ ---        ┆ str    ┆ NTAGE     │
│            ┆            ┆        ┆            ┆   ┆            ┆ f64        ┆        ┆ ---       │
│            ┆            ┆        ┆            ┆   ┆            ┆            ┆        ┆ f64       │
╞════════════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ count      ┆ 2000       ┆ 2000   ┆ 2000       ┆ … ┆ 2000       ┆ 2000.0     ┆ 2000   ┆ 2000.0    │
│ null_count ┆ 0          ┆ 0      ┆ 0          ┆ … ┆ 0          ┆ 0.0        ┆ 0      ┆ 0.0       │
│ mean       ┆ null       ┆ null   ┆ null       ┆ … ┆ null       ┆ 67.0       ┆ null   ┆ 39.4245   │
│ std        ┆ null       ┆ null   ┆ null       ┆ … ┆ null       ┆ 0.0        ┆ null   ┆ 21.83556  │
│ min        ┆ CUST-10006 ┆ Female ┆ Aaren      ┆ … ┆ Accountant ┆ 67.0       ┆ Active ┆ 1.0       │
│            ┆ 7          ┆        ┆            ┆   ┆            ┆            ┆        ┆           │
│ 25%        ┆ null       ┆ null   ┆ null       ┆ … ┆ null       ┆ 67.0       ┆ null   ┆ 20.0      │
│ 50%        ┆ null       ┆ null   ┆ null       ┆ … ┆ null       ┆ 67.0       ┆ null   ┆ 38.0      │
│ 75%        ┆ null       ┆ null   ┆ null       ┆ … ┆ null       ┆ 67.0       ┆ null   ┆ 58.0      │
│ max        ┆ CUST-99918 ┆ Male   ┆ Zoe        ┆ … ┆ Trades     ┆ 67.0       ┆ Closed ┆ 80.0      │
│            ┆ 2          ┆        ┆            ┆   ┆ person     ┆            ┆        ┆           │
└────────────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴────────┴───────────┘

### Find Longest Text Length in Each Column

In [11]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 15)
┌─────────┬────────┬────────────┬───────────┬───┬──────────────┬─────────────┬────────────┬────────┐
│ CUST_ID ┆ GENDER ┆ FIRST_NAME ┆ LAST_NAME ┆ … ┆ EMPLOYMENT_S ┆ MARITAL_STA ┆ PROFESSION ┆ STATUS │
│ ---     ┆ ---    ┆ ---        ┆ ---       ┆   ┆ TATUS        ┆ TUS         ┆ ---        ┆ ---    │
│ u32     ┆ u32    ┆ u32        ┆ u32       ┆   ┆ ---          ┆ ---         ┆ u32        ┆ u32    │
│         ┆        ┆            ┆           ┆   ┆ u32          ┆ u32         ┆            ┆        │
╞═════════╪════════╪════════════╪═══════════╪═══╪══════════════╪═════════════╪════════════╪════════╡
│ 11      ┆ 6      ┆ 14         ┆ 17        ┆ … ┆ 12           ┆ 8           ┆ 18         ┆ 6      │
└─────────┴────────┴────────────┴───────────┴───┴──────────────┴─────────────┴────────────┴────────┘

### Retrieve Data Types of All Columns

In [12]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, String, String, String, String, Int64, String, String, String, String, String, Int64, String, Int64, String, Int64]

### Count Unique Values in Each Column

In [13]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                      Unique values in CUST_ID : 1999
                       Unique values in GENDER : 2
                   Unique values in FIRST_NAME : 1260
                    Unique values in LAST_NAME : 1481
                        Unique values in EMAIL : 1999
                          Unique values in SSN : 1810
                    Unique values in AGE_RANGE : 5
                Unique values in ANNUAL_INCOME : 1992
                   Unique values in BIRTH_YEAR : 63
Unique values in CURRENT_EMPLOYMENT_START_DATE : 674
            Unique values in CUSTOMER_BEHAVIOR : 4
              Unique values in EDUCATION_LEVEL : 5
            Unique values in EMPLOYMENT_STATUS : 4
               Unique values in MARITAL_STATUS : 3
           Unique values in MONTHLY_NET_INCOME : 1843
                   Unique values in PROFESSION : 7
               Unique values in RETIREMENT_AGE : 1
                       Unique values in STATUS : 2
      Unique values in WALLET_SHARE_PERCENTAGE : 80

### Check Distribution of Numerical Columns

In [14]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

BIRTH_YEAR
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ BIRTH_YEAR │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 2000.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 1964.9475  │
│ std        ┆ 16.461903  │
│ min        ┆ 1933.0     │
│ 25%        ┆ 1951.0     │
│ 50%        ┆ 1965.0     │
│ 75%        ┆ 1979.0     │
│ max        ┆ 1995.0     │
└────────────┴────────────┘


MONTHLY_NET_INCOME
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ MONTHLY_NET_INCOME │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 2000.0             │
│ null_count ┆ 0.0                │
│ mean       ┆ 10826.2505         │
│ std        ┆ 6599.978677        │
│ min        ┆ 2400.0             │
│ 25%        ┆ 5729.0             │
│ 50%        ┆ 9020.0             │
│ 75%        ┆ 15316.0            │
│ max        ┆ 37066.0            │
└────────────┴────────────────────┘


RETIREMENT_AGE
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ RETIREMENT_AGE │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 2000.0         │
│ null_count ┆ 0.0            │
│ mean       ┆ 67.0           │
│ std        ┆ 0.0            │
│ min        ┆ 67.0           │
│ 25%        ┆ 67.0           │
│ 50%        ┆ 67.0           │
│ 75%        ┆ 67.0           │
│ max        ┆ 67.0           │
└────────────┴────────────────┘


WALLET_SHARE_PERCENTAGE
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ WALLET_SHARE_PERCENTAGE │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 2000.0                  │
│ null_count ┆ 0.0                     │
│ mean       ┆ 39.4245                 │
│ std        ┆ 21.83556                │
│ min        ┆ 1.0                     │
│ 25%        ┆ 20.0                    │
│ 50%        ┆ 38.0                    │
│ 75%        ┆ 58.0                    │
│ max        ┆ 80.0                    │
└────────────┴─────────────────────────┘

### List Unique Values For Certain Features

In [15]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: CUST_ID (1999 unique values)
shape: (1_999,)
Series: 'CUST_ID' [str]
[
	"CUST-100067"
	"CUST-100282"
	"CUST-100396"
	"CUST-100400"
	"CUST-100417"
	"CUST-100655"
	"CUST-100759"
	"CUST-101785"
	"CUST-101865"
	"CUST-102995"
	"CUST-103026"
	"CUST-103108"
	"CUST-103227"
	"CUST-104309"
	"CUST-104713"
	"CUST-105166"
	"CUST-106996"
	"CUST-107207"
	…
	"CUST-993400"
	"CUST-994052"
	"CUST-994211"
	"CUST-994613"
	"CUST-994795"
	"CUST-994918"
	"CUST-994965"
	"CUST-995095"
	"CUST-996204"
	"CUST-997038"
	"CUST-997072"
	"CUST-997260"
	"CUST-997681"
	"CUST-998954"
	"CUST-998988"
	"CUST-999095"
	"CUST-999182"
]
--------------------------------------------------
Column: GENDER (2 unique values)
shape: (2,)
Series: 'GENDER' [str]
[
	"Female"
	"Male"
]
--------------------------------------------------
Column: FIRST_NAME (1260 unique values)
shape: (1_260,)
Series: 'FIRST_NAME' [str]
[
	"Aaren"
	"Aaron"
	"Abbe"
	"Abbey"
	"Abbott"
	"Abdel"
	"Abelard"
	"Abeu"
	"Abigail"
	"Abram"
	"Adah"
	"Adam"
	"Adams"
	"Addie"
	"Adele"
	"Adella"
	"Adlai"
	"Adolphe"
	…
	"Xavier"
	"Yetty"
	"Yolande"
	"Yolanthe"
	"York"
	"Yorke"
	"Yuma"
	"Yuri"
	"Yves"
	"Yvette"
	"Yvonne"
	"Zachary"
	"Zandra"
	"Zeb"
	"Zebulen"
	"Zenia"
	"Zoe"
]
--------------------------------------------------
Column: LAST_NAME (1481 unique values)
shape: (1_481,)
Series: 'LAST_NAME' [str]
[
	"Abberley"
	"Abbott"
	"Abbotts"
	"Abdie"
	"Aberdein"
	"Abrahami"
	"Abramow"
	"Adamov"
	"Adams"
	"Addenbrooke"
	"Aguilar"
	"Aguirre"
	"Aicheson"
	"Airey"
	"Aitcheson"
	"Akester"
	"Akister"
	"Alans"
	…
	"Wyatt"
	"Wye"
	"Yakovich"
	"Yalden"
	"Yang"
	"Yearby"
	"Yegorov"
	"Yitshak"
	"Young"
	"Younge"
	"Yuryev"
	"Zelner"
	"Zielinski"
	"Zimmer"
	"Zorzin"
	"Zuniga"
	"Zupone"
]
--------------------------------------------------
Column: EMAIL (1999 unique values)
shape: (1_999,)
Series: 'EMAIL' [str]
[
	"aalanse1@mit.edu"
	"aantosjn@mapquest.com"
	"aaron17@gmail.com"
	"aaronbarnes@yahoo.com"
	"aarongutierrez@hotmail.com"
	"aaronpacheco@hotmail.com"
	"aaronrodriguez@yahoo.com"
	"aatlaygx@pinterest.com"
	"aaudsleym1@state.tx.us"
	"abarde7g@tinypic.com"
	"abatalini7k@forbes.com"
	"abeeversee@qq.com"
	"abernaert9t@comcast.net"
	"abevareu@wikia.com"
	"abloxlandpr@devhub.com"
	"abostick4c@samsung.com"
	"aboughqq@opensource.org"
	"abrayfordjx@merriam-webster.co…
	…
	"zduncan@gmail.com"
	"zfotheringhamhz@pcworld.com"
	"zgarcia@gmail.com"
	"zhernandez@yahoo.com"
	"zholder@yahoo.com"
	"zlee@yahoo.com"
	"zmaypoleby@tripadvisor.com"
	"zoe54@gmail.com"
	"zpratt@gmail.com"
	"zrichardson@gmail.com"
	"zrocha@hotmail.com"
	"zsnyder@yahoo.com"
	"zstout@gmail.com"
	"ztucker@hotmail.com"
	"zvilla@yahoo.com"
	"zwye8g@bigcartel.com"
	"zyounge7i@sitemeter.com"
]
--------------------------------------------------
Column: SSN (1810 unique values)
shape: (1_810,)
Series: 'SSN' [str]
[
	"XXX-XX-0004"
	"XXX-XX-0006"
	"XXX-XX-0010"
	"XXX-XX-0023"
	"XXX-XX-0027"
	"XXX-XX-0030"
	"XXX-XX-0034"
	"XXX-XX-0036"
	"XXX-XX-0037"
	"XXX-XX-0046"
	"XXX-XX-0066"
	"XXX-XX-0067"
	"XXX-XX-0070"
	"XXX-XX-0086"
	"XXX-XX-0092"
	"XXX-XX-0094"
	"XXX-XX-0102"
	"XXX-XX-0103"
	…
	"XXX-XX-9898"
	"XXX-XX-9901"
	"XXX-XX-9904"
	"XXX-XX-9928"
	"XXX-XX-9931"
	"XXX-XX-9934"
	"XXX-XX-9941"
	"XXX-XX-9946"
	"XXX-XX-9949"
	"XXX-XX-9951"
	"XXX-XX-9959"
	"XXX-XX-9965"
	"XXX-XX-9966"
	"XXX-XX-9971"
	"XXX-XX-9991"
	"XXX-XX-9992"
	"XXX-XX-9999"
]
--------------------------------------------------
Column: AGE_RANGE (5 unique values)
shape: (5,)
Series: 'AGE_RANGE' [str]
[
	"25 to 29"
	"30 to 39"
	"40 to 54"
	"55 to 64"
	"65 and over"
]
--------------------------------------------------
Column: ANNUAL_INCOME (1992 unique values)
shape: (1_992,)
Series: 'ANNUAL_INCOME' [str]
[
	"$100,092.00 "
	"$100,130.00 "
	"$100,218.00 "
	"$100,307.00 "
	"$100,440.00 "
	"$100,480.00 "
	"$100,612.00 "
	"$100,698.00 "
	"$100,982.00 "
	"$101,071.00 "
	"$101,320.00 "
	"$101,366.00 "
	"$101,367.00 "
	"$101,514.00 "
	"$101,573.00 "
	"$101,804.00 "
	"$102,194.00 "
	"$102,325.00 "
	…
	"$98,011.00 "
	"$98,028.00 "
	"$98,144.00 "
	"$98,248.00 "
	"$98,403.00 "
	"$98,485.00 "
	"$98,593.00 "
	"$98,652.00 "
	"$98,735.00 "
	"$98,751.00 "
	"$98,965.00 "
	"$99,005.00 "
	"$99,152.00 "
	"$99,175.00 "
	"$99,248.00 "
	"$99,935.00 "
	"$99,997.00 "
]
--------------------------------------------------
Column: BIRTH_YEAR (63 unique values)
shape: (63,)
Series: 'BIRTH_YEAR' [i64]
[
	1933
	1934
	1935
	1936
	1937
	1938
	1939
	1940
	1941
	1942
	1943
	1944
	1945
	1946
	1947
	1948
	1949
	1950
	…
	1979
	1980
	1981
	1982
	1983
	1984
	1985
	1986
	1987
	1988
	1989
	1990
	1991
	1992
	1993
	1994
	1995
]
--------------------------------------------------
Column: CURRENT_EMPLOYMENT_START_DATE (674 unique values)
shape: (674,)
Series: 'CURRENT_EMPLOYMENT_START_DATE' [str]
[
	"1/1/14"
	"1/1/16"
	"1/10/15"
	"1/10/16"
	"1/11/15"
	"1/11/16"
	"1/11/17"
	"1/12/15"
	"1/12/16"
	"1/13/16"
	"1/13/17"
	"1/15/14"
	"1/15/16"
	"1/16/14"
	"1/16/15"
	"1/16/16"
	"1/18/14"
	"1/19/15"
	…
	"9/29/14"
	"9/29/15"
	"9/3/15"
	"9/3/17"
	"9/30/15"
	"9/30/16"
	"9/4/14"
	"9/5/16"
	"9/6/15"
	"9/6/16"
	"9/7/15"
	"9/7/16"
	"9/7/17"
	"9/8/14"
	"9/8/15"
	"9/8/16"
	"9/9/14"
]
--------------------------------------------------
Column: CUSTOMER_BEHAVIOR (4 unique values)
shape: (4,)
Series: 'CUSTOMER_BEHAVIOR' [str]
[
	"Aggressive"
	"Conservative"
	"Growth"
	"Moderate"
]
--------------------------------------------------
Column: EDUCATION_LEVEL (5 unique values)
shape: (5,)
Series: 'EDUCATION_LEVEL' [str]
[
	"College"
	"High School"
	"PhD"
	"Professional"
	"University"
]
--------------------------------------------------
Column: EMPLOYMENT_STATUS (4 unique values)
shape: (4,)
Series: 'EMPLOYMENT_STATUS' [str]
[
	"Employed"
	"Retired"
	"Selfemployed"
	"Unemployed"
]
--------------------------------------------------
Column: MARITAL_STATUS (3 unique values)
shape: (3,)
Series: 'MARITAL_STATUS' [str]
[
	"Divorced"
	"Married"
	"Single"
]
--------------------------------------------------
Column: MONTHLY_NET_INCOME (1843 unique values)
shape: (1_843,)
Series: 'MONTHLY_NET_INCOME' [i64]
[
	2400
	2403
	2405
	2408
	2414
	2417
	2420
	2429
	2434
	2435
	2436
	2440
	2442
	2445
	2446
	2451
	2453
	2456
	…
	29708
	29765
	29787
	30652
	30661
	30753
	31286
	31313
	31985
	32054
	32718
	32733
	32813
	36022
	36813
	37007
	37066
]
--------------------------------------------------
Column: PROFESSION (7 unique values)
shape: (7,)
Series: 'PROFESSION' [str]
[
	"Accountant"
	"Data Scientist"
	"Lawyer"
	"Physician"
	"Professor"
	"Software Developer"
	"Trades person"
]
--------------------------------------------------
Column: RETIREMENT_AGE (1 unique values)
shape: (1,)
Series: 'RETIREMENT_AGE' [i64]
[
	67
]
--------------------------------------------------
Column: STATUS (2 unique values)
shape: (2,)
Series: 'STATUS' [str]
[
	"Active"
	"Closed"
]
--------------------------------------------------
Column: WALLET_SHARE_PERCENTAGE (80 unique values)
shape: (80,)
Series: 'WALLET_SHARE_PERCENTAGE' [i64]
[
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	18
	…
	64
	65
	66
	67
	68
	69
	70
	71
	72
	73
	74
	75
	76
	77
	78
	79
	80
]
--------------------------------------------------

In [16]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

### How Many Records Remain IF I Remove Records With Any Nulls In It

In [17]:
def drop_rows_with_any_nulls(df: pl.DataFrame) -> pl.DataFrame:
    """
    Removes all rows from a Polars DataFrame that contain any null values.
    """
    return df.drop_nulls()


drop_rows_with_any_nulls(df)

shape: (2_000, 19)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬────────┬───────────┐
│ CUST_ID    ┆ GENDER ┆ FIRST_NAME ┆ LAST_NAME  ┆ … ┆ PROFESSION ┆ RETIREMENT ┆ STATUS ┆ WALLET_SH │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ _AGE       ┆ ---    ┆ ARE_PERCE │
│ str        ┆ str    ┆ str        ┆ str        ┆   ┆ str        ┆ ---        ┆ str    ┆ NTAGE     │
│            ┆        ┆            ┆            ┆   ┆            ┆ i64        ┆        ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆ i64       │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ CUST-41791 ┆ Male   ┆ Tiphanie   ┆ Dakin      ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 78        │
│ 1          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-75889 ┆ Male   ┆ Michael    ┆ Simpson    ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 76        │
│ 8          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-95868 ┆ Male   ┆ Denise     ┆ Lopez      ┆ … ┆ Data       ┆ 67         ┆ Active ┆ 30        │
│ 4          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-12457 ┆ Male   ┆ Amanda     ┆ Taylor     ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 19        │
│ 4          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-19878 ┆ Male   ┆ Lonnard    ┆ Deware     ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 21        │
│ 1          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-22867 ┆ Female ┆ Larry      ┆ French     ┆ … ┆ Software   ┆ 67         ┆ Active ┆ 45        │
│ 6          ┆        ┆            ┆            ┆   ┆ Developer  ┆            ┆        ┆           │
│ CUST-46412 ┆ Female ┆ Laura      ┆ Yang       ┆ … ┆ Data       ┆ 67         ┆ Active ┆ 69        │
│ 4          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-52940 ┆ Female ┆ Nicolette  ┆ Pimbley    ┆ … ┆ Data       ┆ 67         ┆ Active ┆ 71        │
│ 7          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-52300 ┆ Male   ┆ Creight    ┆ Garmston   ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 13        │
│ 2          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-79485 ┆ Male   ┆ Christy    ┆ Cherry     ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 16        │
│ 3          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-67772 ┆ Male   ┆ Christophe ┆ Page       ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 24        │
│ 0          ┆        ┆ r          ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-84088 ┆ Male   ┆ Dominique  ┆ Hargroves  ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 27        │
│ 0          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-73110 ┆ Male   ┆ Jeremy     ┆ Stranaghan ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 28        │
│ 1          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-93996 ┆ Female ┆ Michelle   ┆ Ward       ┆ … ┆ Software   ┆ 67         ┆ Active ┆ 40        │
│ 0          ┆        ┆            ┆            ┆   ┆ Developer  ┆            ┆        ┆           │
│ CUST-65735 ┆ Male   ┆ Aaron      ┆ Salazar    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 56        │
│ 0          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-23595 ┆ Male   ┆ Stephanie  ┆ Grant      ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 64        │
│ 4          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-98484 ┆ Male   ┆ Hailee     ┆ Luparti    ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 64        │
│ 9          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-57113 ┆ Male   ┆ Reggy      ┆ Ealles     ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 67        │
│ 0          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …      ┆ …         │
│ CUST-17498 ┆ Female ┆ Lori       ┆ Roberts    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 24        │
│ 7          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-46586 ┆ Female ┆ Austin     ┆ Trujillo   ┆ … ┆ Data       ┆ 67         ┆ Closed ┆ 21        │
│ 3          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-48717 ┆ Male   ┆ Tina       ┆ Davis      ┆ … ┆ Lawyer     ┆ 67         ┆ Active ┆ 71        │
│ 0          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-43745 ┆ Female ┆ Victoria   ┆ Hernandez  ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 44        │
│ 9          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-69663 ┆ Female ┆ Marlane    ┆ Ortiger    ┆ … ┆ Professor  ┆ 67         ┆ Closed ┆ 41        │
│ 5          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-39563 ┆ Female ┆ Leora      ┆ Stones     ┆ … ┆ Data       ┆ 67         ┆ Active ┆ 43        │
│ 0          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-27885 ┆ Female ┆ Dylan      ┆ West       ┆ … ┆ Data       ┆ 67         ┆ Closed ┆ 42        │
│ 7          ┆        ┆            ┆            ┆   ┆ Scientist  ┆            ┆        ┆           │
│ CUST-94968 ┆ Female ┆ Dalton     ┆ Johnson    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 10        │
│ 2          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-42388 ┆ Female ┆ Kathryn    ┆ Kerner     ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 8         │
│ 2          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-29839 ┆ Male   ┆ Samantha   ┆ Wright     ┆ … ┆ Accountant ┆ 67         ┆ Active ┆ 20        │
│ 6          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-56463 ┆ Female ┆ Russell    ┆ Gibson     ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 6         │
│ 2          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-63687 ┆ Female ┆ Danika     ┆ Anthonsen  ┆ … ┆ Professor  ┆ 67         ┆ Closed ┆ 7         │
│ 5          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-71729 ┆ Female ┆ Hill       ┆ Kerwood    ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 50        │
│ 6          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-78069 ┆ Female ┆ Jimmy      ┆ Maldonado  ┆ … ┆ Professor  ┆ 67         ┆ Active ┆ 48        │
│ 4          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-78742 ┆ Female ┆ Ann        ┆ Ochoa      ┆ … ┆ Software   ┆ 67         ┆ Active ┆ 19        │
│ 0          ┆        ┆            ┆            ┆   ┆ Developer  ┆            ┆        ┆           │
│ CUST-34648 ┆ Male   ┆ William    ┆ Gonzalez   ┆ … ┆ Physician  ┆ 67         ┆ Active ┆ 24        │
│ 5          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
│ CUST-34013 ┆ Male   ┆ Piper      ┆ Menary     ┆ … ┆ Physician  ┆ 67         ┆ Closed ┆ 23        │
│ 7          ┆        ┆            ┆            ┆   ┆            ┆            ┆        ┆           │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴────────┴───────────┘