## Exploratory Data Analysis

### Import Libraries

In [5]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [6]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [9]:
df = pl.read_csv(
    "../data/Account.csv", 
    ignore_errors=True, 
    truncate_ragged_lines=True
    )

df

shape: (2_000, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ ACQUISITI ┆ INTERNET_ ┆ DATE_FIRS ┆ … ┆ SATISFACT ┆ SECONDARY ┆ SECONDARY ┆ SPECIAL_ │
│ ---       ┆ ON_COST   ┆ BANKING_I ┆ T_ACCOUNT ┆   ┆ ION_RATIN ┆ _ADVISOR_ ┆ _ADVISOR_ ┆ TERMS_IN │
│ str       ┆ ---       ┆ NDICATOR  ┆ _OPENED   ┆   ┆ G_FROM_SU ┆ ID        ┆ ORGANIZAT ┆ DICATOR  │
│           ┆ f64       ┆ ---       ┆ ---       ┆   ┆ RVE…      ┆ ---       ┆ ION…      ┆ ---      │
│           ┆           ┆ bool      ┆ str       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ 62.143782 ┆ true      ┆ 2016-07-1 ┆ … ┆ neutral   ┆ 117227    ┆ 1004      ┆ false    │
│ 11        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ 59.672778 ┆ true      ┆ 2016-07-1 ┆ … ┆ neutral   ┆ 117227    ┆ 1004      ┆ false    │
│ 98        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ 51.088502 ┆ true      ┆ 2017-08-1 ┆ … ┆ satisfied ┆ 112458    ┆ 1001      ┆ false    │
│ 84        ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ 60.41846  ┆ true      ┆ 2016-08-2 ┆ … ┆ very      ┆ 127139    ┆ 1008      ┆ true     │
│ 74        ┆           ┆           ┆ 4         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-1987 ┆ 73.221376 ┆ true      ┆ 2016-08-2 ┆ … ┆ very      ┆ 127139    ┆ 1008      ┆ true     │
│ 81        ┆           ┆           ┆ 4         ┆   ┆ satisfied ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-7172 ┆ 22.301133 ┆ true      ┆ 2017-08-2 ┆ … ┆ very      ┆ 74116     ┆ 1006      ┆ true     │
│ 96        ┆           ┆           ┆ 8         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-7806 ┆ 81.650617 ┆ true      ┆ 2017-08-2 ┆ … ┆ very      ┆ 74116     ┆ 1006      ┆ true     │
│ 94        ┆           ┆           ┆ 8         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-7874 ┆ 19.072539 ┆ false     ┆ 2017-11-2 ┆ … ┆ very diss ┆ 139890    ┆ 1016      ┆ true     │
│ 20        ┆           ┆           ┆ 9         ┆   ┆ atisfied  ┆           ┆           ┆          │
│ CUST-3464 ┆ 55.030259 ┆ true      ┆ 2018-01-0 ┆ … ┆ satisfied ┆ 84892     ┆ 1008      ┆ true     │
│ 85        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ 3.220068  ┆ true      ┆ 2018-01-0 ┆ … ┆ satisfied ┆ 84892     ┆ 1008      ┆ true     │
│ 37        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Number of Nulls in Each Feature

In [10]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (14, 2)
┌─────────────────────────────────┬────────────┐
│ feature                         ┆ null_count │
│ ---                             ┆ ---        │
│ str                             ┆ i64        │
╞═════════════════════════════════╪════════════╡
│ CUST_ID                         ┆ 0          │
│ ACQUISITION_COST                ┆ 0          │
│ INTERNET_BANKING_INDICATOR      ┆ 0          │
│ DATE_FIRST_ACCOUNT_OPENED       ┆ 0          │
│ DATE_LAST_ACCOUNT_OPENED        ┆ 0          │
│ PURSUIT                         ┆ 0          │
│ PRIMARY_ADVISOR_ORGANIZATION_I… ┆ 0          │
│ PRIMARY_BRANCH_PROXIMITY        ┆ 0          │
│ PRIMARY_SPOKEN_LANGUAGE         ┆ 0          │
│ PRIMARY_WRITTEN_LANGUAGE        ┆ 0          │
│ SATISFACTION_RATING_FROM_SURVE… ┆ 0          │
│ SECONDARY_ADVISOR_ID            ┆ 0          │
│ SECONDARY_ADVISOR_ORGANIZATION… ┆ 0          │
│ SPECIAL_TERMS_INDICATOR         ┆ 0          │
└─────────────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [11]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<36} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<36} | {dtype}")

print_schema(df)

Column                               | Data Type
------------------------------------------------------------
CUST_ID                              | String
ACQUISITION_COST                     | Float64
INTERNET_BANKING_INDICATOR           | Boolean
DATE_FIRST_ACCOUNT_OPENED            | String
DATE_LAST_ACCOUNT_OPENED             | String
PURSUIT                              | String
PRIMARY_ADVISOR_ORGANIZATION_ID      | Int64
PRIMARY_BRANCH_PROXIMITY             | Int64
PRIMARY_SPOKEN_LANGUAGE              | String
PRIMARY_WRITTEN_LANGUAGE             | String
SATISFACTION_RATING_FROM_SURVEY      | String
SECONDARY_ADVISOR_ID                 | Int64
SECONDARY_ADVISOR_ORGANIZATION_ID    | Int64
SPECIAL_TERMS_INDICATOR              | Boolean

### Display Summary Statistics for All Columns

In [12]:
summary = df.describe()
print(summary)

shape: (9, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ CUST_ID   ┆ ACQUISITI ┆ INTERNET_ ┆ … ┆ SATISFACT ┆ SECONDARY ┆ SECONDARY ┆ SPECIAL_ │
│ ---       ┆ ---       ┆ ON_COST   ┆ BANKING_I ┆   ┆ ION_RATIN ┆ _ADVISOR_ ┆ _ADVISOR_ ┆ TERMS_IN │
│ str       ┆ str       ┆ ---       ┆ NDICATOR  ┆   ┆ G_FROM_SU ┆ ID        ┆ ORGANIZAT ┆ DICATOR  │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ RVE…      ┆ ---       ┆ ION…      ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2000      ┆ 2000.0    ┆ 2000.0    ┆ … ┆ 2000      ┆ 2000.0    ┆ 2000.0    ┆ 2000.0   │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 49.349437 ┆ 0.503     ┆ … ┆ null      ┆ 94858.757 ┆ 1007.0985 ┆ 0.5065   │
│ std       ┆ null      ┆ 29.056267 ┆ null      ┆ … ┆ null      ┆ 29056.460 ┆ 4.34583   ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆ 899       ┆           ┆          │
│ min       ┆ CUST-1000 ┆ -0.210121 ┆ 0.0       ┆ … ┆ dissatisf ┆ 45049.0   ┆ 1001.0    ┆ 0.0      │
│           ┆ 67        ┆           ┆           ┆   ┆ ied       ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 23.72862  ┆ null      ┆ … ┆ null      ┆ 69637.0   ┆ 1004.0    ┆ null     │
│ 50%       ┆ null      ┆ 48.913863 ┆ null      ┆ … ┆ null      ┆ 96246.0   ┆ 1007.0    ┆ null     │
│ 75%       ┆ null      ┆ 73.615801 ┆ null      ┆ … ┆ null      ┆ 119826.0  ┆ 1010.0    ┆ null     │
│ max       ┆ CUST-9991 ┆ 100.44560 ┆ 1.0       ┆ … ┆ very      ┆ 144944.0  ┆ 1019.0    ┆ 1.0      │
│           ┆ 82        ┆ 5         ┆           ┆   ┆ satisfied ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [13]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 7)
┌─────────┬───────────────┬───────────────┬─────────┬───────────────┬───────────────┬──────────────┐
│ CUST_ID ┆ DATE_FIRST_AC ┆ DATE_LAST_ACC ┆ PURSUIT ┆ PRIMARY_SPOKE ┆ PRIMARY_WRITT ┆ SATISFACTION │
│ ---     ┆ COUNT_OPENED  ┆ OUNT_OPENED   ┆ ---     ┆ N_LANGUAGE    ┆ EN_LANGUAGE   ┆ _RATING_FROM │
│ u32     ┆ ---           ┆ ---           ┆ u32     ┆ ---           ┆ ---           ┆ _SURVE…      │
│         ┆ u32           ┆ u32           ┆         ┆ u32           ┆ u32           ┆ ---          │
│         ┆               ┆               ┆         ┆               ┆               ┆ u32          │
╞═════════╪═══════════════╪═══════════════╪═════════╪═══════════════╪═══════════════╪══════════════╡
│ 11      ┆ 10            ┆ 10            ┆ 19      ┆ 7             ┆ 7             ┆ 17           │
└─────────┴───────────────┴───────────────┴─────────┴───────────────┴───────────────┴──────────────┘

### Retrieve Data Types of All Columns

In [14]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, Float64, Boolean, String, String, String, Int64, Int64, String, String, String, Int64, Int64, Boolean]

### Count Unique Values in Each Column

In [15]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(55), f"{unique_counts}".ljust(6))

                             Unique values in CUST_ID : 1999
                    Unique values in ACQUISITION_COST : 2000
          Unique values in INTERNET_BANKING_INDICATOR : 2
           Unique values in DATE_FIRST_ACCOUNT_OPENED : 228
            Unique values in DATE_LAST_ACCOUNT_OPENED : 228
                             Unique values in PURSUIT : 6
     Unique values in PRIMARY_ADVISOR_ORGANIZATION_ID : 19
            Unique values in PRIMARY_BRANCH_PROXIMITY : 631
             Unique values in PRIMARY_SPOKEN_LANGUAGE : 1
            Unique values in PRIMARY_WRITTEN_LANGUAGE : 1
     Unique values in SATISFACTION_RATING_FROM_SURVEY : 5
                Unique values in SECONDARY_ADVISOR_ID : 995
   Unique values in SECONDARY_ADVISOR_ORGANIZATION_ID : 19
             Unique values in SPECIAL_TERMS_INDICATOR : 2

### Check Distribution of Numerical Columns

In [16]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

ACQUISITION_COST
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ ACQUISITION_COST │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 2000.0           │
│ null_count ┆ 0.0              │
│ mean       ┆ 49.349437        │
│ std        ┆ 29.056267        │
│ min        ┆ -0.210121        │
│ 25%        ┆ 23.72862         │
│ 50%        ┆ 48.913863        │
│ 75%        ┆ 73.615801        │
│ max        ┆ 100.445605       │
└────────────┴──────────────────┘


INTERNET_BANKING_INDICATOR
shape: (9, 2)
┌────────────┬────────────────────────────┐
│ statistic  ┆ INTERNET_BANKING_INDICATOR │
│ ---        ┆ ---                        │
│ str        ┆ f64                        │
╞════════════╪════════════════════════════╡
│ count      ┆ 2000.0                     │
│ null_count ┆ 0.0                        │
│ mean       ┆ 0.503                      │
│ std        ┆ null                       │
│ min        ┆ 0.0                        │
│ 25%        ┆ null                       │
│ 50%        ┆ null                       │
│ 75%        ┆ null                       │
│ max        ┆ 1.0                        │
└────────────┴────────────────────────────┘


PRIMARY_ADVISOR_ORGANIZATION_ID
shape: (9, 2)
┌────────────┬─────────────────────────────────┐
│ statistic  ┆ PRIMARY_ADVISOR_ORGANIZATION_I… │
│ ---        ┆ ---                             │
│ str        ┆ f64                             │
╞════════════╪═════════════════════════════════╡
│ count      ┆ 2000.0                          │
│ null_count ┆ 0.0                             │
│ mean       ┆ 1007.0985                       │
│ std        ┆ 4.34583                         │
│ min        ┆ 1001.0                          │
│ 25%        ┆ 1004.0                          │
│ 50%        ┆ 1007.0                          │
│ 75%        ┆ 1010.0                          │
│ max        ┆ 1019.0                          │
└────────────┴─────────────────────────────────┘


PRIMARY_BRANCH_PROXIMITY
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ PRIMARY_BRANCH_PROXIMITY │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 2000.0                   │
│ null_count ┆ 0.0                      │
│ mean       ┆ 498.031                  │
│ std        ┆ 290.479544               │
│ min        ┆ 3.0                      │
│ 25%        ┆ 248.0                    │
│ 50%        ┆ 506.0                    │
│ 75%        ┆ 744.0                    │
│ max        ┆ 999.0                    │
└────────────┴──────────────────────────┘


SECONDARY_ADVISOR_ID
shape: (9, 2)
┌────────────┬──────────────────────┐
│ statistic  ┆ SECONDARY_ADVISOR_ID │
│ ---        ┆ ---                  │
│ str        ┆ f64                  │
╞════════════╪══════════════════════╡
│ count      ┆ 2000.0               │
│ null_count ┆ 0.0                  │
│ mean       ┆ 94858.757            │
│ std        ┆ 29056.460899         │
│ min        ┆ 45049.0              │
│ 25%        ┆ 69637.0              │
│ 50%        ┆ 96246.0              │
│ 75%        ┆ 119826.0             │
│ max        ┆ 144944.0             │
└────────────┴──────────────────────┘


SECONDARY_ADVISOR_ORGANIZATION_ID
shape: (9, 2)
┌────────────┬─────────────────────────────────┐
│ statistic  ┆ SECONDARY_ADVISOR_ORGANIZATION… │
│ ---        ┆ ---                             │
│ str        ┆ f64                             │
╞════════════╪═════════════════════════════════╡
│ count      ┆ 2000.0                          │
│ null_count ┆ 0.0                             │
│ mean       ┆ 1007.0985                       │
│ std        ┆ 4.34583                         │
│ min        ┆ 1001.0                          │
│ 25%        ┆ 1004.0                          │
│ 50%        ┆ 1007.0                          │
│ 75%        ┆ 1010.0                          │
│ max        ┆ 1019.0                          │
└────────────┴─────────────────────────────────┘


SPECIAL_TERMS_INDICATOR
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ SPECIAL_TERMS_INDICATOR │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 2000.0                  │
│ null_count ┆ 0.0                     │
│ mean       ┆ 0.5065                  │
│ std        ┆ null                    │
│ min        ┆ 0.0                     │
│ 25%        ┆ null                    │
│ 50%        ┆ null                    │
│ 75%        ┆ null                    │
│ max        ┆ 1.0                     │
└────────────┴─────────────────────────┘

### List Unique Values For Certain Features

In [17]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: CUST_ID (1999 unique values)
shape: (1_999,)
Series: 'CUST_ID' [str]
[
	"CUST-100067"
	"CUST-100282"
	"CUST-100396"
	"CUST-100400"
	"CUST-100417"
	"CUST-100655"
	"CUST-100759"
	"CUST-101785"
	"CUST-101865"
	"CUST-102995"
	"CUST-103026"
	"CUST-103108"
	"CUST-103227"
	"CUST-104309"
	"CUST-104713"
	"CUST-105166"
	"CUST-106996"
	"CUST-107207"
	…
	"CUST-993400"
	"CUST-994052"
	"CUST-994211"
	"CUST-994613"
	"CUST-994795"
	"CUST-994918"
	"CUST-994965"
	"CUST-995095"
	"CUST-996204"
	"CUST-997038"
	"CUST-997072"
	"CUST-997260"
	"CUST-997681"
	"CUST-998954"
	"CUST-998988"
	"CUST-999095"
	"CUST-999182"
]
--------------------------------------------------
Column: ACQUISITION_COST (2000 unique values)
shape: (2_000,)
Series: 'ACQUISITION_COST' [f64]
[
	-0.210121
	-0.009624
	0.133669
	0.207109
	0.241075
	0.443007
	0.469562
	0.564322
	0.579648
	0.592617
	0.625614
	0.723366
	0.730375
	0.743789
	0.745143
	0.759676
	0.893706
	0.914405
	…
	99.441134
	99.536167
	99.568318
	99.584106
	99.66162
	99.873683
	99.915383
	99.923572
	99.953999
	100.010307
	100.023722
	100.104388
	100.136744
	100.222248
	100.255112
	100.348228
	100.445605
]
--------------------------------------------------
Column: INTERNET_BANKING_INDICATOR (2 unique values)
shape: (2,)
Series: 'INTERNET_BANKING_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------
Column: DATE_FIRST_ACCOUNT_OPENED (228 unique values)
shape: (228,)
Series: 'DATE_FIRST_ACCOUNT_OPENED' [str]
[
	"2016-01-03"
	"2016-01-05"
	"2016-01-11"
	"2016-01-12"
	"2016-01-13"
	"2016-01-16"
	"2016-01-21"
	"2016-01-23"
	"2016-01-26"
	"2016-01-27"
	"2016-01-28"
	"2016-01-31"
	"2016-02-04"
	"2016-02-10"
	"2016-02-12"
	"2016-02-13"
	"2016-02-14"
	"2016-02-18"
	…
	"2018-07-07"
	"2018-07-11"
	"2018-07-20"
	"2018-07-21"
	"2018-07-23"
	"2018-07-24"
	"2018-07-29"
	"2018-08-01"
	"2018-08-06"
	"2018-08-20"
	"2018-08-27"
	"2018-08-28"
	"2018-09-02"
	"2018-09-04"
	"2018-09-05"
	"2018-09-13"
	"2018-09-14"
]
--------------------------------------------------
Column: DATE_LAST_ACCOUNT_OPENED (228 unique values)
shape: (228,)
Series: 'DATE_LAST_ACCOUNT_OPENED' [str]
[
	"2016-01-03"
	"2016-01-05"
	"2016-01-11"
	"2016-01-12"
	"2016-01-13"
	"2016-01-16"
	"2016-01-21"
	"2016-01-23"
	"2016-01-26"
	"2016-01-27"
	"2016-01-28"
	"2016-01-31"
	"2016-02-04"
	"2016-02-10"
	"2016-02-12"
	"2016-02-13"
	"2016-02-14"
	"2016-02-18"
	…
	"2018-07-07"
	"2018-07-11"
	"2018-07-20"
	"2018-07-21"
	"2018-07-23"
	"2018-07-24"
	"2018-07-29"
	"2018-08-01"
	"2018-08-06"
	"2018-08-20"
	"2018-08-27"
	"2018-08-28"
	"2018-09-02"
	"2018-09-04"
	"2018-09-05"
	"2018-09-13"
	"2018-09-14"
]
--------------------------------------------------
Column: PURSUIT (6 unique values)
shape: (6,)
Series: 'PURSUIT' [str]
[
	"Capital Acquisition"
	"Education Planning"
	"Estate Planning"
	"Increase Net Worth"
	"Philanthropy"
	"Retirement Planning"
]
--------------------------------------------------
Column: PRIMARY_ADVISOR_ORGANIZATION_ID (19 unique values)
shape: (19,)
Series: 'PRIMARY_ADVISOR_ORGANIZATION_ID' [i64]
[
	1001
	1002
	1003
	1004
	1005
	1006
	1007
	1008
	1009
	1010
	1011
	1012
	1013
	1014
	1015
	1016
	1017
	1018
	1019
]
--------------------------------------------------
Column: PRIMARY_BRANCH_PROXIMITY (631 unique values)
shape: (631,)
Series: 'PRIMARY_BRANCH_PROXIMITY' [i64]
[
	3
	4
	8
	9
	10
	13
	14
	15
	16
	18
	19
	20
	22
	24
	25
	26
	27
	29
	…
	980
	981
	982
	983
	984
	985
	987
	988
	989
	990
	992
	993
	994
	995
	996
	998
	999
]
--------------------------------------------------
Column: PRIMARY_SPOKEN_LANGUAGE (1 unique values)
shape: (1,)
Series: 'PRIMARY_SPOKEN_LANGUAGE' [str]
[
	"English"
]
--------------------------------------------------
Column: PRIMARY_WRITTEN_LANGUAGE (1 unique values)
shape: (1,)
Series: 'PRIMARY_WRITTEN_LANGUAGE' [str]
[
	"English"
]
--------------------------------------------------
Column: SATISFACTION_RATING_FROM_SURVEY (5 unique values)
shape: (5,)
Series: 'SATISFACTION_RATING_FROM_SURVEY' [str]
[
	"dissatisfied"
	"neutral"
	"satisfied"
	"very dissatisfied"
	"very satisfied"
]
--------------------------------------------------
Column: SECONDARY_ADVISOR_ID (995 unique values)
shape: (995,)
Series: 'SECONDARY_ADVISOR_ID' [i64]
[
	45049
	45063
	45103
	45316
	45335
	45411
	45487
	45529
	45569
	45600
	45628
	45655
	45950
	45964
	46075
	46182
	46501
	46547
	…
	143517
	143529
	143774
	143829
	143859
	143952
	143965
	144151
	144162
	144185
	144546
	144600
	144671
	144834
	144907
	144910
	144944
]
--------------------------------------------------
Column: SECONDARY_ADVISOR_ORGANIZATION_ID (19 unique values)
shape: (19,)
Series: 'SECONDARY_ADVISOR_ORGANIZATION_ID' [i64]
[
	1001
	1002
	1003
	1004
	1005
	1006
	1007
	1008
	1009
	1010
	1011
	1012
	1013
	1014
	1015
	1016
	1017
	1018
	1019
]
--------------------------------------------------
Column: SPECIAL_TERMS_INDICATOR (2 unique values)
shape: (2,)
Series: 'SPECIAL_TERMS_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------

In [18]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

### How Many Records Remain IF I Remove Records With Any Nulls In It

In [19]:
def drop_rows_with_any_nulls(df: pl.DataFrame) -> pl.DataFrame:
    """
    Removes all rows from a Polars DataFrame that contain any null values.
    """
    return df.drop_nulls()


drop_rows_with_any_nulls(df)

shape: (2_000, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ ACQUISITI ┆ INTERNET_ ┆ DATE_FIRS ┆ … ┆ SATISFACT ┆ SECONDARY ┆ SECONDARY ┆ SPECIAL_ │
│ ---       ┆ ON_COST   ┆ BANKING_I ┆ T_ACCOUNT ┆   ┆ ION_RATIN ┆ _ADVISOR_ ┆ _ADVISOR_ ┆ TERMS_IN │
│ str       ┆ ---       ┆ NDICATOR  ┆ _OPENED   ┆   ┆ G_FROM_SU ┆ ID        ┆ ORGANIZAT ┆ DICATOR  │
│           ┆ f64       ┆ ---       ┆ ---       ┆   ┆ RVE…      ┆ ---       ┆ ION…      ┆ ---      │
│           ┆           ┆ bool      ┆ str       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ 62.143782 ┆ true      ┆ 2016-07-1 ┆ … ┆ neutral   ┆ 117227    ┆ 1004      ┆ false    │
│ 11        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ 59.672778 ┆ true      ┆ 2016-07-1 ┆ … ┆ neutral   ┆ 117227    ┆ 1004      ┆ false    │
│ 98        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ 51.088502 ┆ true      ┆ 2017-08-1 ┆ … ┆ satisfied ┆ 112458    ┆ 1001      ┆ false    │
│ 84        ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ 60.41846  ┆ true      ┆ 2016-08-2 ┆ … ┆ very      ┆ 127139    ┆ 1008      ┆ true     │
│ 74        ┆           ┆           ┆ 4         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-1987 ┆ 73.221376 ┆ true      ┆ 2016-08-2 ┆ … ┆ very      ┆ 127139    ┆ 1008      ┆ true     │
│ 81        ┆           ┆           ┆ 4         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-2286 ┆ 25.343252 ┆ false     ┆ 2017-04-0 ┆ … ┆ very      ┆ 88379     ┆ 1016      ┆ false    │
│ 76        ┆           ┆           ┆ 6         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-4641 ┆ 44.518334 ┆ false     ┆ 2016-02-1 ┆ … ┆ very      ┆ 84254     ┆ 1005      ┆ true     │
│ 24        ┆           ┆           ┆ 0         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-5294 ┆ 53.714719 ┆ false     ┆ 2016-02-1 ┆ … ┆ very      ┆ 84254     ┆ 1005      ┆ true     │
│ 07        ┆           ┆           ┆ 0         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-5230 ┆ 90.463466 ┆ true      ┆ 2016-02-1 ┆ … ┆ neutral   ┆ 114807    ┆ 1002      ┆ false    │
│ 02        ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ CUST-7948 ┆ 26.552599 ┆ true      ┆ 2016-02-1 ┆ … ┆ neutral   ┆ 114807    ┆ 1002      ┆ false    │
│ 53        ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ CUST-6777 ┆ 54.57438  ┆ true      ┆ 2018-01-1 ┆ … ┆ satisfied ┆ 112197    ┆ 1014      ┆ false    │
│ 20        ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ CUST-8408 ┆ 27.598903 ┆ true      ┆ 2018-01-1 ┆ … ┆ satisfied ┆ 112197    ┆ 1014      ┆ false    │
│ 80        ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ CUST-7311 ┆ 96.765084 ┆ true      ┆ 2018-01-1 ┆ … ┆ satisfied ┆ 112197    ┆ 1014      ┆ false    │
│ 01        ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9399 ┆ 74.776109 ┆ true      ┆ 2018-06-0 ┆ … ┆ very diss ┆ 120631    ┆ 1016      ┆ true     │
│ 60        ┆           ┆           ┆ 6         ┆   ┆ atisfied  ┆           ┆           ┆          │
│ CUST-6573 ┆ 73.147812 ┆ false     ┆ 2016-06-2 ┆ … ┆ very      ┆ 77478     ┆ 1003      ┆ false    │
│ 50        ┆           ┆           ┆ 9         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-2359 ┆ 73.954438 ┆ true      ┆ 2016-09-0 ┆ … ┆ satisfied ┆ 103723    ┆ 1010      ┆ false    │
│ 54        ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9848 ┆ 26.771018 ┆ true      ┆ 2016-09-0 ┆ … ┆ satisfied ┆ 103723    ┆ 1010      ┆ false    │
│ 49        ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ CUST-5711 ┆ 2.651146  ┆ true      ┆ 2016-09-0 ┆ … ┆ satisfied ┆ 103723    ┆ 1010      ┆ false    │
│ 30        ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-1749 ┆ 97.980803 ┆ false     ┆ 2018-09-0 ┆ … ┆ very      ┆ 121837    ┆ 1013      ┆ false    │
│ 87        ┆           ┆           ┆ 5         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-4658 ┆ 73.812668 ┆ true      ┆ 2016-07-2 ┆ … ┆ satisfied ┆ 132725    ┆ 1010      ┆ true     │
│ 63        ┆           ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│ CUST-4871 ┆ 14.364744 ┆ false     ┆ 2018-02-0 ┆ … ┆ neutral   ┆ 143507    ┆ 1012      ┆ true     │
│ 70        ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ CUST-4374 ┆ 4.631362  ┆ true      ┆ 2016-12-2 ┆ … ┆ very      ┆ 67461     ┆ 1007      ┆ false    │
│ 59        ┆           ┆           ┆ 3         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-6966 ┆ 15.368614 ┆ true      ┆ 2016-12-2 ┆ … ┆ very      ┆ 67461     ┆ 1007      ┆ false    │
│ 35        ┆           ┆           ┆ 3         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-3956 ┆ 28.250403 ┆ false     ┆ 2017-08-0 ┆ … ┆ very      ┆ 139823    ┆ 1008      ┆ true     │
│ 30        ┆           ┆           ┆ 3         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-2788 ┆ 18.065435 ┆ false     ┆ 2017-08-0 ┆ … ┆ very      ┆ 139823    ┆ 1008      ┆ true     │
│ 57        ┆           ┆           ┆ 3         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-9496 ┆ 5.782327  ┆ false     ┆ 2017-11-0 ┆ … ┆ very      ┆ 131373    ┆ 1002      ┆ true     │
│ 82        ┆           ┆           ┆ 1         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-4238 ┆ 5.795277  ┆ false     ┆ 2017-11-0 ┆ … ┆ very      ┆ 131373    ┆ 1002      ┆ true     │
│ 82        ┆           ┆           ┆ 1         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-2983 ┆ 74.190786 ┆ false     ┆ 2018-01-0 ┆ … ┆ satisfied ┆ 132701    ┆ 1008      ┆ true     │
│ 96        ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│ CUST-5646 ┆ 58.807918 ┆ false     ┆ 2018-01-1 ┆ … ┆ very      ┆ 108109    ┆ 1007      ┆ true     │
│ 32        ┆           ┆           ┆ 7         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-6368 ┆ 57.397186 ┆ false     ┆ 2018-01-1 ┆ … ┆ very      ┆ 108109    ┆ 1007      ┆ true     │
│ 75        ┆           ┆           ┆ 7         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-7172 ┆ 22.301133 ┆ true      ┆ 2017-08-2 ┆ … ┆ very      ┆ 74116     ┆ 1006      ┆ true     │
│ 96        ┆           ┆           ┆ 8         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-7806 ┆ 81.650617 ┆ true      ┆ 2017-08-2 ┆ … ┆ very      ┆ 74116     ┆ 1006      ┆ true     │
│ 94        ┆           ┆           ┆ 8         ┆   ┆ satisfied ┆           ┆           ┆          │
│ CUST-7874 ┆ 19.072539 ┆ false     ┆ 2017-11-2 ┆ … ┆ very diss ┆ 139890    ┆ 1016      ┆ true     │
│ 20        ┆           ┆           ┆ 9         ┆   ┆ atisfied  ┆           ┆           ┆          │
│ CUST-3464 ┆ 55.030259 ┆ true      ┆ 2018-01-0 ┆ … ┆ satisfied ┆ 84892     ┆ 1008      ┆ true     │
│ 85        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ 3.220068  ┆ true      ┆ 2018-01-0 ┆ … ┆ satisfied ┆ 84892     ┆ 1008      ┆ true     │
│ 37        ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘