## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv(
    "../couchbase_scripts/data/Marketing.csv", 
    ignore_errors=True, 
    truncate_ragged_lines=True
    )

df

shape: (2_000, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ ADVERTISI ┆ ATTACHMEN ┆ PREFERRED ┆ … ┆ LOYALTY_R ┆ RECORDED_ ┆ REFERRALS ┆ RELATION │
│ ---       ┆ NG_INDICA ┆ T_ALLOWED ┆ _COMMUNIC ┆   ┆ ATING_COD ┆ VOICE_SAM ┆ _VALUE_CO ┆ SHIP_STA │
│ str       ┆ TOR       ┆ _INDICATO ┆ ATION_FOR ┆   ┆ E         ┆ PLE_ID    ┆ DE        ┆ RT_DATE  │
│           ┆ ---       ┆ R         ┆ M         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ bool      ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆ bool      ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 113633    ┆ 79027     ┆ Very High ┆ 7/12/16  │
│ 11        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 113633    ┆ 79172     ┆ Very High ┆ 7/12/16  │
│ 98        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ true      ┆ true      ┆ Teleconfe ┆ … ┆ 62773     ┆ 70208     ┆ Very Low  ┆ 8/15/17  │
│ 84        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 104010    ┆ 114804    ┆ Very High ┆ 8/24/16  │
│ 74        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1987 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 104010    ┆ 114786    ┆ Very High ┆ 8/24/16  │
│ 81        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-7172 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 54611     ┆ 60037     ┆ Low       ┆ 8/28/17  │
│ 96        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7806 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 54611     ┆ 60168     ┆ Low       ┆ 8/28/17  │
│ 94        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7874 ┆ true      ┆ true      ┆ Video Con ┆ … ┆ 80883     ┆ 90987     ┆ Very High ┆ 11/29/17 │
│ 20        ┆           ┆           ┆ ference   ┆   ┆           ┆           ┆           ┆          │
│ CUST-3464 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 83197     ┆ 138826    ┆ High      ┆ 1/2/18   │
│ 85        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 83197     ┆ 138860    ┆ High      ┆ 1/2/18   │
│ 37        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Number of Nulls in Each Feature

In [4]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (11, 2)
┌──────────────────────────────┬────────────┐
│ feature                      ┆ null_count │
│ ---                          ┆ ---        │
│ str                          ┆ i64        │
╞══════════════════════════════╪════════════╡
│ CUST_ID                      ┆ 0          │
│ ADVERTISING_INDICATOR        ┆ 0          │
│ ATTACHMENT_ALLOWED_INDICATOR ┆ 0          │
│ PREFERRED_COMMUNICATION_FORM ┆ 0          │
│ IMPORTANCE_LEVEL_CODE        ┆ 0          │
│ INFLUENCE_SCORE              ┆ 0          │
│ MARKET_GROUP                 ┆ 0          │
│ LOYALTY_RATING_CODE          ┆ 0          │
│ RECORDED_VOICE_SAMPLE_ID     ┆ 0          │
│ REFERRALS_VALUE_CODE         ┆ 0          │
│ RELATIONSHIP_START_DATE      ┆ 0          │
└──────────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [5]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
CUST_ID                        | String
ADVERTISING_INDICATOR          | Boolean
ATTACHMENT_ALLOWED_INDICATOR   | Boolean
PREFERRED_COMMUNICATION_FORM   | String
IMPORTANCE_LEVEL_CODE          | String
INFLUENCE_SCORE                | Int64
MARKET_GROUP                   | String
LOYALTY_RATING_CODE            | Int64
RECORDED_VOICE_SAMPLE_ID       | Int64
REFERRALS_VALUE_CODE           | String
RELATIONSHIP_START_DATE        | String

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ CUST_ID   ┆ ADVERTISI ┆ ATTACHMEN ┆ … ┆ LOYALTY_R ┆ RECORDED_ ┆ REFERRALS ┆ RELATION │
│ ---       ┆ ---       ┆ NG_INDICA ┆ T_ALLOWED ┆   ┆ ATING_COD ┆ VOICE_SAM ┆ _VALUE_CO ┆ SHIP_STA │
│ str       ┆ str       ┆ TOR       ┆ _INDICATO ┆   ┆ E         ┆ PLE_ID    ┆ DE        ┆ RT_DATE  │
│           ┆           ┆ ---       ┆ R         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ f64       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2000      ┆ 2000.0    ┆ 2000.0    ┆ … ┆ 2000.0    ┆ 2000.0    ┆ 2000      ┆ 2000     │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 0.999     ┆ 0.758     ┆ … ┆ 94560.998 ┆ 95023.823 ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 28951.617 ┆ 29211.000 ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 122       ┆ 747       ┆           ┆          │
│ min       ┆ CUST-1000 ┆ 0.0       ┆ 0.0       ┆ … ┆ 45170.0   ┆ 45213.0   ┆ High      ┆ 1/10/18  │
│           ┆ 67        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 69093.0   ┆ 70423.0   ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 94062.0   ┆ 94886.0   ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 120462.0  ┆ 119812.0  ┆ null      ┆ null     │
│ max       ┆ CUST-9991 ┆ 1.0       ┆ 1.0       ┆ … ┆ 144959.0  ┆ 145001.0  ┆ Very Low  ┆ 9/5/18   │
│           ┆ 82        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 6)
┌─────────┬──────────────────┬──────────────────┬──────────────┬─────────────────┬─────────────────┐
│ CUST_ID ┆ PREFERRED_COMMUN ┆ IMPORTANCE_LEVEL ┆ MARKET_GROUP ┆ REFERRALS_VALUE ┆ RELATIONSHIP_ST │
│ ---     ┆ ICATION_FORM     ┆ _CODE            ┆ ---          ┆ _CODE           ┆ ART_DATE        │
│ u32     ┆ ---              ┆ ---              ┆ u32          ┆ ---             ┆ ---             │
│         ┆ u32              ┆ u32              ┆              ┆ u32             ┆ u32             │
╞═════════╪══════════════════╪══════════════════╪══════════════╪═════════════════╪═════════════════╡
│ 11      ┆ 16               ┆ 15               ┆ 12           ┆ 9               ┆ 8               │
└─────────┴──────────────────┴──────────────────┴──────────────┴─────────────────┴─────────────────┘

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, Boolean, Boolean, String, String, Int64, String, Int64, Int64, String, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                      Unique values in CUST_ID : 1999
        Unique values in ADVERTISING_INDICATOR : 2
 Unique values in ATTACHMENT_ALLOWED_INDICATOR : 2
 Unique values in PREFERRED_COMMUNICATION_FORM : 5
        Unique values in IMPORTANCE_LEVEL_CODE : 3
              Unique values in INFLUENCE_SCORE : 1969
                 Unique values in MARKET_GROUP : 4
          Unique values in LOYALTY_RATING_CODE : 997
     Unique values in RECORDED_VOICE_SAMPLE_ID : 1978
         Unique values in REFERRALS_VALUE_CODE : 5
      Unique values in RELATIONSHIP_START_DATE : 228

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

ADVERTISING_INDICATOR
shape: (9, 2)
┌────────────┬───────────────────────┐
│ statistic  ┆ ADVERTISING_INDICATOR │
│ ---        ┆ ---                   │
│ str        ┆ f64                   │
╞════════════╪═══════════════════════╡
│ count      ┆ 2000.0                │
│ null_count ┆ 0.0                   │
│ mean       ┆ 0.999                 │
│ std        ┆ null                  │
│ min        ┆ 0.0                   │
│ 25%        ┆ null                  │
│ 50%        ┆ null                  │
│ 75%        ┆ null                  │
│ max        ┆ 1.0                   │
└────────────┴───────────────────────┘


ATTACHMENT_ALLOWED_INDICATOR
shape: (9, 2)
┌────────────┬──────────────────────────────┐
│ statistic  ┆ ATTACHMENT_ALLOWED_INDICATOR │
│ ---        ┆ ---                          │
│ str        ┆ f64                          │
╞════════════╪══════════════════════════════╡
│ count      ┆ 2000.0                       │
│ null_count ┆ 0.0                          │
│ mean       ┆ 0.758                        │
│ std        ┆ null                         │
│ min        ┆ 0.0                          │
│ 25%        ┆ null                         │
│ 50%        ┆ null                         │
│ 75%        ┆ null                         │
│ max        ┆ 1.0                          │
└────────────┴──────────────────────────────┘


INFLUENCE_SCORE
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ INFLUENCE_SCORE │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2000.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 95382.4185      │
│ std        ┆ 29099.785599    │
│ min        ┆ 45105.0         │
│ 25%        ┆ 69381.0         │
│ 50%        ┆ 95973.0         │
│ 75%        ┆ 120267.0        │
│ max        ┆ 145055.0        │
└────────────┴─────────────────┘


LOYALTY_RATING_CODE
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ LOYALTY_RATING_CODE │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2000.0              │
│ null_count ┆ 0.0                 │
│ mean       ┆ 94560.9985          │
│ std        ┆ 28951.617122        │
│ min        ┆ 45170.0             │
│ 25%        ┆ 69093.0             │
│ 50%        ┆ 94062.0             │
│ 75%        ┆ 120462.0            │
│ max        ┆ 144959.0            │
└────────────┴─────────────────────┘


RECORDED_VOICE_SAMPLE_ID
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ RECORDED_VOICE_SAMPLE_ID │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 2000.0                   │
│ null_count ┆ 0.0                      │
│ mean       ┆ 95023.823                │
│ std        ┆ 29211.000747             │
│ min        ┆ 45213.0                  │
│ 25%        ┆ 70423.0                  │
│ 50%        ┆ 94886.0                  │
│ 75%        ┆ 119812.0                 │
│ max        ┆ 145001.0                 │
└────────────┴──────────────────────────┘

### List Unique Values For Certain Features

In [11]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: CUST_ID (1999 unique values)
shape: (1_999,)
Series: 'CUST_ID' [str]
[
	"CUST-100067"
	"CUST-100282"
	"CUST-100396"
	"CUST-100400"
	"CUST-100417"
	"CUST-100655"
	"CUST-100759"
	"CUST-101785"
	"CUST-101865"
	"CUST-102995"
	"CUST-103026"
	"CUST-103108"
	"CUST-103227"
	"CUST-104309"
	"CUST-104713"
	"CUST-105166"
	"CUST-106996"
	"CUST-107207"
	…
	"CUST-993400"
	"CUST-994052"
	"CUST-994211"
	"CUST-994613"
	"CUST-994795"
	"CUST-994918"
	"CUST-994965"
	"CUST-995095"
	"CUST-996204"
	"CUST-997038"
	"CUST-997072"
	"CUST-997260"
	"CUST-997681"
	"CUST-998954"
	"CUST-998988"
	"CUST-999095"
	"CUST-999182"
]
--------------------------------------------------
Column: ADVERTISING_INDICATOR (2 unique values)
shape: (2,)
Series: 'ADVERTISING_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------
Column: ATTACHMENT_ALLOWED_INDICATOR (2 unique values)
shape: (2,)
Series: 'ATTACHMENT_ALLOWED_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------
Column: PREFERRED_COMMUNICATION_FORM (5 unique values)
shape: (5,)
Series: 'PREFERRED_COMMUNICATION_FORM' [str]
[
	"Email"
	"In Person"
	"Other"
	"Teleconference"
	"Video Conference"
]
--------------------------------------------------
Column: IMPORTANCE_LEVEL_CODE (3 unique values)
shape: (3,)
Series: 'IMPORTANCE_LEVEL_CODE' [str]
[
	"High priority"
	"Low priority"
	"Normal priority"
]
--------------------------------------------------
Column: INFLUENCE_SCORE (1969 unique values)
shape: (1_969,)
Series: 'INFLUENCE_SCORE' [i64]
[
	45105
	45107
	45132
	45147
	45160
	45163
	45182
	45189
	45191
	45300
	45310
	45317
	45340
	45348
	45356
	45367
	45604
	45628
	…
	144383
	144400
	144473
	144509
	144513
	144518
	144542
	144574
	144592
	144599
	144603
	144612
	144619
	144656
	144847
	145050
	145055
]
--------------------------------------------------
Column: MARKET_GROUP (4 unique values)
shape: (4,)
Series: 'MARKET_GROUP' [str]
[
	"Accumulating"
	"Gifting"
	"Spending"
	"Starting"
]
--------------------------------------------------
Column: LOYALTY_RATING_CODE (997 unique values)
shape: (997,)
Series: 'LOYALTY_RATING_CODE' [i64]
[
	45170
	45203
	45283
	45348
	45510
	45588
	45594
	45606
	45793
	45916
	46064
	46077
	46095
	46118
	46132
	46153
	46200
	46239
	…
	142981
	142982
	143122
	143251
	143286
	143296
	143334
	143381
	143406
	143483
	143492
	143744
	143997
	144773
	144794
	144849
	144959
]
--------------------------------------------------
Column: RECORDED_VOICE_SAMPLE_ID (1978 unique values)
shape: (1_978,)
Series: 'RECORDED_VOICE_SAMPLE_ID' [i64]
[
	45213
	45332
	45348
	45351
	45389
	45396
	45415
	45468
	45471
	45604
	45632
	45682
	45699
	45753
	45809
	45826
	45857
	45895
	…
	143965
	143986
	143987
	143993
	143999
	144004
	144017
	144048
	144051
	144109
	144302
	144364
	144401
	144778
	144811
	144887
	145001
]
--------------------------------------------------
Column: REFERRALS_VALUE_CODE (5 unique values)
shape: (5,)
Series: 'REFERRALS_VALUE_CODE' [str]
[
	"High"
	"Low"
	"Medium"
	"Very High"
	"Very Low"
]
--------------------------------------------------
Column: RELATIONSHIP_START_DATE (228 unique values)
shape: (228,)
Series: 'RELATIONSHIP_START_DATE' [str]
[
	"1/10/18"
	"1/11/16"
	"1/11/17"
	"1/12/16"
	"1/13/16"
	"1/16/16"
	"1/17/18"
	"1/18/18"
	"1/19/18"
	"1/2/18"
	"1/20/17"
	"1/21/16"
	"1/21/17"
	"1/23/16"
	"1/24/17"
	"1/26/16"
	"1/27/16"
	"1/27/17"
	…
	"9/13/16"
	"9/13/17"
	"9/13/18"
	"9/14/16"
	"9/14/18"
	"9/16/16"
	"9/17/17"
	"9/18/16"
	"9/18/17"
	"9/2/18"
	"9/21/16"
	"9/22/16"
	"9/23/16"
	"9/28/16"
	"9/3/17"
	"9/4/18"
	"9/5/18"
]
--------------------------------------------------

In [12]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

### How Many Records Remain IF I Remove Records With Any Nulls In It

In [13]:
def drop_rows_with_any_nulls(df: pl.DataFrame) -> pl.DataFrame:
    """
    Removes all rows from a Polars DataFrame that contain any null values.
    """
    return df.drop_nulls()


drop_rows_with_any_nulls(df)

shape: (2_000, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ ADVERTISI ┆ ATTACHMEN ┆ PREFERRED ┆ … ┆ LOYALTY_R ┆ RECORDED_ ┆ REFERRALS ┆ RELATION │
│ ---       ┆ NG_INDICA ┆ T_ALLOWED ┆ _COMMUNIC ┆   ┆ ATING_COD ┆ VOICE_SAM ┆ _VALUE_CO ┆ SHIP_STA │
│ str       ┆ TOR       ┆ _INDICATO ┆ ATION_FOR ┆   ┆ E         ┆ PLE_ID    ┆ DE        ┆ RT_DATE  │
│           ┆ ---       ┆ R         ┆ M         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ bool      ┆ ---       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str      │
│           ┆           ┆ bool      ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 113633    ┆ 79027     ┆ Very High ┆ 7/12/16  │
│ 11        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 113633    ┆ 79172     ┆ Very High ┆ 7/12/16  │
│ 98        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ true      ┆ true      ┆ Teleconfe ┆ … ┆ 62773     ┆ 70208     ┆ Very Low  ┆ 8/15/17  │
│ 84        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 104010    ┆ 114804    ┆ Very High ┆ 8/24/16  │
│ 74        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1987 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 104010    ┆ 114786    ┆ Very High ┆ 8/24/16  │
│ 81        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2286 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 82003     ┆ 144401    ┆ Very High ┆ 4/6/17   │
│ 76        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4641 ┆ true      ┆ true      ┆ Teleconfe ┆ … ┆ 134016    ┆ 50803     ┆ Low       ┆ 2/10/16  │
│ 24        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-5294 ┆ true      ┆ false     ┆ Teleconfe ┆ … ┆ 134016    ┆ 50855     ┆ Low       ┆ 2/10/16  │
│ 07        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-5230 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 47989     ┆ 117630    ┆ Very High ┆ 2/13/16  │
│ 02        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7948 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 47989     ┆ 117585    ┆ Very High ┆ 2/13/16  │
│ 53        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6777 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 94886     ┆ 126884    ┆ High      ┆ 1/19/18  │
│ 20        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-8408 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 94886     ┆ 126847    ┆ High      ┆ 1/19/18  │
│ 80        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7311 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 94886     ┆ 126856    ┆ High      ┆ 1/19/18  │
│ 01        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9399 ┆ true      ┆ true      ┆ Video Con ┆ … ┆ 58022     ┆ 46196     ┆ Very High ┆ 6/6/18   │
│ 60        ┆           ┆           ┆ ference   ┆   ┆           ┆           ┆           ┆          │
│ CUST-6573 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 59195     ┆ 99494     ┆ Low       ┆ 6/29/16  │
│ 50        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2359 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 92375     ┆ 61046     ┆ High      ┆ 9/1/16   │
│ 54        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9848 ┆ true      ┆ false     ┆ Email     ┆ … ┆ 92375     ┆ 61143     ┆ High      ┆ 9/1/16   │
│ 49        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5711 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 92375     ┆ 61125     ┆ High      ┆ 9/1/16   │
│ 30        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-1749 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 50537     ┆ 89956     ┆ Very High ┆ 9/5/18   │
│ 87        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4658 ┆ true      ┆ true      ┆ Teleconfe ┆ … ┆ 110010    ┆ 56155     ┆ High      ┆ 7/20/16  │
│ 63        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-4871 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 72520     ┆ 69412     ┆ High      ┆ 2/3/18   │
│ 70        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4374 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 93422     ┆ 93268     ┆ Very High ┆ 12/23/16 │
│ 59        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6966 ┆ true      ┆ false     ┆ In Person ┆ … ┆ 93422     ┆ 93316     ┆ Very High ┆ 12/23/16 │
│ 35        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3956 ┆ true      ┆ false     ┆ Teleconfe ┆ … ┆ 120620    ┆ 64186     ┆ Low       ┆ 8/3/17   │
│ 30        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-2788 ┆ true      ┆ true      ┆ Teleconfe ┆ … ┆ 120620    ┆ 64252     ┆ Low       ┆ 8/3/17   │
│ 57        ┆           ┆           ┆ rence     ┆   ┆           ┆           ┆           ┆          │
│ CUST-9496 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 112311    ┆ 96504     ┆ Medium    ┆ 11/1/17  │
│ 82        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4238 ┆ true      ┆ true      ┆ In Person ┆ … ┆ 112311    ┆ 96458     ┆ Medium    ┆ 11/1/17  │
│ 82        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2983 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 64163     ┆ 108086    ┆ Medium    ┆ 1/3/18   │
│ 96        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5646 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 107792    ┆ 136065    ┆ Low       ┆ 1/17/18  │
│ 32        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6368 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 107792    ┆ 136060    ┆ Low       ┆ 1/17/18  │
│ 75        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7172 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 54611     ┆ 60037     ┆ Low       ┆ 8/28/17  │
│ 96        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7806 ┆ true      ┆ true      ┆ Other     ┆ … ┆ 54611     ┆ 60168     ┆ Low       ┆ 8/28/17  │
│ 94        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7874 ┆ true      ┆ true      ┆ Video Con ┆ … ┆ 80883     ┆ 90987     ┆ Very High ┆ 11/29/17 │
│ 20        ┆           ┆           ┆ ference   ┆   ┆           ┆           ┆           ┆          │
│ CUST-3464 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 83197     ┆ 138826    ┆ High      ┆ 1/2/18   │
│ 85        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ true      ┆ true      ┆ Email     ┆ … ┆ 83197     ┆ 138860    ┆ High      ┆ 1/2/18   │
│ 37        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘