## Exploratory Data Analysis

### Import Libraries

In [4]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [5]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [6]:
df = pl.read_csv(
    "../couchbase_scripts/data/Household.csv", 
    ignore_errors=True, 
    truncate_ragged_lines=True
    )

df

shape: (2_000, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ HOUSEHOLD ┆ ADDRESS   ┆ CITY      ┆ … ┆ HEAD_OF_H ┆ HOME_OWNE ┆ URBAN_COD ┆ PRIMARY_ │
│ ---       ┆ _ID       ┆ ---       ┆ ---       ┆   ┆ OUSEHOLD_ ┆ R_INDICAT ┆ E         ┆ ADVISOR_ │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ INDICATOR ┆ OR        ┆ ---       ┆ ID       │
│           ┆ str       ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ bool      ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ HHID-4179 ┆ 3629      ┆ Humble    ┆ … ┆ true      ┆ true      ┆ City      ┆ 50662    │
│ 11        ┆ 11        ┆ Alpine    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Trail     ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ HHID-7588 ┆ 69857     ┆ Sacrament ┆ … ┆ true      ┆ true      ┆ City      ┆ 53281    │
│ 98        ┆ 98        ┆ Winsor St ┆ o         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ HHID-9586 ┆ 4702      ┆ Denver    ┆ … ┆ true      ┆ true      ┆ City      ┆ 108919   │
│ 84        ┆ 84        ┆ Dublin    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ HHID-1245 ┆ 6         ┆ Monroevil ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 104140   │
│ 74        ┆ 74        ┆ Riverdale ┆ le        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Rd #27    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1987 ┆ HHID-1987 ┆ 0 La      ┆ Denver    ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 139823   │
│ 81        ┆ 81        ┆ Follette  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Center    ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-7172 ┆ HHID-7172 ┆ 6 Bunting ┆ Stockton  ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 57742    │
│ 96        ┆ 96        ┆ Parkway   ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7806 ┆ HHID-7806 ┆ 3 Mcauley ┆ Ashland   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 93736    │
│ 94        ┆ 94        ┆ Dr        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7874 ┆ HHID-7874 ┆ 639 Main  ┆ Anchorage ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 139141   │
│ 20        ┆ 20        ┆ St        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3464 ┆ HHID-3464 ┆ 4 B Blue  ┆ Brighton  ┆ … ┆ false     ┆ true      ┆ City      ┆ 139865   │
│ 85        ┆ 85        ┆ Ridge     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ HHID-3401 ┆ 76872     ┆ Garland   ┆ … ┆ false     ┆ true      ┆ City      ┆ 139865   │
│ 37        ┆ 37        ┆ Ramsey    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Way       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Number of Nulls in Each Feature

In [7]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (15, 2)
┌──────────────────────────────┬────────────┐
│ feature                      ┆ null_count │
│ ---                          ┆ ---        │
│ str                          ┆ i64        │
╞══════════════════════════════╪════════════╡
│ CUST_ID                      ┆ 0          │
│ HOUSEHOLD_ID                 ┆ 0          │
│ ADDRESS                      ┆ 0          │
│ CITY                         ┆ 0          │
│ COUNTRY                      ┆ 0          │
│ STATE                        ┆ 0          │
│ ZIP                          ┆ 0          │
│ ADDRESS_LAST_CHANGED_DATE    ┆ 0          │
│ NUMBER_OF_DEPENDENT_ADULTS   ┆ 0          │
│ NUMBER_OF_DEPENDENT_CHILDREN ┆ 0          │
│ FAMILY_SIZE                  ┆ 0          │
│ HEAD_OF_HOUSEHOLD_INDICATOR  ┆ 0          │
│ HOME_OWNER_INDICATOR         ┆ 0          │
│ URBAN_CODE                   ┆ 0          │
│ PRIMARY_ADVISOR_ID           ┆ 0          │
└──────────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [8]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
CUST_ID                        | String
HOUSEHOLD_ID                   | String
ADDRESS                        | String
CITY                           | String
COUNTRY                        | String
STATE                          | String
ZIP                            | String
ADDRESS_LAST_CHANGED_DATE      | String
NUMBER_OF_DEPENDENT_ADULTS     | Int64
NUMBER_OF_DEPENDENT_CHILDREN   | Int64
FAMILY_SIZE                    | Int64
HEAD_OF_HOUSEHOLD_INDICATOR    | Boolean
HOME_OWNER_INDICATOR           | Boolean
URBAN_CODE                     | String
PRIMARY_ADVISOR_ID             | Int64

### Display Summary Statistics for All Columns

In [9]:
summary = df.describe()
print(summary)

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ CUST_ID   ┆ HOUSEHOLD ┆ ADDRESS   ┆ … ┆ HEAD_OF_H ┆ HOME_OWNE ┆ URBAN_COD ┆ PRIMARY_ │
│ ---       ┆ ---       ┆ _ID       ┆ ---       ┆   ┆ OUSEHOLD_ ┆ R_INDICAT ┆ E         ┆ ADVISOR_ │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ INDICATOR ┆ OR        ┆ ---       ┆ ID       │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2000      ┆ 2000      ┆ 2000      ┆ … ┆ 2000.0    ┆ 2000.0    ┆ 2000      ┆ 2000.0   │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 0.8085    ┆ 0.716     ┆ null      ┆ 94858.75 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 29056.46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0899     │
│ min       ┆ CUST-1000 ┆ HHID-1000 ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ City      ┆ 45049.0  │
│           ┆ 67        ┆ 67        ┆ American  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Terrace   ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 69637.0  │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 96246.0  │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 119826.0 │
│ max       ┆ CUST-9991 ┆ HHID-9991 ┆ 99875 5th ┆ … ┆ 1.0       ┆ 1.0       ┆ Urban     ┆ 144944.0 │
│           ┆ 82        ┆ 82        ┆ Center    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [10]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 9)
┌─────────┬──────────────┬─────────┬──────┬───┬───────┬─────┬─────────────────────────┬────────────┐
│ CUST_ID ┆ HOUSEHOLD_ID ┆ ADDRESS ┆ CITY ┆ … ┆ STATE ┆ ZIP ┆ ADDRESS_LAST_CHANGED_DA ┆ URBAN_CODE │
│ ---     ┆ ---          ┆ ---     ┆ ---  ┆   ┆ ---   ┆ --- ┆ TE                      ┆ ---        │
│ u32     ┆ u32          ┆ u32     ┆ u32  ┆   ┆ u32   ┆ u32 ┆ ---                     ┆ u32        │
│         ┆              ┆         ┆      ┆   ┆       ┆     ┆ u32                     ┆            │
╞═════════╪══════════════╪═════════╪══════╪═══╪═══════╪═════╪═════════════════════════╪════════════╡
│ 11      ┆ 11           ┆ 31      ┆ 26   ┆ … ┆ 25    ┆ 5   ┆ 8                       ┆ 5          │
└─────────┴──────────────┴─────────┴──────┴───┴───────┴─────┴─────────────────────────┴────────────┘

### Retrieve Data Types of All Columns

In [11]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, String, String, String, String, Int64, Int64, Int64, Boolean, Boolean, String, Int64]

### Count Unique Values in Each Column

In [12]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                      Unique values in CUST_ID : 1999
                 Unique values in HOUSEHOLD_ID : 1999
                      Unique values in ADDRESS : 2000
                         Unique values in CITY : 885
                      Unique values in COUNTRY : 3
                        Unique values in STATE : 110
                          Unique values in ZIP : 1475
    Unique values in ADDRESS_LAST_CHANGED_DATE : 688
   Unique values in NUMBER_OF_DEPENDENT_ADULTS : 1
 Unique values in NUMBER_OF_DEPENDENT_CHILDREN : 5
                  Unique values in FAMILY_SIZE : 4
  Unique values in HEAD_OF_HOUSEHOLD_INDICATOR : 2
         Unique values in HOME_OWNER_INDICATOR : 2
                   Unique values in URBAN_CODE : 3
           Unique values in PRIMARY_ADVISOR_ID : 995

### Check Distribution of Numerical Columns

In [13]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['ID']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

NUMBER_OF_DEPENDENT_ADULTS
shape: (9, 2)
┌────────────┬────────────────────────────┐
│ statistic  ┆ NUMBER_OF_DEPENDENT_ADULTS │
│ ---        ┆ ---                        │
│ str        ┆ f64                        │
╞════════════╪════════════════════════════╡
│ count      ┆ 2000.0                     │
│ null_count ┆ 0.0                        │
│ mean       ┆ 0.0                        │
│ std        ┆ 0.0                        │
│ min        ┆ 0.0                        │
│ 25%        ┆ 0.0                        │
│ 50%        ┆ 0.0                        │
│ 75%        ┆ 0.0                        │
│ max        ┆ 0.0                        │
└────────────┴────────────────────────────┘


NUMBER_OF_DEPENDENT_CHILDREN
shape: (9, 2)
┌────────────┬──────────────────────────────┐
│ statistic  ┆ NUMBER_OF_DEPENDENT_CHILDREN │
│ ---        ┆ ---                          │
│ str        ┆ f64                          │
╞════════════╪══════════════════════════════╡
│ count      ┆ 2000.0                       │
│ null_count ┆ 0.0                          │
│ mean       ┆ 0.953                        │
│ std        ┆ 0.831346                     │
│ min        ┆ 0.0                          │
│ 25%        ┆ 0.0                          │
│ 50%        ┆ 1.0                          │
│ 75%        ┆ 2.0                          │
│ max        ┆ 4.0                          │
└────────────┴──────────────────────────────┘


FAMILY_SIZE
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ FAMILY_SIZE │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2000.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 2.6095      │
│ std        ┆ 1.160036    │
│ min        ┆ 1.0         │
│ 25%        ┆ 1.0         │
│ 50%        ┆ 3.0         │
│ 75%        ┆ 4.0         │
│ max        ┆ 4.0         │
└────────────┴─────────────┘


HEAD_OF_HOUSEHOLD_INDICATOR
shape: (9, 2)
┌────────────┬─────────────────────────────┐
│ statistic  ┆ HEAD_OF_HOUSEHOLD_INDICATOR │
│ ---        ┆ ---                         │
│ str        ┆ f64                         │
╞════════════╪═════════════════════════════╡
│ count      ┆ 2000.0                      │
│ null_count ┆ 0.0                         │
│ mean       ┆ 0.8085                      │
│ std        ┆ null                        │
│ min        ┆ 0.0                         │
│ 25%        ┆ null                        │
│ 50%        ┆ null                        │
│ 75%        ┆ null                        │
│ max        ┆ 1.0                         │
└────────────┴─────────────────────────────┘


HOME_OWNER_INDICATOR
shape: (9, 2)
┌────────────┬──────────────────────┐
│ statistic  ┆ HOME_OWNER_INDICATOR │
│ ---        ┆ ---                  │
│ str        ┆ f64                  │
╞════════════╪══════════════════════╡
│ count      ┆ 2000.0               │
│ null_count ┆ 0.0                  │
│ mean       ┆ 0.716                │
│ std        ┆ null                 │
│ min        ┆ 0.0                  │
│ 25%        ┆ null                 │
│ 50%        ┆ null                 │
│ 75%        ┆ null                 │
│ max        ┆ 1.0                  │
└────────────┴──────────────────────┘


PRIMARY_ADVISOR_ID
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ PRIMARY_ADVISOR_ID │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 2000.0             │
│ null_count ┆ 0.0                │
│ mean       ┆ 94858.757          │
│ std        ┆ 29056.460899       │
│ min        ┆ 45049.0            │
│ 25%        ┆ 69637.0            │
│ 50%        ┆ 96246.0            │
│ 75%        ┆ 119826.0           │
│ max        ┆ 144944.0           │
└────────────┴────────────────────┘

### List Unique Values For Certain Features

In [14]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: CUST_ID (1999 unique values)
shape: (1_999,)
Series: 'CUST_ID' [str]
[
	"CUST-100067"
	"CUST-100282"
	"CUST-100396"
	"CUST-100400"
	"CUST-100417"
	"CUST-100655"
	"CUST-100759"
	"CUST-101785"
	"CUST-101865"
	"CUST-102995"
	"CUST-103026"
	"CUST-103108"
	"CUST-103227"
	"CUST-104309"
	"CUST-104713"
	"CUST-105166"
	"CUST-106996"
	"CUST-107207"
	…
	"CUST-993400"
	"CUST-994052"
	"CUST-994211"
	"CUST-994613"
	"CUST-994795"
	"CUST-994918"
	"CUST-994965"
	"CUST-995095"
	"CUST-996204"
	"CUST-997038"
	"CUST-997072"
	"CUST-997260"
	"CUST-997681"
	"CUST-998954"
	"CUST-998988"
	"CUST-999095"
	"CUST-999182"
]
--------------------------------------------------
Column: HOUSEHOLD_ID (1999 unique values)
shape: (1_999,)
Series: 'HOUSEHOLD_ID' [str]
[
	"HHID-100067"
	"HHID-100282"
	"HHID-100396"
	"HHID-100400"
	"HHID-100417"
	"HHID-100655"
	"HHID-100759"
	"HHID-101785"
	"HHID-101865"
	"HHID-102995"
	"HHID-103026"
	"HHID-103108"
	"HHID-103227"
	"HHID-104309"
	"HHID-104713"
	"HHID-105166"
	"HHID-106996"
	"HHID-107207"
	…
	"HHID-993400"
	"HHID-994052"
	"HHID-994211"
	"HHID-994613"
	"HHID-994795"
	"HHID-994918"
	"HHID-994965"
	"HHID-995095"
	"HHID-996204"
	"HHID-997038"
	"HHID-997072"
	"HHID-997260"
	"HHID-997681"
	"HHID-998954"
	"HHID-998988"
	"HHID-999095"
	"HHID-999182"
]
--------------------------------------------------
Column: ADDRESS (2000 unique values)
shape: (2_000,)
Series: 'ADDRESS' [str]
[
	"0 American Terrace"
	"0 Bluejay Drive"
	"0 Briar Crest Pass"
	"0 Brickson Park Place"
	"0 Buhler Parkway"
	"0 Buhler Pass"
	"0 Burning Wood Terrace"
	"0 Butterfield Circle"
	"0 Cherokee Center"
	"0 Clyde Gallagher Drive"
	"0 Corry Junction"
	"0 Dakota Lane"
	"0 Doe Crossing Crossing"
	"0 Haas Park"
	"0 Huxley Plaza"
	"0 Kropf Junction"
	"0 La Follette Center"
	"0 Maywood Hill"
	…
	"99 Tank Farm Rd"
	"99 W Sleske Ct #5795"
	"99 Waydell St"
	"9903 Tarrytown Rd"
	"99084 Birchwood Terrace"
	"99146 Sw 6th St"
	"992 Civic Center Dr"
	"992 Hovde Pass"
	"992 W Lemon St"
	"9943 Rd"
	"99436 Mcbride Junction"
	"995 W Main St"
	"996 Market St"
	"996 Raven Court"
	"9968 W Big Beaver Rd"
	"9982 Shawmut Ave"
	"99875 5th Center"
]
--------------------------------------------------
Column: CITY (885 unique values)
shape: (885,)
Series: 'CITY' [str]
[
	"Abbeville"
	"Abbotsford"
	"Aberdeen"
	"Abilene"
	"Abington"
	"Absecon"
	"Acton Vale"
	"Acworth"
	"Aiea"
	"Ajax"
	"Akron"
	"Albanel"
	"Albany"
	"Alberton"
	"Albuquerque"
	"Aldergrove"
	"Alexandria"
	"Alliance"
	…
	"Wichita"
	"Wilkes Barre"
	"Willowdale"
	"Wilmington"
	"Windsor"
	"Winter Haven"
	"Winter Park"
	"Woodside"
	"Woodstock"
	"Worcester"
	"Wynnewood"
	"Yonkers"
	"Young America"
	"Youngstown"
	"Youngsville"
	"Yuba City"
	"Zephyrhills"
]
--------------------------------------------------
Column: COUNTRY (3 unique values)
shape: (3,)
Series: 'COUNTRY' [str]
[
	"Canada"
	"USA"
	"United States"
]
--------------------------------------------------
Column: STATE (110 unique values)
shape: (110,)
Series: 'STATE' [str]
[
	"AK"
	"AL"
	"AR"
	"AZ"
	"Alabama"
	"Alaska"
	"Alberta"
	"Arizona"
	"Arkansas"
	"British Columbia"
	"CA"
	"CO"
	"CT"
	"California"
	"Colorado"
	"Connecticut"
	"DC"
	"DE"
	…
	"South Dakota"
	"TN"
	"TX"
	"Tennessee"
	"Texas"
	"UT"
	"Utah"
	"VA"
	"VT"
	"Virginia"
	"WA"
	"WI"
	"WV"
	"WY"
	"Washington"
	"West Virginia"
	"Wisconsin"
]
--------------------------------------------------
Column: ZIP (1475 unique values)
shape: (1_475,)
Series: 'ZIP' [str]
[
	"10001"
	"10002"
	"10004"
	"10009"
	"10011"
	"10013"
	"10018"
	"10021"
	"10022"
	"10028"
	"10038"
	"10039"
	"10045"
	"10048"
	"10060"
	"10111"
	"10118"
	"10125"
	…
	"V5M"
	"V6L"
	"V6M"
	"V6S"
	"V6V"
	"V6Y"
	"V7A"
	"V7P"
	"V7R"
	"V7W"
	"V7X"
	"V8C"
	"V9A"
	"V9B"
	"V9G"
	"V9J"
	"X0G"
]
--------------------------------------------------
Column: ADDRESS_LAST_CHANGED_DATE (688 unique values)
shape: (688,)
Series: 'ADDRESS_LAST_CHANGED_DATE' [str]
[
	"1/1/15"
	"1/1/16"
	"1/10/14"
	"1/10/15"
	"1/11/15"
	"1/11/16"
	"1/12/15"
	"1/13/16"
	"1/14/15"
	"1/14/17"
	"1/15/15"
	"1/15/16"
	"1/17/16"
	"1/18/16"
	"1/19/14"
	"1/19/15"
	"1/19/16"
	"1/19/17"
	…
	"9/29/14"
	"9/29/15"
	"9/29/17"
	"9/3/15"
	"9/3/16"
	"9/3/17"
	"9/30/14"
	"9/30/15"
	"9/30/16"
	"9/4/17"
	"9/5/15"
	"9/6/15"
	"9/7/14"
	"9/7/15"
	"9/7/17"
	"9/8/15"
	"9/9/14"
]
--------------------------------------------------
Column: NUMBER_OF_DEPENDENT_ADULTS (1 unique values)
shape: (1,)
Series: 'NUMBER_OF_DEPENDENT_ADULTS' [i64]
[
	0
]
--------------------------------------------------
Column: NUMBER_OF_DEPENDENT_CHILDREN (5 unique values)
shape: (5,)
Series: 'NUMBER_OF_DEPENDENT_CHILDREN' [i64]
[
	0
	1
	2
	3
	4
]
--------------------------------------------------
Column: FAMILY_SIZE (4 unique values)
shape: (4,)
Series: 'FAMILY_SIZE' [i64]
[
	1
	2
	3
	4
]
--------------------------------------------------
Column: HEAD_OF_HOUSEHOLD_INDICATOR (2 unique values)
shape: (2,)
Series: 'HEAD_OF_HOUSEHOLD_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------
Column: HOME_OWNER_INDICATOR (2 unique values)
shape: (2,)
Series: 'HOME_OWNER_INDICATOR' [bool]
[
	false
	true
]
--------------------------------------------------
Column: URBAN_CODE (3 unique values)
shape: (3,)
Series: 'URBAN_CODE' [str]
[
	"City"
	"Rural"
	"Urban"
]
--------------------------------------------------
Column: PRIMARY_ADVISOR_ID (995 unique values)
shape: (995,)
Series: 'PRIMARY_ADVISOR_ID' [i64]
[
	45049
	45063
	45103
	45316
	45335
	45411
	45487
	45529
	45569
	45600
	45628
	45655
	45950
	45964
	46075
	46182
	46501
	46547
	…
	143517
	143529
	143774
	143829
	143859
	143952
	143965
	144151
	144162
	144185
	144546
	144600
	144671
	144834
	144907
	144910
	144944
]
--------------------------------------------------

In [15]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

### How Many Records Remain IF I Remove Records With Any Nulls In It

In [16]:
def drop_rows_with_any_nulls(df: pl.DataFrame) -> pl.DataFrame:
    """
    Removes all rows from a Polars DataFrame that contain any null values.
    """
    return df.drop_nulls()


drop_rows_with_any_nulls(df)

shape: (2_000, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ CUST_ID   ┆ HOUSEHOLD ┆ ADDRESS   ┆ CITY      ┆ … ┆ HEAD_OF_H ┆ HOME_OWNE ┆ URBAN_COD ┆ PRIMARY_ │
│ ---       ┆ _ID       ┆ ---       ┆ ---       ┆   ┆ OUSEHOLD_ ┆ R_INDICAT ┆ E         ┆ ADVISOR_ │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ INDICATOR ┆ OR        ┆ ---       ┆ ID       │
│           ┆ str       ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ bool      ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CUST-4179 ┆ HHID-4179 ┆ 3629      ┆ Humble    ┆ … ┆ true      ┆ true      ┆ City      ┆ 50662    │
│ 11        ┆ 11        ┆ Alpine    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Trail     ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7588 ┆ HHID-7588 ┆ 69857     ┆ Sacrament ┆ … ┆ true      ┆ true      ┆ City      ┆ 53281    │
│ 98        ┆ 98        ┆ Winsor St ┆ o         ┆   ┆           ┆           ┆           ┆          │
│ CUST-9586 ┆ HHID-9586 ┆ 4702      ┆ Denver    ┆ … ┆ true      ┆ true      ┆ City      ┆ 108919   │
│ 84        ┆ 84        ┆ Dublin    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1245 ┆ HHID-1245 ┆ 6         ┆ Monroevil ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 104140   │
│ 74        ┆ 74        ┆ Riverdale ┆ le        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Rd #27    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-1987 ┆ HHID-1987 ┆ 0 La      ┆ Denver    ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 139823   │
│ 81        ┆ 81        ┆ Follette  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Center    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2286 ┆ HHID-2286 ┆ 410 Acco  ┆ Glendale  ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 142557   │
│ 76        ┆ 76        ┆ Dr        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4641 ┆ HHID-4641 ┆ 192 Otis  ┆ Anderson  ┆ … ┆ true      ┆ true      ┆ City      ┆ 74963    │
│ 24        ┆ 24        ┆ St        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5294 ┆ HHID-5294 ┆ 6768      ┆ Scranton  ┆ … ┆ true      ┆ true      ┆ City      ┆ 51943    │
│ 07        ┆ 07        ┆ Heath     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Pass      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5230 ┆ HHID-5230 ┆ 981       ┆ Naples    ┆ … ┆ true      ┆ true      ┆ City      ┆ 47954    │
│ 02        ┆ 02        ┆ Hanson    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Park      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7948 ┆ HHID-7948 ┆ 66184 S   ┆ Stroudsbu ┆ … ┆ true      ┆ true      ┆ City      ┆ 106461   │
│ 53        ┆ 53        ┆ Van Buren ┆ rg        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ St        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6777 ┆ HHID-6777 ┆ 433 W     ┆ Boston    ┆ … ┆ true      ┆ true      ┆ City      ┆ 96932    │
│ 20        ┆ 20        ┆ Sedgley   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ave       ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-8408 ┆ HHID-8408 ┆ 8 Dapin   ┆ Saint-And ┆ … ┆ true      ┆ true      ┆ City      ┆ 85655    │
│ 80        ┆ 80        ┆ Street    ┆ ré-Avelli ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ n         ┆   ┆           ┆           ┆           ┆          │
│ CUST-7311 ┆ HHID-7311 ┆ 51        ┆ Saint Pet ┆ … ┆ true      ┆ true      ┆ City      ┆ 52016    │
│ 01        ┆ 01        ┆ Bobwhite  ┆ ersburg   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Terrace   ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9399 ┆ HHID-9399 ┆ 2 Swarthm ┆ Henderson ┆ … ┆ false     ┆ false     ┆ Urban     ┆ 91271    │
│ 60        ┆ 60        ┆ ore Ave   ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6573 ┆ HHID-6573 ┆ 248 S     ┆ Derwood   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 51817    │
│ 50        ┆ 50        ┆ Cobb Dr   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ #377      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2359 ┆ HHID-2359 ┆ 12335     ┆ Newport   ┆ … ┆ true      ┆ true      ┆ City      ┆ 118602   │
│ 54        ┆ 54        ┆ Lagrange  ┆ Beach     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ave       ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9848 ┆ HHID-9848 ┆ 426       ┆ Jamaica   ┆ … ┆ true      ┆ true      ┆ City      ┆ 80728    │
│ 49        ┆ 49        ┆ Rowland   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drive     ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5711 ┆ HHID-5711 ┆ 2 Rieder  ┆ Charlesto ┆ … ┆ true      ┆ true      ┆ City      ┆ 123236   │
│ 30        ┆ 30        ┆ Parkway   ┆ n         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CUST-1749 ┆ HHID-1749 ┆ 6         ┆ San Jose  ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 75604    │
│ 87        ┆ 87        ┆ Greenleaf ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ave       ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4658 ┆ HHID-4658 ┆ 394 Manch ┆ Rockford  ┆ … ┆ true      ┆ true      ┆ City      ┆ 125359   │
│ 63        ┆ 63        ┆ ester     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4871 ┆ HHID-4871 ┆ 322 New   ┆ Milwaukee ┆ … ┆ false     ┆ true      ┆ City      ┆ 52974    │
│ 70        ┆ 70        ┆ Horizon   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-4374 ┆ HHID-4374 ┆ 73 State  ┆ Phoenix   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 75834    │
│ 59        ┆ 59        ┆ Road 434  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ E         ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6966 ┆ HHID-6966 ┆ 735 Orin  ┆ Buffalo   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 138640   │
│ 35        ┆ 35        ┆ Parkway   ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3956 ┆ HHID-3956 ┆ 5502      ┆ Little    ┆ … ┆ true      ┆ true      ┆ Urban     ┆ 106457   │
│ 30        ┆ 30        ┆ Bunker    ┆ Current   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Hill      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Avenue    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2788 ┆ HHID-2788 ┆ 98 Connec ┆ Chagrin   ┆ … ┆ true      ┆ true      ┆ Urban     ┆ 87799    │
│ 57        ┆ 57        ┆ ticut Ave ┆ Falls     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Nw        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-9496 ┆ HHID-9496 ┆ 37275 St  ┆ Middle    ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 64991    │
│ 82        ┆ 82        ┆ Rt 17m M  ┆ Island    ┆   ┆           ┆           ┆           ┆          │
│ CUST-4238 ┆ HHID-4238 ┆ 61079     ┆ Olympia   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 143517   │
│ 82        ┆ 82        ┆ Riverside ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Circle    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-2983 ┆ HHID-2983 ┆ 228       ┆ Baltimore ┆ … ┆ true      ┆ true      ┆ City      ┆ 127443   │
│ 96        ┆ 96        ┆ Runamuck  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Pl #2808  ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-5646 ┆ HHID-5646 ┆ 7 W       ┆ San Jose  ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 96915    │
│ 32        ┆ 32        ┆ Jackson   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-6368 ┆ HHID-6368 ┆ 8         ┆ San       ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 101694   │
│ 75        ┆ 75        ┆ Westport  ┆ Antonio   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Center    ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7172 ┆ HHID-7172 ┆ 6 Bunting ┆ Stockton  ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 57742    │
│ 96        ┆ 96        ┆ Parkway   ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7806 ┆ HHID-7806 ┆ 3 Mcauley ┆ Ashland   ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 93736    │
│ 94        ┆ 94        ┆ Dr        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-7874 ┆ HHID-7874 ┆ 639 Main  ┆ Anchorage ┆ … ┆ true      ┆ false     ┆ Urban     ┆ 139141   │
│ 20        ┆ 20        ┆ St        ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3464 ┆ HHID-3464 ┆ 4 B Blue  ┆ Brighton  ┆ … ┆ false     ┆ true      ┆ City      ┆ 139865   │
│ 85        ┆ 85        ┆ Ridge     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Blvd      ┆           ┆   ┆           ┆           ┆           ┆          │
│ CUST-3401 ┆ HHID-3401 ┆ 76872     ┆ Garland   ┆ … ┆ false     ┆ true      ┆ City      ┆ 139865   │
│ 37        ┆ 37        ┆ Ramsey    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Way       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘