## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/tokenized_access_logs.csv")

df

shape: (469_977, 8)
┌────────────┬────────────┬────────────┬───────────┬──────────┬────────────┬───────────┬───────────┐
│ product    ┆ category   ┆ log_date   ┆ log_month ┆ log_hour ┆ department ┆ ip        ┆ url_link  │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ str        ┆ str       ┆ i64      ┆ str        ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪══════════╪════════════╪═══════════╪═══════════╡
│ adidas     ┆ baseball & ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fitness    ┆ 37.97.182 ┆ /departme │
│ Brazuca    ┆ softball   ┆ 6:00       ┆           ┆          ┆            ┆ .65       ┆ nt/fitnes │
│ 2017       ┆            ┆            ┆           ┆          ┆            ┆           ┆ s/categor │
│ Official   ┆            ┆            ┆           ┆          ┆            ┆           ┆ y/b…      │
│ M…         ┆            ┆            ┆           ┆          ┆            ┆           ┆           │
│ The North  ┆ hunting &  ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fan shop   ┆ 206.56.11 ┆ /departme │
│ Face       ┆ shooting   ┆ 6:00       ┆           ┆          ┆            ┆ 2.1       ┆ nt/fan%20 │
│ Women's    ┆            ┆            ┆           ┆          ┆            ┆           ┆ shop/cate │
│ Recon B…   ┆            ┆            ┆           ┆          ┆            ┆           ┆ gor…      │
│ adidas     ┆ featured   ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ apparel    ┆ 215.143.1 ┆ /departme │
│ Kids' RG   ┆ shops      ┆ 6:00       ┆           ┆          ┆            ┆ 80.0      ┆ nt/appare │
│ III Mid    ┆            ┆            ┆           ┆          ┆            ┆           ┆ l/categor │
│ Footba…    ┆            ┆            ┆           ┆          ┆            ┆           ┆ y/f…      │
│ Under      ┆ electronic ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ footwear   ┆ 206.56.11 ┆ /departme │
│ Armour     ┆ s          ┆ 6:00       ┆           ┆          ┆            ┆ 2.1       ┆ nt/footwe │
│ Men's Comp ┆            ┆            ┆           ┆          ┆            ┆           ┆ ar/catego │
│ ression…   ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
│ Pelican    ┆ water      ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fan shop   ┆ 136.108.5 ┆ /departme │
│ Sunstream  ┆ sports     ┆ 6:01       ┆           ┆          ┆            ┆ 6.242     ┆ nt/fan%20 │
│ 100 Kayak  ┆            ┆            ┆           ┆          ┆            ┆           ┆ shop/cate │
│            ┆            ┆            ┆           ┆          ┆            ┆           ┆ gor…      │
│ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …          ┆ …         ┆ …         │
│ Nike Men's ┆ as seen on ┆ 10/9/2017  ┆ Oct       ┆ 21       ┆ footwear   ┆ 93.166.57 ┆ /departme │
│ Free TR    ┆ tv!        ┆ 21:21      ┆           ┆          ┆            ┆ .36       ┆ nt/footwe │
│ 5.0 TB     ┆            ┆            ┆           ┆          ┆            ┆           ┆ ar/catego │
│ Trai…      ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
│ Under      ┆ fitness    ┆ 10/9/2017  ┆ Oct       ┆ 21       ┆ footwear   ┆ 126.175.2 ┆ /departme │
│ Armour     ┆ accessorie ┆ 21:21      ┆           ┆          ┆            ┆ .58       ┆ nt/footwe │
│ Hustle     ┆ s          ┆            ┆           ┆          ┆            ┆           ┆ ar/catego │
│ Storm      ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
│ Medi…      ┆            ┆            ┆           ┆          ┆            ┆           ┆           │
│ Under      ┆ fitness    ┆ 10/9/2017  ┆ Oct       ┆ 21       ┆ footwear   ┆ 201.210.1 ┆ /departme │
│ Armour     ┆ accessorie ┆ 21:22      ┆           ┆          ┆            ┆ 9.242     ┆ nt/footwe │
│ Hustle     ┆ s          ┆            ┆           ┆          ┆            ┆           ┆ ar/catego │
│ Storm      ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
│ Medi…      ┆            ┆            ┆           ┆          ┆            ┆           ┆           │
│ Nike Men's ┆ women's    ┆ 10/9/2017  ┆ Oct       ┆ 21       ┆ golf       ┆ 56.81.167 ┆ /departme │
│ Dri-FIT    ┆ apparel    ┆ 21:22      ┆           ┆          ┆            ┆ .135      ┆ nt/golf/c │
│ Victory    ┆            ┆            ┆           ┆          ┆            ┆           ┆ ategory/w │
│ Gol…       ┆            ┆            ┆           ┆          ┆            ┆           ┆ ome…      │
│ Bridgeston ┆ electronic ┆ 10/9/2017  ┆ Oct       ┆ 21       ┆ outdoors   ┆ 146.184.2 ┆ /departme │
│ e e6       ┆ s          ┆ 21:23      ┆           ┆          ┆            ┆ 39.226    ┆ nt/outdoo │
│ Straight   ┆            ┆            ┆           ┆          ┆            ┆           ┆ rs/catego │
│ Distan…    ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
└────────────┴────────────┴────────────┴───────────┴──────────┴────────────┴───────────┴───────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬──────────┬────────────┬───────────┬───────────┐
│ product    ┆ category   ┆ log_date   ┆ log_month ┆ log_hour ┆ department ┆ ip        ┆ url_link  │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ str        ┆ str       ┆ i64      ┆ str        ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪══════════╪════════════╪═══════════╪═══════════╡
│ adidas     ┆ baseball & ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fitness    ┆ 37.97.182 ┆ /departme │
│ Brazuca    ┆ softball   ┆ 6:00       ┆           ┆          ┆            ┆ .65       ┆ nt/fitnes │
│ 2017       ┆            ┆            ┆           ┆          ┆            ┆           ┆ s/categor │
│ Official   ┆            ┆            ┆           ┆          ┆            ┆           ┆ y/b…      │
│ M…         ┆            ┆            ┆           ┆          ┆            ┆           ┆           │
│ The North  ┆ hunting &  ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fan shop   ┆ 206.56.11 ┆ /departme │
│ Face       ┆ shooting   ┆ 6:00       ┆           ┆          ┆            ┆ 2.1       ┆ nt/fan%20 │
│ Women's    ┆            ┆            ┆           ┆          ┆            ┆           ┆ shop/cate │
│ Recon B…   ┆            ┆            ┆           ┆          ┆            ┆           ┆ gor…      │
│ adidas     ┆ featured   ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ apparel    ┆ 215.143.1 ┆ /departme │
│ Kids' RG   ┆ shops      ┆ 6:00       ┆           ┆          ┆            ┆ 80.0      ┆ nt/appare │
│ III Mid    ┆            ┆            ┆           ┆          ┆            ┆           ┆ l/categor │
│ Footba…    ┆            ┆            ┆           ┆          ┆            ┆           ┆ y/f…      │
│ Under      ┆ electronic ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ footwear   ┆ 206.56.11 ┆ /departme │
│ Armour     ┆ s          ┆ 6:00       ┆           ┆          ┆            ┆ 2.1       ┆ nt/footwe │
│ Men's Comp ┆            ┆            ┆           ┆          ┆            ┆           ┆ ar/catego │
│ ression…   ┆            ┆            ┆           ┆          ┆            ┆           ┆ ry/…      │
│ Pelican    ┆ water      ┆ 9/1/2017   ┆ Sep       ┆ 6        ┆ fan shop   ┆ 136.108.5 ┆ /departme │
│ Sunstream  ┆ sports     ┆ 6:01       ┆           ┆          ┆            ┆ 6.242     ┆ nt/fan%20 │
│ 100 Kayak  ┆            ┆            ┆           ┆          ┆            ┆           ┆ shop/cate │
│            ┆            ┆            ┆           ┆          ┆            ┆           ┆ gor…      │
└────────────┴────────────┴────────────┴───────────┴──────────┴────────────┴───────────┴───────────┘

### Retrieve Basic Information About DataFrame

In [5]:
print(df.shape)
print(df.dtypes)

(469977, 8)
[String, String, String, String, Int64, String, String, String]

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ product   ┆ category  ┆ log_date  ┆ … ┆ log_hour  ┆ departmen ┆ ip        ┆ url_link │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ t         ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 469977    ┆ 469977    ┆ 469977    ┆ … ┆ 469977.0  ┆ 469977    ┆ 469977    ┆ 469977   │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 14.591827 ┆ null      ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 5.574014  ┆ null      ┆ null      ┆ null     │
│ min       ┆ Bag Boy   ┆ accessori ┆ 1/1/2018  ┆ … ┆ 0.0       ┆ apparel   ┆ 1.100.203 ┆ /departm │
│           ┆ Beverage  ┆ es        ┆ 10:00     ┆   ┆           ┆           ┆ .104      ┆ ent/appa │
│           ┆ Holder    ┆           ┆           ┆   ┆           ┆           ┆           ┆ rel/cate │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gory/c…  │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 10.0      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 15.0      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 20.0      ┆ null      ┆ null      ┆ null     │
│ max       ┆ insta-bed ┆ women's   ┆ 9/9/2017  ┆ … ┆ 23.0      ┆ outdoors  ┆ 99.99.191 ┆ /departm │
│           ┆ Neverflat ┆ golf      ┆ 9:59      ┆   ┆           ┆           ┆ .106      ┆ ent/outd │
│           ┆ Air       ┆ clubs     ┆           ┆   ┆           ┆           ┆           ┆ oors/cat │
│           ┆ Mattre…   ┆           ┆           ┆   ┆           ┆           ┆           ┆ egory/…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 7)
┌─────────┬──────────┬──────────┬───────────┬────────────┬─────┬──────────┐
│ product ┆ category ┆ log_date ┆ log_month ┆ department ┆ ip  ┆ url_link │
│ ---     ┆ ---      ┆ ---      ┆ ---       ┆ ---        ┆ --- ┆ ---      │
│ u32     ┆ u32      ┆ u32      ┆ u32       ┆ u32        ┆ u32 ┆ u32      │
╞═════════╪══════════╪══════════╪═══════════╪════════════╪═════╪══════════╡
│ 45      ┆ 20       ┆ 16       ┆ 3         ┆ 9          ┆ 15  ┆ 130      │
└─────────┴──────────┴──────────┴───────────┴────────────┴─────┴──────────┘

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, Int64, String, String, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                      Unique values in product : 76
                     Unique values in category : 33
                     Unique values in log_date : 160815
                    Unique values in log_month : 5
                     Unique values in log_hour : 24
                   Unique values in department : 6
                           Unique values in ip : 3340
                     Unique values in url_link : 152

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

log_hour
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ log_hour  │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 469977.0  │
│ null_count ┆ 0.0       │
│ mean       ┆ 14.591827 │
│ std        ┆ 5.574014  │
│ min        ┆ 0.0       │
│ 25%        ┆ 10.0      │
│ 50%        ┆ 15.0      │
│ 75%        ┆ 20.0      │
│ max        ┆ 23.0      │
└────────────┴───────────┘

### List Unique Values for Select Columns/Features

In [11]:
cols_2_check = [
    "product",
    "category",
    "log_month",
    "log_hour",
    "department",
    "url_link"
]

for col in cols_2_check:
    unique_values = df[col].unique().sort().to_list()
    print(f"Column: {col} [{len(unique_values)}]")
    print(f"Unique values: {unique_values}\n")

Column: product [76]
Unique values: ['Bag Boy Beverage Holder', 'Bag Boy M330 Push Cart', 'Bridgestone e6 Straight Distance NFL Carolina', 'Bridgestone e6 Straight Distance NFL San Dieg', 'Bridgestone e6 Straight Distance NFL Tennesse', 'Bushnell Pro X7 Jolt Slope Rangefinder', 'Cleveland Golf Collegiate My Custom Wedge 588', "Cleveland Golf Women's 588 RTX CB Satin Chrom", 'Clicgear 8.0 Shoe Brush', 'Clicgear Rovic Cooler Bag', "Columbia Men's PFG Anchor Tough T-Shirt", "Diamondback Boys' Insight 24 Performance Hybr", "Diamondback Women's Serene Classic Comfort Bi", 'Field & Stream Sportsman 16 Gun Fire Safe', 'Fitbit The One Wireless Activity & Sleep Trac', 'Garmin Approach S3 Golf GPS Watch', 'Garmin Approach S4 Golf GPS Watch', 'Garmin Forerunner 910XT GPS Watch', 'Glove It Imperial Golf Towel', 'Glove It Urban Brick Golf Towel', "Glove It Women's Imperial Golf Glove", "Glove It Women's Mod Oval Golf Glove", "Hirzl Men's Hybrid Golf Glove", "Hirzl Women's Soffft Flex Golf Glove", "LIJA Women's Button Golf Dress", "LIJA Women's Eyelet Sleeveless Golf Polo", "LIJA Women's Mid-Length Panel Golf Shorts", 'MDGolf Pittsburgh Penguins Putter', "Merrell Men's All Out Flash Trail Running Sho", "Merrell Women's Grassbow Sport Hiking Shoe", "Merrell Women's Siren Mid Waterproof Hiking B", 'Mio ALPHA Heart Rate Monitor/Sport Watch', 'Nike Dri-FIT Crew Sock 6 Pack', "Nike Men's CJ Elite 2 TD Football Cleat", "Nike Men's Comfort 2 Slide", "Nike Men's Dri-FIT Victory Golf Polo", "Nike Men's Fingertrap Max Training Shoe", "Nike Men's Free 5.0+ Running Shoe", "Nike Men's Free TR 5.0 TB Training Shoe", "Nike Women's Free 5.0 TR FIT PRT 4 Training S", "O'Brien Men's Neoprene Life Vest", 'Ogio Race Golf Shoes', 'Pelican Sunstream 100 Kayak', 'Perfect Fitness Perfect Rip Deck', 'Polar FT4 Heart Rate Monitor', 'Polar Loop Activity Tracker', 'SOLE E25 Elliptical', 'SOLE E35 Elliptical', 'Stiga Master Series ST3100 Competition Indoor', "TYR Boys' Team Digi Jammer", 'TaylorMade 2017 Purelite Stand Bag', 'Team Golf New England Patriots Putter Grip', 'Team Golf Pittsburgh Steelers Putter Grip', 'Team Golf St. Louis Cardinals Putter Grip', 'Team Golf Tennessee Volunteers Putter Grip', 'Team Golf Texas Longhorns Putter Grip', "The North Face Women's Recon Backpack", 'Titleist Club Glove Travel Cover', 'Titleist Pro V1x Golf Balls', 'Titleist Pro V1x High Numbers Golf Balls', 'Titleist Pro V1x High Numbers Personalized Go', "Top Flite Women's 2017 XL Hybrid", "Under Armour Girls' Toddler Spine Surge Runni", 'Under Armour Hustle Storm Medium Duffle Bag', "Under Armour Kids' Mercenary Slide", "Under Armour Men's Compression EV SL Slide", "Under Armour Men's Tech II T-Shirt", "Under Armour Women's Ignite Slide", "Under Armour Women's Micro G Skulpt Running S", 'Yakima DoubleDown Ace Hitch Mount 4-Bike Rack', 'adidas Brazuca 2017 Official Match Ball', "adidas Kids' F5 Messi FG Soccer Cleat", "adidas Kids' RG III Mid Football Cleat", "adidas Men's Germany Black Crest Away Tee", 'adidas Youth Germany Black/Red Away Match Soc', 'insta-bed Neverflat Air Mattress']

Column: category [33]
Unique values: ['accessories', 'as seen on  tv!', 'baseball & softball', 'basketball', 'boxing & mma', 'camping & hiking', 'cardio equipment', 'cleats', 'electronics', 'featured shops', 'fishing', 'fitness accessories', "girls' apparel", 'golf apparel', 'golf bags & carts', 'golf balls', 'golf gloves', 'golf shoes', 'hockey', 'hunting & shooting', 'indoor outdoor games', "kids' golf clubs", 'lacrosse', "men's footwear", "men's golf clubs", 'shop by sport', 'soccer', 'strength training', 'tennis & racquet', 'trade-in', 'water sports', "women's apparel", "women's golf clubs"]

Column: log_month [5]
Unique values: ['Dec', 'Jan', 'Nov', 'Oct', 'Sep']

Column: log_hour [24]
Unique values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

Column: department [6]
Unique values: ['apparel ', 'fan shop ', 'fitness ', 'footwear ', 'golf ', 'outdoors ']

Column: url_link [152]