## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
# accessed_date,duration_secs,network_protocol,ip,bytes,accessed_from,age,gender,country,membership,language,sales,returned,returned_amount,pay_method

df = pl.read_csv("data/data.csv",
                 ignore_errors=True)

df

shape: (172_838, 15)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ accessed_d ┆ duration_ ┆ network_p ┆ ip        ┆ … ┆ sales    ┆ returned ┆ returned_ ┆ pay_metho │
│ ate        ┆ (secs)    ┆ rotocol   ┆ ---       ┆   ┆ ---      ┆ ---      ┆ amount    ┆ d         │
│ ---        ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64      ┆ str      ┆ ---       ┆ ---       │
│ str        ┆ i64       ┆ str       ┆           ┆   ┆          ┆          ┆ f64       ┆ str       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 2017-03-14 ┆ 2533      ┆ TCP       ┆ 1.10.195. ┆ … ┆ 261.96   ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:57.1 ┆           ┆           ┆ 126       ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4034      ┆ TCP       ┆ 1.1.217.2 ┆ … ┆ 731.94   ┆ No       ┆ 0.0       ┆ Debit     │
│ 17:43:57.1 ┆           ┆           ┆ 11        ┆   ┆          ┆          ┆           ┆ Card      │
│ 72         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 1525      ┆ TCP       ┆ 1.115.198 ┆ … ┆ 14.62    ┆ No       ┆ 0.0       ┆ Cash      │
│ 17:43:26.1 ┆           ┆           ┆ .107      ┆   ┆          ┆          ┆           ┆           │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 4572      ┆ TCP       ┆ 1.121.152 ┆ … ┆ 957.5775 ┆ No       ┆ 0.0       ┆ Credit    │
│ 17:43:26.1 ┆           ┆           ┆ .143      ┆   ┆          ┆          ┆           ┆ Card      │
│ 35         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-14 ┆ 3652      ┆ TCP       ┆ 1.123.135 ┆ … ┆ 22.368   ┆ No       ┆ 0.0       ┆ Cash      │
│ 18:17:09.0 ┆           ┆           ┆ .213      ┆   ┆          ┆          ┆           ┆           │
│ 05         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …        ┆ …         ┆ …         │
│ 2017-03-16 ┆ 4372      ┆ TCP       ┆ 94.197.12 ┆ … ┆ 0.0      ┆ Yes      ┆ 143.36    ┆ Debit     │
│ 11:42:01.2 ┆           ┆           ┆ 1.229     ┆   ┆          ┆          ┆           ┆ Card      │
│ 98         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 2167      ┆ TCP       ┆ 129.110.2 ┆ … ┆ 15.15    ┆ No       ┆ 0.0       ┆ Cash      │
│ 12:10:17.3 ┆           ┆           ┆ 41.72     ┆   ┆          ┆          ┆           ┆           │
│ 40         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 2725      ┆ TCP       ┆ 185.119.2 ┆ … ┆ 600.16   ┆ No       ┆ 0.0       ┆ Credit    │
│ 12:10:17.3 ┆           ┆           ┆ 52.121    ┆   ┆          ┆          ┆           ┆ Card      │
│ 40         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 3728      ┆ TCP       ┆ 185.145.1 ┆ … ┆ 75.75    ┆ No       ┆ 0.0       ┆ Cash      │
│ 15:52:58.3 ┆           ┆           ┆ 07.23     ┆   ┆          ┆          ┆           ┆           │
│ 42         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 2017-03-16 ┆ 3420      ┆ TCP       ┆ 202.69.12 ┆ … ┆ 23.46    ┆ No       ┆ 0.0       ┆ Credit    │
│ 15:52:58.3 ┆           ┆           ┆ .251      ┆   ┆          ┆          ┆           ┆ Card      │
│ 42         ┆           ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

### Retrieve Basic Information About DataFrame

In [4]:
print(df.shape)
print(df.dtypes)

(172838, 15)
[String, Int64, String, String, Int64, String, Int64, String, String, String, String, Float64, String, Float64, String]

### Display Summary Statistics for All Columns

In [5]:
summary = df.describe()
summary

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ statistic ┆ accessed_ ┆ duration_ ┆ network_p ┆ … ┆ sales     ┆ returned ┆ returned_ ┆ pay_metho │
│ ---       ┆ date      ┆ (secs)    ┆ rotocol   ┆   ┆ ---       ┆ ---      ┆ amount    ┆ d         │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ str      ┆ ---       ┆ ---       │
│           ┆ str       ┆ f64       ┆ str       ┆   ┆           ┆          ┆ f64       ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ count     ┆ 172838    ┆ 172838.0  ┆ 172838    ┆ … ┆ 172838.0  ┆ 172838   ┆ 172838.0  ┆ 172838    │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0        ┆ 0.0       ┆ 0         │
│ t         ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ mean      ┆ null      ┆ 3248.0318 ┆ null      ┆ … ┆ 411.34644 ┆ null     ┆ 74.012092 ┆ null      │
│           ┆           ┆ 27        ┆           ┆   ┆ 9         ┆          ┆           ┆           │
│ std       ┆ null      ┆ 1010.8722 ┆ null      ┆ … ┆ 785.53786 ┆ null     ┆ 364.44643 ┆ null      │
│           ┆           ┆ 7         ┆           ┆   ┆ 8         ┆          ┆ 5         ┆           │
│ min       ┆ 2017-03-1 ┆ 1500.0    ┆ HTTP      ┆ … ┆ 0.0       ┆ No       ┆ 0.0       ┆ Cash      │
│           ┆ 4 17:43:2 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 6.135     ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ 25%       ┆ null      ┆ 2371.0    ┆ null      ┆ … ┆ 5.23      ┆ null     ┆ 0.0       ┆ null      │
│ 50%       ┆ null      ┆ 3246.0    ┆ null      ┆ … ┆ 46.92     ┆ null     ┆ 0.0       ┆ null      │
│ 75%       ┆ null      ┆ 4124.0    ┆ null      ┆ … ┆ 600.16    ┆ null     ┆ 0.0       ┆ null      │
│ max       ┆ 2017-03-2 ┆ 5000.0    ┆ UDP       ┆ … ┆ 11199.968 ┆ Yes      ┆ 22638.48  ┆ Others    │
│           ┆ 1 23:59:3 ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│           ┆ 0.671     ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

### Find Longest Text Length in Each Column

In [6]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 10)
┌─────────────┬─────────────┬─────┬────────────┬───┬────────────┬──────────┬──────────┬────────────┐
│ accessed_da ┆ network_pro ┆ ip  ┆ accessed_F ┆ … ┆ membership ┆ language ┆ returned ┆ pay_method │
│ te          ┆ tocol       ┆ --- ┆ fom        ┆   ┆ ---        ┆ ---      ┆ ---      ┆ ---        │
│ ---         ┆ ---         ┆ u32 ┆ ---        ┆   ┆ u32        ┆ u32      ┆ u32      ┆ u32        │
│ u32         ┆ u32         ┆     ┆ u32        ┆   ┆            ┆          ┆          ┆            │
╞═════════════╪═════════════╪═════╪════════════╪═══╪════════════╪══════════╪══════════╪════════════╡
│ 23          ┆ 6           ┆ 16  ┆ 15         ┆ … ┆ 13         ┆ 10       ┆ 3        ┆ 11         │
└─────────────┴─────────────┴─────┴────────────┴───┴────────────┴──────────┴──────────┴────────────┘

### Count of Unique Values in Each Column

In [7]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"{col} :".rjust(48), f"{unique_counts}".ljust(6))

                                 accessed_date : 81747
                               duration_(secs) : 3501
                              network_protocol : 5
                                            ip : 137199
                                         bytes : 4695
                                 accessed_Ffom : 8
                                           age : 53
                                        gender : 3
                                       country : 27
                                    membership : 3
                                      language : 30
                                         sales : 5600
                                      returned : 2
                               returned_amount : 2135
                                    pay_method : 4

### Check Distribution of Numerical Columns

In [8]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

duration_(secs)
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ duration_(secs) │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 172838.0        │
│ null_count ┆ 0.0             │
│ mean       ┆ 3248.031827     │
│ std        ┆ 1010.87227      │
│ min        ┆ 1500.0          │
│ 25%        ┆ 2371.0          │
│ 50%        ┆ 3246.0          │
│ 75%        ┆ 4124.0          │
│ max        ┆ 5000.0          │
└────────────┴─────────────────┘


bytes
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ bytes       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 172838.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ 1535.206858 │
│ std        ┆ 6349.555845 │
│ min        ┆ 28.0        │
│ 25%        ┆ 264.0       │
│ 50%        ┆ 589.0       │
│ 75%        ┆ 2430.0      │
│ max        ┆ 932858.0    │
└────────────┴─────────────┘


age
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ age       │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 84714.0   │
│ null_count ┆ 88124.0   │
│ mean       ┆ 43.438263 │
│ std        ┆ 14.980135 │
│ min        ┆ 18.0      │
│ 25%        ┆ 30.0      │
│ 50%        ┆ 43.0      │
│ 75%        ┆ 56.0      │
│ max        ┆ 69.0      │
└────────────┴───────────┘


sales
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ sales      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 172838.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 411.346449 │
│ std        ┆ 785.537868 │
│ min        ┆ 0.0        │
│ 25%        ┆ 5.23       │
│ 50%        ┆ 46.92      │
│ 75%        ┆ 600.16     │
│ max        ┆ 11199.968  │
└────────────┴────────────┘


returned_amount
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ returned_amount │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 172838.0        │
│ null_count ┆ 0.0             │
│ mean       ┆ 74.012092       │
│ std        ┆ 364.446435      │
│ min        ┆ 0.0             │
│ 25%        ┆ 0.0             │
│ 50%        ┆ 0.0             │
│ 75%        ┆ 0.0             │
│ max        ┆ 22638.48        │
└────────────┴─────────────────┘

### Retrieve Unique Values For Select Features

In [9]:
unique_cols_check = [
    "network_protocol",
    "accessed_Ffom",
    "gender",
    "country",
    "membership",
    "language",
    "returned",
    "pay_method",
    "age"
]

for col in unique_cols_check:
    unique_vals = df.select(col).unique()
    print(f"{col} ({len(unique_vals)}): {unique_vals}")

network_protocol (5): shape: (5, 1)
┌──────────────────┐
│ network_protocol │
│ ---              │
│ str              │
╞══════════════════╡
│ HTTP             │
│ ICMP             │
│ TCP              │
│ UDP              │
│ HTTP             │
└──────────────────┘
accessed_Ffom (8): shape: (8, 1)
┌─────────────────┐
│ accessed_Ffom   │
│ ---             │
│ str             │
╞═════════════════╡
│ Mozilla Firefox │
│ Safari          │
│ Chrome          │
│ Android App     │
│ Others          │
│ Microsoft Edge  │
│ SafFRi          │
│ IOS App         │
└─────────────────┘
gender (3): shape: (3, 1)
┌─────────┐
│ gender  │
│ ---     │
│ str     │
╞═════════╡
│ Unknown │
│ Female  │
│ Male    │
└─────────┘
country (27): shape: (27, 1)
┌─────────┐
│ country │
│ ---     │
│ str     │
╞═════════╡
│ RU      │
│ MX      │
│ DK      │
│ IN      │
│ AE      │
│ …       │
│ PL      │
│ CH      │
│ AR      │
│ CA      │
│ US      │
└─────────┘
membership (3): shape: (3, 1)
┌───────────────┐
│ membership    │
│ ---           │
│ str           │
╞═══════════════╡
│ Normal        │
│ Premium       │
│ Not Logged In │
└───────────────┘
language (30): shape: (30, 1)
┌───────────┐
│ language  │
│ ---       │
│ str       │
╞═══════════╡
│ urdu      │
│ swedish   │
│ polish    │
│ Russian   │
│ Italian   │
│ …         │
│ romanian  │
│ mongolian │
│ norwegian │
│ serbian   │
│ slovene   │
└───────────┘
returned (2): shape: (2, 1)
┌──────────┐
│ returned │
│ ---      │
│ str      │
╞══════════╡
│ No       │
│ Yes      │
└──────────┘
pay_method (4): shape: (4, 1)
┌─────────────┐
│ pay_method  │
│ ---         │
│ str         │
╞═════════════╡
│ Debit Card  │
│ Others      │
│ Cash        │
│ Credit Card │
└─────────────┘
age (53): shape: (53, 1)
┌──────┐
│ age  │
│ ---  │
│ i64  │
╞══════╡
│ 42   │
│ null │
│ 18   │
│ 48   │
│ 45   │
│ …    │
│ 41   │
│ 65   │
│ 68   │
│ 59   │
│ 62   │
└──────┘