In [1]:
import pandas as pd

### Fact Table

In [2]:
df = pd.read_csv("mysql_scripts/fact_table.csv")

df

,payment_key,customer_key,time_key,item_key,store_key,quantity,unit,unit_price,total_price
0,P026,C004510,T049189,I00177,S00307,1,ct,35.0,35.0
1,P022,C008967,T041209,I00248,S00595,1,rolls,26.0,26.0
2,P030,C007261,T03633,I00195,S00496,8,ct,12.5,100.0
3,P032,C007048,T084631,I00131,S0086,8,ct,14.0,112.0
4,P014,C006430,T071276,I00050,S00488,8,cans,8.0,64.0
...,...,...,...,...,...,...,...,...,...
999995,P010,C003726,T09247,I00063,S00502,5,cans,40.0,200.0
999996,P021,C002581,T023483,I00252,S00225,1,ct,11.0,11.0
999997,P035,C006133,T039372,I00119,S00555,7,ct,53.0,371.0
999998,P031,C008735,T097975,I00257,S00440,2,ct,21.0,42.0
999999,P032,C004067,T018028,I00044,S00326,10,cans,8.0,80.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   payment_key   1000000 non-null  object
 1   customer_key  1000000 non-null  object
 2   time_key      1000000 non-null  object
 3   item_key      1000000 non-null  object
 4   store_key     1000000 non-null  object
 5   quantity      1000000 non-null  int64
 6   unit          996277 non-null   object
 7   unit_price    1000000 non-null  float64
 8   total_price   1000000 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 68.7+ MB

In [4]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 101:
        print(f"unique values in {col} ({len(unique_values)}): {unique_values}")
    else:
        print(f"unique values in {col} ({len(unique_values)})")

unique values in payment_key (39): ['P026' 'P022' 'P030' 'P032' 'P014' 'P006' 'P023' 'P027' 'P025' 'P019'
 'P018' 'P003' 'P016' 'P011' 'P015' 'P013' 'P001' 'P028' 'P020' 'P010'
 'P012' 'P017' 'P033' 'P029' 'P036' 'P021' 'P002' 'P035' 'P024' 'P037'
 'P004' 'P038' 'P034' 'P008' 'P005' 'P009' 'P031' 'P007' 'P039']
unique values in customer_key (9191)
unique values in time_key (99993)
unique values in item_key (264)
unique values in store_key (726)
unique values in quantity (11): [ 1  8  5  2 11 10  3  6  9  7  4]
unique values in unit (19): ['ct' 'rolls' 'cans' 'bottles' 'bags' 'oz' 'tubs' 'cartons' 'lb' 'tins'
 'ct.' 'pack' 'pk' 'bars' 'Bags' 'oz.' nan 'Ct' 'botlltes']
unique values in unit_price (46): [35.   26.   12.5  14.    8.   22.   15.5   6.75 15.   20.   16.    7.5
 17.   42.    6.    9.   45.   19.   12.   24.   17.5  33.   16.25 18.
 13.   40.   32.   21.   16.5  10.   13.5  19.5  25.   28.   11.5  29.
 11.   23.   22.5  55.   48.   53.   44.   37.   20.5  46.  ]
unique values in total_price (285)

In [5]:
def longest_string_length_per_column(df):
    df = df.astype(str)
    return df.apply(lambda col: col.str.len().max())

longest_lengths = longest_string_length_per_column(df)
print(longest_lengths)

payment_key     4
customer_key    7
time_key        7
item_key        6
store_key       6
quantity        2
unit            8
unit_price      5
total_price     6
dtype: int64

### Customer Dimension Table

In [6]:
df = pd.read_csv("mysql_scripts/customer_dim.csv")

df

     customer_key             name     contact_no            nid
0         C000001            sumit  8801920345851  7505075708899
1         C000002         tammanne  8801817069329  1977731324842
2         C000003    kailash kumar  8801663795774  3769494056318
3         C000004  bhagwati prasad  8801533627961  9378834712725
4         C000005             ajay  8801943715786  3540815556323
...           ...              ...            ...            ...
9186      C009187        smt radha  8801563029753  1057824928189
9187      C009188     tulsi sharma  8801794982266  7970880905205
9188      C009189        madhubala  8801890032435  3101930298150
9189      C009190       pintu devi  8801563290767  7234328323528
9190      C009191            roopa  8801524507359  5682728390307

[9191 rows x 4 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9191 entries, 0 to 9190
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_key  9191 non-null   object
 1   name          9164 non-null   object
 2   contact_no    9191 non-null   int64
 3   nid           9191 non-null   int64
dtypes: int64(2), object(2)
memory usage: 287.3+ KB

In [8]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 101:
        print(f"unique values in {col} ({len(unique_values)}): {unique_values}")
    else:
        print(f"unique values in {col} ({len(unique_values)})")

unique values in customer_key (9191)
unique values in name (4535)
unique values in contact_no (9190)
unique values in nid (9191)

In [9]:
def longest_string_length_per_column(df):
    df = df.astype(str)
    return df.apply(lambda col: col.str.len().max())

longest_lengths = longest_string_length_per_column(df)
print(longest_lengths)

customer_key     7
name            50
contact_no      13
nid             13
dtype: int64

### Item Dimension Table

In [10]:
df = pd.read_csv("mysql_scripts/item_dim.csv", encoding='utf-8', encoding_errors='ignore')

df

,item_key,item_name,desc,unit_price,man_country,supplier,unit
0,I00001,A&W Root Beer - 12 oz cans,a. Beverage - Soda,11.50,Netherlands,Bolsius Boxmeer,cans
1,I00002,A&W Root Beer Diet - 12 oz cans,a. Beverage - Soda,6.75,poland,CHROMADURLIN S.A.S,cans
2,I00003,Barq's Root Beer - 12 oz cans,a. Beverage - Soda,6.75,Bangladesh,DENIMACH LTD,cans
3,I00004,Cherry Coke 12oz,a. Beverage - Soda,6.75,Netherlands,Bolsius Boxmeer,cans
4,I00005,Cherry Coke Zero 12 pack,a. Beverage - Soda,6.75,Finland,HARDFORD AB,cans
...,...,...,...,...,...,...,...
259,I00260,Napkins Square Lunch,Kitchen Supplies,15.00,Cambodia,NINGBO SEDUNO IMP & EXP CO.LTD,ct
260,I00261,POM 2 ply paper towels,Kitchen Supplies,33.00,Lithuania,BIGSO AB,ct
261,I00262,Strong Everyday Napkins,Kitchen Supplies,14.00,Netherlands,Bolsius Boxmeer,ct
262,I00263,Advil 2 pill packets,Medicine,14.00,Lithuania,BIGSO AB,Ct
263,I00264,Tylenol Extra Strength 2 pill packets,Medicine,15.00,India,Indo Count Industries Ltd,Ct

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   item_key     264 non-null    object
 1   item_name    264 non-null    object
 2   desc         264 non-null    object
 3   unit_price   264 non-null    float64
 4   man_country  264 non-null    object
 5   supplier     264 non-null    object
 6   unit         263 non-null    object
dtypes: float64(1), object(6)
memory usage: 14.6+ KB

In [12]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 101:
        print(f"unique values in {col} ({len(unique_values)}): {unique_values}")
    else:
        print(f"unique values in {col} ({len(unique_values)})")

unique values in item_key (264)
unique values in item_name (259)
unique values in desc (30): ['a. Beverage - Soda' 'a. Beverage Sparkling Water'
 'Beverage - Energy/Protein ' 'Beverage - Energy/Protein'
 'Beverage - Gatorade' 'Beverage - Iced Tea' 'Beverage - Juice'
 'Beverage Water' 'Coffee Cream' 'Coffee Creamer' 'Coffee Ground'
 'Coffee Hot Cocoa' 'Coffee K-Cups' 'Coffee K-Cups Tea' 'Coffee Stirrers'
 'Coffee Sweetener' 'Dishware - Bowls' 'Dishware - Cups Cold'
 'Dishware - Cups Hot' 'Dishware - Plates' 'Dishware - Utensils'
 'Food - Chips' 'Food - Chocolate' 'Food - Healthy' 'Food - Nuts'
 'Food - Snacks' 'Food - Sweets' 'Gum - Mints' 'Kitchen Supplies'
 'Medicine']
unique values in unit_price (46): [11.5   6.75 16.25 16.   23.   26.   22.   28.   24.    8.   40.   55.
 37.   20.   17.5  15.5  17.   29.   15.   14.   18.    9.    7.5  10.
 13.   11.   19.    6.   16.5  22.5  42.   44.   53.   48.   46.   45.
 25.   12.5  19.5  32.   21.   35.   12.   20.5  13.5  33.  ]
unique values in man_country (10): ['Netherlands' 'poland' 'Bangladesh' 'Finland' 'Lithuania' 'India'
 'Germany' 'China' 'United States' 'Cambodia']
unique values in supplier (10): ['Bolsius Boxmeer' 'CHROMADURLIN S.A.S' 'DENIMACH LTD' 'HARDFORD AB'
 'BIGSO AB' 'Indo Count Industries Ltd' 'Friedola 1888 GmbH'
 'CHERRY GROUP CO.,LTD' 'MAESA SAS' 'NINGBO SEDUNO IMP & EXP CO.LTD']
unique values in unit (19): ['cans' 'bottles' 'ct' 'botlltes' 'cartons' 'oz' 'oz.' 'tubs' 'ct.' 'pk'
 'bags' 'Bags' nan 'bars' 'lb' 'tins' 'rolls' 'pack' 'Ct']

In [13]:
def longest_string_length_per_column(df):
    df = df.astype(str)
    return df.apply(lambda col: col.str.len().max())

longest_lengths = longest_string_length_per_column(df)
print(longest_lengths)

item_key        6
item_name      44
desc           27
unit_price      5
man_country    13
supplier       30
unit            8
dtype: int64

### Store Dimension Table

In [14]:
df = pd.read_csv("mysql_scripts/store_dim.csv", encoding='utf-8', encoding_errors='ignore')

df

    store_key division  district                  upazila
0       S0001   SYLHET  HABIGANJ               AJMIRIGANJ
1       S0002   SYLHET  HABIGANJ                  BAHUBAL
2       S0003   SYLHET  HABIGANJ               BANIACHONG
3       S0004   SYLHET  HABIGANJ              CHUNARUGHAT
4       S0005   SYLHET  HABIGANJ           HABIGANJ SADAR
..        ...      ...       ...                      ...
721    S00722  BARISAL   BARISAL                    HIZLA
722    S00723  BARISAL   BARISAL  BARISAL SADAR (KOTWALI)
723    S00724  BARISAL   BARISAL              MEHENDIGANJ
724    S00725  BARISAL   BARISAL                   MULADI
725    S00726  BARISAL   BARISAL                 WAZIRPUR

[726 rows x 4 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 726 entries, 0 to 725
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_key  726 non-null    object
 1   division   726 non-null    object
 2   district   726 non-null    object
 3   upazila    726 non-null    object
dtypes: object(4)
memory usage: 22.8+ KB

In [16]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 101:
        print(f"unique values in {col} ({len(unique_values)}): {unique_values}")
    else:
        print(f"unique values in {col} ({len(unique_values)})")

unique values in store_key (726)
unique values in division (7): ['SYLHET' 'RANGPUR' 'RAJSHAHI' 'KHULNA' 'DHAKA' 'CHITTAGONG' 'BARISAL']
unique values in district (64): ['HABIGANJ' 'MAULVIBAZAR' 'SUNAMGANJ' 'SYLHET' 'DINAJPUR' 'GAIBANDHA'
 'KURIGRAM' 'LALMONIRHAT' 'NILPHAMARI' 'PANCHAGARH' 'RANGPUR' 'THAKURGAON'
 'BOGRA' 'JOYPURHAT' 'NAOGAON' 'NATORE' 'CHAPAI NABABGANJ' 'PABNA'
 'RAJSHAHI' 'SIRAJGANJ' 'BAGERHAT' 'CHUADANGA' 'JESSORE' 'JHENAIDAH'
 'KHULNA' 'KUSHTIA' 'MAGURA' 'MEHERPUR' 'NARAIL' 'SATKHIRA' 'DHAKA'
 'FARIDPUR' 'GAZIPUR' 'GOPALGANJ' 'JAMALPUR' 'KISHOREGONJ' 'MADARIPUR'
 'MANIKGANJ' 'MUNSHIGANJ' 'MYMENSINGH' 'NARAYANGANJ' 'NARSINGDI'
 'NETRAKONA' 'RAJBARI' 'SHARIATPUR' 'SHERPUR' 'TANGAIL' 'BANDARBAN'
 'BRAHMANBARIA' 'CHANDPUR' 'CHITTAGONG' 'COMILLA' "COX'S BAZAR" 'FENI'
 'KHAGRACHHARI' 'LAKSHMIPUR' 'NOAKHALI' 'RANGAMATI' 'BARGUNA' 'BARISAL'
 'BHOLA' 'JHALOKATI' 'PATUAKHALI' 'PIROJPUR']
unique values in upazila (540)

In [17]:
def longest_string_length_per_column(df):
    df = df.astype(str)
    return df.apply(lambda col: col.str.len().max())

longest_lengths = longest_string_length_per_column(df)
print(longest_lengths)

store_key     6
division     10
district     16
upazila      23
dtype: int64

### The other tables are small enough that I can just manually check them.