In [1]:
# %pip install --upgrade pip

In [2]:
# %pip install seaborn

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [12]:
df = pd.read_csv("pg_scripts/data-FULL DATASET.csv")

df

,crash_record_id,crash_date_estimate,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,trafficway_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,crash_location
0,23a79931ef555d54118f64dc9be2cf2dbf59636ce253f7...,NaN,09/05/2023 07:05:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DUSK,ANGLE,"FIVE POINT, OR MORE",...,2.0,0.0,2.0,0.0,19,3,9,NaN,NaN,NaN
1,2675c13fd0f474d730a5b780968b3cafc7c12d7adb661f...,NaN,09/22/2023 06:45:00 PM,50,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",REAR END,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,2.0,0.0,18,6,9,NaN,NaN,NaN
2,5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...,NaN,07/29/2023 02:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,1.0,0.0,14,7,7,41.854120,-87.665902,POINT (-87.665902342962 41.854120262952)
3,7ebf015016f83d09b321afd671a836d6b148330535d5df...,NaN,08/09/2023 11:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,NOT DIVIDED,...,0.0,0.0,2.0,0.0,23,4,8,NaN,NaN,NaN
4,6c1659069e9c6285a650e70d6f9b574ed5f64c12888479...,NaN,08/18/2023 12:50:00 PM,15,OTHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,OTHER,...,1.0,0.0,1.0,0.0,12,6,8,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794951,b4944ab32a9f692cf95c2645b6683f032e74932532947d...,NaN,11/06/2023 07:00:00 AM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,ONE-WAY,...,0.0,0.0,1.0,0.0,7,2,11,41.923618,-87.656457,POINT (-87.656457235481 41.923618409759)
794952,d4bca3b24c17b9af828558fc95699da3c57fe7ea07daf5...,NaN,10/31/2023 06:30:00 PM,30,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,SIDESWIPE SAME DIRECTION,OTHER,...,0.0,0.0,2.0,0.0,18,3,10,41.722257,-87.585276,POINT (-87.585275565077 41.722257273006)
794953,ef84ea51375f9e29d55d99fb2b1dfaf8ea9d1fbc0f667e...,NaN,11/04/2023 11:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,ONE-WAY,...,0.0,0.0,1.0,0.0,23,7,11,41.705477,-87.621737,POINT (-87.621736842174 41.705477132435)
794954,9ba7b0e570841fc865b62892fb4931684ce4abe8162ee1...,NaN,11/06/2023 06:35:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,NOT DIVIDED,...,0.0,0.0,4.0,0.0,18,2,11,41.778165,-87.750264,POINT (-87.750264456164 41.778165162179)
794955,b2bd97994325bbc4c059742f1d87453b6364e6eb245809...,NaN,11/06/2023 07:00:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,...,0.0,0.0,2.0,0.0,19,2,11,41.808667,-87.684286,POINT (-87.684285695776 41.808667279513)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 794956 entries, 0 to 794955
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   crash_record_id                794956 non-null  object
 1   crash_date_estimate            59606 non-null   object
 2   crash_date                     794956 non-null  object
 3   posted_speed_limit             794956 non-null  int64
 4   traffic_control_device         794956 non-null  object
 5   device_condition               794956 non-null  object
 6   weather_condition              794956 non-null  object
 7   lighting_condition             794956 non-null  object
 8   first_crash_type               794956 non-null  object
 9   trafficway_type                794956 non-null  object
 10  lane_count                     199006 non-null  float64
 11  alignment                      794956 non-null  object
 12  roadway_surface_condition      794956 non-null  object
 13  road_defect                    794956 non-null  object
 14  report_type                    771698 non-null  object
 15  crash_type                     794956 non-null  object
 16  intersection_related           182215 non-null  object
 17  not_right_of_way               36727 non-null   object
 18  hit_and_run                    248626 non-null  object
 19  damage                         794956 non-null  object
 20  date_police_notified           794956 non-null  object
 21  primary_contributory_cause     794956 non-null  object
 22  secondary_contributory_cause   794956 non-null  object
 23  street_no                      794956 non-null  int64
 24  street_direction               794952 non-null  object
 25  street_name                    794955 non-null  object
 26  beat_of_occurrence             794951 non-null  float64
 27  photos_taken                   10371 non-null   object
 28  statements_taken               17557 non-null   object
 29  dooring                        2461 non-null    object
 30  work_zone                      4603 non-null    object
 31  work_zone_type                 3574 non-null    object
 32  workers_present                1178 non-null    object
 33  num_units                      794956 non-null  int64
 34  most_severe_injury             793204 non-null  object
 35  injuries_total                 793215 non-null  float64
 36  injuries_fatal                 793215 non-null  float64
 37  injuries_incapacitating        793215 non-null  float64
 38  injuries_non_incapacitating    793215 non-null  float64
 39  injuries_reported_not_evident  793215 non-null  float64
 40  injuries_no_indication         793215 non-null  float64
 41  injuries_unknown               793215 non-null  float64
 42  crash_hour                     794956 non-null  int64
 43  crash_day_of_week              794956 non-null  int64
 44  crash_month                    794956 non-null  int64
 45  latitude                       789567 non-null  float64
 46  longitude                      789567 non-null  float64
 47  crash_location                 789567 non-null  object
dtypes: float64(11), int64(6), object(31)
memory usage: 291.1+ MB

In [14]:
df.describe()

,posted_speed_limit,lane_count,street_no,beat_of_occurrence,num_units,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude
count,794956.000000,1.990060e+05,794956.000000,794951.000000,794956.000000,793215.000000,793215.000000,793215.000000,793215.000000,793215.000000,793215.000000,793215.0,794956.000000,794956.000000,794956.000000,789567.000000,789567.000000
mean,28.402547,1.333032e+01,3688.085435,1242.916397,2.034919,0.189448,0.001195,0.020032,0.107025,0.061195,2.004313,0.0,13.202800,4.122344,6.787978,41.854788,-87.673450
std,6.179272,2.961623e+03,2887.990566,705.268208,0.452475,0.565654,0.037456,0.165673,0.422095,0.318451,1.158715,0.0,5.568727,1.980411,3.405398,0.337523,0.686153
min,0.000000,0.000000e+00,0.000000,111.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,0.000000,-87.936193
25%,30.000000,2.000000e+00,1248.000000,714.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,9.000000,2.000000,4.000000,41.782429,-87.721709
50%,30.000000,2.000000e+00,3201.000000,1211.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,14.000000,4.000000,7.000000,41.874743,-87.674094
75%,30.000000,4.000000e+00,5600.000000,1822.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.0,17.000000,6.000000,10.000000,41.924336,-87.633300
max,99.000000,1.191625e+06,451100.000000,6100.000000,18.000000,21.000000,4.000000,10.000000,21.000000,15.000000,61.000000,0.0,23.000000,7.000000,12.000000,42.022780,0.000000

In [15]:
df.nunique()

crash_record_id                  794956
crash_date_estimate                   2
crash_date                       521033
posted_speed_limit                   45
traffic_control_device               19
device_condition                      8
weather_condition                    12
lighting_condition                    6
first_crash_type                     18
trafficway_type                      20
lane_count                           41
alignment                             6
roadway_surface_condition             7
road_defect                           7
report_type                           3
crash_type                            2
intersection_related                  2
not_right_of_way                      2
hit_and_run                           2
damage                                3
date_police_notified             603015
primary_contributory_cause           40
secondary_contributory_cause         40
street_no                         11694
street_direction                      4
street_name                        1632
beat_of_occurrence                  276
photos_taken                          2
statements_taken                      2
dooring                               2
work_zone                             2
work_zone_type                        4
workers_present                       2
num_units                            17
most_severe_injury                    5
injuries_total                       20
injuries_fatal                        5
injuries_incapacitating              10
injuries_non_incapacitating          19
injuries_reported_not_evident        13
injuries_no_indication               48
injuries_unknown                      1
crash_hour                           24
crash_day_of_week                     7
crash_month                          12
latitude                         294569
longitude                        294535
crash_location                   294737
dtype: int64

In [16]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 25:
        print(f"{col} ({len(unique_values)}): {unique_values}")
    else:
        print(f"{col} ({len(unique_values)})")

crash_record_id (794956)
crash_date_estimate (3): [nan 'Y' 'N']
crash_date (521033)
posted_speed_limit (45)
traffic_control_device (19): ['TRAFFIC SIGNAL' 'NO CONTROLS' 'OTHER' 'UNKNOWN' 'OTHER WARNING SIGN'
 'STOP SIGN/FLASHER' 'PEDESTRIAN CROSSING SIGN' 'OTHER REG. SIGN' 'YIELD'
 'LANE USE MARKING' 'RAILROAD CROSSING GATE' 'FLASHING CONTROL SIGNAL'
 'SCHOOL ZONE' 'POLICE/FLAGMAN' 'DELINEATORS' 'OTHER RAILROAD CROSSING'
 'RR CROSSING SIGN' 'NO PASSING' 'BICYCLE CROSSING SIGN']
device_condition (8): ['FUNCTIONING PROPERLY' 'NO CONTROLS' 'FUNCTIONING IMPROPERLY' 'UNKNOWN'
 'OTHER' 'NOT FUNCTIONING' 'MISSING' 'WORN REFLECTIVE MATERIAL']
weather_condition (12): ['CLEAR' 'SNOW' 'RAIN' 'UNKNOWN' 'CLOUDY/OVERCAST' 'FOG/SMOKE/HAZE'
 'BLOWING SNOW' 'FREEZING RAIN/DRIZZLE' 'OTHER' 'SEVERE CROSS WIND GATE'
 'SLEET/HAIL' 'BLOWING SAND, SOIL, DIRT']
lighting_condition (6): ['DUSK' 'DARKNESS, LIGHTED ROAD' 'DAYLIGHT' 'DARKNESS' 'UNKNOWN' 'DAWN']
first_crash_type (18): ['ANGLE' 'REAR END' 'PARKED MOTOR VEHICLE' 'SIDESWIPE SAME DIRECTION'
 'PEDESTRIAN' 'FIXED OBJECT' 'TURNING' 'SIDESWIPE OPPOSITE DIRECTION'
 'REAR TO FRONT' 'HEAD ON' 'REAR TO SIDE' 'PEDALCYCLIST' 'OTHER OBJECT'
 'ANIMAL' 'REAR TO REAR' 'OTHER NONCOLLISION' 'OVERTURNED' 'TRAIN']
trafficway_type (20): ['FIVE POINT, OR MORE' 'DIVIDED - W/MEDIAN BARRIER'
 'DIVIDED - W/MEDIAN (NOT RAISED)' 'NOT DIVIDED' 'OTHER' 'ONE-WAY'
 'PARKING LOT' 'T-INTERSECTION' 'RAMP' 'FOUR WAY' 'UNKNOWN' 'ALLEY'
 'UNKNOWN INTERSECTION TYPE' 'DRIVEWAY' 'TRAFFIC ROUTE' 'NOT REPORTED'
 'CENTER TURN LANE' 'L-INTERSECTION' 'Y-INTERSECTION' 'ROUNDABOUT']
lane_count (42)
alignment (6): ['STRAIGHT AND LEVEL' 'CURVE ON GRADE' 'CURVE, LEVEL' 'STRAIGHT ON GRADE'
 'STRAIGHT ON HILLCREST' 'CURVE ON HILLCREST']
roadway_surface_condition (7): ['DRY' 'SNOW OR SLUSH' 'WET' 'UNKNOWN' 'OTHER' 'ICE' 'SAND, MUD, DIRT']
road_defect (7): ['NO DEFECTS' 'UNKNOWN' 'DEBRIS ON ROADWAY' 'OTHER' 'WORN SURFACE'
 'SHOULDER DEFECT' 'RUT, HOLES']
report_type (4): ['ON SCENE' 'NOT ON SCENE (DESK REPORT)' nan 'AMENDED']
crash_type (2): ['INJURY AND / OR TOW DUE TO CRASH' 'NO INJURY / DRIVE AWAY']
intersection_related (3): ['Y' nan 'N']
not_right_of_way (3): [nan 'Y' 'N']
hit_and_run (3): [nan 'Y' 'N']
damage (3): ['OVER $1,500' '$501 - $1,500' '$500 OR LESS']
date_police_notified (603015)
primary_contributory_cause (40)
secondary_contributory_cause (40)
street_no (11694)
street_direction (5): ['S' 'W' 'E' 'N' nan]
street_name (1633)
beat_of_occurrence (277)
photos_taken (3): [nan 'Y' 'N']
statements_taken (3): [nan 'Y' 'N']
dooring (3): [nan 'Y' 'N']
work_zone (3): [nan 'Y' 'N']
work_zone_type (5): [nan 'CONSTRUCTION' 'UTILITY' 'UNKNOWN' 'MAINTENANCE']
workers_present (3): [nan 'Y' 'N']
num_units (17): [ 2  4  1  3  5  6  7  8 12  9 11 10 14 18 13 15 16]
most_severe_injury (6): ['INCAPACITATING INJURY' 'NO INDICATION OF INJURY'
 'NONINCAPACITATING INJURY' 'FATAL' 'REPORTED, NOT EVIDENT' nan]
injuries_total (21): [ 3.  0.  1.  2.  5. nan  4.  6. 15.  7.  9.  8. 12. 10. 21. 11. 17. 14.
 19. 13. 16.]
injuries_fatal (6): [ 0.  1. nan  2.  3.  4.]
injuries_incapacitating (11): [ 1.  0.  5. nan  2.  3.  4.  6.  7. 10.  8.]
injuries_non_incapacitating (20): [ 2.  0.  1.  5. nan  3.  4.  6.  7. 10.  8. 21. 14. 12. 19.  9. 18. 11.
 15. 16.]
injuries_reported_not_evident (14): [ 0.  2. nan  1.  3.  5.  4. 10.  6.  8.  7. 11.  9. 15.]
injuries_no_indication (49)
injuries_unknown (2): [ 0. nan]
crash_hour (24): [19 18 14 23 12  8 17 16 15 13 10  0  6  5 22 11 21  9 20  1  7  2  3  4]
crash_day_of_week (7): [3 6 7 4 2 1 5]
crash_month (12): [ 9  7  8 11  2  1 10 12  5  6  3  4]
latitude (294570)
longitude (294536)
crash_location (294738)

In [17]:
# Count null values per column
null_counts = df.isnull().sum()
null_counts

crash_record_id                       0
crash_date_estimate              735350
crash_date                            0
posted_speed_limit                    0
traffic_control_device                0
device_condition                      0
weather_condition                     0
lighting_condition                    0
first_crash_type                      0
trafficway_type                       0
lane_count                       595950
alignment                             0
roadway_surface_condition             0
road_defect                           0
report_type                       23258
crash_type                            0
intersection_related             612741
not_right_of_way                 758229
hit_and_run                      546330
damage                                0
date_police_notified                  0
primary_contributory_cause            0
secondary_contributory_cause          0
street_no                             0
street_direction                      4
street_name                           1
beat_of_occurrence                    5
photos_taken                     784585
statements_taken                 777399
dooring                          792495
work_zone                        790353
work_zone_type                   791382
workers_present                  793778
num_units                             0
most_severe_injury                 1752
injuries_total                     1741
injuries_fatal                     1741
injuries_incapacitating            1741
injuries_non_incapacitating        1741
injuries_reported_not_evident      1741
injuries_no_indication             1741
injuries_unknown                   1741
crash_hour                            0
crash_day_of_week                     0
crash_month                           0
latitude                           5389
longitude                          5389
crash_location                     5389
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 794956 entries, 0 to 794955
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   crash_record_id                794956 non-null  object
 1   crash_date_estimate            59606 non-null   object
 2   crash_date                     794956 non-null  object
 3   posted_speed_limit             794956 non-null  int64
 4   traffic_control_device         794956 non-null  object
 5   device_condition               794956 non-null  object
 6   weather_condition              794956 non-null  object
 7   lighting_condition             794956 non-null  object
 8   first_crash_type               794956 non-null  object
 9   trafficway_type                794956 non-null  object
 10  lane_count                     199006 non-null  float64
 11  alignment                      794956 non-null  object
 12  roadway_surface_condition      794956 non-null  object
 13  road_defect                    794956 non-null  object
 14  report_type                    771698 non-null  object
 15  crash_type                     794956 non-null  object
 16  intersection_related           182215 non-null  object
 17  not_right_of_way               36727 non-null   object
 18  hit_and_run                    248626 non-null  object
 19  damage                         794956 non-null  object
 20  date_police_notified           794956 non-null  object
 21  primary_contributory_cause     794956 non-null  object
 22  secondary_contributory_cause   794956 non-null  object
 23  street_no                      794956 non-null  int64
 24  street_direction               794952 non-null  object
 25  street_name                    794955 non-null  object
 26  beat_of_occurrence             794951 non-null  float64
 27  photos_taken                   10371 non-null   object
 28  statements_taken               17557 non-null   object
 29  dooring                        2461 non-null    object
 30  work_zone                      4603 non-null    object
 31  work_zone_type                 3574 non-null    object
 32  workers_present                1178 non-null    object
 33  num_units                      794956 non-null  int64
 34  most_severe_injury             793204 non-null  object
 35  injuries_total                 793215 non-null  float64
 36  injuries_fatal                 793215 non-null  float64
 37  injuries_incapacitating        793215 non-null  float64
 38  injuries_non_incapacitating    793215 non-null  float64
 39  injuries_reported_not_evident  793215 non-null  float64
 40  injuries_no_indication         793215 non-null  float64
 41  injuries_unknown               793215 non-null  float64
 42  crash_hour                     794956 non-null  int64
 43  crash_day_of_week              794956 non-null  int64
 44  crash_month                    794956 non-null  int64
 45  latitude                       789567 non-null  float64
 46  longitude                      789567 non-null  float64
 47  crash_location                 789567 non-null  object
dtypes: float64(11), int64(6), object(31)
memory usage: 291.1+ MB

In [20]:
import pandas as pd
from tabulate import tabulate
from pandas.api.types import is_string_dtype

def find_and_display_longest_strings(df):
    # Initialize a list to store results
    results = []
    
    # Iterate through columns
    for column in df.columns:
        # Check if the column has string data type
        if is_string_dtype(df[column]):
            # Find the longest string in the column
            longest_string_index = df[column].astype(str).str.len().idxmax()
            longest_string = df.loc[longest_string_index, column]
            # Store the result
            results.append([column, longest_string, len(longest_string)])
    
    # Create a DataFrame from the results
    result_df = pd.DataFrame(results, columns=['Column', 'Longest String', 'Length'])
    
    # Sort the results by length in descending order
    result_df = result_df.sort_values('Length', ascending=False).reset_index(drop=True)
    
    # Display the results in a pretty table
    print("\nLongest Strings in Each Column:")
    print(tabulate(result_df, headers='keys', tablefmt='pretty', showindex=False))
    
    return result_df

result = find_and_display_longest_strings(df)

Longest Strings in Each Column:
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------+
|            Column            |                                                          Longest String                                                          | Length |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------+
|       crash_record_id        | 23a79931ef555d54118f64dc9be2cf2dbf59636ce253f7a1179c4a1c091442a6eeab8352220c7c56ca1ff7c4b4b0fc345c74e3e85ecb9d43deeb66b5f803d4a0 |  128   |
|  primary_contributory_cause  |                         OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER                         |   80   |
| secondary_contributory_cause |                         OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELESS, NEGLIGENT OR AGGRESSIVE MANNER                         |   80   |
|          crash_type          |                                                 INJURY AND / OR TOW DUE TO CRASH                                                 |   32   |
|       trafficway_type        |                                                 DIVIDED - W/MEDIAN (NOT RAISED)                                                  |   31   |
|       first_crash_type       |                                                   SIDESWIPE OPPOSITE DIRECTION                                                   |   28   |
|    traffic_control_device    |                                                     PEDESTRIAN CROSSING SIGN                                                     |   24   |
|       device_condition       |                                                     WORN REFLECTIVE MATERIAL                                                     |   24   |
|      weather_condition       |                                                     BLOWING SAND, SOIL, DIRT                                                     |   24   |
|          crash_date          |                                                      09/05/2023 07:05:00 PM                                                      |   22   |
|      lighting_condition      |                                                      DARKNESS, LIGHTED ROAD                                                      |   22   |
|     date_police_notified     |                                                      09/05/2023 07:05:00 PM                                                      |   22   |
|          alignment           |                                                      STRAIGHT ON HILLCREST                                                       |   21   |
|         road_defect          |                                                        DEBRIS ON ROADWAY                                                         |   17   |
|  roadway_surface_condition   |                                                         SAND, MUD, DIRT                                                          |   15   |
|            damage            |                                                          $501 - $1,500                                                           |   13   |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------+--------+

In [25]:
longest_string_index = df['street_name'].astype(str).str.len().idxmax()
longest_string = len(df.loc[longest_string_index, 'street_name'])
print(longest_string)

31

In [26]:
longest_string_index = df['crash_location'].astype(str).str.len().idxmax()
longest_string = len(df.loc[longest_string_index, 'crash_location'])
print(longest_string)

40