## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/data.csv")

df

shape: (7_991, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ OrderNumb ┆ SalesChan ┆ Warehouse ┆ ProcuredD ┆ … ┆ OrderQuan ┆ DiscountA ┆ UnitCost  ┆ UnitPric │
│ er        ┆ nel       ┆ Code      ┆ ate       ┆   ┆ tity      ┆ pplied    ┆ ---       ┆ e        │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SO -      ┆ In-Store  ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 5         ┆ 0.08      ┆ $1,001.18 ┆ $1,963.1 │
│ 000101    ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 3         ┆ 0.08      ┆ $3,348.66 ┆ $3,939.6 │
│ 000102    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 1         ┆ 0.05      ┆ $781.22   ┆ $1,775.5 │
│ 000103    ┆ or        ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Wholesale ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 8         ┆ 0.08      ┆ $1,464.69 ┆ $2,324.9 │
│ 000104    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-NMK1 ┆ 10/4/2018 ┆ … ┆ 8         ┆ 0.1       ┆ $1,476.14 ┆ $1,822.4 │
│ 000105    ┆ or        ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SO -      ┆ In-Store  ┆ WARE-MKL1 ┆ 26/9/20   ┆ … ┆ 1         ┆ 0.08      ┆ $121.94   ┆ $234.50  │
│ 0008087   ┆           ┆ 006       ┆           ┆   ┆           ┆           ┆           ┆          │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 26/9/20   ┆ … ┆ 6         ┆ 0.05      ┆ $1,921.56 ┆ $3,202.6 │
│ 0008088   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-UHY1 ┆ 26/9/20   ┆ … ┆ 5         ┆ 0.2       ┆ $2,792.76 ┆ $3,825.7 │
│ 0008089   ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 26/9/20   ┆ … ┆ 8         ┆ 0.1       ┆ $804.00   ┆ $1,072.0 │
│ 0008090   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ In-Store  ┆ WARE-UHY1 ┆ 26/9/20   ┆ … ┆ 5         ┆ 0.08      ┆ $1,370.82 ┆ $2,211.0 │
│ 0008091   ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Basic Information About DataFrame

In [4]:
print(df.shape)
print(df.dtypes)

(7991, 16)
[String, String, String, String, String, String, String, String, Int64, Int64, Int64, Int64, Int64, Float64, String, String]

### Display Summary Statistics for All Columns

In [5]:
summary = df.describe()
print(summary)

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ OrderNumb ┆ SalesChan ┆ Warehouse ┆ … ┆ OrderQuan ┆ DiscountA ┆ UnitCost  ┆ UnitPric │
│ ---       ┆ er        ┆ nel       ┆ Code      ┆   ┆ tity      ┆ pplied    ┆ ---       ┆ e        │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 7991      ┆ 7991      ┆ 7991      ┆ … ┆ 7991.0    ┆ 7991.0    ┆ 7991      ┆ 7991     │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.525341  ┆ 0.115649  ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 2.312631  ┆ 0.085018  ┆ null      ┆ null     │
│ min       ┆ SO -      ┆ Distribut ┆ WARE-MKL1 ┆ … ┆ 1.0       ┆ 0.05      ┆ $1,001.18 ┆ $1,005.0 │
│           ┆ 0001000   ┆ or        ┆ 006       ┆   ┆           ┆           ┆           ┆ 0        │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.0       ┆ 0.05      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 5.0       ┆ 0.08      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 7.0       ┆ 0.15      ┆ null      ┆ null     │
│ max       ┆ SO -      ┆ Wholesale ┆ WARE-XYS1 ┆ … ┆ 8.0       ┆ 0.4       ┆ $999.91   ┆ $998.30  │
│           ┆ 000999    ┆           ┆ 001       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [6]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ OrderNumb ┆ SalesChan ┆ Warehouse ┆ ProcuredD ┆ … ┆ DeliveryD ┆ CurrencyC ┆ UnitCost ┆ UnitPrice │
│ er        ┆ nel       ┆ Code      ┆ ate       ┆   ┆ ate       ┆ ode       ┆ ---      ┆ ---       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32      ┆ u32       │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 12        ┆ 11        ┆ 12        ┆ 9         ┆ … ┆ 10        ┆ 3         ┆ 9        ┆ 9         │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

### Retrieve Unique Values for Select Features

In [7]:
# pl.Config.set_tbl_max_rows(None)
pl.Config.set_tbl_rows(1000)

cols_unique_vals = [
    "ProcuredDate",
    "OrderDate",
    "ShipDate",
    "DeliveryDate"
]

for col in cols_unique_vals:
    unique_vals = df.select(col).unique()
    print(f"{col}: {unique_vals}")

ProcuredDate: shape: (11, 1)
┌──────────────┐
│ ProcuredDate │
│ ---          │
│ str          │
╞══════════════╡
│ 27/10/18     │
│ 26/9/20      │
│ 10/4/2018    │
│ 19/7/18      │
│ 10/3/2020    │
│ 23/8/19      │
│ 1/12/2019    │
│ 18/6/20      │
│ 15/5/19      │
│ 31/12/17     │
│ 4/2/2019     │
└──────────────┘
OrderDate: shape: (945, 1)
┌────────────┐
│ OrderDate  │
│ ---        │
│ str        │
╞════════════╡
│ 21/11/18   │
│ 06/08/2020 │
│ 14/5/20    │
│ 02/05/2019 │
│ 05/05/2019 │
│ 27/8/19    │
│ 10/11/2018 │
│ 30/9/19    │
│ 13/12/19   │
│ 11/12/2019 │
│ 11/11/2018 │
│ 02/06/2020 │
│ 07/04/2019 │
│ 18/6/18    │
│ 15/8/19    │
│ 10/05/2020 │
│ 26/8/20    │
│ 24/5/20    │
│ 21/9/19    │
│ 25/11/19   │
│ 12/02/2019 │
│ 03/09/2019 │
│ 29/4/20    │
│ 27/5/19    │
│ 16/7/20    │
│ 14/6/18    │
│ 24/11/19   │
│ 05/01/2019 │
│ 05/07/2019 │
│ 05/10/2018 │
│ 30/8/19    │
│ 19/9/18    │
│ 20/5/20    │
│ 02/09/2019 │
│ 20/12/19   │
│ 07/11/2020 │
│ 30/12/20   │
│ 07/05/2019 │
│ 21/6/20    │
│ 19/12/18   │
│ 28/2/19    │
│ 22/10/20   │
│ 15/12/18   │
│ 29/5/19    │
│ 25/10/19   │
│ 27/12/20   │
│ 03/09/2018 │
│ 08/03/2020 │
│ 22/2/20    │
│ 18/10/18   │
│ 17/12/20   │
│ 30/11/18   │
│ 04/11/2019 │
│ 07/08/2020 │
│ 09/10/2020 │
│ 22/11/18   │
│ 08/09/2019 │
│ 08/05/2020 │
│ 27/11/18   │
│ 27/12/19   │
│ 30/8/18    │
│ 10/05/2019 │
│ 09/04/2019 │
│ 20/11/19   │
│ 25/9/20    │
│ 22/12/18   │
│ 06/06/2020 │
│ 14/8/18    │
│ 19/2/19    │
│ 06/10/2019 │
│ 25/5/20    │
│ 05/03/2019 │
│ 22/9/18    │
│ 06/07/2019 │
│ 16/5/19    │
│ 09/04/2020 │
│ 19/10/20   │
│ 28/5/20    │
│ 28/1/19    │
│ 27/11/20   │
│ 19/8/20    │
│ 14/11/18   │
│ 19/9/20    │
│ 10/09/2020 │
│ 29/12/18   │
│ 08/04/2019 │
│ 27/5/20    │
│ 28/7/19    │
│ 30/9/20    │
│ 13/11/20   │
│ 24/7/20    │
│ 08/08/2019 │
│ 09/06/2018 │
│ 18/10/20   │
│ 08/10/2019 │
│ 03/01/2020 │
│ 15/5/20    │
│ 29/11/18   │
│ 28/6/19    │
│ 02/11/2019 │
│ 08/02/2020 │
│ 25/12/18   │
│ 14/9/20    │
│ 16/12/19   │
│ 24/11/20   │
│ 14/7/19    │
│ 11/09/2018 │
│ 18/11/18   │
│ 09/08/2019 │
│ 04/01/2019 │
│ 14/2/19    │
│ 16/1/20    │
│ 30/9/18    │
│ 04/03/2020 │
│ 12/05/2020 │
│ 19/11/18   │
│ 20/9/18    │
│ 05/09/2020 │
│ 14/1/20    │
│ 08/04/2020 │
│ 17/6/20    │
│ 30/12/19   │
│ 03/08/2019 │
│ 24/6/19    │
│ 11/12/2018 │
│ 07/02/2019 │
│ 09/09/2019 │
│ 16/2/20    │
│ 18/9/20    │
│ 07/03/2020 │
│ 07/09/2020 │
│ 03/07/2020 │
│ 28/7/18    │
│ 30/8/20    │
│ 30/7/18    │
│ 12/08/2020 │
│ 07/11/2018 │
│ 25/6/18    │
│ 16/8/18    │
│ 23/3/19    │
│ 28/3/20    │
│ 07/05/2020 │
│ 21/8/20    │
│ 30/10/18   │
│ 26/9/18    │
│ 20/9/19    │
│ 20/10/18   │
│ 20/7/20    │
│ 14/1/19    │
│ 14/3/20    │
│ 01/05/2020 │
│ 10/10/2018 │
│ 29/9/19    │
│ 22/10/18   │
│ 22/7/18    │
│ 27/10/19   │
│ 11/07/2018 │
│ 01/11/2018 │
│ 11/04/2019 │
│ 21/5/20    │
│ 10/12/2020 │
│ 01/11/2019 │
│ 29/3/20    │
│ 17/7/20    │
│ 13/12/18   │
│ 04/09/2019 │
│ 21/12/19   │
│ 13/5/19    │
│ 21/10/18   │
│ 13/10/20   │
│ 29/8/19    │
│ 03/03/2020 │
│ 20/6/19    │
│ 26/5/19    │
│ 31/7/18    │
│ 21/3/20    │
│ 01/05/2019 │
│ 29/11/20   │
│ 27/2/19    │
│ 28/3/19    │
│ 13/11/18   │
│ 13/10/19   │
│ 01/01/2019 │
│ 03/02/2019 │
│ 20/3/19    │
│ 12/02/2020 │
│ 26/10/18   │
│ 05/07/2020 │
│ 02/11/2020 │
│ 28/4/20    │
│ 03/06/2019 │
│ 18/1/19    │
│ 29/11/19   │
│ 08/01/2020 │
│ 13/3/20    │
│ 18/7/18    │
│ 09/09/2020 │
│ 09/03/2020 │
│ 21/4/19    │
│ 11/11/2019 │
│ 24/11/18   │
│ 25/11/20   │
│ 08/02/2019 │
│ 31/5/19    │
│ 30/1/20    │
│ 07/06/2019 │
│ 22/9/20    │
│ 11/05/2019 │
│ 29/8/20    │
│ 25/3/19    │
│ 27/9/18    │
│ 24/10/18   │
│ 24/3/20    │
│ 21/11/20   │
│ 26/6/19    │
│ 17/4/19    │
│ 01/03/2020 │
│ 01/06/2020 │
│ 19/6/18    │
│ 29/1/19    │
│ 17/1/20    │
│ 30/10/20   │
│ 23/9/20    │
│ 04/08/2020 │
│ 19/11/20   │
│ 17/8/19    │
│ 31/3/19    │
│ 19/11/19   │
│ 01/03/2019 │
│ 25/8/19    │
│ 01/08/2019 │
│ 04/06/2020 │
│ 23/10/18   │
│ 28/8/18    │
│ 05/08/2019 │
│ 14/9/18    │
│ 09/01/2020 │
│ 04/08/2019 │
│ 30/5/20    │
│ 04/11/2020 │
│ 04/05/2020 │
│ 30/3/19    │
│ 18/12/19   │
│ 17/2/20    │
│ 31/7/20    │
│ 25/6/20    │
│ 06/09/2019 │
│ 21/1/19    │
│ 08/06/2020 │
│ 06/11/2020 │
│ 26/2/20    │
│ 13/9/18    │
│ 26/3/19    │
│ 19/10/19   │
│ 19/1/19    │
│ 15/2/19    │
│ 26/4/20    │
│ 10/12/2019 │
│ 07/12/2019 │
│ 23/12/20   │
│ 11/05/2020 │
│ 18/2/20    │
│ 15/12/20   │
│ 10/02/2020 │
│ 22/12/19   │
│ 10/11/2020 │
│ 11/06/2019 │
│ 17/6/18    │
│ 12/06/2020 │
│ 27/6/19    │
│ 04/04/2019 │
│ 02/08/2019 │
│ 09/11/2018 │
│ 14/4/20    │
│ 09/11/2020 │
│ 04/12/2019 │
│ 09/01/2019 │
│ 31/12/19   │
│ 17/10/18   │
│ 09/03/2019 │
│ 21/9/20    │
│ 26/1/20    │
│ 20/1/20    │
│ 14/6/20    │
│ 06/08/2019 │
│ 27/11/19   │
│ 22/7/20    │
│ 24/3/19    │
│ 23/5/20    │
│ 26/12/19   │
│ 11/02/2020 │
│ 22/1/19    │
│ 19/2/20    │
│ 01/04/2019 │
│ 28/9/20    │
│ 14/10/20   │
│ 08/08/2020 │
│ 15/12/19   │
│ 15/11/18   │
│ 16/5/20    │
│ 01/12/2019 │
│ 30/11/19   │
│ 10/04/2020 │
│ 19/5/20    │
│ 06/07/2020 │
│ 13/11/19   │
│ 11/03/2020 │
│ 14/6/19    │
│ 12/07/2019 │
│ 27/7/19    │
│ 06/09/2020 │
│ 12/07/2018 │
│ 27/10/18   │
│ 18/6/19    │
│ 20/10/20   │
│ 25/7/19    │
│ 31/10/18   │
│ 22/8/19    │
│ 09/11/2019 │
│ 12/12/2020 │
│ 29/12/19   │
│ 13/1/19    │
│ 25/12/20   │
│ 10/10/2020 │
│ 29/7/19    │
│ 23/2/19    │
│ 28/9/19    │
│ 21/12/18   │
│ 06/12/2019 │
│ 07/10/2020 │
│ 13/9/20    │
│ 08/12/2019 │
│ 02/04/2020 │
│ 04/06/2018 │
│ 05/02/2020 │
│ 26/6/18    │
│ 21/8/19    │
│ 16/9/20    │
│ 18/8/19    │
│ 22/3/20    │
│ 12/04/2020 │
│ 20/7/19    │
│ 27/6/18    │
│ 20/4/20    │
│ 21/7/19    │
│ 23/12/19   │
│ 11/01/2020 │
│ 12/11/2019 │
│ 05/07/2018 │
│ 31/1/19    │
│ 29/10/19   │
│ 20/12/20   │
│ 22/2/19    │
│ 05/12/2018 │
│ 07/12/2018 │
│ 09/08/2020 │
│ 15/8/18    │
│ 20/2/20    │
│ 18/12/20   │
│ 11/06/2018 │
│ 09/07/2019 │
│ 04/02/2019 │
│ 10/01/2019 │
│ 24/8/19    │
│ 25/10/18   │
│ 16/4/19    │
│ 28/6/18    │
│ 16/4/20    │
│ 21/11/19   │
│ 03/06/2020 │
│ 17/9/20    │
│ 12/07/2020 │
│ 09/07/2020 │
│ 13/6/18    │
│ 06/09/2018 │
│ 03/08/2020 │
│ 20/8/20    │
│ 25/2/20    │
│ 15/6/18    │
│ 14/12/19   │
│ 03/10/2018 │
│ 01/02/2019 │
│ 28/12/19   │
│ 09/05/2020 │
│ 24/8/18    │
│ 06/10/2018 │
│ 02/07/2020 │
│ 02/01/2019 │
│ 11/10/2018 │
│ 15/10/18   │
│ 17/11/18   │
│ 23/6/20    │
│ 26/12/20   │
│ 13/9/19    │
│ 10/04/2019 │
│ 20/8/19    │
│ 23/6/18    │
│ 02/09/2018 │
│ 24/9/20    │
│ 02/05/2020 │
│ 12/10/2019 │
│ 30/6/18    │
│ 10/07/2020 │
│ 19/7/20    │
│ 17/3/20    │
│ 01/07/2019 │
│ 07/06/2020 │
│ 07/07/2020 │
│ 15/9/18    │
│ 08/03/2019 │
│ 04/11/2018 │
│ 29/10/18   │
│ 06/06/2019 │
│ 17/12/19   │
│ 17/5/20    │
│ 05/04/2020 │
│ 24/12/20   │
│ 06/01/2020 │
│ 08/06/2019 │
│ 26/2/19    │
│ 09/06/2020 │
│ 06/04/2019 │
│ 13/12/20   │
│ 19/7/18    │
│ 06/11/2019 │
│ 05/06/2019 │
│ 31/12/18   │
│ 22/6/19    │
│ 01/08/2020 │
│ 15/6/19    │
│ 02/08/2020 │
│ 13/8/20    │
│ 02/10/2018 │
│ 15/4/20    │
│ 28/12/20   │
│ 30/6/20    │
│ 07/07/2019 │
│ 31/5/20    │
│ 14/3/19    │
│ 26/9/20    │
│ 30/10/19   │
│ 16/7/18    │
│ 26/6/20    │
│ 22/6/20    │
│ 12/10/2018 │
│ 12/09/2019 │
│ 05/08/2020 │
│ 29/7/18    │
│ 16/10/18   │
│ 29/1/20    │
│ 21/7/18    │
│ 06/05/2020 │
│ 10/06/2019 │
│ 09/10/2018 │
│ 24/7/18    │
│ 20/11/20   │
│ 19/12/20   │
│ 25/8/20    │
│ 28/5/19    │
│ 10/12/2018 │
│ 02/01/2020 │
│ 18/4/20    │
│ 01/07/2020 │
│ 09/02/2020 │
│ 02/10/2019 │
│ 23/6/19    │
│ 09/10/2019 │
│ 02/07/2019 │
│ 29/9/20    │
│ 26/10/19   │
│ 27/3/20    │
│ 03/11/2020 │
│ 21/1/20    │
│ 04/10/2019 │
│ 06/03/2020 │
│ 22/3/19    │
│ 24/6/20    │
│ 21/5/19    │
│ 04/10/2018 │
│ 17/4/20    │
│ 07/10/2018 │
│ 10/08/2020 │
│ 04/12/2020 │
│ 15/2/20    │
│ 14/7/20    │
│ 05/06/2020 │
│ 28/11/20   │
│ 23/2/20    │
│ 20/5/19    │
│ 05/09/2018 │
│ 30/7/19    │
│ 29/12/20   │
│ 30/12/18   │
│ 24/4/20    │
│ 10/03/2020 │
│ 04/03/2019 │
│ 14/11/19   │
│ 14/5/19    │
│ 05/05/2020 │
│ 21/4/20    │
│ 03/06/2018 │
│ 08/01/2019 │
│ 15/10/20   │
│ 16/8/20    │
│ 26/11/19   │
│ 10/07/2019 │
│ 09/07/2018 │
│ 18/1/20    │
│ 02/02/2020 │
│ 22/1/20    │
│ 02/06/2019 │
│ 15/9/19    │
│ 03/04/2020 │
│ 01/10/2020 │
│ 23/10/19   │
│ 06/05/2019 │
│ 13/4/19    │
│ 02/10/2020 │
│ 02/06/2018 │
│ 04/05/2019 │
│ 31/1/20    │
│ 14/12/20   │
│ 26/4/19    │
│ 24/2/20    │
│ 13/6/19    │
│ 03/05/2019 │
│ 27/7/18    │
│ 24/9/18    │
│ 24/5/19    │
│ 10/09/2019 │
│ 13/5/20    │
│ 22/7/19    │
│ 06/12/2020 │
│ 24/12/19   │
│ 10/07/2018 │
│ 13/7/19    │
│ 21/6/18    │
│ 20/6/20    │
│ 26/12/18   │
│ 06/08/2018 │
│ 17/3/19    │
│ 25/8/18    │
│ 22/5/20    │
│ 26/9/19    │
│ 14/8/20    │
│ 05/10/2019 │
│ 27/10/20   │
│ 30/5/19    │
│ 01/09/2020 │
│ 11/07/2020 │
│ 03/07/2019 │
│ 29/6/18    │
│ 07/11/2019 │
│ 05/11/2020 │
│ 24/6/18    │
│ 25/10/20   │
│ 19/6/20    │
│ 24/8/20    │
│ 02/09/2020 │
│ 22/8/20    │
│ 20/6/18    │
│ 22/8/18    │
│ 23/8/20    │
│ 06/11/2018 │
│ 02/02/2019 │
│ 19/9/19    │
│ 23/1/19    │
│ 16/6/20    │
│ 15/7/20    │
│ 18/3/19    │
│ 01/06/2018 │
│ 26/7/18    │
│ 24/7/19    │
│ 28/12/18   │
│ 18/9/18    │
│ 16/3/20    │
│ 12/06/2018 │
│ 22/11/20   │
│ 03/05/2020 │
│ 02/12/2018 │
│ 24/10/20   │
│ 15/10/19   │
│ 16/2/19    │
│ 23/11/19   │
│ 18/5/20    │
│ 18/8/18    │
│ 23/7/18    │
│ 21/9/18    │
│ 12/03/2020 │
│ 18/7/20    │
│ 08/08/2018 │
│ 21/3/19    │
│ 28/9/18    │
│ 17/9/18    │
│ 14/8/19    │
│ 31/10/19   │
│ 13/3/19    │
│ 16/11/18   │
│ 30/11/20   │
│ 18/5/19    │
│ 11/08/2019 │
│ 25/9/19    │
│ 10/09/2018 │
│ 31/8/19    │
│ 06/02/2020 │
│ 08/09/2018 │
│ 09/02/2019 │
│ 18/6/20    │
│ 06/10/2020 │
│ 07/07/2018 │
│ 28/1/20    │
│ 07/09/2019 │
│ 13/7/18    │
│ 29/7/20    │
│ 29/3/19    │
│ 23/7/20    │
│ 12/12/2018 │
│ 17/8/20    │
│ 15/11/20   │
│ 28/6/20    │
│ 21/7/20    │
│ 29/9/18    │
│ 22/6/18    │
│ 11/10/2020 │
│ 25/11/18   │
│ 15/4/19    │
│ 06/03/2019 │
│ 06/07/2018 │
│ 08/05/2019 │
│ 31/5/18    │
│ 03/08/2018 │
│ 28/4/19    │
│ 12/05/2019 │
│ 26/8/19    │
│ 01/12/2020 │
│ 09/12/2020 │
│ 02/12/2019 │
│ 07/03/2019 │
│ 29/6/19    │
│ 24/2/19    │
│ 16/3/19    │
│ 08/12/2018 │
│ 19/4/20    │
│ 17/5/19    │
│ 21/2/19    │
│ 27/4/19    │
│ 11/09/2019 │
│ 16/1/19    │
│ 19/10/18   │
│ 26/11/18   │
│ 04/06/2019 │
│ 20/4/19    │
│ 01/04/2020 │
│ 02/12/2020 │
│ 15/1/19    │
│ 20/10/19   │
│ 05/12/2020 │
│ 29/5/20    │
│ 20/11/18   │
│ 19/5/19    │
│ 22/9/19    │
│ 03/11/2018 │
│ 16/11/20   │
│ 05/06/2018 │
│ 28/10/18   │
│ 28/11/18   │
│ 23/9/18    │
│ 04/01/2020 │
│ 14/2/20    │
│ 28/10/20   │
│ 27/8/18    │
│ 12/06/2019 │
│ 03/10/2020 │
│ 25/9/18    │
│ 13/8/18    │
│ 16/12/18   │
│ 30/3/20    │
│ 01/02/2020 │
│ 27/6/20    │
│ 21/6/19    │
│ 07/12/2020 │
│ 27/9/19    │
│ 25/6/19    │
│ 20/8/18    │
│ 24/9/19    │
│ 23/7/19    │
│ 06/04/2020 │
│ 18/3/20    │
│ 26/7/19    │
│ 17/11/20   │
│ 22/5/19    │
│ 27/1/20    │
│ 11/06/2020 │
│ 25/4/20    │
│ 13/7/20    │
│ 04/10/2020 │
│ 31/8/18    │
│ 25/4/19    │
│ 08/12/2020 │
│ 03/09/2020 │
│ 08/06/2018 │
│ 02/04/2019 │
│ 07/10/2019 │
│ 28/7/20    │
│ 16/6/19    │
│ 23/10/20   │
│ 03/01/2019 │
│ 04/09/2020 │
│ 19/3/19    │
│ 09/06/2019 │
│ 28/8/19    │
│ 19/7/19    │
│ 15/8/20    │
│ 27/3/19    │
│ 26/11/20   │
│ 16/8/19    │
│ 07/01/2020 │
│ 20/3/20    │
│ 16/12/20   │
│ 24/12/18   │
│ 11/02/2019 │
│ 15/3/19    │
│ 05/12/2019 │
│ 15/5/19    │
│ 11/08/2018 │
│ 31/8/20    │
│ 01/09/2019 │
│ 04/09/2018 │
│ 10/01/2020 │
│ 27/9/20    │
│ 10/06/2020 │
│ 29/4/19    │
│ 02/11/2018 │
│ 13/2/20    │
│ 29/6/20    │
│ 23/4/19    │
│ 17/2/19    │
│ 06/02/2019 │
│ 27/7/20    │
│ 18/2/19    │
│ 23/11/18   │
│ 24/4/19    │
│ 08/11/2018 │
│ 21/2/20    │
│ 29/10/20   │
│ 03/04/2019 │
│ 18/8/20    │
│ 23/4/20    │
│ 28/11/19   │
│ 16/6/18    │
│ 07/09/2018 │
│ 02/08/2018 │
│ 27/4/20    │
│ 01/01/2020 │
│ 12/11/2018 │
│ 11/03/2019 │
│ 30/7/20    │
│ 14/12/18   │
│ 07/02/2020 │
│ 28/8/20    │
│ 28/10/19   │
│ 23/9/19    │
│ 10/11/2019 │
│ 18/10/19   │
│ 10/03/2019 │
│ 03/11/2019 │
│ 23/11/20   │
│ 17/12/18   │
│ 10/08/2019 │
│ 15/1/20    │
│ 01/06/2019 │
│ 03/12/2018 │
│ 13/1/20    │
│ 26/3/20    │
│ 01/09/2018 │
│ 07/06/2018 │
│ 07/08/2018 │
│ 08/07/2018 │
│ 18/9/19    │
│ 04/02/2020 │
│ 18/12/18   │
│ 29/8/18    │
│ 05/01/2020 │
│ 13/8/19    │
│ 13/4/20    │
│ 20/12/18   │
│ 17/7/18    │
│ 08/11/2019 │
│ 28/2/20    │
│ 23/5/19    │
│ 23/8/19    │
│ 17/8/18    │
│ 14/11/20   │
│ 25/2/19    │
│ 11/01/2019 │
│ 22/11/19   │
│ 29/2/20    │
│ 13/6/20    │
│ 01/07/2018 │
│ 14/10/18   │
│ 16/10/20   │
│ 08/11/2020 │
│ 07/01/2019 │
│ 01/10/2019 │
│ 02/03/2020 │
│ 10/10/2019 │
│ 14/9/19    │
│ 12/12/2019 │
│ 08/10/2018 │
│ 09/12/2018 │
│ 25/7/18    │
│ 16/9/19    │
│ 12/01/2020 │
│ 31/7/19    │
│ 31/3/20    │
│ 26/1/19    │
│ 08/10/2020 │
│ 12/09/2020 │
│ 17/7/19    │
│ 17/1/19    │
│ 03/10/2019 │
│ 05/08/2018 │
│ 14/7/18    │
│ 27/1/19    │
│ 27/12/18   │
│ 19/3/20    │
│ 06/06/2018 │
│ 25/7/20    │
│ 06/12/2018 │
│ 10/06/2018 │
│ 30/4/20    │
│ 30/6/19    │
│ 24/10/19   │
│ 05/11/2019 │
│ 15/9/20    │
│ 22/10/19   │
│ 07/08/2019 │
│ 04/07/2020 │
│ 10/08/2018 │
│ 12/01/2019 │
│ 24/1/19    │
│ 19/4/19    │
│ 17/11/19   │
│ 23/12/18   │
│ 26/5/20    │
│ 25/5/19    │
│ 19/8/19    │
│ 19/1/20    │
│ 16/10/19   │
│ 03/03/2019 │
│ 15/7/19    │
│ 05/09/2019 │
│ 11/08/2020 │
│ 26/10/20   │
│ 26/7/20    │
│ 12/10/2020 │
│ 25/1/20    │
│ 16/11/19   │
│ 17/6/19    │
│ 11/07/2019 │
│ 08/07/2019 │
│ 13/10/18   │
│ 14/10/19   │
│ 15/11/19   │
│ 21/10/20   │
│ 03/02/2020 │
│ 04/12/2018 │
│ 19/6/19    │
│ 19/8/18    │
│ 04/04/2020 │
│ 02/07/2018 │
│ 21/12/20   │
│ 13/2/19    │
│ 04/08/2018 │
│ 08/09/2020 │
│ 27/2/20    │
│ 12/03/2019 │
│ 12/09/2018 │
│ 27/8/20    │
│ 25/1/19    │
│ 30/1/19    │
│ 16/7/19    │
│ 23/8/18    │
│ 17/10/20   │
│ 12/08/2018 │
│ 07/04/2020 │
│ 15/7/18    │
│ 04/07/2019 │
│ 11/10/2019 │
│ 15/6/20    │
│ 19/12/19   │
│ 31/10/20   │
│ 30/4/19    │
│ 01/08/2018 │
│ 09/05/2019 │
│ 09/08/2018 │
│ 14/4/19    │
│ 25/3/20    │
│ 05/04/2019 │
│ 02/03/2019 │
│ 26/8/18    │
│ 20/1/19    │
│ 12/08/2019 │
│ 05/02/2019 │
│ 18/4/19    │
│ 25/12/19   │
│ 22/4/20    │
│ 05/10/2020 │
│ 09/09/2018 │
│ 20/2/19    │
│ 12/11/2020 │
│ 16/9/18    │
│ 09/12/2019 │
│ 23/1/20    │
│ 08/07/2020 │
│ 17/10/19   │
│ 23/3/20    │
│ 24/1/20    │
│ 01/12/2018 │
│ 06/01/2019 │
│ 15/3/20    │
│ 18/11/19   │
│ 11/12/2020 │
│ 03/12/2019 │
│ 01/10/2018 │
│ 10/02/2019 │
│ 21/8/18    │
│ 22/12/20   │
│ 21/10/19   │
│ 05/03/2020 │
│ 03/07/2018 │
│ 20/9/20    │
│ 22/4/19    │
│ 01/11/2020 │
│ 04/07/2018 │
│ 11/09/2020 │
│ 05/11/2018 │
│ 20/7/18    │
│ 12/04/2019 │
│ 18/11/20   │
│ 11/11/2020 │
│ 17/9/19    │
│ 03/12/2020 │
│ 18/7/19    │
│ 11/04/2020 │
└────────────┘
ShipDate: shape: (966, 1)
┌────────────┐
│ ShipDate   │
│ ---        │
│ str        │
╞════════════╡
│ 15/12/19   │
│ 3/8/2019   │
│ 28/8/20    │
│ 23/10/19   │
│ 8/1/2020   │
│ 25/4/19    │
│ 4/9/2018   │
│ 19/9/19    │
│ 17/6/18    │
│ 15/9/18    │
│ 16/11/19   │
│ 8/10/2019  │
│ 20/4/19    │
│ 17/7/18    │
│ 6/9/2019   │
│ 19/3/19    │
│ 6/3/2019   │
│ 12/10/2019 │
│ 21/8/19    │
│ 18/8/18    │
│ 11/3/2020  │
│ 1/1/2019   │
│ 12/2/2019  │
│ 10/12/2020 │
│ 29/6/18    │
│ 10/7/2019  │
│ 30/8/18    │
│ 27/7/18    │
│ 19/5/19    │
│ 7/1/2021   │
│ 23/2/20    │
│ 14/10/18   │
│ 9/1/2020   │
│ 12/7/2018  │
│ 30/9/18    │
│ 14/6/18    │
│ 22/1/21    │
│ 21/11/18   │
│ 29/11/20   │
│ 26/6/19    │
│ 17/4/19    │
│ 22/10/18   │
│ 21/5/20    │
│ 14/7/19    │
│ 10/9/2018  │
│ 7/2/2019   │
│ 20/5/20    │
│ 14/10/20   │
│ 27/8/20    │
│ 9/10/2018  │
│ 28/9/18    │
│ 20/6/18    │
│ 17/11/18   │
│ 18/10/19   │
│ 18/1/19    │
│ 21/9/20    │
│ 11/5/2019  │
│ 31/3/20    │
│ 1/2/2019   │
│ 27/2/20    │
│ 22/3/19    │
│ 24/2/20    │
│ 30/12/20   │
│ 4/4/2020   │
│ 15/11/20   │
│ 26/7/19    │
│ 19/2/19    │
│ 27/1/19    │
│ 14/12/20   │
│ 17/1/21    │
│ 24/8/18    │
│ 23/8/18    │
│ 10/6/2019  │
│ 20/8/20    │
│ 15/12/20   │
│ 24/7/20    │
│ 4/8/2018   │
│ 10/6/2018  │
│ 24/4/20    │
│ 6/7/2018   │
│ 31/5/19    │
│ 6/1/2020   │
│ 23/9/18    │
│ 15/4/20    │
│ 8/3/2020   │
│ 24/10/20   │
│ 10/1/2021  │
│ 1/8/2019   │
│ 3/7/2020   │
│ 11/1/2019  │
│ 19/12/18   │
│ 3/8/2018   │
│ 9/1/2019   │
│ 30/11/19   │
│ 6/2/2020   │
│ 10/4/2020  │
│ 13/1/19    │
│ 12/1/2020  │
│ 26/10/19   │
│ 18/4/20    │
│ 7/8/2019   │
│ 20/11/19   │
│ 22/12/19   │
│ 19/9/18    │
│ 29/2/20    │
│ 15/11/18   │
│ 23/2/19    │
│ 1/7/2018   │
│ 16/9/20    │
│ 17/6/19    │
│ 20/11/18   │
│ 22/2/20    │
│ 28/6/18    │
│ 2/12/2018  │
│ 1/8/2020   │
│ 13/7/19    │
│ 11/8/2019  │
│ 13/12/18   │
│ 29/12/18   │
│ 20/7/18    │
│ 25/12/18   │
│ 6/12/2020  │
│ 17/4/20    │
│ 19/1/19    │
│ 9/5/2020   │
│ 2/7/2020   │
│ 19/4/19    │
│ 26/12/20   │
│ 9/8/2018   │
│ 3/3/2019   │
│ 26/11/18   │
│ 25/10/20   │
│ 4/4/2019   │
│ 16/3/19    │
│ 25/3/19    │
│ 28/11/19   │
│ 12/6/2018  │
│ 4/2/2019   │
│ 13/6/19    │
│ 6/9/2018   │
│ 10/1/2019  │
│ 16/9/19    │
│ 28/1/20    │
│ 22/7/19    │
│ 28/8/19    │
│ 11/7/2020  │
│ 6/5/2020   │
│ 6/12/2019  │
│ 26/12/18   │
│ 22/1/19    │
│ 30/12/19   │
│ 23/12/19   │
│ 15/5/19    │
│ 25/3/20    │
│ 10/9/2020  │
│ 12/5/2020  │
│ 7/6/2018   │
│ 17/3/19    │
│ 11/7/2019  │
│ 9/8/2020   │
│ 2/2/2019   │
│ 30/6/20    │
│ 15/8/18    │
│ 5/12/2019  │
│ 22/4/20    │
│ 28/7/18    │
│ 20/2/19    │
│ 26/4/20    │
│ 22/3/20    │
│ 14/3/19    │
│ 28/7/19    │
│ 5/5/2020   │
│ 18/4/19    │
│ 16/3/20    │
│ 7/5/2020   │
│ 10/1/2020  │
│ 1/1/2020   │
│ 4/3/2019   │
│ 14/2/19    │
│ 3/9/2020   │
│ 7/10/2020  │
│ 31/12/18   │
│ 10/2/2020  │
│ 7/1/2019   │
│ 25/7/19    │
│ 27/7/20    │
│ 8/8/2018   │
│ 3/9/2018   │
│ 15/8/20    │
│ 3/9/2019   │
│ 19/12/19   │
│ 31/12/20   │
│ 22/8/20    │
│ 2/9/2018   │
│ 31/10/20   │
│ 29/9/19    │
│ 7/7/2019   │
│ 5/7/2018   │
│ 25/2/20    │
│ 15/11/19   │
│ 11/9/2018  │
│ 22/1/20    │
│ 9/1/2021   │
│ 13/5/20    │
│ 9/6/2018   │
│ 23/1/19    │
│ 14/12/19   │
│ 23/1/21    │
│ 9/9/2019   │
│ 6/7/2019   │
│ 18/11/18   │
│ 16/10/19   │
│ 2/11/2019  │
│ 12/11/2020 │
│ 29/10/19   │
│ 30/5/20    │
│ 22/5/19    │
│ 10/9/2019  │
│ 21/9/18    │
│ 15/6/20    │
│ 2/7/2019   │
│ 12/6/2020  │
│ 11/9/2019  │
│ 7/12/2019  │
│ 26/11/20   │
│ 18/9/18    │
│ 26/8/19    │
│ 28/10/18   │
│ 13/12/19   │
│ 7/9/2019   │
│ 24/7/18    │
│ 29/12/20   │
│ 29/6/19    │
│ 24/11/20   │
│ 14/8/20    │
│ 22/6/19    │
│ 1/11/2020  │
│ 23/5/19    │
│ 16/12/19   │
│ 1/8/2018   │
│ 9/2/2019   │
│ 4/11/2020  │
│ 10/5/2019  │
│ 16/4/20    │
│ 4/9/2020   │
│ 19/8/19    │
│ 26/1/20    │
│ 19/11/20   │
│ 3/11/2020  │
│ 8/9/2020   │
│ 23/10/20   │
│ 20/12/20   │
│ 1/10/2020  │
│ 22/12/18   │
│ 15/7/20    │
│ 6/9/2020   │
│ 7/6/2019   │
│ 20/9/19    │
│ 16/6/18    │
│ 24/1/21    │
│ 3/11/2018  │
│ 8/7/2018   │
│ 29/4/20    │
│ 19/7/20    │
│ 17/12/20   │
│ 2/9/2019   │
│ 17/8/18    │
│ 27/9/19    │
│ 7/1/2020   │
│ 22/7/18    │
│ 17/11/19   │
│ 5/10/2020  │
│ 5/8/2018   │
│ 19/11/18   │
│ 1/3/2019   │
│ 9/11/2020  │
│ 17/7/19    │
│ 1/7/2020   │
│ 4/1/2021   │
│ 13/4/20    │
│ 10/5/2020  │
│ 11/6/2020  │
│ 14/8/19    │
│ 21/3/19    │
│ 29/10/20   │
│ 7/8/2018   │
│ 16/1/21    │
│ 25/10/18   │
│ 17/2/19    │
│ 24/12/19   │
│ 6/10/2018  │
│ 30/3/19    │
│ 20/1/20    │
│ 30/4/19    │
│ 28/11/18   │
│ 22/6/18    │
│ 19/8/20    │
│ 16/12/18   │
│ 30/6/19    │
│ 26/9/19    │
│ 27/10/19   │
│ 27/8/18    │
│ 22/9/19    │
│ 15/5/20    │
│ 21/12/18   │
│ 9/6/2020   │
│ 31/8/18    │
│ 27/11/20   │
│ 7/3/2019   │
│ 6/11/2018  │
│ 4/7/2018   │
│ 4/2/2020   │
│ 26/2/20    │
│ 6/8/2020   │
│ 25/5/20    │
│ 18/7/20    │
│ 2/12/2019  │
│ 25/9/20    │
│ 27/8/19    │
│ 12/4/2019  │
│ 21/1/19    │
│ 2/4/2019   │
│ 6/4/2019   │
│ 12/8/2019  │
│ 30/12/18   │
│ 26/8/20    │
│ 12/3/2019  │
│ 17/6/20    │
│ 24/4/19    │
│ 2/12/2020  │
│ 10/7/2020  │
│ 21/3/20    │
│ 13/11/18   │
│ 20/3/20    │
│ 27/10/20   │
│ 15/9/20    │
│ 17/9/20    │
│ 13/9/19    │
│ 23/6/20    │
│ 1/4/2020   │
│ 18/7/18    │
│ 27/6/19    │
│ 30/3/20    │
│ 3/6/2019   │
│ 17/9/19    │
│ 17/8/19    │
│ 14/1/19    │
│ 1/9/2018   │
│ 14/2/20    │
│ 28/2/20    │
│ 4/10/2019  │
│ 21/10/19   │

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, String, String, String, String, Int64, Int64, Int64, Int64, Int64, Float64, String, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                  Unique values in OrderNumber : 7991
                 Unique values in SalesChannel : 4
                Unique values in WarehouseCode : 6
                 Unique values in ProcuredDate : 11
                    Unique values in OrderDate : 945
                     Unique values in ShipDate : 966
                 Unique values in DeliveryDate : 966
                 Unique values in CurrencyCode : 1
                  Unique values in SalesTeamID : 28
                   Unique values in CustomerID : 50
                      Unique values in StoreID : 367
                    Unique values in ProductID : 47
                Unique values in OrderQuantity : 8
              Unique values in DiscountApplied : 7
                     Unique values in UnitCost : 5252
                    Unique values in UnitPrice : 664

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

SalesTeamID
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ SalesTeamID │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 7991.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 14.384307   │
│ std        ┆ 7.986086    │
│ min        ┆ 1.0         │
│ 25%        ┆ 8.0         │
│ 50%        ┆ 14.0        │
│ 75%        ┆ 21.0        │
│ max        ┆ 28.0        │
└────────────┴─────────────┘


CustomerID
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ CustomerID │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 7991.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 25.457014  │
│ std        ┆ 14.414883  │
│ min        ┆ 1.0        │
│ 25%        ┆ 13.0       │
│ 50%        ┆ 25.0       │
│ 75%        ┆ 38.0       │
│ max        ┆ 50.0       │
└────────────┴────────────┘


StoreID
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ StoreID    │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 7991.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 183.850081 │
│ std        ┆ 105.903946 │
│ min        ┆ 1.0        │
│ 25%        ┆ 91.0       │
│ 50%        ┆ 183.0      │
│ 75%        ┆ 276.0      │
│ max        ┆ 367.0      │
└────────────┴────────────┘


ProductID
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ ProductID │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 7991.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 23.771743 │
│ std        ┆ 13.526545 │
│ min        ┆ 1.0       │
│ 25%        ┆ 12.0      │
│ 50%        ┆ 24.0      │
│ 75%        ┆ 36.0      │
│ max        ┆ 47.0      │
└────────────┴───────────┘


OrderQuantity
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ OrderQuantity │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 7991.0        │
│ null_count ┆ 0.0           │
│ mean       ┆ 4.525341      │
│ std        ┆ 2.312631      │
│ min        ┆ 1.0           │
│ 25%        ┆ 3.0           │
│ 50%        ┆ 5.0           │
│ 75%        ┆ 7.0           │
│ max        ┆ 8.0           │
└────────────┴───────────────┘


DiscountApplied
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ DiscountApplied │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 7991.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 0.115649        │
│ std        ┆ 0.085018        │
│ min        ┆ 0.05            │
│ 25%        ┆ 0.05            │
│ 50%        ┆ 0.08            │
│ 75%        ┆ 0.15            │
│ max        ┆ 0.4             │
└────────────┴─────────────────┘

### Retrieve Count of Nulls In Each Feature

In [11]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)

pl.Config.set_tbl_rows(100)
null_counts

shape: (16, 2)
┌─────────────────┬────────────┐
│ feature         ┆ null_count │
│ ---             ┆ ---        │
│ str             ┆ i64        │
╞═════════════════╪════════════╡
│ OrderNumber     ┆ 0          │
│ SalesChannel    ┆ 0          │
│ WarehouseCode   ┆ 0          │
│ ProcuredDate    ┆ 0          │
│ OrderDate       ┆ 0          │
│ ShipDate        ┆ 0          │
│ DeliveryDate    ┆ 0          │
│ CurrencyCode    ┆ 0          │
│ SalesTeamID     ┆ 0          │
│ CustomerID      ┆ 0          │
│ StoreID         ┆ 0          │
│ ProductID       ┆ 0          │
│ OrderQuantity   ┆ 0          │
│ DiscountApplied ┆ 0          │
│ UnitCost        ┆ 0          │
│ UnitPrice       ┆ 0          │
└─────────────────┴────────────┘

### Display Unique Values For Each Feature

In [12]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
pl.Config.set_tbl_rows(1000)
list_unique_values_under_threshold(df)

Column: SalesChannel (4 unique values)
shape: (4,)
Series: 'SalesChannel' [str]
[
	"Distributor"
	"In-Store"
	"Online"
	"Wholesale"
]
--------------------------------------------------
Column: WarehouseCode (6 unique values)
shape: (6,)
Series: 'WarehouseCode' [str]
[
	"WARE-MKL1006"
	"WARE-NBV1002"
	"WARE-NMK1003"
	"WARE-PUJ1005"
	"WARE-UHY1004"
	"WARE-XYS1001"
]
--------------------------------------------------
Column: ProcuredDate (11 unique values)
shape: (11,)
Series: 'ProcuredDate' [str]
[
	"1/12/2019"
	"10/3/2020"
	"10/4/2018"
	"15/5/19"
	"18/6/20"
	"19/7/18"
	"23/8/19"
	"26/9/20"
	"27/10/18"
	"31/12/17"
	"4/2/2019"
]
--------------------------------------------------
Column: OrderDate (945 unique values)
shape: (945,)
Series: 'OrderDate' [str]
[
	"01/01/2019"
	"01/01/2020"
	"01/02/2019"
	"01/02/2020"
	"01/03/2019"
	"01/03/2020"
	"01/04/2019"
	"01/04/2020"
	"01/05/2019"
	"01/05/2020"
	"01/06/2018"
	"01/06/2019"
	"01/06/2020"
	"01/07/2018"
	"01/07/2019"
	"01/07/2020"
	"01/08/2018"
	"01/08/2019"
	"01/08/2020"
	"01/09/2018"
	"01/09/2019"
	"01/09/2020"
	"01/10/2018"
	"01/10/2019"
	"01/10/2020"
	"01/11/2018"
	"01/11/2019"
	"01/11/2020"
	"01/12/2018"
	"01/12/2019"
	"01/12/2020"
	"02/01/2019"
	"02/01/2020"
	"02/02/2019"
	"02/02/2020"
	"02/03/2019"
	"02/03/2020"
	"02/04/2019"
	"02/04/2020"
	"02/05/2019"
	"02/05/2020"
	"02/06/2018"
	"02/06/2019"
	"02/06/2020"
	"02/07/2018"
	"02/07/2019"
	"02/07/2020"
	"02/08/2018"
	"02/08/2019"
	"02/08/2020"
	"02/09/2018"
	"02/09/2019"
	"02/09/2020"
	"02/10/2018"
	"02/10/2019"
	"02/10/2020"
	"02/11/2018"
	"02/11/2019"
	"02/11/2020"
	"02/12/2018"
	"02/12/2019"
	"02/12/2020"
	"03/01/2019"
	"03/01/2020"
	"03/02/2019"
	"03/02/2020"
	"03/03/2019"
	"03/03/2020"
	"03/04/2019"
	"03/04/2020"
	"03/05/2019"
	"03/05/2020"
	"03/06/2018"
	"03/06/2019"
	"03/06/2020"
	"03/07/2018"
	"03/07/2019"
	"03/07/2020"
	"03/08/2018"
	"03/08/2019"
	"03/08/2020"
	"03/09/2018"
	"03/09/2019"
	"03/09/2020"
	"03/10/2018"
	"03/10/2019"
	"03/10/2020"
	"03/11/2018"
	"03/11/2019"
	"03/11/2020"
	"03/12/2018"
	"03/12/2019"
	"03/12/2020"
	"04/01/2019"
	"04/01/2020"
	"04/02/2019"
	"04/02/2020"
	"04/03/2019"
	"04/03/2020"
	"04/04/2019"
	"04/04/2020"
	"04/05/2019"
	"04/05/2020"
	"04/06/2018"
	"04/06/2019"
	"04/06/2020"
	"04/07/2018"
	"04/07/2019"
	"04/07/2020"
	"04/08/2018"
	"04/08/2019"
	"04/08/2020"
	"04/09/2018"
	"04/09/2019"
	"04/09/2020"
	"04/10/2018"
	"04/10/2019"
	"04/10/2020"
	"04/11/2018"
	"04/11/2019"
	"04/11/2020"
	"04/12/2018"
	"04/12/2019"
	"04/12/2020"
	"05/01/2019"
	"05/01/2020"
	"05/02/2019"
	"05/02/2020"
	"05/03/2019"
	"05/03/2020"
	"05/04/2019"
	"05/04/2020"
	"05/05/2019"
	"05/05/2020"
	"05/06/2018"
	"05/06/2019"
	"05/06/2020"
	"05/07/2018"
	"05/07/2019"
	"05/07/2020"
	"05/08/2018"
	"05/08/2019"
	"05/08/2020"
	"05/09/2018"
	"05/09/2019"
	"05/09/2020"
	"05/10/2018"
	"05/10/2019"
	"05/10/2020"
	"05/11/2018"
	"05/11/2019"
	"05/11/2020"
	"05/12/2018"
	"05/12/2019"
	"05/12/2020"
	"06/01/2019"
	"06/01/2020"
	"06/02/2019"
	"06/02/2020"
	"06/03/2019"
	"06/03/2020"
	"06/04/2019"
	"06/04/2020"
	"06/05/2019"
	"06/05/2020"
	"06/06/2018"
	"06/06/2019"
	"06/06/2020"
	"06/07/2018"
	"06/07/2019"
	"06/07/2020"
	"06/08/2018"
	"06/08/2019"
	"06/08/2020"
	"06/09/2018"
	"06/09/2019"
	"06/09/2020"
	"06/10/2018"
	"06/10/2019"
	"06/10/2020"
	"06/11/2018"
	"06/11/2019"
	"06/11/2020"
	"06/12/2018"
	"06/12/2019"
	"06/12/2020"
	"07/01/2019"
	"07/01/2020"
	"07/02/2019"
	"07/02/2020"
	"07/03/2019"
	"07/03/2020"
	"07/04/2019"
	"07/04/2020"
	"07/05/2019"
	"07/05/2020"
	"07/06/2018"
	"07/06/2019"
	"07/06/2020"
	"07/07/2018"
	"07/07/2019"
	"07/07/2020"
	"07/08/2018"
	"07/08/2019"
	"07/08/2020"
	"07/09/2018"
	"07/09/2019"
	"07/09/2020"
	"07/10/2018"
	"07/10/2019"
	"07/10/2020"
	"07/11/2018"
	"07/11/2019"
	"07/11/2020"
	"07/12/2018"
	"07/12/2019"
	"07/12/2020"
	"08/01/2019"
	"08/01/2020"
	"08/02/2019"
	"08/02/2020"
	"08/03/2019"
	"08/03/2020"
	"08/04/2019"
	"08/04/2020"
	"08/05/2019"
	"08/05/2020"
	"08/06/2018"
	"08/06/2019"
	"08/06/2020"
	"08/07/2018"
	"08/07/2019"
	"08/07/2020"
	"08/08/2018"
	"08/08/2019"
	"08/08/2020"
	"08/09/2018"
	"08/09/2019"
	"08/09/2020"
	"08/10/2018"
	"08/10/2019"
	"08/10/2020"
	"08/11/2018"
	"08/11/2019"
	"08/11/2020"
	"08/12/2018"
	"08/12/2019"
	"08/12/2020"
	"09/01/2019"
	"09/01/2020"
	"09/02/2019"
	"09/02/2020"
	"09/03/2019"
	"09/03/2020"
	"09/04/2019"
	"09/04/2020"
	"09/05/2019"
	"09/05/2020"
	"09/06/2018"
	"09/06/2019"
	"09/06/2020"
	"09/07/2018"
	"09/07/2019"
	"09/07/2020"
	"09/08/2018"
	"09/08/2019"
	"09/08/2020"
	"09/09/2018"
	"09/09/2019"
	"09/09/2020"
	"09/10/2018"
	"09/10/2019"
	"09/10/2020"
	"09/11/2018"
	"09/11/2019"
	"09/11/2020"
	"09/12/2018"
	"09/12/2019"
	"09/12/2020"
	"10/01/2019"
	"10/01/2020"
	"10/02/2019"
	"10/02/2020"
	"10/03/2019"
	"10/03/2020"
	"10/04/2019"
	"10/04/2020"
	"10/05/2019"
	"10/05/2020"
	"10/06/2018"
	"10/06/2019"
	"10/06/2020"
	"10/07/2018"
	"10/07/2019"
	"10/07/2020"
	"10/08/2018"
	"10/08/2019"
	"10/08/2020"
	"10/09/2018"
	"10/09/2019"
	"10/09/2020"
	"10/10/2018"
	"10/10/2019"
	"10/10/2020"
	"10/11/2018"
	"10/11/2019"
	"10/11/2020"
	"10/12/2018"
	"10/12/2019"
	"10/12/2020"
	"11/01/2019"
	"11/01/2020"
	"11/02/2019"
	"11/02/2020"
	"11/03/2019"
	"11/03/2020"
	"11/04/2019"
	"11/04/2020"
	"11/05/2019"
	"11/05/2020"
	"11/06/2018"
	"11/06/2019"
	"11/06/2020"
	"11/07/2018"
	"11/07/2019"
	"11/07/2020"
	"11/08/2018"
	"11/08/2019"
	"11/08/2020"
	"11/09/2018"
	"11/09/2019"
	"11/09/2020"
	"11/10/2018"
	"11/10/2019"
	"11/10/2020"
	"11/11/2018"
	"11/11/2019"
	"11/11/2020"
	"11/12/2018"
	"11/12/2019"
	"11/12/2020"
	"12/01/2019"
	"12/01/2020"
	"12/02/2019"
	"12/02/2020"
	"12/03/2019"
	"12/03/2020"
	"12/04/2019"
	"12/04/2020"
	"12/05/2019"
	"12/05/2020"
	"12/06/2018"
	"12/06/2019"
	"12/06/2020"
	"12/07/2018"
	"12/07/2019"
	"12/07/2020"
	"12/08/2018"
	"12/08/2019"
	"12/08/2020"
	"12/09/2018"
	"12/09/2019"
	"12/09/2020"
	"12/10/2018"
	"12/10/2019"
	"12/10/2020"
	"12/11/2018"
	"12/11/2019"
	"12/11/2020"
	"12/12/2018"
	"12/12/2019"
	"12/12/2020"
	"13/1/19"
	"13/1/20"
	"13/10/18"
	"13/10/19"
	"13/10/20"
	"13/11/18"
	"13/11/19"
	"13/11/20"
	"13/12/18"
	"13/12/19"
	"13/12/20"
	"13/2/19"
	"13/2/20"
	"13/3/19"
	"13/3/20"
	"13/4/19"
	"13/4/20"
	"13/5/19"
	"13/5/20"
	"13/6/18"
	"13/6/19"
	"13/6/20"
	"13/7/18"
	"13/7/19"
	"13/7/20"
	"13/8/18"
	"13/8/19"
	"13/8/20"
	"13/9/18"
	"13/9/19"
	"13/9/20"
	"14/1/19"
	"14/1/20"
	"14/10/18"
	"14/10/19"
	"14/10/20"
	"14/11/18"
	"14/11/19"
	"14/11/20"
	"14/12/18"
	"14/12/19"
	"14/12/20"
	"14/2/19"
	"14/2/20"
	"14/3/19"
	"14/3/20"
	"14/4/19"
	"14/4/20"
	"14/5/19"
	"14/5/20"
	"14/6/18"
	"14/6/19"
	"14/6/20"
	"14/7/18"
	"14/7/19"
	"14/7/20"
	"14/8/18"
	"14/8/19"
	"14/8/20"
	"14/9/18"
	"14/9/19"
	"14/9/20"
	"15/1/19"
	"15/1/20"
	"15/10/18"
	"15/10/19"
	"15/10/20"
	"15/11/18"
	"15/11/19"
	"15/11/20"
	"15/12/18"
	"15/12/19"
	"15/12/20"
	"15/2/19"
	"15/2/20"
	"15/3/19"
	"15/3/20"
	"15/4/19"
	"15/4/20"
	"15/5/19"
	"15/5/20"
	"15/6/18"
	"15/6/19"
	"15/6/20"
	"15/7/18"
	"15/7/19"
	"15/7/20"
	"15/8/18"
	"15/8/19"
	"15/8/20"
	"15/9/18"
	"15/9/19"
	"15/9/20"
	"16/1/19"
	"16/1/20"
	"16/10/18"
	"16/10/19"
	"16/10/20"
	"16/11/18"
	"16/11/19"
	"16/11/20"
	"16/12/18"
	"16/12/19"
	"16/12/20"
	"16/2/19"
	"16/2/20"
	"16/3/19"
	"16/3/20"
	"16/4/19"
	"16/4/20"
	"16/5/19"
	"16/5/20"
	"16/6/18"
	"16/6/19"
	"16/6/20"
	"16/7/18"
	"16/7/19"
	"16/7/20"
	"16/8/18"
	"16/8/19"
	"16/8/20"
	"16/9/18"
	"16/9/19"
	"16/9/20"
	"17/1/19"
	"17/1/20"
	"17/10/18"
	"17/10/19"
	"17/10/20"
	"17/11/18"
	"17/11/19"
	"17/11/20"
	"17/12/18"
	"17/12/19"
	"17/12/20"
	"17/2/19"
	"17/2/20"
	"17/3/19"
	"17/3/20"
	"17/4/19"
	"17/4/20"
	"17/5/19"
	"17/5/20"
	"17/6/18"
	"17/6/19"
	"17/6/20"
	"17/7/18"
	"17/7/19"
	"17/7/20"
	"17/8/18"
	"17/8/19"
	"17/8/20"
	"17/9/18"
	"17/9/19"
	"17/9/20"
	"18/1/19"
	"18/1/20"
	"18/10/18"
	"18/10/19"
	"18/10/20"
	"18/11/18"
	"18/11/19"
	"18/11/20"
	"18/12/18"
	"18/12/19"
	"18/12/20"
	"18/2/19"
	"18/2/20"
	"18/3/19"
	"18/3/20"
	"18/4/19"
	"18/4/20"
	"18/5/19"
	"18/5/20"
	"18/6/18"
	"18/6/19"
	"18/6/20"
	"18/7/18"
	"18/7/19"
	"18/7/20"
	"18/8/18"
	"18/8/19"
	"18/8/20"
	"18/9/18"
	"18/9/19"
	"18/9/20"
	"19/1/19"
	"19/1/20"
	"19/10/18"
	"19/10/19"
	"19/10/20"
	"19/11/18"
	"19/11/19"
	"19/11/20"
	"19/12/18"
	"19/12/19"
	"19/12/20"
	"19/2/19"
	"19/2/20"
	"19/3/19"
	"19/3/20"
	"19/4/19"
	"19/4/20"
	"19/5/19"
	"19/5/20"
	"19/6/18"
	"19/6/19"
	"19/6/20"
	"19/7/18"
	"19/7/19"
	"19/7/20"
	"19/8/18"
	"19/8/19"
	"19/8/20"
	"19/9/18"
	"19/9/19"
	"19/9/20"
	"20/1/19"
	"20/1/20"
	"20/10/18"
	"20/10/19"
	"20/10/20"
	"20/11/18"
	"20/11/19"
	"20/11/20"
	"20/12/18"
	"20/12/19"
	"20/12/20"
	"20/2/19"
	"20/2/20"
	"20/3/19"
	"20/3/20"
	"20/4/19"
	"20/4/20"
	"20/5/19"
	"20/5/20"
	"20/6/18"
	"20/6/19"
	"20/6/20"
	"20/7/18"
	"20/7/19"
	"20/7/20"
	"20/8/18"
	"20/8/19"
	"20/8/20"
	"20/9/18"
	"20/9/19"
	"20/9/20"
	"21/1/19"
	"21/1/20"
	"21/10/18"
	"21/10/19"
	"21/10/20"
	"21/11/18"
	"21/11/19"
	"21/11/20"
	"21/12/18"
	"21/12/19"
	"21/12/20"
	"21/2/19"
	"21/2/20"
	"21/3/19"
	"21/3/20"
	"21/4/19"
	"21/4/20"
	"21/5/19"
	"21/5/20"
	"21/6/18"
	"21/6/19"
	"21/6/20"
	"21/7/18"
	"21/7/19"
	"21/7/20"
	"21/8/18"
	"21/8/19"
	"21/8/20"
	"21/9/18"
	"21/9/19"
	"21/9/20"
	"22/1/19"
	"22/1/20"
	"22/10/18"
	"22/10/19"
	"22/10/20"
	"22/11/18"
	"22/11/19"
	"22/11/20"
	"22/12/18"
	"22/12/19"
	"22/12/20"
	"22/2/19"
	"22/2/20"
	"22/3/19"
	"22/3/20"
	"22/4/19"
	"22/4/20"
	"22/5/19"
	"22/5/20"
	"22/6/18"
	"22/6/19"
	"22/6/20"
	"22/7/18"
	"22/7/19"
	"22/7/20"
	"22/8/18"
	"22/8/19"
	"22/8/20"
	"22/9/18"
	"22/9/19"
	"22/9/20"
	"23/1/19"
	"23/1/20"
	"23/10/18"
	"23/10/19"
	"23/10/20"
	"23/11/18"
	"23/11/19"
	"23/11/20"
	"23/12/18"
	"23/12/19"
	"23/12/20"
	"23/2/19"
	"23/2/20"
	"23/3/19"
	"23/3/20"
	"23/4/19"
	"23/4/20"
	"23/5/19"
	"23/5/20"
	"23/6/18"
	"23/6/19"
	"23/6/20"
	"23/7/18"
	"23/7/19"
	"23/7/20"
	"23/8/18"
	"23/8/19"
	"23/8/20"
	"23/9/18"
	"23/9/19"
	"23/9/20"
	"24/1/19"
	"24/1/20"
	"24/10/18"
	"24/10/19"
	"24/10/20"
	"24/11/18"
	"24/11/19"
	"24/11/20"
	"24/12/18"
	"24/12/19"
	"24/12/20"
	"24/2/19"
	"24/2/20"
	"24/3/19"
	"24/3/20"
	"24/4/19"
	"24/4/20"
	"24/5/19"
	"24/5/20"
	"24/6/18"
	"24/6/19"
	"24/6/20"
	"24/7/18"
	"24/7/19"
	"24/7/20"
	"24/8/18"
	"24/8/19"
	"24/8/20"
	"24/9/18"
	"24/9/19"
	"24/9/20"
	"25/1/19"
	"25/1/20"
	"25/10/18"
	"25/10/19"
	"25/10/20"
	"25/11/18"
	"25/11/19"
	"25/11/20"
	"25/12/18"
	"25/12/19"
	"25/12/20"
	"25/2/19"
	"25/2/20"
	"25/3/19"
	"25/3/20"
	"25/4/19"
	"25/4/20"
	"25/5/19"
	"25/5/20"
	"25/6/18"
	"25/6/19"
	"25/6/20"
	"25/7/18"
	"25/7/19"
	"25/7/20"
	"25/8/18"
	"25/8/19"
	"25/8/20"
	"25/9/18"
	"25/9/19"
	"25/9/20"
	"26/1/19"
	"26/1/20"
	"26/10/18"
	"26/10/19"
	"26/10/20"
	"26/11/18"
	"26/11/19"
	"26/11/20"
	"26/12/18"
	"26/12/19"
	"26/12/20"
	"26/2/19"
	"26/2/20"
	"26/3/19"
	"26/3/20"
	"26/4/19"
	"26/4/20"
	"26/5/19"
	"26/5/20"
	"26/6/18"
	"26/6/19"
	"26/6/20"
	"26/7/18"
	"26/7/19"
	"26/7/20"
	"26/8/18"
	"26/8/19"
	"26/8/20"
	"26/9/18"
	"26/9/19"
	"26/9/20"
	"27/1/19"
	"27/1/20"
	"27/10/18"
	"27/10/19"
	"27/10/20"
	"27/11/18"
	"27/11/19"
	"27/11/20"
	"27/12/18"
	"27/12/19"
	"27/12/20"
	"27/2/19"
	"27/2/20"
	"27/3/19"
	"27/3/20"
	"27/4/19"
	"27/4/20"
	"27/5/19"
	"27/5/20"
	"27/6/18"
	"27/6/19"
	"27/6/20"
	"27/7/18"
	"27/7/19"
	"27/7/20"
	"27/8/18"
	"27/8/19"
	"27/8/20"
	"27/9/18"
	"27/9/19"
	"27/9/20"
	"28/1/19"
	"28/1/20"
	"28/10/18"
	"28/10/19"
	"28/10/20"
	"28/11/18"
	"28/11/19"
	"28/11/20"
	"28/12/18"
	"28/12/19"
	"28/12/20"
	"28/2/19"
	"28/2/20"
	"28/3/19"
	"28/3/20"
	"28/4/19"
	"28/4/20"
	"28/5/19"
	"28/5/20"
	"28/6/18"
	"28/6/19"
	"28/6/20"
	"28/7/18"
	"28/7/19"
	"28/7/20"
	"28/8/18"
	"28/8/19"
	"28/8/20"
	"28/9/18"
	"28/9/19"
	"28/9/20"
	"29/1/19"
	"29/1/20"
	"29/10/18"
	"29/10/19"
	"29/10/20"
	"29/11/18"
	"29/11/19"
	"29/11/20"
	"29/12/18"
	"29/12/19"
	"29/12/20"
	"29/2/20"
	"29/3/19"
	"29/3/20"
	"29/4/19"
	"29/4/20"
	"29/5/19"
	"29/5/20"
	"29/6/18"
	"29/6/19"
	"29/6/20"
	"29/7/18"
	"29/7/19"
	"29/7/20"
	"29/8/18"
	"29/8/19"
	"29/8/20"
	"29/9/18"
	"29/9/19"
	"29/9/20"
	"30/1/19"
	"30/1/20"
	"30/10/18"
	"30/10/19"
	"30/10/20"
	"30/11/18"
	"30/11/19"
	"30/11/20"
	"30/12/18"
	"30/12/19"
	"30/12/20"
	"30/3/19"
	"30/3/20"
	"30/4/19"
	"30/4/20"
	"30/5/19"
	"30/5/20"
	"30/6/18"
	"30/6/19"
	"30/6/20"
	"30/7/18"
	"30/7/19"
	"30/7/20"
	"30/8/18"
	"30/8/19"
	"30/8/20"
	"30/9/18"
	"30/9/19"
	"30/9/20"
	"31/1/19"
	"31/1/20"
	"31/10/18"
	"31/10/19"
	"31/10/20"
	"31/12/18"
	"31/12/19"
	"31/3/19"
	"31/3/20"
	"31/5/18"
	"31/5/19"
	"31/5/20"
	"31/7/18"
	"31/7/19"
	"31/7/20"
	"31/8/18"
	"31/8/19"
	"31/8/20"
]
--------------------------------------------------
Column: ShipDate (966 unique values)
shape: (966,)
Series: 'ShipDate' [str]
[
	"1/1/2019"
	"1/1/2020"
	"1/1/2021"
	"1/10/2018"
	"1/10/2019"
	"1/10/2020"
	"1/11/2018"
	"1/11/2019"
	"1/11/2020"
	"1/12/2018"
	"1/12/2019"
	"1/12/2020"
	"1/2/2019"
	"1/2/2020"
	"1/3/2019"
	"1/3/2020"
	"1/4/2019"
	"1/4/2020"
	"1/5/2019"
	"1/5/2020"
	"1/6/2019"
	"1/6/2020"
	"1/7/2018"
	"1/7/2019"
	"1/7/2020"
	"1/8/2018"
	"1/8/2019"
	"1/8/2020"
	"1/9/2018"
	"1/9/2019"
	"1/9/2020"
	"10/1/2019"
	"10/1/2020"
	"10/1/2021"
	"10/10/2018"
	"10/10/2019"
	"10/10/2020"
	"10/11/2018"
	"10/11/2019"
	"10/11/2020"
	"10/12/2018"
	"10/12/2019"
	"10/12/2020"
	"10/2/2019"
	"10/2/2020"
	"10/3/2019"
	"10/3/2020"
	"10/4/2019"
	"10/4/2020"
	"10/5/2019"
	"10/5/2020"
	"10/6/2018"
	"10/6/2019"
	"10/6/2020"
	"10/7/2018"
	"10/7/2019"
	"10/7/2020"
	"10/8/2018"
	"10/8/2019"
	"10/8/2020"
	"10/9/2018"
	"10/9/2019"
	"10/9/2020"
	"11/1/2019"
	"11/1/2020"
	"11/1/2021"
	"11/10/2018"
	"11/10/2019"
	"11/10/2020"
	"11/11/2018"
	"11/11/2019"
	"11/11/2020"
	"11/12/2018"
	"11/12/2019"
	"11/12/2020"
	"11/2/2019"
	"11/2/2020"
	"11/3/2019"
	"11/3/2020"
	"11/4/2019"
	"11/4/2020"
	"11/5/2019"
	"11/5/2020"
	"11/6/2018"
	"11/6/2019"
	"11/6/2020"
	"11/7/2018"
	"11/7/2019"
	"11/7/2020"
	"11/8/2018"
	"11/8/2019"
	"11/8/2020"
	"11/9/2018"
	"11/9/2019"
	"11/9/2020"
	"12/1/2019"
	"12/1/2020"
	"12/1/2021"
	"12/10/2018"
	"12/10/2019"
	"12/10/2020"
	"12/11/2018"
	"12/11/2019"
	"12/11/2020"
	"12/12/2018"
	"12/12/2019"
	"12/12/2020"
	"12/2/2019"
	"12/2/2020"
	"12/3/2019"
	"12/3/2020"
	"12/4/2019"
	"12/4/2020"
	"12/5/2019"
	"12/5/2020"
	"12/6/2018"
	"12/6/2019"
	"12/6/2020"
	"12/7/2018"
	"12/7/2019"
	"12/7/2020"
	"12/8/2018"
	"12/8/2019"
	"12/8/2020"
	"12/9/2018"
	"12/9/2019"
	"12/9/2020"
	"13/1/19"
	"13/1/20"
	"13/1/21"
	"13/10/18"
	"13/10/19"
	"13/10/20"
	"13/11/18"
	"13/11/19"
	"13/11/20"
	"13/12/18"
	"13/12/19"
	"13/12/20"
	"13/2/19"
	"13/2/20"
	"13/3/19"
	"13/3/20"
	"13/4/19"
	"13/4/20"
	"13/5/19"
	"13/5/20"
	"13/6/18"
	"13/6/19"
	"13/6/20"
	"13/7/18"
	"13/7/19"
	"13/7/20"
	"13/8/18"
	"13/8/19"
	"13/8/20"
	"13/9/18"
	"13/9/19"
	"13/9/20"
	"14/1/19"
	"14/1/20"
	"14/1/21"
	"14/10/18"
	"14/10/19"
	"14/10/20"
	"14/11/18"
	"14/11/19"
	"14/11/20"
	"14/12/18"
	"14/12/19"
	"14/12/20"
	"14/2/19"
	"14/2/20"
	"14/3/19"
	"14/3/20"
	"14/4/19"
	"14/4/20"
	"14/5/19"
	"14/5/20"
	"14/6/18"
	"14/6/19"
	"14/6/20"
	"14/7/18"
	"14/7/19"
	"14/7/20"
	"14/8/18"
	"14/8/19"
	"14/8/20"
	"14/9/18"
	"14/9/19"
	"14/9/20"
	"15/1/19"
	"15/1/20"
	"15/1/21"
	"15/10/18"
	"15/10/19"
	"15/10/20"
	"15/11/18"
	"15/11/19"
	"15/11/20"
	"15/12/18"
	"15/12/19"
	"15/12/20"
	"15/2/19"
	"15/2/20"
	"15/3/19"
	"15/3/20"
	"15/4/19"
	"15/4/20"
	"15/5/19"
	"15/5/20"
	"15/6/18"
	"15/6/19"
	"15/6/20"
	"15/7/18"
	"15/7/19"
	"15/7/20"
	"15/8/18"
	"15/8/19"
	"15/8/20"
	"15/9/18"
	"15/9/19"
	"15/9/20"
	"16/1/19"
	"16/1/20"
	"16/1/21"
	"16/10/18"
	"16/10/19"
	"16/10/20"
	"16/11/18"
	"16/11/19"
	"16/11/20"
	"16/12/18"
	"16/12/19"
	"16/12/20"
	"16/2/19"
	"16/2/20"
	"16/3/19"
	"16/3/20"
	"16/4/19"
	"16/4/20"
	"16/5/19"
	"16/5/20"
	"16/6/18"
	"16/6/19"
	"16/6/20"
	"16/7/18"
	"16/7/19"
	"16/7/20"
	"16/8/18"
	"16/8/19"
	"16/8/20"
	"16/9/18"
	"16/9/19"
	"16/9/20"
	"17/1/19"
	"17/1/20"
	"17/1/21"
	"17/10/18"
	"17/10/19"
	"17/10/20"
	"17/11/18"
	"17/11/19"
	"17/11/20"
	"17/12/18"
	"17/12/19"
	"17/12/20"
	"17/2/19"
	"17/2/20"
	"17/3/19"
	"17/3/20"
	"17/4/19"
	"17/4/20"
	"17/5/19"
	"17/5/20"
	"17/6/18"
	"17/6/19"
	"17/6/20"
	"17/7/18"
	"17/7/19"
	"17/7/20"
	"17/8/18"
	"17/8/19"
	"17/8/20"
	"17/9/18"
	"17/9/19"
	"17/9/20"
	"18/1/19"
	"18/1/20"
	"18/1/21"
	"18/10/18"
	"18/10/19"
	"18/10/20"
	"18/11/18"
	"18/11/19"
	"18/11/20"
	"18/12/18"
	"18/12/19"
	"18/12/20"
	"18/2/19"
	"18/2/20"
	"18/3/19"
	"18/3/20"
	"18/4/19"
	"18/4/20"
	"18/5/19"
	"18/5/20"
	"18/6/18"
	"18/6/19"
	"18/6/20"
	"18/7/18"
	"18/7/19"
	"18/7/20"
	"18/8/18"
	"18/8/19"
	"18/8/20"
	"18/9/18"
	"18/9/19"
	"18/9/20"
	"19/1/19"
	"19/1/20"
	"19/1/21"
	"19/10/18"
	"19/10/19"
	"19/10/20"
	"19/11/18"
	"19/11/19"
	"19/11/20"
	"19/12/18"
	"19/12/19"
	"19/12/20"
	"19/2/19"
	"19/2/20"
	"19/3/19"
	"19/3/20"
	"19/4/19"
	"19/4/20"
	"19/5/19"
	"19/5/20"
	"19/6/18"
	"19/6/19"
	"19/6/20"
	"19/7/18"
	"19/7/19"
	"19/7/20"
	"19/8/18"
	"19/8/19"
	"19/8/20"
	"19/9/18"
	"19/9/19"
	"19/9/20"
	"2/1/2019"
	"2/1/2020"
	"2/1/2021"
	"2/10/2018"
	"2/10/2019"
	"2/10/2020"
	"2/11/2018"
	"2/11/2019"
	"2/11/2020"
	"2/12/2018"
	"2/12/2019"
	"2/12/2020"
	"2/2/2019"
	"2/2/2020"
	"2/3/2019"
	"2/3/2020"
	"2/4/2019"
	"2/4/2020"
	"2/5/2019"
	"2/5/2020"
	"2/6/2018"
	"2/6/2019"
	"2/6/2020"
	"2/7/2018"
	"2/7/2019"
	"2/7/2020"
	"2/8/2018"
	"2/8/2019"
	"2/8/2020"
	"2/9/2018"
	"2/9/2019"
	"2/9/2020"
	"20/1/19"
	"20/1/20"
	"20/1/21"
	"20/10/18"
	"20/10/19"
	"20/10/20"
	"20/11/18"
	"20/11/19"
	"20/11/20"
	"20/12/18"
	"20/12/19"
	"20/12/20"
	"20/2/19"
	"20/2/20"
	"20/3/19"
	"20/3/20"
	"20/4/19"
	"20/4/20"
	"20/5/19"
	"20/5/20"
	"20/6/18"
	"20/6/19"
	"20/6/20"
	"20/7/18"
	"20/7/19"
	"20/7/20"
	"20/8/18"
	"20/8/19"
	"20/8/20"
	"20/9/18"
	"20/9/19"
	"20/9/20"
	"21/1/19"
	"21/1/20"
	"21/1/21"
	"21/10/18"
	"21/10/19"
	"21/10/20"
	"21/11/18"
	"21/11/19"
	"21/11/20"
	"21/12/18"
	"21/12/19"
	"21/12/20"
	"21/2/19"
	"21/2/20"
	"21/3/19"
	"21/3/20"
	"21/4/19"
	"21/4/20"
	"21/5/19"
	"21/5/20"
	"21/6/18"
	"21/6/19"
	"21/6/20"
	"21/7/18"
	"21/7/19"
	"21/7/20"
	"21/8/18"
	"21/8/19"
	"21/8/20"
	"21/9/18"
	"21/9/19"
	"21/9/20"
	"22/1/19"
	"22/1/20"
	"22/1/21"
	"22/10/18"
	"22/10/19"
	"22/10/20"
	"22/11/18"
	"22/11/19"
	"22/11/20"
	"22/12/18"
	"22/12/19"
	"22/12/20"
	"22/2/19"
	"22/2/20"
	"22/3/19"
	"22/3/20"
	"22/4/19"
	"22/4/20"
	"22/5/19"
	"22/5/20"
	"22/6/18"
	"22/6/19"
	"22/6/20"
	"22/7/18"
	"22/7/19"
	"22/7/20"
	"22/8/18"
	"22/8/19"
	"22/8/20"
	"22/9/18"
	"22/9/19"
	"22/9/20"
	"23/1/19"
	"23/1/20"
	"23/1/21"
	"23/10/18"
	"23/10/19"
	"23/10/20"
	"23/11/18"
	"23/11/19"
	"23/11/20"
	"23/12/18"
	"23/12/19"
	"23/12/20"
	"23/2/19"
	"23/2/20"
	"23/3/19"
	"23/3/20"
	"23/4/19"
	"23/4/20"
	"23/5/19"
	"23/5/20"
	"23/6/18"
	"23/6/19"
	"23/6/20"
	"23/7/18"
	"23/7/19"
	"23/7/20"
	"23/8/18"
	"23/8/19"
	"23/8/20"
	"23/9/18"
	"23/9/19"
	"23/9/20"
	"24/1/19"
	"24/1/20"
	"24/1/21"
	"24/10/18"
	"24/10/19"
	"24/10/20"
	"24/11/18"
	"24/11/19"
	"24/11/20"
	"24/12/18"
	"24/12/19"
	"24/12/20"
	"24/2/19"
	"24/2/20"
	"24/3/19"
	"24/3/20"
	"24/4/19"
	"24/4/20"
	"24/5/19"
	"24/5/20"
	"24/6/18"
	"24/6/19"
	"24/6/20"
	"24/7/18"
	"24/7/19"
	"24/7/20"
	"24/8/18"
	"24/8/19"
	"24/8/20"
	"24/9/18"
	"24/9/19"
	"24/9/20"
	"25/1/19"
	"25/1/20"
	"25/10/18"
	"25/10/19"
	"25/10/20"
	"25/11/18"
	"25/11/19"
	"25/11/20"
	"25/12/18"
	"25/12/19"
	"25/12/20"
	"25/2/19"
	"25/2/20"
	"25/3/19"
	"25/3/20"
	"25/4/19"
	"25/4/20"
	"25/5/19"
	"25/5/20"
	"25/6/18"
	"25/6/19"
	"25/6/20"
	"25/7/18"
	"25/7/19"
	"25/7/20"
	"25/8/18"
	"25/8/19"
	"25/8/20"
	"25/9/18"
	"25/9/19"
	"25/9/20"
	"26/1/19"
	"26/1/20"
	"26/10/18"
	"26/10/19"
	"26/10/20"
	"26/11/18"
	"26/11/19"
	"26/11/20"
	"26/12/18"
	"26/12/19"
	"26/12/20"
	"26/2/19"
	"26/2/20"
	"26/3/19"
	"26/3/20"
	"26/4/19"
	"26/4/20"
	"26/5/19"
	"26/5/20"
	"26/6/18"
	"26/6/19"
	"26/6/20"
	"26/7/18"
	"26/7/19"
	"26/7/20"
	"26/8/18"
	"26/8/19"
	"26/8/20"
	"26/9/18"
	"26/9/19"
	"26/9/20"
	"27/1/19"
	"27/1/20"
	"27/10/18"
	"27/10/19"
	"27/10/20"
	"27/11/18"
	"27/11/19"
	"27/11/20"
	"27/12/18"
	"27/12/19"
	"27/12/20"
	"27/2/19"
	"27/2/20"
	"27/3/19"
	"27/3/20"
	"27/4/19"
	"27/4/20"
	"27/5/19"
	"27/5/20"
	"27/6/18"
	"27/6/19"
	"27/6/20"
	"27/7/18"
	"27/7/19"
	"27/7/20"
	"27/8/18"
	"27/8/19"
	"27/8/20"
	"27/9/18"
	"27/9/19"