## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

## Exploratory Data Analysis with Polars

### Load CSV File into Polars DataFrame

In [4]:
df = pl.read_csv("data-loader/data/data.csv",
                 ignore_errors=True)

df

shape: (2_240, 29)
┌───────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ record_id ┆ Year_Birth ┆ Education ┆ Marital_S ┆ … ┆ Complain ┆ Z_CostCon ┆ Z_Revenue ┆ Response │
│ ---       ┆ ---        ┆ ---       ┆ tatus     ┆   ┆ ---      ┆ tact      ┆ ---       ┆ ---      │
│ i64       ┆ i64        ┆ str       ┆ ---       ┆   ┆ i64      ┆ ---       ┆ i64       ┆ i64      │
│           ┆            ┆           ┆ str       ┆   ┆          ┆ i64       ┆           ┆          │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 5524      ┆ 1957       ┆ Graduatio ┆ Single    ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 1        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 2174      ┆ 1954       ┆ Graduatio ┆ Single    ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 4141      ┆ 1965       ┆ Graduatio ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 6182      ┆ 1984       ┆ Graduatio ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 5324      ┆ 1981       ┆ PhD       ┆ Married   ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│ …         ┆ …          ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 10870     ┆ 1967       ┆ Graduatio ┆ Married   ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 4001      ┆ 1946       ┆ PhD       ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│ 7270      ┆ 1981       ┆ Graduatio ┆ Divorced  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 8235      ┆ 1956       ┆ Master    ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│ 9405      ┆ 1954       ┆ PhD       ┆ Married   ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 1        │
└───────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [5]:
column_data_types = zip(df.columns, df.dtypes)

for column, dtype in column_data_types:
    print(f"{column}:\t\t{dtype}")

record_id:		Int64
Year_Birth:		Int64
Education:		String
Marital_Status:		String
Income:		Int64
Kidhome:		Int64
Teenhome:		Int64
Dt_Customer:		String
Recency:		Int64
MntWines:		Int64
MntFruits:		Int64
MntMeatProducts:		Int64
MntFishProducts:		Int64
MntSweetProducts:		Int64
MntGoldProds:		Int64
NumDealsPurchases:		Int64
NumWebPurchases:		Int64
NumCatalogPurchases:		Int64
NumStorePurchases:		Int64
NumWebVisitsMonth:		Int64
AcceptedCmp3:		Int64
AcceptedCmp4:		Int64
AcceptedCmp5:		Int64
AcceptedCmp1:		Int64
AcceptedCmp2:		Int64
Complain:		Int64
Z_CostContact:		Int64
Z_Revenue:		Int64
Response:		Int64

### Display First Few Rows to Understand Structure of Data

In [6]:
print(df.head())

shape: (5, 29)
┌───────────┬────────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ record_id ┆ Year_Birth ┆ Education ┆ Marital_S ┆ … ┆ Complain ┆ Z_CostCon ┆ Z_Revenue ┆ Response │
│ ---       ┆ ---        ┆ ---       ┆ tatus     ┆   ┆ ---      ┆ tact      ┆ ---       ┆ ---      │
│ i64       ┆ i64        ┆ str       ┆ ---       ┆   ┆ i64      ┆ ---       ┆ i64       ┆ i64      │
│           ┆            ┆           ┆ str       ┆   ┆          ┆ i64       ┆           ┆          │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 5524      ┆ 1957       ┆ Graduatio ┆ Single    ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 1        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 2174      ┆ 1954       ┆ Graduatio ┆ Single    ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 4141      ┆ 1965       ┆ Graduatio ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 6182      ┆ 1984       ┆ Graduatio ┆ Together  ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
│           ┆            ┆ n         ┆           ┆   ┆          ┆           ┆           ┆          │
│ 5324      ┆ 1981       ┆ PhD       ┆ Married   ┆ … ┆ 0        ┆ 3         ┆ 11        ┆ 0        │
└───────────┴────────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

### Retrieve Basic Information About DataFrame

In [10]:
print(df.shape)
print(df.dtypes)

(2240, 29)
[Int64, Int64, String, String, Int64, Int64, Int64, String, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64]

### Display Summary Statistics for All Columns

In [11]:
summary = df.describe()
print(summary)

shape: (9, 30)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ record_id ┆ Year_Birt ┆ Education ┆ … ┆ Complain ┆ Z_CostCon ┆ Z_Revenue ┆ Response │
│ ---        ┆ ---       ┆ h         ┆ ---       ┆   ┆ ---      ┆ tact      ┆ ---       ┆ ---      │
│ str        ┆ f64       ┆ ---       ┆ str       ┆   ┆ f64      ┆ ---       ┆ f64       ┆ f64      │
│            ┆           ┆ f64       ┆           ┆   ┆          ┆ f64       ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 2240.0    ┆ 2240.0    ┆ 2240      ┆ … ┆ 2240.0   ┆ 2240.0    ┆ 2240.0    ┆ 2240.0   │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 0.0      ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ mean       ┆ 5592.1598 ┆ 1968.8058 ┆ null      ┆ … ┆ 0.009375 ┆ 3.0       ┆ 11.0      ┆ 0.149107 │
│            ┆ 21        ┆ 04        ┆           ┆   ┆          ┆           ┆           ┆          │
│ std        ┆ 3246.6621 ┆ 11.984069 ┆ null      ┆ … ┆ 0.096391 ┆ 0.0       ┆ 0.0       ┆ 0.356274 │
│            ┆ 98        ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ min        ┆ 0.0       ┆ 1893.0    ┆ 2n Cycle  ┆ … ┆ 0.0      ┆ 3.0       ┆ 11.0      ┆ 0.0      │
│ 25%        ┆ 2829.0    ┆ 1959.0    ┆ null      ┆ … ┆ 0.0      ┆ 3.0       ┆ 11.0      ┆ 0.0      │
│ 50%        ┆ 5462.0    ┆ 1970.0    ┆ null      ┆ … ┆ 0.0      ┆ 3.0       ┆ 11.0      ┆ 0.0      │
│ 75%        ┆ 8427.0    ┆ 1977.0    ┆ null      ┆ … ┆ 0.0      ┆ 3.0       ┆ 11.0      ┆ 0.0      │
│ max        ┆ 11191.0   ┆ 1996.0    ┆ PhD       ┆ … ┆ 1.0      ┆ 3.0       ┆ 11.0      ┆ 1.0      │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

### Counting Null Values in Each Column

In [12]:
for col in df.columns:
    print(f"{col} : {df[col].is_null().sum()}")

record_id : 0
Year_Birth : 0
Education : 0
Marital_Status : 0
Income : 24
Kidhome : 0
Teenhome : 0
Dt_Customer : 0
Recency : 0
MntWines : 0
MntFruits : 0
MntMeatProducts : 0
MntFishProducts : 0
MntSweetProducts : 0
MntGoldProds : 0
NumDealsPurchases : 0
NumWebPurchases : 0
NumCatalogPurchases : 0
NumStorePurchases : 0
NumWebVisitsMonth : 0
AcceptedCmp3 : 0
AcceptedCmp4 : 0
AcceptedCmp5 : 0
AcceptedCmp1 : 0
AcceptedCmp2 : 0
Complain : 0
Z_CostContact : 0
Z_Revenue : 0
Response : 0

### Find Longest Text Length in Each Column

In [13]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 3)
┌───────────┬────────────────┬─────────────┐
│ Education ┆ Marital_Status ┆ Dt_Customer │
│ ---       ┆ ---            ┆ ---         │
│ u32       ┆ u32            ┆ u32         │
╞═══════════╪════════════════╪═════════════╡
│ 10        ┆ 8              ┆ 10          │
└───────────┴────────────────┴─────────────┘

### Retrieve Data Types of All Columns

In [14]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Int64, Int64, String, String, Int64, Int64, Int64, String, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64, Int64]

### Count Unique Values in Each Column

In [15]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                    Unique values in record_id : 2240
                   Unique values in Year_Birth : 59
                    Unique values in Education : 5
               Unique values in Marital_Status : 8
                       Unique values in Income : 1975
                      Unique values in Kidhome : 3
                     Unique values in Teenhome : 3
                  Unique values in Dt_Customer : 663
                      Unique values in Recency : 100
                     Unique values in MntWines : 776
                    Unique values in MntFruits : 158
              Unique values in MntMeatProducts : 558
              Unique values in MntFishProducts : 182
             Unique values in MntSweetProducts : 177
                 Unique values in MntGoldProds : 213
            Unique values in NumDealsPurchases : 15
              Unique values in NumWebPurchases : 15
          Unique values in NumCatalogPurchases : 14
            Unique values in NumStorePurchases : 14
            Unique values in NumWebVisitsMonth : 16
                 Unique values in AcceptedCmp3 : 2
                 Unique values in AcceptedCmp4 : 2
                 Unique values in AcceptedCmp5 : 2
                 Unique values in AcceptedCmp1 : 2
                 Unique values in AcceptedCmp2 : 2
                     Unique values in Complain : 2
                Unique values in Z_CostContact : 1
                    Unique values in Z_Revenue : 1
                     Unique values in Response : 2

### Retrieve Unique Values in Column If There Are Fewer Than 100

In [16]:
for col in df.columns:
    unique_values = df[col].unique()
    if len(unique_values) < 20:
        print(f"'{col}' {len(unique_values)}: {unique_values}")

'Education' 5: shape: (5,)
Series: 'Education' [str]
[
	"Master"
	"Basic"
	"2n Cycle"
	"PhD"
	"Graduation"
]
'Marital_Status' 8: shape: (8,)
Series: 'Marital_Status' [str]
[
	"Single"
	"Married"
	"Absurd"
	"Together"
	"Widow"
	"Alone"
	"YOLO"
	"Divorced"
]
'Kidhome' 3: shape: (3,)
Series: 'Kidhome' [i64]
[
	0
	1
	2
]
'Teenhome' 3: shape: (3,)
Series: 'Teenhome' [i64]
[
	0
	1
	2
]
'NumDealsPurchases' 15: shape: (15,)
Series: 'NumDealsPurchases' [i64]
[
	0
	1
	2
	3
	4
	…
	10
	11
	12
	13
	15
]
'NumWebPurchases' 15: shape: (15,)
Series: 'NumWebPurchases' [i64]
[
	0
	1
	2
	3
	4
	…
	10
	11
	23
	25
	27
]
'NumCatalogPurchases' 14: shape: (14,)
Series: 'NumCatalogPurchases' [i64]
[
	0
	1
	2
	3
	4
	…
	9
	10
	11
	22
	28
]
'NumStorePurchases' 14: shape: (14,)
Series: 'NumStorePurchases' [i64]
[
	0
	1
	2
	3
	4
	…
	9
	10
	11
	12
	13
]
'NumWebVisitsMonth' 16: shape: (16,)
Series: 'NumWebVisitsMonth' [i64]
[
	0
	1
	2
	3
	4
	…
	13
	14
	17
	19
	20
]
'AcceptedCmp3' 2: shape: (2,)
Series: 'AcceptedCmp3' [i64]
[
	0
	1
]
'AcceptedCmp4' 2: shape: (2,)
Series: 'AcceptedCmp4' [i64]
[
	0
	1
]
'AcceptedCmp5' 2: shape: (2,)
Series: 'AcceptedCmp5' [i64]
[
	0
	1
]
'AcceptedCmp1' 2: shape: (2,)
Series: 'AcceptedCmp1' [i64]
[
	0
	1
]
'AcceptedCmp2' 2: shape: (2,)
Series: 'AcceptedCmp2' [i64]
[
	0
	1
]
'Complain' 2: shape: (2,)
Series: 'Complain' [i64]
[
	0
	1
]
'Z_CostContact' 1: shape: (1,)
Series: 'Z_CostContact' [i64]
[
	3
]
'Z_Revenue' 1: shape: (1,)
Series: 'Z_Revenue' [i64]
[
	11
]
'Response' 2: shape: (2,)
Series: 'Response' [i64]
[
	0
	1
]

### Check Distribution of Numerical Columns

In [17]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

record_id
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ record_id   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2240.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 5592.159821 │
│ std        ┆ 3246.662198 │
│ min        ┆ 0.0         │
│ 25%        ┆ 2829.0      │
│ 50%        ┆ 5462.0      │
│ 75%        ┆ 8427.0      │
│ max        ┆ 11191.0     │
└────────────┴─────────────┘


Year_Birth
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ Year_Birth  │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2240.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 1968.805804 │
│ std        ┆ 11.984069   │
│ min        ┆ 1893.0      │
│ 25%        ┆ 1959.0      │
│ 50%        ┆ 1970.0      │
│ 75%        ┆ 1977.0      │
│ max        ┆ 1996.0      │
└────────────┴─────────────┘


Income
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ Income       │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2216.0       │
│ null_count ┆ 24.0         │
│ mean       ┆ 52247.251354 │
│ std        ┆ 25173.076661 │
│ min        ┆ 1730.0       │
│ 25%        ┆ 35322.0      │
│ 50%        ┆ 51390.0      │
│ 75%        ┆ 68487.0      │
│ max        ┆ 666666.0     │
└────────────┴──────────────┘


Kidhome
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Kidhome  │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 2240.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.444196 │
│ std        ┆ 0.538398 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 1.0      │
│ max        ┆ 2.0      │
└────────────┴──────────┘


Teenhome
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Teenhome │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 2240.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.50625  │
│ std        ┆ 0.544538 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 1.0      │
│ max        ┆ 2.0      │
└────────────┴──────────┘


Recency
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ Recency   │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2240.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 49.109375 │
│ std        ┆ 28.962453 │
│ min        ┆ 0.0       │
│ 25%        ┆ 24.0      │
│ 50%        ┆ 49.0      │
│ 75%        ┆ 74.0      │
│ max        ┆ 99.0      │
└────────────┴───────────┘


MntWines
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ MntWines   │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 2240.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 303.935714 │
│ std        ┆ 336.597393 │
│ min        ┆ 0.0        │
│ 25%        ┆ 24.0       │
│ 50%        ┆ 174.0      │
│ 75%        ┆ 504.0      │
│ max        ┆ 1493.0     │
└────────────┴────────────┘


MntFruits
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ MntFruits │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2240.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 26.302232 │
│ std        ┆ 39.773434 │
│ min        ┆ 0.0       │
│ 25%        ┆ 1.0       │
│ 50%        ┆ 8.0       │
│ 75%        ┆ 33.0      │
│ max        ┆ 199.0     │
└────────────┴───────────┘


MntMeatProducts
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ MntMeatProducts │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2240.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 166.95          │
│ std        ┆ 225.715373      │
│ min        ┆ 0.0             │
│ 25%        ┆ 16.0            │
│ 50%        ┆ 67.0            │
│ 75%        ┆ 232.0           │
│ max        ┆ 1725.0          │
└────────────┴─────────────────┘


MntFishProducts
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ MntFishProducts │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2240.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 37.525446       │
│ std        ┆ 54.628979       │
│ min        ┆ 0.0             │
│ 25%        ┆ 3.0             │
│ 50%        ┆ 12.0            │
│ 75%        ┆ 50.0            │
│ max        ┆ 259.0           │
└────────────┴─────────────────┘


MntSweetProducts
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ MntSweetProducts │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 2240.0           │
│ null_count ┆ 0.0              │
│ mean       ┆ 27.062946        │
│ std        ┆ 41.280498        │
│ min        ┆ 0.0              │
│ 25%        ┆ 1.0              │
│ 50%        ┆ 8.0              │
│ 75%        ┆ 33.0             │
│ max        ┆ 263.0            │
└────────────┴──────────────────┘


MntGoldProds
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ MntGoldProds │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 44.021875    │
│ std        ┆ 52.167439    │
│ min        ┆ 0.0          │
│ 25%        ┆ 9.0          │
│ 50%        ┆ 24.0         │
│ 75%        ┆ 56.0         │
│ max        ┆ 362.0        │
└────────────┴──────────────┘


NumDealsPurchases
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ NumDealsPurchases │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 2240.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 2.325             │
│ std        ┆ 1.932238          │
│ min        ┆ 0.0               │
│ 25%        ┆ 1.0               │
│ 50%        ┆ 2.0               │
│ 75%        ┆ 3.0               │
│ max        ┆ 15.0              │
└────────────┴───────────────────┘


NumWebPurchases
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ NumWebPurchases │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2240.0          │
│ null_count ┆ 0.0             │
│ mean       ┆ 4.084821        │
│ std        ┆ 2.778714        │
│ min        ┆ 0.0             │
│ 25%        ┆ 2.0             │
│ 50%        ┆ 4.0             │
│ 75%        ┆ 6.0             │
│ max        ┆ 27.0            │
└────────────┴─────────────────┘


NumCatalogPurchases
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ NumCatalogPurchases │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2240.0              │
│ null_count ┆ 0.0                 │
│ mean       ┆ 2.662054            │
│ std        ┆ 2.923101            │
│ min        ┆ 0.0                 │
│ 25%        ┆ 0.0                 │
│ 50%        ┆ 2.0                 │
│ 75%        ┆ 4.0                 │
│ max        ┆ 28.0                │
└────────────┴─────────────────────┘


NumStorePurchases
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ NumStorePurchases │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 2240.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 5.790179          │
│ std        ┆ 3.250958          │
│ min        ┆ 0.0               │
│ 25%        ┆ 3.0               │
│ 50%        ┆ 5.0               │
│ 75%        ┆ 8.0               │
│ max        ┆ 13.0              │
└────────────┴───────────────────┘


NumWebVisitsMonth
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ NumWebVisitsMonth │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 2240.0            │
│ null_count ┆ 0.0               │
│ mean       ┆ 5.316518          │
│ std        ┆ 2.426645          │
│ min        ┆ 0.0               │
│ 25%        ┆ 3.0               │
│ 50%        ┆ 6.0               │
│ 75%        ┆ 7.0               │
│ max        ┆ 20.0              │
└────────────┴───────────────────┘


AcceptedCmp3
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ AcceptedCmp3 │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.072768     │
│ std        ┆ 0.259813     │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 0.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


AcceptedCmp4
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ AcceptedCmp4 │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.074554     │
│ std        ┆ 0.262728     │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 0.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


AcceptedCmp5
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ AcceptedCmp5 │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.072768     │
│ std        ┆ 0.259813     │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 0.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


AcceptedCmp1
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ AcceptedCmp1 │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.064286     │
│ std        ┆ 0.245316     │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 0.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


AcceptedCmp2
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ AcceptedCmp2 │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2240.0       │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.013393     │
│ std        ┆ 0.114976     │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 0.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


Complain
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Complain │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 2240.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.009375 │
│ std        ┆ 0.096391 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 0.0      │
│ max        ┆ 1.0      │
└────────────┴──────────┘


Z_CostContact
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ Z_CostContact │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 2240.0        │
│ null_count ┆ 0.0           │
│ mean       ┆ 3.0           │
│ std        ┆ 0.0           │
│ min        ┆ 3.0           │
│ 25%        ┆ 3.0           │
│ 50%        ┆ 3.0           │
│ 75%        ┆ 3.0           │
│ max        ┆ 3.0           │
└────────────┴───────────────┘


Z_Revenue
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ Z_Revenue │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 2240.0    │
│ null_count ┆ 0.0       │
│ mean       ┆ 11.0      │
│ std        ┆ 0.0       │
│ min        ┆ 11.0      │
│ 25%        ┆ 11.0      │
│ 50%        ┆ 11.0      │
│ 75%        ┆ 11.0      │
│ max        ┆ 11.0      │
└────────────┴───────────┘


Response
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Response │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 2240.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.149107 │
│ std        ┆ 0.356274 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 0.0      │
│ max        ┆ 1.0      │
└────────────┴──────────┘