# Cleaning the Input Data so Apache NiFi Can Use It

### Import Libraries

In [ ]:
import sys

import pandas as pd

### Display Library & Scripting Versions

In [2]:
sys.version[0:6]
pd.__version__

'2.2.3'

### Retrieve Dataset

In [3]:
df = pd.read_csv("../data/orig-complaints.csv")

df

/var/folders/93/v_c2ph_17t97zdkzc4_ccjtw0000gn/T/ipykernel_27527/306139693.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/orig-complaints.csv")

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-06-13,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,PA,18640.0,NaN,Consent not provided,Web,2019-06-13,Closed with explanation,Yes,NaN,3274605
1,2019-11-01,Vehicle loan or lease,Loan,Struggling to pay your loan,Denied request to lower payments,I contacted Ally on Friday XX/XX/XXXX after fa...,Company has responded to the consumer and the ...,ALLY FINANCIAL INC.,NJ,8854.0,NaN,Consent provided,Web,2019-11-01,Closed with explanation,Yes,NaN,3425257
2,2019-04-01,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account status incorrect,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PA,19067.0,NaN,Consent not provided,Web,2019-04-01,Closed with explanation,Yes,NaN,3198225
3,2019-04-10,Credit card or prepaid card,Store credit card,Closing your account,Can't close your account,NaN,Company believes it acted appropriately as aut...,Atlanticus Services Corporation,WI,54409.0,Older American,NaN,Referral,2019-04-16,Closed with explanation,No,NaN,3207424
4,2020-04-21,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,Capital One Auto Finance incorrectly and witho...,NaN,CAPITAL ONE FINANCIAL CORPORATION,GA,30024.0,NaN,Consent provided,Web,2020-04-21,Closed with explanation,Yes,NaN,3616748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396028,2017-02-09,Debt collection,I do not know,Cont'd attempts collect debt not owed,Debt resulted from identity theft,I have disputed my debts several times with no...,NaN,Bonneville Billing and Collections,UT,84054.0,Servicemember,Consent provided,Web,2017-02-09,Closed with explanation,Yes,No,2334969
2396029,2015-04-29,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,My father died in XX/XX/XXXX. Left me his only...,NaN,"CITIBANK, N.A.",OK,74066.0,NaN,Consent provided,Web,2015-04-29,Closed with explanation,Yes,No,1352738
2396030,2017-03-31,Credit reporting,NaN,Credit reporting company's investigation,No notice of investigation status/result,cfbp i would Like to file a complaint on Exper...,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,MN,55379.0,NaN,Consent provided,Web,2017-03-31,Closed with non-monetary relief,Yes,Yes,2412926
2396031,2017-01-16,Credit reporting,NaN,Incorrect information on credit report,Account status,My husband and I are in the middle of an FHA S...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",GA,30215.0,NaN,Consent provided,Web,2017-01-16,Closed with explanation,Yes,No,2292586
2396032,2018-03-07,Mortgage,Other type of mortgage,Trouble during payment process,NaN,NaN,Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,CA,91304.0,NaN,NaN,Referral,2018-03-08,Closed with explanation,Yes,NaN,2837068

### Provide Summary/Descriptive Statistics About Dataset

In [4]:
df.describe(include='all')

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
count,2396033,2396033,2160869,2396033,1754933,835210,981388,2396033,2357531,2357314.0,290472,1662032,2396033,2396033,2396030,2396033,768459,2.396033e+06
unique,3675,18,76,165,221,748939,11,6236,63,58013.0,3,4,6,3624,8,2,2,NaN
top,2017-09-08,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,There are many mistakes appear in my report wi...,Company has responded to the consumer and the ...,"EQUIFAX, INC.",CA,30349.0,Servicemember,Consent provided,Web,2017-09-08,Closed with explanation,Yes,No,NaN
freq,3553,905199,894276,555620,349749,1035,792233,369481,307983,2098.0,155277,835565,1941796,3387,1973090,2351112,620081,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.897986e+06
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.301007e+06
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000953e+06
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.116133e+06
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.891388e+06
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.039227e+06

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2396033 entries, 0 to 2396032
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 object
 1   Product                       object
 2   Sub-product                   object
 3   Issue                         object
 4   Sub-issue                     object
 5   Consumer complaint narrative  object
 6   Company public response       object
 7   Company                       object
 8   State                         object
 9   ZIP code                      object
 10  Tags                          object
 11  Consumer consent provided?    object
 12  Submitted via                 object
 13  Date sent to company          object
 14  Company response to consumer  object
 15  Timely response?              object
 16  Consumer disputed?            object
 17  Complaint ID                  int64
dtypes: int64(1), object(17)
memory usage: 329.0+ MB

### Remove Excess New Lines in String Columns

In [6]:
for col in df.select_dtypes(include=['object', 'string']):
    df[col] = df[col].str.replace('\n', '', regex=True)
    df[col] = df[col].str.replace('( ', ' ', regex=False)
    df[col] = df[col].str.replace(' )', ' ', regex=False)
    df[col] = df[col].str.replace('  ', ' ', regex=False)
    df[col] = df[col].str.replace(' ,', ' ', regex=False)
    df[col] = df[col].str.replace(' .', ' ', regex=False)
    df[col] = df[col].str.replace(' # ', ' - ', regex=False)

df

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-06-13,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,PA,NaN,NaN,Consent not provided,Web,2019-06-13,Closed with explanation,Yes,NaN,3274605
1,2019-11-01,Vehicle loan or lease,Loan,Struggling to pay your loan,Denied request to lower payments,I contacted Ally on Friday XX/XX/XXXX after fa...,Company has responded to the consumer and the ...,ALLY FINANCIAL INC.,NJ,NaN,NaN,Consent provided,Web,2019-11-01,Closed with explanation,Yes,NaN,3425257
2,2019-04-01,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account status incorrect,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PA,NaN,NaN,Consent not provided,Web,2019-04-01,Closed with explanation,Yes,NaN,3198225
3,2019-04-10,Credit card or prepaid card,Store credit card,Closing your account,Can't close your account,NaN,Company believes it acted appropriately as aut...,Atlanticus Services Corporation,WI,NaN,Older American,NaN,Referral,2019-04-16,Closed with explanation,No,NaN,3207424
4,2020-04-21,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,Capital One Auto Finance incorrectly and witho...,NaN,CAPITAL ONE FINANCIAL CORPORATION,GA,NaN,NaN,Consent provided,Web,2020-04-21,Closed with explanation,Yes,NaN,3616748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396028,2017-02-09,Debt collection,I do not know,Cont'd attempts collect debt not owed,Debt resulted from identity theft,I have disputed my debts several times with no...,NaN,Bonneville Billing and Collections,UT,NaN,Servicemember,Consent provided,Web,2017-02-09,Closed with explanation,Yes,No,2334969
2396029,2015-04-29,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,My father died in XX/XX/XXXX. Left me his only...,NaN,"CITIBANK, N.A.",OK,NaN,NaN,Consent provided,Web,2015-04-29,Closed with explanation,Yes,No,1352738
2396030,2017-03-31,Credit reporting,NaN,Credit reporting company's investigation,No notice of investigation status/result,cfbp i would Like to file a complaint on Exper...,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,MN,NaN,NaN,Consent provided,Web,2017-03-31,Closed with non-monetary relief,Yes,Yes,2412926
2396031,2017-01-16,Credit reporting,NaN,Incorrect information on credit report,Account status,My husband and I are in the middle of an FHA S...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",GA,NaN,NaN,Consent provided,Web,2017-01-16,Closed with explanation,Yes,No,2292586
2396032,2018-03-07,Mortgage,Other type of mortgage,Trouble during payment process,NaN,NaN,Company has responded to the consumer and the ...,WELLS FARGO & COMPANY,CA,NaN,NaN,NaN,Referral,2018-03-08,Closed with explanation,Yes,NaN,2837068

### Save Cleaned Dataset

In [7]:
df.to_csv(
    "../data/complaints.csv",
    index=False
    )