## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data-old/Iowa_Liquor_Sales.csv", ignore_errors=True)

df

shape: (27_489_743, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ invoice_i ┆ date_of_s ┆ store_num ┆ store_nam ┆ … ┆ iowa_wate ┆ iowa_wate ┆ county_bo ┆ us_count │
│ tem_numbe ┆ ale       ┆ ber       ┆ e         ┆   ┆ rshed_sub ┆ rsheds    ┆ undaries_ ┆ ies      │
│ r         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _basins   ┆ ---       ┆ of_iowa   ┆ ---      │
│ ---       ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ str      │
│ str       ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ INV-07718 ┆ 10/05/201 ┆ 4091      ┆ FAREWAY   ┆ … ┆ 20        ┆ 19        ┆ 16        ┆ 1,785    │
│ 300026    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #705 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CLEAR LA… ┆   ┆           ┆           ┆           ┆          │
│ INV-07790 ┆ 10/09/201 ┆ 2651      ┆ HY-VEE /  ┆ … ┆ 14        ┆ 190       ┆ 28        ┆ 177      │
│ 400037    ┆ 7         ┆           ┆ WAVERLY   ┆   ┆           ┆           ┆           ┆          │
│ INV-07747 ┆ 10/05/201 ┆ 3831      ┆ THE       ┆ … ┆ 25        ┆ 314       ┆ 52        ┆ 1,368    │
│ 400001    ┆ 7         ┆           ┆ MARKET OF ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ MADRID    ┆   ┆           ┆           ┆           ┆          │
│ INV-07622 ┆ 10/03/201 ┆ 5140      ┆ A TO Z    ┆ … ┆ 37        ┆ 429       ┆ 23        ┆ 181      │
│ 300001    ┆ 7         ┆           ┆ LIQUOR    ┆   ┆           ┆           ┆           ┆          │
│ INV-07688 ┆ 10/04/201 ┆ 2623      ┆ HY-VEE    ┆ … ┆ 35        ┆ 213       ┆ 36        ┆ 1,891    │
│ 900026    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #4  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / SIOUX   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ C…        ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ INV-07782 ┆ 10/06/201 ┆ 4268      ┆ FAREWAY   ┆ … ┆ 24        ┆ 165       ┆ 6         ┆ 1,794    │
│ 800011    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #531 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ALGONA    ┆   ┆           ┆           ┆           ┆          │
│ INV-07743 ┆ 10/05/201 ┆ 4539      ┆ CASEY'S   ┆ … ┆ 27        ┆ 330       ┆ 51        ┆ 1,783    │
│ 100018    ┆ 7         ┆           ┆ GENERAL   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #40 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / SC…     ┆   ┆           ┆           ┆           ┆          │
│ INV-07829 ┆ 10/09/201 ┆ 5299      ┆ PEARL     ┆ … ┆ 56        ┆ 87        ┆ 68        ┆ 1,835    │
│ 100005    ┆ 7         ┆           ┆ CITY      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ TOBACCO & ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ LIQUOR    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ OU…       ┆   ┆           ┆           ┆           ┆          │
│ INV-07731 ┆ 10/05/201 ┆ 2528      ┆ HY-VEE    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 700060    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #3  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / DES     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ MOI…      ┆   ┆           ┆           ┆           ┆          │
│ INV-07657 ┆ 10/04/201 ┆ 2806      ┆ OSCO #881 ┆ … ┆ 56        ┆ 82        ┆ 55        ┆ 1,745    │
│ 700040    ┆ 7         ┆           ┆ / CLINTON ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Number of Nulls in Each Feature

In [4]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)
null_counts

shape: (29, 2)
┌────────────────────────────────┬────────────┐
│ feature                        ┆ null_count │
│ ---                            ┆ ---        │
│ str                            ┆ i64        │
╞════════════════════════════════╪════════════╡
│ invoice_item_number            ┆ 0          │
│ date_of_sale                   ┆ 0          │
│ store_number                   ┆ 0          │
│ store_name                     ┆ 0          │
│ store_address                  ┆ 82714      │
│ store_city                     ┆ 82713      │
│ store_zip_code                 ┆ 90720      │
│ store_location                 ┆ 2497618    │
│ store_county_number            ┆ 3356900    │
│ store_county                   ┆ 159516     │
│ item_category                  ┆ 16974      │
│ category_name                  ┆ 25040      │
│ vendor_number                  ┆ 9          │
│ vendor_name                    ┆ 7          │
│ item_number                    ┆ 3          │
│ item_description               ┆ 0          │
│ pack                           ┆ 0          │
│ bottle_volume                  ┆ 0          │
│ state_bottle_cost              ┆ 221        │
│ state_bottle_retail            ┆ 244        │
│ bottles_sold                   ┆ 2219       │
│ sale_dollars                   ┆ 10         │
│ volume_sold_liters             ┆ 6347       │
│ volume_sold_gallons            ┆ 163        │
│ iowa_zip_code_tabulation_areas ┆ 2506680    │
│ iowa_watershed_sub_basins      ┆ 2506680    │
│ iowa_watersheds                ┆ 2506680    │
│ county_boundaries_of_iowa      ┆ 2506680    │
│ us_counties                    ┆ 2497621    │
└────────────────────────────────┴────────────┘

### Retrieve Basic Information About DataFrame

In [5]:
print(df.shape)
print(df.dtypes)

(27489743, 29)
[String, String, Int64, String, String, String, Int64, String, Int64, String, Int64, String, Int64, String, Int64, String, Int64, String, Float64, Float64, Int64, String, Float64, Float64, Int64, Int64, Int64, Int64, String]

In [19]:
def print_schema(df: pl.DataFrame):
    print(f"{'Column':<30} | {'Data Type'}")
    print("-" * 60)
    for name, dtype in zip(df.columns, df.dtypes):
        print(f"{name:<30} | {dtype}")

print_schema(df)

Column                         | Data Type
------------------------------------------------------------
invoice_item_number            | String
date_of_sale                   | String
store_number                   | Int64
store_name                     | String
store_address                  | String
store_city                     | String
store_zip_code                 | Int64
store_location                 | String
store_county_number            | Int64
store_county                   | String
item_category                  | Int64
category_name                  | String
vendor_number                  | Int64
vendor_name                    | String
item_number                    | Int64
item_description               | String
pack                           | Int64
bottle_volume                  | String
state_bottle_cost              | Float64
state_bottle_retail            | Float64
bottles_sold                   | Int64
sale_dollars                   | String
volume_sold_liters             | Float64
volume_sold_gallons            | Float64
iowa_zip_code_tabulation_areas | Int64
iowa_watershed_sub_basins      | Int64
iowa_watersheds                | Int64
county_boundaries_of_iowa      | Int64
us_counties                    | String

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ invoice_i ┆ date_of_s ┆ store_num ┆ … ┆ iowa_wate ┆ iowa_wate ┆ county_bo ┆ us_count │
│ ---       ┆ tem_numbe ┆ ale       ┆ ber       ┆   ┆ rshed_sub ┆ rsheds    ┆ undaries_ ┆ ies      │
│ str       ┆ r         ┆ ---       ┆ ---       ┆   ┆ _basins   ┆ ---       ┆ of_iowa   ┆ ---      │
│           ┆ ---       ┆ str       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str      │
│           ┆ str       ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 27489743  ┆ 27489743  ┆ 2.7489743 ┆ … ┆ 2.4983063 ┆ 2.4983063 ┆ 2.4983063 ┆ 24992122 │
│           ┆           ┆           ┆ e7        ┆   ┆ e7        ┆ e7        ┆ e7        ┆          │
│ null_coun ┆ 0         ┆ 0         ┆ 0.0       ┆ … ┆ 2.50668e6 ┆ 2.50668e6 ┆ 2.50668e6 ┆ 2497621  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 3858.8387 ┆ … ┆ 27.119045 ┆ 249.07225 ┆ 51.852436 ┆ null     │
│           ┆           ┆           ┆ 45        ┆   ┆           ┆ 8         ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ 1210.7930 ┆ … ┆ 13.671209 ┆ 113.48307 ┆ 21.263153 ┆ null     │
│           ┆           ┆           ┆ 91        ┆   ┆           ┆ 1         ┆           ┆          │
│ min       ┆ 306831300 ┆ 01/02/201 ┆ 2106.0    ┆ … ┆ 1.0       ┆ 3.0       ┆ 1.0       ┆ 1,137    │
│           ┆ 001       ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 2621.0    ┆ … ┆ 18.0      ┆ 137.0     ┆ 35.0      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ 3869.0    ┆ … ┆ 25.0      ┆ 264.0     ┆ 57.0      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ 4748.0    ┆ … ┆ 35.0      ┆ 332.0     ┆ 64.0      ┆ null     │
│ max       ┆ S44440008 ┆ 12/31/202 ┆ 10270.0   ┆ … ┆ 56.0      ┆ 534.0     ┆ 99.0      ┆ 727      │
│           ┆ 3         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ invoice_i ┆ date_of_s ┆ store_nam ┆ store_add ┆ … ┆ item_desc ┆ bottle_vo ┆ sale_doll ┆ us_count │
│ tem_numbe ┆ ale       ┆ e         ┆ ress      ┆   ┆ ription   ┆ lume      ┆ ars       ┆ ies      │
│ r         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
│ u32       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 16        ┆ 10        ┆ 58        ┆ 55        ┆ … ┆ 63        ┆ 7         ┆ 10        ┆ 5        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, Int64, String, String, String, Int64, String, Int64, String, Int64, String, Int64, String, Int64, String, Int64, String, Float64, Float64, Int64, String, Float64, Float64, Int64, Int64, Int64, Int64, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

          Unique values in invoice_item_number : 27489743
                 Unique values in date_of_sale : 3021
                 Unique values in store_number : 2982
                   Unique values in store_name : 3175
                Unique values in store_address : 2983
                   Unique values in store_city : 484
               Unique values in store_zip_code : 517
               Unique values in store_location : 9412
          Unique values in store_county_number : 100
                 Unique values in store_county : 101
                Unique values in item_category : 115
                Unique values in category_name : 104
                Unique values in vendor_number : 470
                  Unique values in vendor_name : 592
                  Unique values in item_number : 12901
             Unique values in item_description : 11877
                         Unique values in pack : 28
                Unique values in bottle_volume : 58
            Unique values in state_bottle_cost : 3544
          Unique values in state_bottle_retail : 4007
                 Unique values in bottles_sold : 554
                 Unique values in sale_dollars : 33820
           Unique values in volume_sold_liters : 1397
          Unique values in volume_sold_gallons : 1935
Unique values in iowa_zip_code_tabulation_areas : 514
    Unique values in iowa_watershed_sub_basins : 55
              Unique values in iowa_watersheds : 287
    Unique values in county_boundaries_of_iowa : 100
                  Unique values in us_counties : 113

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

store_number
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ store_number │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2.7489743e7  │
│ null_count ┆ 0.0          │
│ mean       ┆ 3858.838745  │
│ std        ┆ 1210.793091  │
│ min        ┆ 2106.0       │
│ 25%        ┆ 2621.0       │
│ 50%        ┆ 3869.0       │
│ 75%        ┆ 4748.0       │
│ max        ┆ 10270.0      │
└────────────┴──────────────┘


store_zip_code
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ store_zip_code │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 2.7399023e7    │
│ null_count ┆ 90720.0        │
│ mean       ┆ 51258.555818   │
│ std        ┆ 989.999209     │
│ min        ┆ 50002.0        │
│ 25%        ┆ 50315.0        │
│ 50%        ┆ 51054.0        │
│ 75%        ┆ 52302.0        │
│ max        ┆ 80904.0        │
└────────────┴────────────────┘


store_county_number
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ store_county_number │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2.4132843e7         │
│ null_count ┆ 3.3569e6            │
│ mean       ┆ 57.259133           │
│ std        ┆ 27.287104           │
│ min        ┆ 1.0                 │
│ 25%        ┆ 31.0                │
│ 50%        ┆ 62.0                │
│ 75%        ┆ 77.0                │
│ max        ┆ 99.0                │
└────────────┴─────────────────────┘


item_category
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ item_category │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 2.7472769e7   │
│ null_count ┆ 16974.0       │
│ mean       ┆ 1.0499e6      │
│ std        ┆ 81397.774702  │
│ min        ┆ 101220.0      │
│ 25%        ┆ 1.0122e6      │
│ 50%        ┆ 1.0312e6      │
│ 75%        ┆ 1.0624e6      │
│ max        ┆ 1.9012e6      │
└────────────┴───────────────┘


vendor_number
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ vendor_number │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 2.7489734e7   │
│ null_count ┆ 9.0           │
│ mean       ┆ 270.954235    │
│ std        ┆ 144.041265    │
│ min        ┆ 10.0          │
│ 25%        ┆ 115.0         │
│ 50%        ┆ 260.0         │
│ 75%        ┆ 395.0         │
│ max        ┆ 987.0         │
└────────────┴───────────────┘


item_number
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ item_number  │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2.748974e7   │
│ null_count ┆ 3.0          │
│ mean       ┆ 49624.170969 │
│ std        ┆ 72114.66944  │
│ min        ┆ 101.0        │
│ 25%        ┆ 27066.0      │
│ 50%        ┆ 39382.0      │
│ 75%        ┆ 64866.0      │
│ max        ┆ 999996.0     │
└────────────┴──────────────┘


pack
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ pack        │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 2.7489743e7 │
│ null_count ┆ 0.0         │
│ mean       ┆ 12.159554   │
│ std        ┆ 7.741659    │
│ min        ┆ 1.0         │
│ 25%        ┆ 6.0         │
│ 50%        ┆ 12.0        │
│ 75%        ┆ 12.0        │
│ max        ┆ 336.0       │
└────────────┴─────────────┘


state_bottle_cost
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ state_bottle_cost │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 2.7489522e7       │
│ null_count ┆ 221.0             │
│ mean       ┆ 10.497055         │
│ std        ┆ 8.633821          │
│ min        ┆ 0.0               │
│ 25%        ┆ 5.54              │
│ 50%        ┆ 8.32              │
│ 75%        ┆ 12.8              │
│ max        ┆ 906.5             │
└────────────┴───────────────────┘


state_bottle_retail
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ state_bottle_retail │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2.7489499e7         │
│ null_count ┆ 244.0               │
│ mean       ┆ 15.755247           │
│ std        ┆ 12.910136           │
│ min        ┆ 0.0                 │
│ 25%        ┆ 8.4                 │
│ 50%        ┆ 12.5                │
│ 75%        ┆ 19.35               │
│ max        ┆ 899.99              │
└────────────┴─────────────────────┘


bottles_sold
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ bottles_sold │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 2.7487524e7  │
│ null_count ┆ 2219.0       │
│ mean       ┆ 10.625377    │
│ std        ┆ 24.439117    │
│ min        ┆ -648.0       │
│ 25%        ┆ 3.0          │
│ 50%        ┆ 6.0          │
│ 75%        ┆ 12.0         │
│ max        ┆ 999.0        │
└────────────┴──────────────┘


volume_sold_liters
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ volume_sold_liters │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 2.7483396e7        │
│ null_count ┆ 6347.0             │
│ mean       ┆ 8.824372           │
│ std        ┆ 24.255347          │
│ min        ┆ -648.0             │
│ 25%        ┆ 1.5                │
│ 50%        ┆ 4.8                │
│ 75%        ┆ 10.5               │
│ max        ┆ 999.0              │
└────────────┴────────────────────┘


volume_sold_gallons
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ volume_sold_gallons │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 2.748958e7          │
│ null_count ┆ 163.0               │
│ mean       ┆ 2.408352            │
│ std        ┆ 8.575242            │
│ min        ┆ -171.18             │
│ 25%        ┆ 0.4                 │
│ 50%        ┆ 1.26                │
│ 75%        ┆ 2.77                │
│ max        ┆ 998.57              │
└────────────┴─────────────────────┘


iowa_zip_code_tabulation_areas
shape: (9, 2)
┌────────────┬────────────────────────────────┐
│ statistic  ┆ iowa_zip_code_tabulation_areas │
│ ---        ┆ ---                            │
│ str        ┆ f64                            │
╞════════════╪════════════════════════════════╡
│ count      ┆ 2.4983063e7                    │
│ null_count ┆ 2.50668e6                      │
│ mean       ┆ 504.515818                     │
│ std        ┆ 266.201715                     │
│ min        ┆ 1.0                            │
│ 25%        ┆ 233.0                          │
│ 50%        ┆ 523.0                          │
│ 75%        ┆ 767.0                          │
│ max        ┆ 935.0                          │
└────────────┴────────────────────────────────┘


iowa_watershed_sub_basins
shape: (9, 2)
┌────────────┬───────────────────────────┐
│ statistic  ┆ iowa_watershed_sub_basins │
│ ---        ┆ ---                       │
│ str        ┆ f64                       │
╞════════════╪═══════════════════════════╡
│ count      ┆ 2.4983063e7               │
│ null_count ┆ 2.50668e6                 │
│ mean       ┆ 27.119045                 │
│ std        ┆ 13.671209                 │
│ min        ┆ 1.0                       │
│ 25%        ┆ 18.0                      │
│ 50%        ┆ 25.0                      │
│ 75%        ┆ 35.0                      │
│ max        ┆ 56.0                      │
└────────────┴───────────────────────────┘


iowa_watersheds
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ iowa_watersheds │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 2.4983063e7     │
│ null_count ┆ 2.50668e6       │
│ mean       ┆ 249.072258      │
│ std        ┆ 113.483071      │
│ min        ┆ 3.0             │
│ 25%        ┆ 137.0           │
│ 50%        ┆ 264.0           │
│ 75%        ┆ 332.0           │
│ max        ┆ 534.0           │
└────────────┴─────────────────┘


county_boundaries_of_iowa
shape: (9, 2)
┌────────────┬───────────────────────────┐
│ statistic  ┆ county_boundaries_of_iowa │
│ ---        ┆ ---                       │
│ str        ┆ f64                       │
╞════════════╪═══════════════════════════╡
│ count      ┆ 2.4983063e7               │
│ null_count ┆ 2.50668e6                 │
│ mean       ┆ 51.852436                 │
│ std        ┆ 21.263153                 │
│ min        ┆ 1.0                       │
│ 25%        ┆ 35.0                      │
│ 50%        ┆ 57.0                      │
│ 75%        ┆ 64.0                      │
│ max        ┆ 99.0                      │
└────────────┴───────────────────────────┘

### List Unique Values For Certain Features

In [11]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: date_of_sale (3021 unique values)
shape: (3_021,)
Series: 'date_of_sale' [str]
[
	"01/02/2013"
	"01/02/2014"
	"01/02/2018"
	"01/02/2019"
	"01/02/2020"
	"01/02/2022"
	"01/02/2023"
	"01/03/2012"
	"01/03/2013"
	"01/03/2017"
	"01/03/2018"
	"01/03/2019"
	"01/03/2020"
	"01/03/2022"
	"01/03/2023"
	"01/04/2012"
	"01/04/2016"
	"01/04/2017"
	…
	"12/29/2022"
	"12/30/2013"
	"12/30/2014"
	"12/30/2015"
	"12/30/2016"
	"12/30/2019"
	"12/30/2020"
	"12/30/2021"
	"12/30/2022"
	"12/31/2012"
	"12/31/2013"
	"12/31/2014"
	"12/31/2015"
	"12/31/2018"
	"12/31/2019"
	"12/31/2020"
	"12/31/2021"
]
--------------------------------------------------
Column: store_number (2982 unique values)
shape: (2_982,)
Series: 'store_number' [i64]
[
	2106
	2113
	2130
	2132
	2152
	2161
	2178
	2190
	2191
	2200
	2201
	2205
	2228
	2233
	2238
	2248
	2260
	2285
	…
	10240
	10241
	10243
	10244
	10245
	10248
	10249
	10251
	10254
	10256
	10257
	10258
	10259
	10260
	10261
	10269
	10270
]
--------------------------------------------------
Column: store_name (3175 unique values)
shape: (3_175,)
Series: 'store_name' [str]
[
	""DOUBLE ""D"" LIQUOR STORE""
	"'DA BOOZE BARN / WEST BEND"
	"10TH HOLE INN & SUITE / GIFT S…
	"16TH AVE BP / CEDAR RAPIDS"
	"173 CRAFT DISTILLERY"
	"173 CRAFT DISTILLERY (ET)"
	"1ST AVE BP / CEDAR RAPIDS"
	"1ST STOP BEVERAGE SHOP"
	"218 FUEL EXPRESS"
	"218 FUEL EXPRESS & CHUBBY'S LI…
	"3-OAKS DISTILLERY, LLC"
	"380BP / SWISHER"
	"3RD ST CONVENIENCE"
	"4 WAY STOP SHOP / MOVILLE"
	"6 CORNERS GAS & GRUB"
	"7 DAYS MART / COUNCIL BLUFFS"
	"7 RAYOS LIQUOR STORE"
	"7-ELEVEN # 34464Z"
	…
	"YESWAY STORE # 10019/ MASON CI…
	"YESWAY STORE # 10020/ STORY CI…
	"YESWAY STORE # 10021/ WEBSTER …
	"YESWAY STORE # 10022/ WATERLOO"
	"YESWAY STORE # 10023/ WATERLOO"
	"YESWAY STORE # 10025/ NEWTON"
	"YESWAY STORE # 10026/ MASON CI…
	"YESWAY STORE # 10029/ CLARION"
	"YESWAY STORE # 10034/ BELMOND"
	"YESWAY STORE # 1029/ CLARION"
	"YESWAY STORE # 1036/ KANAWHA"
	"YESWAY STORE #1037/ GRIMES"
	"YESWAY STORE #1198 / SWEA CITY"
	"YOUR PRIVATE BAR / URBANDALE"
	"YR DOLLAR STOP"
	"Z'S QUICKBREAK"
	"ZAPF'S PRONTO MARKET"
]
--------------------------------------------------
Column: store_address (2983 unique values)
shape: (2_983,)
Series: 'store_address' [str]
[
	null
	"1 GROVE ROAD"
	"1 HAWKEYE DR"
	"1 HAWKEYE DRIVE"
	"1, GROVE RD"
	"10  3RD ST NW"
	"10 3RD ST. NW, STE B"
	"10 3RD STREET NW STE B"
	"100 1ST STREET"
	"100 8TH STREET SW"
	"100 AMHERST BLVD"
	"100 E  OAKDALE BLVD"
	"100 E ELM"
	"100 E ELM ST"
	"100 E JACKSON ST"
	"100 E MADISON ST"
	"100 EUCLID AVE"
	"100 GRANT ST"
	…
	"975 S 11TH ST"
	"9761 UNIVERSITY AVE."
	"977 198TH PL."
	"990 ROBINS SQUARE DR."
	"990, ROBINS SQUARE DR"
	"9915 DOUGLAS AVE"
	"9915, DOUGLAS AVE"
	"998 8TH AVE"
	"999 MIDDLE RD"
	"9TH ST SW B"
	"FIRST & MAIN"
	"HIGHWAY 65 SOUTH"
	"HWY 71 & HWY 175"
	"HWY 9 & 71"
	"ONE PRAIRIE MEADOWS DRIVE"
	"PO BOX 1317"
	"PO BOX 261  310 W DILLON"
]
--------------------------------------------------
Column: store_city (484 unique values)
shape: (484,)
Series: 'store_city' [str]
[
	null
	"ACKLEY"
	"ADAIR"
	"ADEL"
	"AFTON"
	"AINSWORTH"
	"AKRON"
	"ALBERT CITY"
	"ALBIA"
	"ALBION"
	"ALBURNETT"
	"ALDEN"
	"ALGONA"
	"ALLERTON"
	"ALLISON"
	"ALTA"
	"ALTA VISTA"
	"ALTON"
	…
	"WEST LIBERTY"
	"WEST POINT"
	"WEST UNION"
	"WEVER"
	"WHAT CHEER"
	"WHEATLAND"
	"WHITTEMORE"
	"WILLIAMSBURG"
	"WILTON"
	"WINDSOR HEIGHTS"
	"WINFIELD"
	"WINTERSET"
	"WINTHROP"
	"WOODBINE"
	"WOODWARD"
	"WYOMING"
	"ZWINGLE"
]
--------------------------------------------------
Column: store_zip_code (517 unique values)
shape: (517,)
Series: 'store_zip_code' [i64]
[
	null
	50002
	50003
	50005
	50006
	50008
	50009
	50010
	50014
	50015
	50020
	50021
	50022
	50023
	50025
	50028
	50033
	50035
	…
	52767
	52768
	52772
	52773
	52774
	52776
	52777
	52778
	52801
	52802
	52803
	52804
	52806
	52807
	56201
	57222
	80904
]
--------------------------------------------------
Column: store_county_number (100 unique values)
shape: (100,)
Series: 'store_county_number' [i64]
[
	null
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	…
	83
	84
	85
	86
	87
	88
	89
	90
	91
	92
	93
	94
	95
	96
	97
	98
	99
]
--------------------------------------------------
Column: store_county (101 unique values)
shape: (101,)
Series: 'store_county' [str]
[
	null
	"ADAIR"
	"ADAMS"
	"ALLAMAKEE"
	"APPANOOSE"
	"AUDUBON"
	"BENTON"
	"BLACK HAWK"
	"BOONE"
	"BREMER"
	"BUCHANAN"
	"BUENA VISTA"
	"BUTLER"
	"CALHOUN"
	"CARROLL"
	"CASS"
	"CEDAR"
	"CERRO GORDO"
	…
	"SHELBY"
	"SIOUX"
	"STORY"
	"TAMA"
	"TAYLOR"
	"UNION"
	"VAN BUREN"
	"WAPELLO"
	"WARREN"
	"WASHINGTON"
	"WAYNE"
	"WEBSTER"
	"WINNEBAGO"
	"WINNESHIEK"
	"WOODBURY"
	"WORTH"
	"WRIGHT"
]
--------------------------------------------------
Column: item_category (115 unique values)
shape: (115,)
Series: 'item_category' [i64]
[
	null
	101220
	1011000
	1011100
	1011200
	1011250
	1011300
	1011400
	1011500
	1011600
	1011700
	1011800
	1012000
	1012100
	1012200
	1012210
	1012300
	1012400
	…
	1090000
	1091000
	1091100
	1091200
	1091300
	1091400
	1092000
	1092100
	1101100
	1501100
	1700000
	1701100
	1701200
	1900000
	1901000
	1901100
	1901200
]
--------------------------------------------------
Column: category_name (104 unique values)
shape: (104,)
Series: 'category_name' [str]
[
	null
	"100 PROOF VODKA"
	"100% AGAVE TEQUILA"
	"AGED DARK RUM"
	"AMARETTO - IMPORTED"
	"AMERICAN ALCOHOL"
	"AMERICAN AMARETTO"
	"AMERICAN BRANDIES"
	"AMERICAN COCKTAILS"
	"AMERICAN CORDIALS & LIQUEURS"
	"AMERICAN DISTILLED SPIRITS SPE…
	"AMERICAN DRY GINS"
	"AMERICAN FLAVORED VODKA"
	"AMERICAN GRAPE BRANDIES"
	"AMERICAN SCHNAPPS"
	"AMERICAN SLOE GINS"
	"AMERICAN VODKAS"
	"AMERICAN WHISKIES"
	…
	"SPECIAL ORDER ITEMS"
	"SPICED RUM"
	"STRAIGHT BOURBON WHISKIES"
	"STRAIGHT RYE WHISKIES"
	"STRAWBERRY SCHNAPPS"
	"TEMPORARY & SPECIALTY PACKAGES"
	"TENNESSEE WHISKIES"
	"TEQUILA"
	"TRIPLE SEC"
	"TROPICAL FRUIT SCHNAPPS"
	"VODKA 80 PROOF"
	"VODKA FLAVORED"
	"WATERMELON SCHNAPPS"
	"WHISKEY LIQUEUR"
	"WHITE CREME DE CACAO"
	"WHITE CREME DE MENTHE"
	"WHITE RUM"
]
--------------------------------------------------
Column: vendor_number (470 unique values)
shape: (470,)
Series: 'vendor_number' [i64]
[
	null
	10
	14
	27
	33
	35
	51
	55
	61
	65
	68
	69
	79
	80
	82
	85
	86
	89
	…
	900
	901
	902
	907
	908
	911
	917
	924
	926
	927
	932
	962
	969
	971
	977
	978
	987
]
--------------------------------------------------
Column: vendor_name (592 unique values)
shape: (592,)
Series: 'vendor_name' [str]
[
	null
	"10TH MOUNTAIN WHISKEY & SPIRIT…
	"173 CRAFT DISTILLERY"
	"21ST CENTURY SPIRITS LLC"
	"3 BADGE CORPORATION"
	"3 BADGE MIXOLOGY"
	"3-OAKS DISTILLERY, LLC"
	"45TH PARALLEL SPIRITS"
	"A HARDY / U.S.A., LTD."
	"A HARDY USA LTD"
	"A V BRANDS INC"
	"ADAMBA IMPORTS INT'L, INC."
	"AHA TORO SPIRITS INC"
	"AHA TORO SPIRITS INC / AHA YET…
	"AIKO IMPORTERS INC"
	"ALLEGHENY DISTILLING LLC"
	"ALTAMAR BRANDS LLC"
	"ALTOS PLANOS INC."
	…
	"WILSON DANIELS LTD."
	"WINDY HILL SPIRITS"
	"WINE INTELLIGENCE"
	"WINE IS FINE INC"
	"WINEBOW INC"
	"WINEBOW, INC."
	"WINESOURCE INTERNATIONAL INC."
	"WMC-PBD LLC/ PINE BLUFFS DISTI…
	"WOODY CREEK DISTILLERS"
	"WOODY CREEK DISTILLERS LLC"
	"WORLD TRADE LIQUOR IMPORTS LLC"
	"WORLDWIDE LIBATIONS, LLC"
	"WRS CO. LLC / WRS IMPORTS"
	"WYCH DR. DISTILLING, LLC"
	"YAHARA BAY DISTILLERS INC"
	"YAHARA BAY DISTILLERS, INC"
	"ZING ZANG, LLC"
]
--------------------------------------------------
Column: pack (28 unique values)
shape: (28,)
Series: 'pack' [i64]
[
	1
	2
	3
	4
	5
	6
	8
	9
	10
	12
	15
	16
	18
	20
	24
	28
	30
	32
	44
	48
	60
	80
	96
	120
	160
	288
	312
	336
]
--------------------------------------------------
Column: bottle_volume (58 unique values)
shape: (58,)
Series: 'bottle_volume' [str]
[
	"0"
	"1,000"
	"1,125"
	"1,200"
	"1,420"
	"1,500"
	"1,508"
	"1,750"
	"1,800"
	"1,850"
	"1,950"
	"100"
	"12"
	"140,000"
	"15"
	"150"
	"175"
	"180,000"
	…
	"400"
	"425"
	"5,250"
	"50"
	"500"
	"502"
	"6,000"
	"600"
	"603"
	"7,580"
	"700"
	"750"
	"800"
	"850"
	"9,000"
	"900"
	"950"
]
--------------------------------------------------
Column: state_bottle_cost (3544 unique values)
shape: (3_544,)
Series: 'state_bottle_cost' [f64]
[
	null
	0.0
	0.19
	0.33
	0.43
	0.48
	0.51
	0.55
	0.59
	0.66
	0.89
	0.9
	0.93
	0.94
	0.95
	0.97
	0.98
	0.99
	…
	540.0
	549.99
	559.99
	563.4
	567.99
	575.0
	599.99
	674.16
	674.99
	675.0
	700.0
	726.81
	727.0
	750.0
	800.0
	850.0
	906.5
]
--------------------------------------------------
Column: state_bottle_retail (4007 unique values)
shape: (4_007,)
Series: 'state_bottle_retail' [f64]
[
	null
	0.0
	0.29
	0.5
	0.65
	0.72
	0.76
	0.83
	0.88
	0.99
	1.34
	1.35
	1.4
	1.41
	1.43
	1.46
	1.47
	1.48
	…
	658.19
	675.0
	719.99
	720.0
	724.5
	747.96
	749.99
	750.0
	764.94
	782.49
	810.0
	824.99
	839.99
	845.1
	851.99
	862.5
	899.99
]
--------------------------------------------------
Column: bottles_sold (554 unique values)
shape: (554,)
Series: 'bottles_sold' [i64]
[
	null
	-648
	-360
	-294
	-240
	-228
	-200
	-192
	-180
	-156
	-150
	-144
	-132
	-120
	-108
	-96
	-84
	-72
	…
	900
	907
	910
	912
	918
	924
	930
	936
	942
	948
	960
	972
	980
	984
	990
	996
	999
]
--------------------------------------------------
Column: volume_sold_liters (1397 unique values)
shape: (1_397,)
Series: 'volume_sold_liters' [f64]
[
	null
	-648.0
	-630.0
	-360.0
	-315.0
	-262.5
	-228.0
	-220.5
	-189.0
	-168.0
	-156.0
	-147.0
	-105.0
	-99.0
	-96.0
	-94.5
	-84.0
	-75.0
	…
	955.5
	960.0
	963.0
	966.0
	967.5
	971.25
	972.0
	976.5
	980.0
	981.0
	984.0
	985.5
	987.0
	990.0
	996.0
	997.5
	999.0
]
--------------------------------------------------
Column: volume_sold_gallons (1935 unique values)
shape: (1_935,)
Series: 'volume_sold_gallons' [f64]
[
	null
	-171.18
	-166.42
	-95.1
	-83.21
	-69.34
	-60.23
	-58.24
	-49.92
	-44.38
	-41.21
	-38.83
	-27.73
	-26.15
	-25.36
	-24.96
	-22.19
	-19.81
	…
	887.61
	912.98
	915.35
	929.22
	931.99
	932.0
	934.9
	951.01
	951.02
	960.52
	965.28
	970.83
	972.42
	974.79
	993.02
	997.97
	998.57
]
--------------------------------------------------
Column: iowa_zip_code_tabulation_areas (514 unique values)
shape: (514,)
Series: 'iowa_zip_code_tabulation_areas' [i64]
[
	null
	1
	2
	4
	6
	7
	9
	11
	13
	14
	15
	20
	22
	25
	26
	27
	30
	34
	…
	905
	908
	909
	910
	911
	912
	913
	914
	916
	917
	920
	921
	923
	924
	925
	927
	935
]
--------------------------------------------------
Column: iowa_watershed_sub_basins (55 unique values)
shape: (55,)
Series: 'iowa_watershed_sub_basins' [i64]
[
	null
	1
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	18
	…
	40
	41
	42
	43
	44
	45
	46
	47
	48
	49
	50
	51
	52
	53
	54
	55
	56
]
--------------------------------------------------
Column: iowa_watersheds (287 unique values)
shape: (287,)
Series: 'iowa_watersheds' [i64]
[
	null
	3
	6
	13
	17
	18
	19
	20
	23
	34
	35
	36
	37
	38
	39
	41
	49
	50
	…
	469
	472
	473
	474
	475
	479
	486
	487
	491
	503
	504
	508
	517
	531
	532
	533
	534
]
--------------------------------------------------
Column: county_boundaries_of_iowa (100 unique values)
shape: (100,)
Series: 'county_boundaries_of_iowa' [i64]
[
	null
	1
	2
	3
	4
	5
	6
	7
	8
	9
	10
	11
	12
	13
	14
	15
	16
	17
	…
	83
	84
	85
	86
	87
	88
	89
	90
	91
	92
	93
	94
	95
	96
	97
	98
	99
]
--------------------------------------------------
Column: us_counties (113 unique values)
shape: (113,)
Series: 'us_counties' [str]
[
	null
	"1,137"
	"1,355"
	"1,364"
	"1,365"
	"1,366"
	"1,367"
	"1,368"
	"1,369"
	"1,370"
	"1,371"
	"1,372"
	"1,373"
	"1,374"
	"1,447"
	"1,745"
	"1,746"
	"1,747"
	…
	"289"
	"290"
	"291"
	"292"
	"293"
	"294"
	"295"
	"296"
	"297"
	"298"
	"299"
	"300"
	"301"
	"302"
	"303"
	"304"
	"727"
]
--------------------------------------------------

In [12]:
def list_unique_values_over_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count > threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_over_threshold(df)

Column: invoice_item_number (27489743 unique values)
shape: (27_489_743,)
Series: 'invoice_item_number' [str]
[
	"306831300001"
	"306831300002"
	"306831300003"
	"306831300004"
	"306831300005"
	"306831300006"
	"306831300007"
	"306831300008"
	"306831300009"
	"306831300010"
	"306831300011"
	"306831300012"
	"306831300013"
	"306831300014"
	"306831300015"
	"306831300016"
	"306831300017"
	"306831300018"
	…
	"S444400067"
	"S444400068"
	"S444400069"
	"S444400070"
	"S444400071"
	"S444400072"
	"S444400073"
	"S444400074"
	"S444400075"
	"S444400076"
	"S444400077"
	"S444400078"
	"S444400079"
	"S444400080"
	"S444400081"
	"S444400082"
	"S444400083"
]
--------------------------------------------------
Column: store_location (9412 unique values)
shape: (9_412,)
Series: 'store_location' [str]
[
	null
	"POINT (-100.022029 37.763303)"
	"POINT (-101.924438 51.856783)"
	"POINT (-104.845334 38.848017)"
	"POINT (-73.982421 40.305231)"
	"POINT (-73.982421 40.305231000…
	"POINT (-77.31187 35.96278)"
	"POINT (-78.41659 40.51419)"
	"POINT (-80.34522 42.02256)"
	"POINT (-84.499766 33.755447)"
	"POINT (-89.08865 42.27797)"
	"POINT (-89.931319 38.517837)"
	"POINT (-90.180476 41.86723)"
	"POINT (-90.18057 41.86701)"
	"POINT (-90.180801 41.866271)"
	"POINT (-90.18083800999995 41.8…
	"POINT (-90.18083801 41.8671950…
	"POINT (-90.18135802399996 41.8…
	…
	"POINT (-96.487711033 42.994979…
	"POINT (-96.487949 43.008899)"
	"POINT (-96.488094 42.997038)"
	"POINT (-96.48809400000002 42.9…
	"POINT (-96.48809400000002 42.9…
	"POINT (-96.48867998099996 42.9…
	"POINT (-96.488679981 42.997183…
	"POINT (-96.50175700699998 43.4…
	"POINT (-96.501757007 43.495728…
	"POINT (-96.50552 43.49704)"
	"POINT (-96.559417041 42.828441…
	"POINT (-96.560848 42.827477)"
	"POINT (-96.56297 42.82309)"
	"POINT (-96.563106 42.823106)"
	"POINT (-96.56323 42.823106)"
	"POINT (-96.56328998299995 42.8…
	"POINT (-96.563289983 42.822745…
]
--------------------------------------------------
Column: item_number (12901 unique values)
shape: (12_901,)
Series: 'item_number' [i64]
[
	null
	101
	102
	104
	107
	108
	114
	115
	122
	124
	127
	129
	133
	139
	145
	146
	149
	155
	…
	999929
	999930
	999931
	999932
	999934
	999935
	999936
	999937
	999938
	999939
	999940
	999991
	999992
	999993
	999994
	999995
	999996
]
--------------------------------------------------
Column: item_description (11877 unique values)
shape: (11_877,)
Series: 'item_description' [str]
[
	""BEEFEATER ""24""""
	""JOSE CUERVO SILVER ""ROLLING …
	""RUMCHATA ""GOCHATAS""""
	""RUMCHATA ""MINICHATAS"" CREAM…
	"(RI)1 RYE"
	"10 CANE RUM"
	"100 ANOS ANEJO"
	"100 ANOS AZUL 100% AGAVE"
	"10TH MOUNTAIN BOURBON"
	"135 EAST HYOGO JAPANESE DRY GI…
	"135° EAST HYOGO JAPANESE DRY G…
	"135� EAST HYOGO JAPANESE DRY G…
	"173 CRAFT DISTILLERY BOURBON W…
	"173 CRAFT DISTILLERY BROKEN BE…
	"173 CRAFT DISTILLERY BROKEN BE…
	"173 CRAFT DISTILLERY VOLUMETRI…
	"173 CRAFT DISTILLERY VOLUMETRI…
	"1792 12YR OLD BOURBON"
	…
	"ZIGNUM ANEJO MEZCAL"
	"ZIGNUM SILVER MEZCAL"
	"ZING 72 GIN W/COPPER CUP"
	"ZING ZANG BLAZING BLOODY MARY …
	"ZING ZANG BLOODY MARY RTS"
	"ZIRBENZ STONE PINE LIQUEUR OF …
	"ZIYAD BERRY BUSSIN TEA"
	"ZIYAD LEMON RUSH"
	"ZIYAD WATERMELON DRIP"
	"ZIYAD WHITE RYE"
	"ZIYAD WHITE RYE DISCO"
	"ZU BISON GRASS VODKA"
	"ZUBROWKA BISON GRASS VODKA"
	"ZUCCA RABARBARO"
	"ZWACK"
	"ZWACK UNICUM"
	"ZYR VODKA"
]
--------------------------------------------------
Column: sale_dollars (33820 unique values)
shape: (33_820,)
Series: 'sale_dollars' [str]
[
	null
	"-1,026.00"
	"-1,039.08"
	"-1,061.28"
	"-1,079.64"
	"-1,080.00"
	"-1,085.40"
	"-1,124.40"
	"-1,133.76"
	"-1,152.00"
	"-1,169.88"
	"-1,170.00"
	"-1,188.48"
	"-1,237.50"
	"-1,259.52"
	"-1,261.44"
	"-1,348.80"
	"-1,386.00"
	…
	"996.96"
	"997.08"
	"997.20"
	"997.56"
	"997.80"
	"997.92"
	"998.16"
	"998.40"
	"998.46"
	"998.64"
	"999.00"
	"999.12"
	"999.36"
	"999.44"
	"999.54"
	"999.60"
	"999.72"
]
--------------------------------------------------

In [14]:
# List the columns to check
cols = [
    "iowa_zip_code_tabulation_areas",
    "iowa_watershed_sub_basins",
    "iowa_watersheds",
    "county_boundaries_of_iowa"
]

# Create a boolean mask for each column being null, then sum the row-wise nulls
null_mask = df.select([pl.col(c).is_null().alias(c) for c in cols])

# Sum across the selected columns to see if all are null in the same row
same_null_rows = null_mask.select(
    (pl.sum_horizontal(null_mask.columns) == len(cols)).alias("all_null")
)

# Count how many rows have all those columns null at the same time
count_all_null = same_null_rows.filter(pl.col("all_null")).height

# Display the result
if count_all_null == 2506680:
    print(f"The nulls are all in the same Rows as: Rows where all {len(cols)} columns are null: {count_all_null}")

The nulls are all in the same Rows as: Rows where all 4 columns are null: 2506680

### How Many Records Remain IF I Remove Records With Any Nulls In It

In [15]:
def drop_rows_with_any_nulls(df: pl.DataFrame) -> pl.DataFrame:
    """
    Removes all rows from a Polars DataFrame that contain any null values.
    """
    return df.drop_nulls()


drop_rows_with_any_nulls(df)

shape: (21_784_789, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ invoice_i ┆ date_of_s ┆ store_num ┆ store_nam ┆ … ┆ iowa_wate ┆ iowa_wate ┆ county_bo ┆ us_count │
│ tem_numbe ┆ ale       ┆ ber       ┆ e         ┆   ┆ rshed_sub ┆ rsheds    ┆ undaries_ ┆ ies      │
│ r         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _basins   ┆ ---       ┆ of_iowa   ┆ ---      │
│ ---       ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ str      │
│ str       ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ INV-07718 ┆ 10/05/201 ┆ 4091      ┆ FAREWAY   ┆ … ┆ 20        ┆ 19        ┆ 16        ┆ 1,785    │
│ 300026    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #705 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CLEAR LA… ┆   ┆           ┆           ┆           ┆          │
│ INV-07790 ┆ 10/09/201 ┆ 2651      ┆ HY-VEE /  ┆ … ┆ 14        ┆ 190       ┆ 28        ┆ 177      │
│ 400037    ┆ 7         ┆           ┆ WAVERLY   ┆   ┆           ┆           ┆           ┆          │
│ INV-07747 ┆ 10/05/201 ┆ 3831      ┆ THE       ┆ … ┆ 25        ┆ 314       ┆ 52        ┆ 1,368    │
│ 400001    ┆ 7         ┆           ┆ MARKET OF ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ MADRID    ┆   ┆           ┆           ┆           ┆          │
│ INV-07622 ┆ 10/03/201 ┆ 5140      ┆ A TO Z    ┆ … ┆ 37        ┆ 429       ┆ 23        ┆ 181      │
│ 300001    ┆ 7         ┆           ┆ LIQUOR    ┆   ┆           ┆           ┆           ┆          │
│ INV-07688 ┆ 10/04/201 ┆ 2623      ┆ HY-VEE    ┆ … ┆ 35        ┆ 213       ┆ 36        ┆ 1,891    │
│ 900026    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #4  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / SIOUX   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ C…        ┆   ┆           ┆           ┆           ┆          │
│ INV-07753 ┆ 10/06/201 ┆ 2668      ┆ HY-VEE    ┆ … ┆ 52        ┆ 508       ┆ 96        ┆ 1,777    │
│ 000029    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ LEON      ┆   ┆           ┆           ┆           ┆          │
│ INV-07694 ┆ 10/04/201 ┆ 2594      ┆ HY-VEE    ┆ … ┆ 35        ┆ 213       ┆ 36        ┆ 1,891    │
│ 100090    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SIOUX     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CITY      ┆   ┆           ┆           ┆           ┆          │
│ INV-07755 ┆ 10/06/201 ┆ 3591      ┆ ACKLEY    ┆ … ┆ 18        ┆ 231       ┆ 41        ┆ 1,786    │
│ 500005    ┆ 7         ┆           ┆ SUPER     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ FOODS     ┆   ┆           ┆           ┆           ┆          │
│ INV-07654 ┆ 10/04/201 ┆ 4013      ┆ WAL-MART  ┆ … ┆ 56        ┆ 86        ┆ 68        ┆ 1,835    │
│ 300034    ┆ 7         ┆           ┆ 0841 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ TIPTON    ┆   ┆           ┆           ┆           ┆          │
│ INV-07742 ┆ 10/05/201 ┆ 4190      ┆ FAREWAY   ┆ … ┆ 27        ┆ 180       ┆ 51        ┆ 1,783    │
│ 900023    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #888 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ JEFFERSO… ┆   ┆           ┆           ┆           ┆          │
│ INV-07766 ┆ 10/06/201 ┆ 2553      ┆ HY-VEE    ┆ … ┆ 49        ┆ 479       ┆ 84        ┆ 300      │
│ 000023    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CRESTON   ┆   ┆           ┆           ┆           ┆          │
│ INV-07633 ┆ 10/03/201 ┆ 2529      ┆ HY-VEE    ┆ … ┆ 18        ┆ 264       ┆ 45        ┆ 287      │
│ 100007    ┆ 7         ┆           ┆ DRUGSTORE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #4 /      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CEDAR RA… ┆   ┆           ┆           ┆           ┆          │
│ INV-07696 ┆ 10/04/201 ┆ 4157      ┆ FAREWAY   ┆ … ┆ 22        ┆ 292       ┆ 61        ┆ 1,792    │
│ 000024    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #993 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NORTH LI… ┆   ┆           ┆           ┆           ┆          │
│ INV-07795 ┆ 10/09/201 ┆ 3773      ┆ BENZ DIST ┆ … ┆ 18        ┆ 264       ┆ 45        ┆ 287      │
│ 700064    ┆ 7         ┆           ┆ RIBUTING  ┆   ┆           ┆           ┆           ┆          │
│ INV-07798 ┆ 10/09/201 ┆ 3612      ┆ B AND C   ┆ … ┆ 7         ┆ 80        ┆ 43        ┆ 1,790    │
│ 500122    ┆ 7         ┆           ┆ LIQUOR /  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ MAQUOKETA ┆   ┆           ┆           ┆           ┆          │
│ INV-07740 ┆ 10/05/201 ┆ 3806      ┆ TARGET    ┆ … ┆ 27        ┆ 333       ┆ 64        ┆ 1,878    │
│ 800005    ┆ 7         ┆           ┆ STORE     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ T-1901 /  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ WDM       ┆   ┆           ┆           ┆           ┆          │
│ INV-07747 ┆ 10/05/201 ┆ 4577      ┆ CASEY'S   ┆ … ┆ 25        ┆ 315       ┆ 62        ┆ 1,746    │
│ 300012    ┆ 7         ┆           ┆ GENERAL   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #2551 / … ┆   ┆           ┆           ┆           ┆          │
│ INV-07827 ┆ 10/09/201 ┆ 4303      ┆ MEPO      ┆ … ┆ 10        ┆ 109       ┆ 89        ┆ 1,778    │
│ 900016    ┆ 7         ┆           ┆ FOODS     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ INV-07710 ┆ 10/05/201 ┆ 5058      ┆ KUM & GO  ┆ … ┆ 27        ┆ 332       ┆ 64        ┆ 1,878    │
│ 800003    ┆ 7         ┆           ┆ # 542 /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ URBANDALE ┆   ┆           ┆           ┆           ┆          │
│ INV-07686 ┆ 10/04/201 ┆ 2637      ┆ HY-VEE #5 ┆ … ┆ 56        ┆ 84        ┆ 67        ┆ 1,881    │
│ 300094    ┆ 7         ┆           ┆ /         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ DAVENPORT ┆   ┆           ┆           ┆           ┆          │
│ INV-07683 ┆ 10/04/201 ┆ 3776      ┆ WAL-MART  ┆ … ┆ 56        ┆ 83        ┆ 67        ┆ 1,881    │
│ 700001    ┆ 7         ┆           ┆ 5115 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ DAVENPORT ┆   ┆           ┆           ┆           ┆          │
│ INV-07638 ┆ 10/03/201 ┆ 2571      ┆ HY-VEE    ┆ … ┆ 18        ┆ 244       ┆ 35        ┆ 176      │
│ 300134    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #2  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ /         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ WATERLO…  ┆   ┆           ┆           ┆           ┆          │
│ INV-07836 ┆ 10/09/201 ┆ 4904      ┆ LARCHWOOD ┆ … ┆ 33        ┆ 198       ┆ 1         ┆ 1,829    │
│ 500006    ┆ 7         ┆           ┆ QUICK     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STOP      ┆   ┆           ┆           ┆           ┆          │
│ INV-07836 ┆ 10/09/201 ┆ 4904      ┆ LARCHWOOD ┆ … ┆ 33        ┆ 198       ┆ 1         ┆ 1,829    │
│ 500015    ┆ 7         ┆           ┆ QUICK     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STOP      ┆   ┆           ┆           ┆           ┆          │
│ INV-07706 ┆ 10/05/201 ┆ 5029      ┆ THE       ┆ … ┆ 56        ┆ 83        ┆ 67        ┆ 1,881    │
│ 500009    ┆ 7         ┆           ┆ LIQUOR    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STOP LLC  ┆   ┆           ┆           ┆           ┆          │
│ INV-07677 ┆ 10/04/201 ┆ 2600      ┆ HY-VEE    ┆ … ┆ 11        ┆ 133       ┆ 76        ┆ 290      │
│ 100019    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ OSKALOOSA ┆   ┆           ┆           ┆           ┆          │
│ INV-07726 ┆ 10/05/201 ┆ 2579      ┆ HY-VEE    ┆ … ┆ 12        ┆ 135       ┆ 65        ┆ 296      │
│ 000050    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ GRINNELL  ┆   ┆           ┆           ┆           ┆          │
│ INV-07658 ┆ 10/04/201 ┆ 2616      ┆ HY-VEE    ┆ … ┆ 56        ┆ 82        ┆ 55        ┆ 1,745    │
│ 800137    ┆ 7         ┆           ┆ FOOD AND  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ DRUG /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ CLINTON   ┆   ┆           ┆           ┆           ┆          │
│ INV-07630 ┆ 10/03/201 ┆ 4678      ┆ FAREWAY   ┆ … ┆ 27        ┆ 331       ┆ 62        ┆ 1,746    │
│ 500005    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #124 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ADEL      ┆   ┆           ┆           ┆           ┆          │
│ INV-07735 ┆ 10/05/201 ┆ 2592      ┆ HY-VEE    ┆ … ┆ 21        ┆ 277       ┆ 54        ┆ 1,831    │
│ 600027    ┆ 7         ┆           ┆ DRUGSTORE ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / MARSHAL ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ LTOW…     ┆   ┆           ┆           ┆           ┆          │
│ INV-07783 ┆ 10/06/201 ┆ 2585      ┆ HY-VEE    ┆ … ┆ 24        ┆ 165       ┆ 6         ┆ 1,794    │
│ 300008    ┆ 7         ┆           ┆ WINE AND  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ SPIRITS / ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ALGO…     ┆   ┆           ┆           ┆           ┆          │
│ INV-07813 ┆ 10/09/201 ┆ 2555      ┆ HY-VEE    ┆ … ┆ 10        ┆ 121       ┆ 99        ┆ 1,827    │
│ 100057    ┆ 7         ┆           ┆ FOOD      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE /   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ KEOKUK    ┆   ┆           ┆           ┆           ┆          │
│ INV-07782 ┆ 10/06/201 ┆ 4268      ┆ FAREWAY   ┆ … ┆ 24        ┆ 165       ┆ 6         ┆ 1,794    │
│ 800011    ┆ 7         ┆           ┆ STORES    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ #531 /    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ALGONA    ┆   ┆           ┆           ┆           ┆          │
│ INV-07743 ┆ 10/05/201 ┆ 4539      ┆ CASEY'S   ┆ … ┆ 27        ┆ 330       ┆ 51        ┆ 1,783    │
│ 100018    ┆ 7         ┆           ┆ GENERAL   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ STORE #40 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ / SC…     ┆   ┆           ┆           ┆           ┆          │
│ INV-07657 ┆ 10/04/201 ┆ 2806      ┆ OSCO #881 ┆ … ┆ 56        ┆ 82        ┆ 55        ┆ 1,745    │
│ 700040    ┆ 7         ┆           ┆ / CLINTON ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘