## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/dataset.csv", separator=",")

df

shape: (50_000, 20)
┌─────┬────────┬─────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Age ┆ Gender ┆ Smoking ┆ Alcohol_Con ┆ … ┆ ECG_Results ┆ Exercise_In ┆ Max_Heart_R ┆ Heart_Attac │
│ --- ┆ ---    ┆ ---     ┆ sumption    ┆   ┆ ---         ┆ duced_Angin ┆ ate_Achieve ┆ k_Risk      │
│ i64 ┆ str    ┆ i64     ┆ ---         ┆   ┆ str         ┆ a           ┆ d           ┆ ---         │
│     ┆        ┆         ┆ i64         ┆   ┆             ┆ ---         ┆ ---         ┆ str         │
│     ┆        ┆         ┆             ┆   ┆             ┆ i64         ┆ i64         ┆             │
╞═════╪════════╪═════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 69  ┆ Female ┆ 1       ┆ 0           ┆ … ┆ Normal      ┆ 0           ┆ 114         ┆ Low         │
│ 32  ┆ Male   ┆ 0       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 173         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 89  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ ST-T        ┆ 0           ┆ 109         ┆ Low         │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 78  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ Left        ┆ 0           ┆ 129         ┆ Low         │
│     ┆        ┆         ┆             ┆   ┆ Ventricular ┆             ┆             ┆             │
│     ┆        ┆         ┆             ┆   ┆ Hypertrophy ┆             ┆             ┆             │
│ 38  ┆ Female ┆ 1       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 124         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ …   ┆ …      ┆ …       ┆ …           ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ 21  ┆ Male   ┆ 0       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 122         ┆ High        │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 35  ┆ Female ┆ 0       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 121         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 46  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ Left        ┆ 0           ┆ 125         ┆ Low         │
│     ┆        ┆         ┆             ┆   ┆ Ventricular ┆             ┆             ┆             │
│     ┆        ┆         ┆             ┆   ┆ Hypertrophy ┆             ┆             ┆             │
│ 56  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ Normal      ┆ 0           ┆ 149         ┆ Moderate    │
│ 72  ┆ Male   ┆ 0       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 144         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
└─────┴────────┴─────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 20)
┌─────┬────────┬─────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Age ┆ Gender ┆ Smoking ┆ Alcohol_Con ┆ … ┆ ECG_Results ┆ Exercise_In ┆ Max_Heart_R ┆ Heart_Attac │
│ --- ┆ ---    ┆ ---     ┆ sumption    ┆   ┆ ---         ┆ duced_Angin ┆ ate_Achieve ┆ k_Risk      │
│ i64 ┆ str    ┆ i64     ┆ ---         ┆   ┆ str         ┆ a           ┆ d           ┆ ---         │
│     ┆        ┆         ┆ i64         ┆   ┆             ┆ ---         ┆ ---         ┆ str         │
│     ┆        ┆         ┆             ┆   ┆             ┆ i64         ┆ i64         ┆             │
╞═════╪════════╪═════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 69  ┆ Female ┆ 1       ┆ 0           ┆ … ┆ Normal      ┆ 0           ┆ 114         ┆ Low         │
│ 32  ┆ Male   ┆ 0       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 173         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 89  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ ST-T        ┆ 0           ┆ 109         ┆ Low         │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
│ 78  ┆ Male   ┆ 0       ┆ 1           ┆ … ┆ Left        ┆ 0           ┆ 129         ┆ Low         │
│     ┆        ┆         ┆             ┆   ┆ Ventricular ┆             ┆             ┆             │
│     ┆        ┆         ┆             ┆   ┆ Hypertrophy ┆             ┆             ┆             │
│ 38  ┆ Female ┆ 1       ┆ 0           ┆ … ┆ ST-T        ┆ 0           ┆ 124         ┆ Moderate    │
│     ┆        ┆         ┆             ┆   ┆ abnormality ┆             ┆             ┆             │
└─────┴────────┴─────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### Display Summary Statistics for All Columns

In [5]:
summary = df.describe()
print(summary)

shape: (9, 21)
┌────────────┬───────────┬────────┬──────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ statistic  ┆ Age       ┆ Gender ┆ Smoking  ┆ … ┆ ECG_Result ┆ Exercise_I ┆ Max_Heart ┆ Heart_Att │
│ ---        ┆ ---       ┆ ---    ┆ ---      ┆   ┆ s          ┆ nduced_Ang ┆ _Rate_Ach ┆ ack_Risk  │
│ str        ┆ f64       ┆ str    ┆ f64      ┆   ┆ ---        ┆ ina        ┆ ieved     ┆ ---       │
│            ┆           ┆        ┆          ┆   ┆ str        ┆ ---        ┆ ---       ┆ str       │
│            ┆           ┆        ┆          ┆   ┆            ┆ f64        ┆ f64       ┆           │
╞════════════╪═══════════╪════════╪══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ count      ┆ 50000.0   ┆ 50000  ┆ 50000.0  ┆ … ┆ 50000      ┆ 50000.0    ┆ 50000.0   ┆ 50000     │
│ null_count ┆ 0.0       ┆ 0      ┆ 0.0      ┆ … ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0         │
│ mean       ┆ 53.3987   ┆ null   ┆ 0.29842  ┆ … ┆ null       ┆ 0.20164    ┆ 149.30534 ┆ null      │
│ std        ┆ 20.799006 ┆ null   ┆ 0.457569 ┆ … ┆ null       ┆ 0.401229   ┆ 28.823699 ┆ null      │
│ min        ┆ 18.0      ┆ Female ┆ 0.0      ┆ … ┆ Left Ventr ┆ 0.0        ┆ 100.0     ┆ High      │
│            ┆           ┆        ┆          ┆   ┆ icular Hyp ┆            ┆           ┆           │
│            ┆           ┆        ┆          ┆   ┆ ertrophy   ┆            ┆           ┆           │
│ 25%        ┆ 35.0      ┆ null   ┆ 0.0      ┆ … ┆ null       ┆ 0.0        ┆ 124.0     ┆ null      │
│ 50%        ┆ 53.0      ┆ null   ┆ 0.0      ┆ … ┆ null       ┆ 0.0        ┆ 149.0     ┆ null      │
│ 75%        ┆ 71.0      ┆ null   ┆ 1.0      ┆ … ┆ null       ┆ 0.0        ┆ 174.0     ┆ null      │
│ max        ┆ 89.0      ┆ Male   ┆ 1.0      ┆ … ┆ ST-T abnor ┆ 1.0        ┆ 199.0     ┆ Moderate  │
│            ┆           ┆        ┆          ┆   ┆ mality     ┆            ┆           ┆           │
└────────────┴───────────┴────────┴──────────┴───┴────────────┴────────────┴───────────┴───────────┘

### Find Longest Text Length in Each Column

In [6]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 7)
┌────────┬───────────────┬──────────────┬───────────────┬─────────────┬─────────────┬──────────────┐
│ Gender ┆ Physical_Acti ┆ Stress_Level ┆ Chest_Pain_Ty ┆ Thalassemia ┆ ECG_Results ┆ Heart_Attack │
│ ---    ┆ vity_Level    ┆ ---          ┆ pe            ┆ ---         ┆ ---         ┆ _Risk        │
│ u32    ┆ ---           ┆ u32          ┆ ---           ┆ u32         ┆ u32         ┆ ---          │
│        ┆ u32           ┆              ┆ u32           ┆             ┆             ┆ u32          │
╞════════╪═══════════════╪══════════════╪═══════════════╪═════════════╪═════════════╪══════════════╡
│ 6      ┆ 8             ┆ 8            ┆ 12            ┆ 17          ┆ 28          ┆ 8            │
└────────┴───────────────┴──────────────┴───────────────┴─────────────┴─────────────┴──────────────┘

### Retrieve Data Types of All Columns

In [7]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Int64, String, Int64, Int64, String, Float64, Int64, Int64, Float64, Int64, Int64, Int64, String, String, String, Int64, String, Int64, Int64, String]

### Count Unique Values in Each Column

In [8]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                          Unique values in Age : 72
                       Unique values in Gender : 2
                      Unique values in Smoking : 2
          Unique values in Alcohol_Consumption : 2
      Unique values in Physical_Activity_Level : 3
                          Unique values in BMI : 2501
                     Unique values in Diabetes : 2
                 Unique values in Hypertension : 2
            Unique values in Cholesterol_Level : 1501
                   Unique values in Resting_BP : 90
                   Unique values in Heart_Rate : 70
               Unique values in Family_History : 2
                 Unique values in Stress_Level : 3
              Unique values in Chest_Pain_Type : 4
                  Unique values in Thalassemia : 3
          Unique values in Fasting_Blood_Sugar : 2
                  Unique values in ECG_Results : 3
      Unique values in Exercise_Induced_Angina : 2
      Unique values in Max_Heart_Rate_Achieved : 100
            Unique values in Heart_Attack_Risk : 3

### Check Distribution of Numerical Columns

In [9]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

Age
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ Age       │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 50000.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 53.3987   │
│ std        ┆ 20.799006 │
│ min        ┆ 18.0      │
│ 25%        ┆ 35.0      │
│ 50%        ┆ 53.0      │
│ 75%        ┆ 71.0      │
│ max        ┆ 89.0      │
└────────────┴───────────┘


Smoking
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Smoking  │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 50000.0  │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.29842  │
│ std        ┆ 0.457569 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 1.0      │
│ max        ┆ 1.0      │
└────────────┴──────────┘


Alcohol_Consumption
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ Alcohol_Consumption │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 50000.0             │
│ null_count ┆ 0.0                 │
│ mean       ┆ 0.40198             │
│ std        ┆ 0.490303            │
│ min        ┆ 0.0                 │
│ 25%        ┆ 0.0                 │
│ 50%        ┆ 0.0                 │
│ 75%        ┆ 1.0                 │
│ max        ┆ 1.0                 │
└────────────┴─────────────────────┘


BMI
shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ BMI       │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 50000.0   │
│ null_count ┆ 0.0       │
│ mean       ┆ 27.519357 │
│ std        ┆ 7.225176  │
│ min        ┆ 15.0      │
│ 25%        ┆ 21.27     │
│ 50%        ┆ 27.54     │
│ 75%        ┆ 33.77     │
│ max        ┆ 40.0      │
└────────────┴───────────┘


Diabetes
shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ Diabetes │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 50000.0  │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.19884  │
│ std        ┆ 0.399131 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 0.0      │
│ max        ┆ 1.0      │
└────────────┴──────────┘


Hypertension
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ Hypertension │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 50000.0      │
│ null_count ┆ 0.0          │
│ mean       ┆ 0.29738      │
│ std        ┆ 0.45711      │
│ min        ┆ 0.0          │
│ 25%        ┆ 0.0          │
│ 50%        ┆ 0.0          │
│ 75%        ┆ 1.0          │
│ max        ┆ 1.0          │
└────────────┴──────────────┘


Cholesterol_Level
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ Cholesterol_Level │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 50000.0           │
│ null_count ┆ 0.0               │
│ mean       ┆ 225.036444        │
│ std        ┆ 43.317373         │
│ min        ┆ 150.0             │
│ 25%        ┆ 187.3             │
│ 50%        ┆ 225.1             │
│ 75%        ┆ 262.6             │
│ max        ┆ 300.0             │
└────────────┴───────────────────┘


Resting_BP
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ Resting_BP │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 50000.0    │
│ null_count ┆ 0.0        │
│ mean       ┆ 134.4341   │
│ std        ┆ 25.907961  │
│ min        ┆ 90.0       │
│ 25%        ┆ 112.0      │
│ 50%        ┆ 134.0      │
│ 75%        ┆ 157.0      │
│ max        ┆ 179.0      │
└────────────┴────────────┘


Heart_Rate
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ Heart_Rate │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 50000.0    │
│ null_count ┆ 0.0        │
│ mean       ┆ 94.53048   │
│ std        ┆ 20.187124  │
│ min        ┆ 60.0       │
│ 25%        ┆ 77.0       │
│ 50%        ┆ 94.0       │
│ 75%        ┆ 112.0      │
│ max        ┆ 129.0      │
└────────────┴────────────┘


Family_History
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ Family_History │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 50000.0        │
│ null_count ┆ 0.0            │
│ mean       ┆ 0.30034        │
│ std        ┆ 0.45841        │
│ min        ┆ 0.0            │
│ 25%        ┆ 0.0            │
│ 50%        ┆ 0.0            │
│ 75%        ┆ 1.0            │
│ max        ┆ 1.0            │
└────────────┴────────────────┘


Fasting_Blood_Sugar
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ Fasting_Blood_Sugar │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 50000.0             │
│ null_count ┆ 0.0                 │
│ mean       ┆ 0.14936             │
│ std        ┆ 0.356447            │
│ min        ┆ 0.0                 │
│ 25%        ┆ 0.0                 │
│ 50%        ┆ 0.0                 │
│ 75%        ┆ 0.0                 │
│ max        ┆ 1.0                 │
└────────────┴─────────────────────┘


Exercise_Induced_Angina
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ Exercise_Induced_Angina │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 50000.0                 │
│ null_count ┆ 0.0                     │
│ mean       ┆ 0.20164                 │
│ std        ┆ 0.401229                │
│ min        ┆ 0.0                     │
│ 25%        ┆ 0.0                     │
│ 50%        ┆ 0.0                     │
│ 75%        ┆ 0.0                     │
│ max        ┆ 1.0                     │
└────────────┴─────────────────────────┘


Max_Heart_Rate_Achieved
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ Max_Heart_Rate_Achieved │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 50000.0                 │
│ null_count ┆ 0.0                     │
│ mean       ┆ 149.30534               │
│ std        ┆ 28.823699               │
│ min        ┆ 100.0                   │
│ 25%        ┆ 124.0                   │
│ 50%        ┆ 149.0                   │
│ 75%        ┆ 174.0                   │
│ max        ┆ 199.0                   │
└────────────┴─────────────────────────┘

### Retrieve Count of Nulls For Each Feature

In [10]:
null_counts = df.null_count().to_dict(as_series=False)

print("Null counts per column:")
for column, count in null_counts.items():
    print(f"{column}: {count[0]}")

Null counts per column:
Age: 0
Gender: 0
Smoking: 0
Alcohol_Consumption: 0
Physical_Activity_Level: 0
BMI: 0
Diabetes: 0
Hypertension: 0
Cholesterol_Level: 0
Resting_BP: 0
Heart_Rate: 0
Family_History: 0
Stress_Level: 0
Chest_Pain_Type: 0
Thalassemia: 0
Fasting_Blood_Sugar: 0
ECG_Results: 0
Exercise_Induced_Angina: 0
Max_Heart_Rate_Achieved: 0
Heart_Attack_Risk: 0

### List Unique Values For Certain Features

In [11]:
def list_unique_values_under_threshold(df: pl.DataFrame, threshold: int = 5000):
    for col in df.columns:
        unique_count = df.select(pl.col(col).n_unique()).item()
        if unique_count < threshold:
            unique_vals = df.select(pl.col(col).unique().sort()).to_series()
            print(f"Column: {col} ({unique_count} unique values)")
            print(unique_vals)
            print("-" * 50)

# Apply to your DataFrame
list_unique_values_under_threshold(df)

Column: Age (72 unique values)
shape: (72,)
Series: 'Age' [i64]
[
	18
	19
	20
	21
	22
	…
	85
	86
	87
	88
	89
]
--------------------------------------------------
Column: Gender (2 unique values)
shape: (2,)
Series: 'Gender' [str]
[
	"Female"
	"Male"
]
--------------------------------------------------
Column: Smoking (2 unique values)
shape: (2,)
Series: 'Smoking' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Alcohol_Consumption (2 unique values)
shape: (2,)
Series: 'Alcohol_Consumption' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Physical_Activity_Level (3 unique values)
shape: (3,)
Series: 'Physical_Activity_Level' [str]
[
	"High"
	"Low"
	"Moderate"
]
--------------------------------------------------
Column: BMI (2501 unique values)
shape: (2_501,)
Series: 'BMI' [f64]
[
	15.0
	15.01
	15.02
	15.03
	15.04
	…
	39.96
	39.97
	39.98
	39.99
	40.0
]
--------------------------------------------------
Column: Diabetes (2 unique values)
shape: (2,)
Series: 'Diabetes' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Hypertension (2 unique values)
shape: (2,)
Series: 'Hypertension' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Cholesterol_Level (1501 unique values)
shape: (1_501,)
Series: 'Cholesterol_Level' [f64]
[
	150.0
	150.1
	150.2
	150.3
	150.4
	…
	299.6
	299.7
	299.8
	299.9
	300.0
]
--------------------------------------------------
Column: Resting_BP (90 unique values)
shape: (90,)
Series: 'Resting_BP' [i64]
[
	90
	91
	92
	93
	94
	…
	175
	176
	177
	178
	179
]
--------------------------------------------------
Column: Heart_Rate (70 unique values)
shape: (70,)
Series: 'Heart_Rate' [i64]
[
	60
	61
	62
	63
	64
	…
	125
	126
	127
	128
	129
]
--------------------------------------------------
Column: Family_History (2 unique values)
shape: (2,)
Series: 'Family_History' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Stress_Level (3 unique values)
shape: (3,)
Series: 'Stress_Level' [str]
[
	"High"
	"Low"
	"Moderate"
]
--------------------------------------------------
Column: Chest_Pain_Type (4 unique values)
shape: (4,)
Series: 'Chest_Pain_Type' [str]
[
	"Asymptomatic"
	"Atypical"
	"Non-anginal"
	"Typical"
]
--------------------------------------------------
Column: Thalassemia (3 unique values)
shape: (3,)
Series: 'Thalassemia' [str]
[
	"Fixed defect"
	"Normal"
	"Reversible defect"
]
--------------------------------------------------
Column: Fasting_Blood_Sugar (2 unique values)
shape: (2,)
Series: 'Fasting_Blood_Sugar' [i64]
[
	0
	1
]
--------------------------------------------------
Column: ECG_Results (3 unique values)
shape: (3,)
Series: 'ECG_Results' [str]
[
	"Left Ventricular Hypertrophy"
	"Normal"
	"ST-T abnormality"
]
--------------------------------------------------
Column: Exercise_Induced_Angina (2 unique values)
shape: (2,)
Series: 'Exercise_Induced_Angina' [i64]
[
	0
	1
]
--------------------------------------------------
Column: Max_Heart_Rate_Achieved (100 unique values)
shape: (100,)
Series: 'Max_Heart_Rate_Achieved' [i64]
[
	100
	101
	102
	103
	104
	…
	195
	196
	197
	198
	199
]
--------------------------------------------------
Column: Heart_Attack_Risk (3 unique values)
shape: (3,)
Series: 'Heart_Attack_Risk' [str]
[
	"High"
	"Low"
	"Moderate"
]
--------------------------------------------------